### ISSUE TITLE
Shippable IP ranges

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1016]
Hello,
would it be possible to provide us (the ones that use shippable in dedicated hosts) some IP ranges that we can whitelist in our firewall rules for shippable to access port 22?

**Comment by manishas** [comment]
@pmoust let me get back to you on this...

**Comment by grue** [comment]
+1 to this. I'd be interested as well.

**Comment by gavinheavyside** [comment]
+1 from me too.

**Comment by chschuermann** [comment]
+1

**Comment by bittner** [comment]
This would be urgent for us at the moment.  +1

**Comment by bradenstenning** [comment]
+1

**Comment by axon-dev** [comment]
+1

**Comment by avinci** [comment]
This is a tough one....We constantly change our IPs due to how we manage host machines. I think the only real solution is to create a NAT and then make sure all our traffic is always routed through a NAT and then give you the NAT box IP....

Would that make sense?

**Comment by avinci** [comment]
closing this. please let us know if you still need this

**Comment by rsteckler** [comment]
I think this is important.  I need to keep port 22 (SSH) open so Shippable can talk to my production servers.  I'd really like to limit the IP range that can access my production box.

Many other companies list their IP ranges so network folks can lock things down.  Here are two examples:

Stripe:  https://stripe.com/docs/ips
MongoDB Cloud Manager:  https://docs.cloud.mongodb.com/reference/firewall-configuration/

In addition, without making too many assumptions about Shippable's stack, there might be a security benefit to you guys directly.  Right now it sounds like you allow all of your servers to egress directly to the internet.  To solve this problem, you would route all traffic through a NAT/Proxy that would give you centralized control over your traffic egress patterns.

**Comment by BlueDragonX** [comment]
I would like this as well for the same reason. Allowing unrestricted public access to port 22 is a security concern.

**Comment by rvrignaud** [comment]
I would be also very interested on this one. NAT traffic would match our use case.

**Comment by sarahleeashraf** [comment]
We need this!

**Comment by truk70** [comment]
We need this too!

**Comment by harissarwar** [comment]
We need this too.

**Comment by wakatta** [comment]
Can you please implement something like what wercker is: http://devcenter.wercker.com/docs/faq/what-ip-to-whitelist

**Comment by rageshkrishna** [comment]
@wakatta You should be able to whitelist `52.6.173.6` now. Let me know if you still have trouble.

**Comment by rvrignaud** [comment]
@rageshkrishna Do you mean that Shippable can warranty that all access to public resources during builds will have this public IP as source ?
Is there any formal documentation ?

**Comment by rageshkrishna** [comment]
@rvrignaud Sorry, no, that's not what this issue was originally about. This is only if you want to restrict incoming connections on port 22 for initialization of custom nodes.

This does not apply to build machines.

**Comment by rageshkrishna** [comment]
Let me clarify that -- this does not apply to build machines if you are using dynamic nodes.

**Comment by BlueDragonX** [comment]
We don't need this anymore as we're moving our build and deploy process off of Shippable. That this was ignored and closed out of hand is an example of why we're moving.

**Comment by manishas** [comment]
@BlueDragonX this issue was from over 2 years ago when the team was much smaller. It shouldn't have been closed, but it isn't indicative of how support issues are handled today.

Several months ago, we tried to onboard you to our private ticketing system reserved for customers with 4+ nodes and also offered to jump on a call every couple of weeks or as required and work with you to address concerns and prioritize feature requests. I haven't received a response yet, but those are still great options to get very quick help/answers and to request new features.

This is our support forum for free users and paying customers who run small workloads on Shippable. The SLA is best effort unless it is a high severity issue. Having said that, we are very quick to respond to any issues that come in and every engineer on the team now contributes to handling support issues. In fact, several customers have pointed to the excellent response time as a big reason why they chose Shippable.... not many companies offer direct access to the core engineering team right off the bat. Our [Enterprise support tier](https://www.shippable.com/premium-support.html) even offers a private Slack channel with direct access to our core team.

I would love to work with you and make sure you and your team are happy, let me know if you want to jump on a call and I'll make sure your issues/requests are escalated.

**Comment by manishas** [comment]
Re-opening this issue since it has received a lot of +1 comments.

**Comment by nmarjanovic** [comment]
+1

**Comment by jm2242** [comment]
Are there any updates on this issue?

**Comment by rageshkrishna** [comment]
It certainly took us a while to get around to it, but this feature is finally available.

Node pools can be configured to use a static IP address now. Docs are at http://docs.shippable.com/platform/tutorial/runtime/manage-node-pools/#using-static-ip-to-whitelist-traffic-from-on-demand-nodes

**Comment by BlueDragonX** [comment]
That's not what we were asking for. We really needed to be able to whitelist the IP addresses of the Shippable machines that SSH into the BYON worker nodes - you know, for security.

On the other hand, we don't use Shippable anymore, for _so many_ reasons. Even better, I no longer work there!
