### ISSUE TITLE
how to save a local image and use it on a dedicate host?

### ISSUE THREAD

**Issue by adamyao** [Shippable/support#1022]
I am using a dedicate host and use build_image: shippable/minv2. But it takes long time (about 40 minutes) for boot process. How can I save the image on the dedicate host and use it when boot, so it will be quicker? Thanks.

**Comment by adamyao** [comment]
My second and following builds were much faster. Does Shippable is automatically using the previous minion?

**Comment by manishas** [comment]
@adamyao can you send me links to a build that was slow in the boot section and one that wasn't? We can take a look.

**Comment by adamyao** [comment]
Thanks Manishas.
The slow one:  https://app.shippable.com/builds/54cfbdff03c39d0d00f5ce13
A quicker one: https://app.shippable.com/builds/54cfe1568320dc0e00957b01

**Comment by manishas** [comment]
@adamyao I see that all your latest builds are pretty fast, so this was a one time thing. We are working on improving the dedicated hosts architecture so this will no longer be an issue in the near future.

I am closing this issue for now, but please do re-open if you see slow builds due to this issue again.
