### ISSUE TITLE
Shippable is ignoring my script and running something else

### ISSUE THREAD

**Issue by velo** [Shippable/support#1027]
Hi,

I have something like this on my shippable.yml:
````
script:
  - mvn clean install -Pproduction,IT -T1C -DforkCount=1C | grep '[INFOERRORWARNING]'
````

But, when shippable run it does this shippable_retry ....
https://app.shippable.com/builds/54d1321d33d2890e0001ed7e

````
install
 shippable_retry mvn install -DskipTests=true
````

How can I make shippable run my script instead this skipTests thing?

**Comment by velo** [comment]
Also, my log file is incomplete when I download it.... so I'm not really sure if the build passed.
https://app.shippable.com/builds/54d1321d33d2890e0001ed7e/1/console

**Comment by rageshkrishna** [comment]
@velo For the first problem, you should move your `mvn clean install` command to the `install` section. Once you do that, Shippable will no longer invoke a default install command for you.

The second problem is happening because there's an open bug against our database that is preventing the complete contents from being returned. As a quick fix, it might help if you can run your mvn install in quiet mode as I see that right now the console is filling up with the download status numbers.

**Comment by velo** [comment]
ok, thanks

**Comment by manishas** [comment]
@velo the console log download issue is already an open issue - #951. Please follow that issue for a resolution.
