### ISSUE TITLE
How do I upgrade my account?

### ISSUE THREAD

**Issue by Neku** [Shippable/support#1048]
I don't see where I can upgrade my account in the interface

**Comment by manishas** [comment]
@Neku In the Shippable UI, you will need to go to the org you want to upgrade, click on 'Plans and Billing' at the top right of the org page, save a credit card, and then select the Startup plan.

Please do not delete card details after upgrading since this automatically downgrades you to the free plan.

**Comment by mariocesar** [comment]
Will be nice to have a single upgrade action button on the board, I spend 30 minutes browsing the site! :(
