### ISSUE TITLE
[Consolidated Feature request] Support additional languages

### ISSUE THREAD

**Issue by manuel-rubio** [Shippable/support#105]
Hi,

I'll try to build my ephp project in shippable and I can see an advice to open an issue to support that so, here is my issue! please, give support to erlang language!

My repo is: https://github.com/altenwald/ephp.git

Thanks.

**Comment by manishas** [comment]
Consolidating all asks for additional languages here.

C/C++ - #312 (workaround is to provide custom docker container and lie about the language as python

Perl - #360

**Comment by manuel-rubio** [comment]
I don't believe it! did you give support for Rust and not for Erlang?

**Comment by manishas** [comment]
Neither is supported officially at the moment. I am just consolidating all requests for additional languages. 

That said, many customers are using custom docker images with their language tools installed and lying in the language  tag by saying language: python   This isn't a supported feature but many folks were successfully able to run builds.

**Comment by manuel-rubio** [comment]
I was reviewing... and finally makes no sense :-D ... if I have a docker image, my docker image, I can install inside whatever, makes no sense tell the people: support C/C++; if my docker image has a `gcc` compiler obviously is supported.

**Comment by manishas** [comment]
You're right, but we have a mandatory language tag in the yml that will not recognize unsupported languages. Hence the need for lying in the tag.

**Comment by larsbrinkhoff** [comment]
Note that adding support for C should be particularly easy.  The support is already there in the image.

**Comment by avinci** [comment]
I think most of these have been added and also we allow sudo to install anything else in `install` section. We are going to be releasing updates images in the next 2 weeks. But for now our list of languages supported is what we are going with.

**Comment by larsbrinkhoff** [comment]
Which languages are included in that list?

Is the documentation at http://docs.shippable.com/supported_services/ up to date?

**Comment by cemo** [comment]
```
Languages

Clojure
GO
Java
Node.js
PHP
Python
Ruby
Scala
C
```

http://docs.shippable.com/gs_supported/

**Comment by JJ** [comment]
The link above is forbidden...

**Comment by manishas** [comment]
http://docs.shippable.com/ci/supported-languages/

**Comment by JJ** [comment]
Should I understand that list is closed?

**Comment by manishas** [comment]
Those are the languages supported out of the box today. You can also use a custom image for any unsupported language. 

Can you explain your scenario a bit so I can recommend the best approach? What programming language are you looking for? Do you need a build matrix?

**Comment by JJ** [comment]
I am using a custom build process here
https://app.shippable.com/github/JJ/doc/runs?branchName=master
However, it takes some time to install some Perl utilities that are
standard in Perl build environments, like cpanm and JUnit plugin for
TAP::Harness; instead, it spends some time checking out stuff with Ruby
that I don't need. I wonder why Perl is not supported, since it's much more
popular than other languages that are supported, such as Scala or Clojure,
that is why I was asking if that list is closed or we can expect it to be
expanded in the future.
(Actually what I'm building is perl6 stuff, but it does need Perl for some
things. I'm not asking for Perl 6 support, however)

**Comment by manishas** [comment]
As of today, the best way to build for an unsupported language is to specify language: none in your yml and use a custom docker image that has all the pre-requisites in the image. 
http://docs.shippable.com/ci/custom-docker-image/

The list isn’t closed, it’s just what’s supported today. Because of custom image support, we’ve found people already build on a big variety of languages and platforms, and we usually add support for some of them as we see adoption. I’ll discuss with the team about adding perl or at least building a recommended image that folks can use.

**Comment by JJ** [comment]
2018-04-22 18:36 GMT+02:00 Manisha <notifications@github.com>:

> As of today, the best way to build for an unsupported language is to
> specify language: none in your yml and use a custom docker image that has
> all the pre-requisites in the image.
> http://docs.shippable.com/ci/custom-docker-image/
>
> The list isn’t closed, it’s just what’s supported today. Because of custom
> image support, we’ve found people already build on a big variety of
> languages and platforms, and we usually add support for some of them as we
> see adoption. I’ll discuss with the team about adding perl or at least
> building a recommended image that folks can use.
>

Thanks!

**Comment by flukejones** [comment]
Nice to see that language `none` is an option so we can use unsupported languages, but I would love to see support for Rust added officially soon (and by extension, wasm).
Official support is the one thing that prevents my being able to convince my workplace to adopt Shippable.
