### ISSUE TITLE
push artifacts to github in a different branch

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1052]
Hi, 

I would like to push builds onto a specific branch in a github. For eg. master branch artifacts are pushed to deploy branch. Also if branch is uat, I would want to push artifacts onto a branch called deploy-uat.

Is there a workflow in shippable which can help me do this?

Thanksm

**Comment by rageshkrishna** [comment]
Hi @naveensky. If I've understood this correctly, you want to push code from a successful build to a different branch. I think you should be able to do this with some simple bash scripting.

So you need to push successful builds on `master` to `deploy`, and successful builds on `uat` to `deploy-uat`. You can create an `pushOnSuccess.sh` script that does this:
````
#!/bin/bash -e

if [ "$BRANCH" == "master" ] && [ "$PULL_REQUEST" == false ]; then
  git checkout -B deploy
  git push -f -u origin deploy
fi;

if [ "$BRANCH" == "uat" ] && [ "$PULL_REQUEST" == false ]; then
  git checkout -B "deploy-uat"
  git push -f -u origin "deploy-uat"
fi;
````

You should `chmod +x pushOnSuccess.sh` before committing so it'll be executable.

And then update your YML file to call this script in after_success:
````
after_success:
 - ./pushOnSuccess.sh
````

The only caveat is that you'll need to be careful not to end up with an infinite loop of builds, because each push can potentially trigger new builds. You can use the `branches` directive in your YML to specify branches to include or exclude to mitigate this.

**Comment by naveensky** [comment]
@rageshkrishna - Yeah, this is exactly what I wanted. Let me try doing this once

**Comment by naveensky** [comment]
@rageshkrishna - I am closing this issue for now. Will need some time to test out your solution. Thanks a ton for your help :)
