### ISSUE TITLE
Locale not being set properly

### ISSUE THREAD

**Issue by adamwgoldberg** [Shippable/support#1062]
I'm not sure this is a Shippable-specific issue, but I get the following warning message, which appears to be related to Postgres not starting and/or hanging on every query:

<pre>
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
</pre>

I've tried to run:
<pre>
  sudo locale-gen en_US.UTF-8
  sudo dpkg-reconfigure locales
</pre>
 as part of the before_script, but to no avail.

**Comment by rageshkrishna** [comment]
@adamwgoldberg Which docker image are you using? This should be working correctly on all the shippable images. Let me know if you need any help setting it up on any custom images.

**Comment by adamwgoldberg** [comment]
It's a custom image... What should I be running?

**Comment by rageshkrishna** [comment]
We do the locale setup in our Dockerfile with this:
````
FROM ubuntu:12.04

RUN locale-gen en_US en_US.UTF-8 && \
    dpkg-reconfigure locales
````
Are you using a public docker image? If you are, I can try playing around with it a little to see what's going on. Can you also point me to a build ID where you're running in to this? I'd like to take a look at the logs. Thanks!

**Comment by manishas** [comment]
@rageshkrishna he's using dedicated hosts with his custom image.

**Comment by rageshkrishna** [comment]
@adamwgoldberg I noticed that your YML file is still sending languages as a list instead of a string. We're currently not processing this correctly, causing your build script to be generated incorrectly. Can you please try modifying your YML so the language tag looks like this:
````
language: scala
````
This should fix some of the environment variable issues in your builds.

**Comment by adamwgoldberg** [comment]
Docker image: adamwgoldberg/deepdive:unstable
Dockerfile: https://github.com/HazyResearch/deepdive/blob/adam-docker/Dockerfile
Example: https://app.shippable.com/builds/54e1d160c44f060e0073ac0a

**Comment by pmoust** [comment]
Had this issue in https://github.com/Shippable/support/issues/994
Bypassed it then by defining the locale prior to launching the service

**Comment by rageshkrishna** [comment]
@adamwgoldberg I was trying to run the same commands as the build using your image and a couple of things caught my attention:

1. We don't run source `.bashrc` when running a build. I'm not sure if your build depends on this happening.
2. Your build is locking up because postgres is waiting for a password:
````
root@c069f1610019:~# psql -h localhost -U postgres -c 'create database deepdive_test;'
Password for user postgres:
````

**Comment by adamwgoldberg** [comment]
It doesn't wait for the password when I run it "locally" on docker, so intuition says it is Shippable specific. I can run the full flow in the docker container directly. Is there something obvious I'm missing? And the .bashrc file isn't needed, but I copied the global env vars just in case. 

https://github.com/HazyResearch/deepdive/blob/shippable-branch/shippable.yml
