### ISSUE TITLE
When push multiple branches sometimes build only one

### ISSUE THREAD

**Issue by denya** [Shippable/support#1071]
Hi!

My bitbucket id: denya
Project: 542447b980088cee586cd665

When i push two branches (develop and master) at the one git pull command to btibucket, usually shippable builds only one branch.
I don't know, is it 'cause bitbucket doesn't make proper webhooks (for both branches) or it's bug in shippable?

Example build id 54e6eff965be240e00672409 (triggered only for develop branch, not for master)
So we had start build manually (id 54e6f1f565be240e00672467)

```
denyamsk@Denyas-MacBook-Air:/Users/denyamsk/code/proj$ (develop)git push
Counting objects: 19, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (12/12), 1.67 KiB | 0 bytes/s, done.
Total 12 (delta 6), reused 0 (delta 0)
To git@bitbucket.org:denya/robonect.git
   36a4daa..4ede88c  develop -> develop
   36a4daa..09d39bb  master -> master
```

Thanks!

**Comment by manishas** [comment]
@denya this is a bitbucket bug. I see an error in the Notifications tab for your project saying that 'A build was skipped due to missing branch in webhook', which means we did not get the branch name in the webhook from bitbucket. This is because Bitbucket webhooks have a known issue when fast-forwarded merges are pushed.

Please see https://github.com/Shippable/support/issues/897 for more details and a workaround.

**Comment by denya** [comment]
@manishas Thanks a lot!

**Comment by manishas** [comment]
Closing since this is a BitBucket issue and there is a workaround. Let us know if you run into any other issues.

Thanks!
