### ISSUE TITLE
Builds not processed

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1080]
Hi guys!

Love your system, but for some reason my builds for `inventid/neo` do not seem to get processed anymore. Neither when I push, nor when I run them from app.shippable.com

I have enabled the Dedicated Hosts feature, since I wanted to play around with it a bit more. However, I cannot find whether that is impacting anything (the builds simply never show up).

**Comment by manishas** [comment]
@rogierslag you need the build_image key in your yml in order to use dedicated hosts. 

See the blog at http://blog.shippable.com/dedicated-hosts-

our default image for multi-tenant service is shippable/minv2. You can specify this in your yml if you just want to continue using it with your dedicated hosts -

build_image: shippable/minv2

**Comment by manishas** [comment]
the error is surfaced in your Notifications tab for the inventid/Neo on Shippable -
![screen shot 2015-02-23 at 4 36 42 pm](https://cloud.githubusercontent.com/assets/2983749/6340980/34aff4b0-bb7a-11e4-9b74-db512712b3ef.png)

We're going to make a couple of changes to make sure the notifications tab is more prominent when there are unread notifications.

**Comment by rogierslag** [comment]
:+1: ill fixup a custom Docker container for use with the dedicated hosts anyway!
