### ISSUE TITLE
Test scripts take a lot longer to complete on success

### ISSUE THREAD

**Issue by geshan** [Shippable/support#1118]
The phpunit tests I run finishes in ~19 seconds but the script takes ~190 to finish. Is is because of the code coverage reports or whats the reason?

Actually those same tests run in a like 2 seconds in my machine. 

Please have a look:

![Slow passing script](http://s8.postimg.org/pu0olxnx1/Selection_003.png)

**Comment by geshan** [comment]
any updates??

**Comment by manishas** [comment]
@geshan sorry we haven't looked at this yet. We'll investigate this and let you know.

**Comment by geshan** [comment]
The main issue is this :https://github.com/Shippable/support/issues/349

After I remove the code coverage it still takes longer but does not timeout. It as 33 simple unit tests with PHP Unit it should not be an issue even to get the code coverage but it a timeout if I add code coverage.

**Comment by manishas** [comment]
@geshan sorry we were consumed with the new features that came out today We'll take a look at this tomorrow and try to figure out why it's taking so long to generate code coverage.

**Comment by manishas** [comment]
@geshan  here is our response from engineering. Can you try the suggestion below and let us know if it works for you? -

I think this is because of the test directory not being mentioned in the command. Customer has just given phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage

The format of phpUnit is phpunit --log-junit <file> --coverage-xml <dir> <directory> .

for eg phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage tests/calculator_test.php to run calculator_test.php.

These are the two references that I used to come up with this .https://phpunit.de/manual/current/en/textui.html#textui.clioptions , https://phpunit.de/manual/current/en/organizing-tests.html .

**Comment by geshan** [comment]
thanks for the reply @manishas and the references, I tried running 

```
- ./vendor/bin/phpunit  --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage tests
```

Still it times out though the tests ran in 1.8 minutes which without coverage takes 4.64 seconds on shippable itself. I am quite confused on this issue. For now I am doing the tests without code coverage.  There should be an easier way to do this as locally it has no problems at all.

**Comment by rageshkrishna** [comment]
@geshan Another one of our customers reported some success by using a whitelist filter for PHPUnit. Can you please try out the solution in https://github.com/Shippable/support/issues/1263#issuecomment-88907061 and see if it helps your project?

**Comment by geshan** [comment]
thanks will have a look.

**Comment by manishas** [comment]
Closing this issue. @geshan please re-open if this didnt help.
