### ISSUE TITLE
Builds hanging again and not starting....

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1130]
Perhaps yet another message processor issue?

**Comment by manishas** [comment]
Looking into it...

**Comment by avinci** [comment]
hey @chriskinsman i am seeing that everything is fine on our end. Any particular project or subscription you are having issues with?

**Comment by avinci** [comment]
i think this project, ps-common we are seeing that its YML format cannot be parsed. it was around the same time you opened the issue. Is this the right project

**Comment by chriskinsman** [comment]
Yep. Testing out triggered builds. Will look at yml

**Comment by chriskinsman** [comment]
That was it.  I figured the build would kick off and fail.  My bad.  It won't even kick off and you get a notification.  Would be nice if the notification had more details about the issue.

**Comment by avinci** [comment]
I am working on that exact bad UX right now. I have run into the same issue multiple times. Hope everything else is working out better..

**Comment by mikefeldmangh** [comment]
I'm new to Shippable but I think I might be having the same problem so I didn't want to create a new issue. When I run my build I just see "Waiting for build information..." for a really long time. If I try to cancel the build or rerun it I get a generic error. One time I got the build to kick off by logging out and back in. That's not working for me now. Is this the same problem? If it is a problem with my shippable.yml, how do I know where the problem is?

**Comment by manishas** [comment]
@mikefeldmangh are you signing in using github or bitbucket? i can't seem to find your github username in our system.

**Comment by mikefeldmangh** [comment]
Sorry. bitbucket. My username there is mikefeldman.

**Comment by manishas** [comment]
We've redesigned the UI and the yml error should be more obvious now. 

@mikefeldmangh please let me know if you need help with your build. Sorry it missed our radar :(
