### ISSUE TITLE
Build navigation is clunky and difficult

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1164]
Having moved over from Travis, I think you have the advantage because of the ability to run custom images and make use of dedicated machines.

However, the navigation/UI is behind Travis. When I am trying to find a rerun of a build, or to jump between branch/PR builds, I get horribly lost. Some thoughts in the hope that you can make it even better:

* I'm never sure when a link is going to take me to github or stay in Shippable. There is no need to link back to github because I already know how to find it.
* The Build History doesn't say the name of the PR, actually claiming it is the master branch... I'm afraid I'm not good at parsing the git-hashes!
* I expected the Pull Requests tab to show me the builds for the pull request. This view is no use to me. What I really want to do is see the latest builds for the various pull requests (and ignoring previous broken builds on each PR), against the latest commit message.
* Logs are constantly running off the bottom of the page. #1160
* A summary / status of the main branches would be nice. An "everything should be green" tab.
* ctrl-click is not opening links in new tabs..... **arrrrrrrrrrrgh!** It really should.
* The "Builds" tab summary to the left of the build console log is eating up a **lot** of screen real estate.

**Comment by manishas** [comment]
Some issues have been addressed with the new UI -

I'm never sure when a link is going to take me to github or stay in Shippable. There is no need to link back to github because I already know how to find it.
-Addressed. Clicking on a project name or org name will never take you back to github.

The Build History doesn't say the name of the PR, actually claiming it is the master branch... I'm afraid I'm not good at parsing the git-hashes!
- We now include PR commit message. So this should be addressed.

I expected the Pull Requests tab to show me the builds for the pull request. This view is no use to me. What I really want to do is see the latest builds for the various pull requests (and ignoring previous broken builds on each PR), against the latest commit message.
- This is partially addressed. You can filter the build history by pull requests, branch, etc.

Logs are constantly running off the bottom of the page. #1160
- will check this one out.

A summary / status of the main branches would be nice. An "everything should be green" tab.
ctrl-click is not opening links in new tabs..... arrrrrrrrrrrgh! It really should.
- This is done. The latest status of all branches of a project are shown on the project dashboard.

The "Builds" tab summary to the left of the build console log is eating up a lot of screen real estate.
- Addressed.
