### ISSUE TITLE
YML parser error

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1175]
Your YML parser doesn't like comments very much.

e.g. this file is considered invalid https://github.com/ensime/ensime-emacs/blob/4612c7fc228a318a71f7ba42d2097c03041a8f4f/.travis.yml

**Comment by manishas** [comment]
feedback from engineering -

The YML file on this project is being parsed correctly. I have verified that the envs, install and script commands are set up correctly for the build.

However, the build still fails because the customer is downloading and running a custom build of emacs to run the tests which expects `/home/travis/emacs-$EMACS_VERSION-bin` to exist. Our builds have $HOME set to `/home/shippable` on minv2 so they'll need to use $HOME instead of hard-coding `/home/travis`.

**Comment by fommil** [comment]
Nonsense! They are looking at the wrong failure. I'm fully aware of integration migrations with my move from travis. Do they *really* want me to create another failing case?

**Comment by fommil** [comment]
I created an isolated project to show the problem. The exact file linked from above

https://github.com/fommil/shippable-fail/blob/de710e7c83e370c99505f82339fb83a7dbcb1427/shippable.yml

produces:

```
 Error in YML for fommil/shippable-fail  Today at 10:00 AM High

Building on a dedicated node requires a build image. Specify the image to use in YML with the "build_image" tag or within your project settings.
```

**Comment by fommil** [comment]
ok, looks like you have fixed the parsing error in the meantime because it is starting up now (and getting to the expected build level errors).
