### ISSUE TITLE
Occasional Error

### ISSUE THREAD

**Issue by codeviking** [Shippable/support#1184]
Our build fails frequently with the following error:

```shell
/home/shippable/.nvm/v0.10.33/bin/npm -> /home/shippable/.nvm/v0.10.33/lib/node_modules/npm/bin/npm-cli.js
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "node" "/home/shippable/.nvm/v0.10.33/bin/npm" "update" "-g"
npm ERR! node v0.10.33
npm ERR! npm  v2.6.1
npm ERR! path ../../../lib/node_modules/npm/man/man7/npm-coding-style.7
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, symlink '../../../lib/node_modules/npm/man/man7/npm-coding-style.7'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shippable/workspace/src/github.com/allenai/parsers/npm-debug.log
Stopping services
Build completed
Skipping artifact upload
Build completed
```

Re-running the build usually resolves the issue.

**Comment by manishas** [comment]
We'll take a look at what's going on. I'll update the issue when I have more information.

**Comment by manishas** [comment]
@codeviking can you point me to a build that has failed with this error? Thanks!

**Comment by codeviking** [comment]
Here's an example:

https://app.shippable.com/builds/5508a25fe1d1e30d000b3504

Isn't this something you guys could query so that the customer doesn't have to dig it up?

**Comment by manishas** [comment]
Thanks! I could just find one example of this error in the last few days and was wondering if we were missing something since the issue said frequent failures. Other builds seem to fail with other errors.

We're taking a look into this... will update you as soon as we figure it out.

**Comment by manishas** [comment]
here's the response from our engineering -

It appears to happen because NPM is trying to rename a file but it can't find the file, but because it happens infrequently and can't be duplicated its not possible to find a solution at this time. The only possible problems that could cause this that I can think of is the minion messed up or was preoccupied. The only suggestion I have that might make a difference is instead of just updating NPM try re-installing nvm then run nvm install 0.10.33 and npm update -g

The errors here look exactly like the ones here https://github.com/npm/npm/issues/7562#issue-60153428 . There is also a solution mentioned in the comment.


Can you try the solution in the comment and let me know if it works? Thanks!

**Comment by codeviking** [comment]
So, I'm not sure what the solution involves.   Do we need to add steps to our `shippable.yml` which uninstall `nvm`, install `nvm` and then install `node 0.10.33` and `npm update -g`?  This seems like it'd slow down our builds which is not ideal.

Also, I'll add that we *never* see this behavior on our local machines or dedicated servers -- we *only* see it in the shippable environment, leading me to believe it has something to do with your guys configuration / setup.

Please advise.

**Comment by manishas** [comment]
Follow up from our engineer... let me know if it makes sense. -
------
1. The problem here is with npm. As mentioned here https://github.com/npm/npm/issues/7562#issue-60153428 . An `npm update -g` which was supposed to install a newer version of npm will actually uninstall npm on our system if something went wrong while updating.
2. To overcome this, instead of using `npm update -g`, it would be better if we use `curl -L https://www.npmjs.org/install.sh | sh` which will also install the latest version of npm without any issues. 
 For Example:
![selection_194](https://cloud.githubusercontent.com/assets/1583444/6828820/b664e5ba-d335-11e4-846f-aef5002233d8.png)

------
Also, an explanation of why you dont see it locally -

I believe that the older versions of npm might have a bug which is does this. The later versions might not have this and they might work well.

It doesn't happen on their local system because they already will have a version of npm which runs their build succesfully and there will be no necessity of running npm update -g everytime and hence they dont see this on their system.
-------

**Comment by codeviking** [comment]
The reason for the error still doesn't make sense to me, as we run `npm update -g` on machines without issue.

That said, the core reason for my confusion is that it was your team that had us add the `npm cache clean` and `npm update -g` calls to our `shippable.yml` file:
```
before_install:
  - nvm install 0.10.33
  - nvm use 0.10.33
  - npm cache clean
  - npm update -g
```

I never understood the reasons for these steps originally -- so should we replace them with the command you mentioned or remove them entirely?

**Comment by codeviking** [comment]
After digging deeper, we're simply proceeding with removing `npm update -g` (which your team told us to add to our builds).  Conceptually it doesn't make sense, as we'd like our build server to match our production environments as closely as possible, meaning we'd like to install as very specific version of node (and accordingly a specific version of npm).

I'll let you know if we continue to see the issue -- I'd also appreciate any insight into why your team feel it's advisable to run `npm update -g` with each build.

**Comment by manishas** [comment]
Closing this issue since the occasional error issue has been resolved.
