### ISSUE TITLE
Cannot start Elasticsearch?

### ISSUE THREAD

**Issue by Repox** [Shippable/support#1187]
I'm trying to add some mappings and Groovy scripts to Elasticsearch. When this is done, trying to start Elasticssearch results in the following:

    sudo mkdir /etc/elasticsearch/scripts
    sudo mkdir /etc/elasticsearch/templates
    sudo cp ansible/elasticsearch/files/*.groovy /etc/elasticsearch/scripts/
    sudo cp ansible/elasticsearch/files/mappings.json /etc/elasticsearch/templates/mappings.json
    sudo /usr/share/elasticsearch/bin/elasticsearch &
    sleep 10
    sudo service elasticsearch restart
        * Starting Elasticsearch Server
    error: "Read-only file system" setting key "vm.max_map_count"
         ...done.

My `shippable.yml` looks like the following:

		---
		language: php

		#build_image: shippableimages/ubuntu1404_php

		php:
		 - 5.5

		services:
		 - mysql
		 - redis
		 #- elasticsearch
		 - rabbitmq

		addons:
		  hosts:
		    - api.letszebra.com

		before_install:
		  - composer self-update

		before_script:
		  - sudo apt-get update
		  - cp .env.shippable .env
		  - sudo mkdir /etc/elasticsearch/scripts
		  - sudo mkdir /etc/elasticsearch/templates
		  - sudo cp ansible/elasticsearch/files/*.groovy /etc/elasticsearch/scripts/
		  - sudo cp ansible/elasticsearch/files/mappings.json /etc/elasticsearch/templates/mappings.json
		  - sudo /usr/share/elasticsearch/bin/elasticsearch &
		  - sleep 10
		  - sudo service elasticsearch restart
		  - mysql -e 'create database zebra;'
		  - composer install --prefer-dist
		  - php artisan clear-compiled
		  - php artisan migrate --seed

		after_script:
		  - sudo service elasticsearch stop

		script:
		 - vendor/bin/phpunit

		notifications:
		  email: false

**Comment by manishas** [comment]
@Repox I looked up this error and it seems to me that to start elasticsearch the way you want to, you'll need to have a docker container running in privileged mode.

http://stackoverflow.com/questions/28936090/in-docker-container-im-seeing-read-only-filesystem-error
https://github.com/docker/docker/issues/5703

Our multi-tenant build containers do not run in privileged mode. However, you can use dedicated hosts with Shippable and you can run privileged containers on those hosts since they are dedicated for your builds. More details at - 
http://blog.shippable.com/dedicated-hosts-
http://docs.shippable.com/en/latest/config.html#dedicated-hosts

Let me know if this helps.

**Comment by Repox** [comment]
Well, I tried running it as priviliged on a dedicated host, but no luck. I scripted my way out of it instead.
