### ISSUE TITLE
Problem with installation of Percona Server

### ISSUE THREAD

**Issue by stekycz** [Shippable/support#1188]
Hi,

I uses my GitHub username stekycz on Shippable. I have tried to run tests for my project using Percona Server database. However the build freezed on purging mysql configuration.

**Script:**
```shell
sudo apt-get remove --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
```

**Output:**
```shell
...
Removing mysql-client-core-5.5 ...
Removing mysql-common ...
Purging configuration files for mysql-common ...
Removing mysql-server-5.5 ...
Purging configuration files for mysql-server-5.5 ...
```

Thank you for some advise

**Comment by manishas** [comment]
@stekycz can you send me a link to the frozen build? I cannot seem to find it in our system.

**Comment by pilec** [comment]
@manishas  Here it is: https://app.shippable.com/builds/550b051eb28fe00d0038fccc

**Comment by stekycz** [comment]
@manishas Once more https://app.shippable.com/builds/550feddc21d6a90b00367ccc

**Comment by stekycz** [comment]
@manishas I have moved somewhere else! However it is still freezed on configuration changes during installation https://app.shippable.com/builds/5511727d5b59870c00c0cd0c . Previous builds have tried to purge configuration after removing. Is it possible there is some problem with changing of configuration files?

**Comment by manishas** [comment]
@stekycz here is the response from our engineers -

Adding DEBIAN_FRONTEND=noninteractive to the command, so it is sudo DEBIAN_FRONTEND=noninteractive apt-get remove --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5, will allow the script to continue (tested by putting it in an otherwise empty script file and using that file in the script section of shippable.yml). However, I have not found how to specify if the MySQL databases should be removed or not. http://unix.stackexchange.com/questions/106552/apt-get-install-without-debconf-prompt

**Comment by stekycz** [comment]
@manishas Yes, it helped! Thank you :-)
