### ISSUE TITLE
Git sync from bitbucket.org - wrong directory

### ISSUE THREAD

**Issue by muizsyed** [Shippable/support#1226]
As part of the git_sync process, when its cloning its cloning into wrong directory, looking at the output in git_synce it does this

git clone ssh://git@bitbucket.org/username/project.git /root/workspace/src/bitbucket.com/username/project'

You can see its changed from bitbucket.org to bitbucket.com

I dont know if its related to this
https://github.com/Shippable/support/issues/476

**Comment by vially** [comment]
Any update on this?

This is causing issues when working with Go projects because the import paths are "bitbucket.org/username/repo".

Given that bitbucket.com redirects to bitbucket.org I think clonning into `~/workspace/src/bitbucket.org` should be the default without having to set any environment variables.

**Comment by muizsyed** [comment]
Hi vially, I fixed this by adding the following to shippable.yml

env:
  global:
  - SHIPPABLE_REPO_DIR="$HOME/workspace/src/bitbucket.org/$REPO_NAME"
  - TRAVIS_BUILD_DIR="$HOME/workspace/src/bitbucket.org/$REPO_NAME";

**Comment by vially** [comment]
@muizsyed Thanks for the reply.

That seems to fix it for me as well, although I still think that `SHIPPABLE_REPO_DIR` should default to that value without having to define it explicitly.
