### ISSUE TITLE
Connection refused to neo4j

### ISSUE THREAD

**Issue by MarneeDear** [Shippable/support#1253]
I keep getting connection refused to neo4j.
Below is my yml.  I have neo4j specified as a service.  How can I check if it is running?  

It fails on the first line of seed_database.py where it just tries to get the version of neo4j using the default URL:  http://localhost:7474/db/data/

print Graph().neo4j_version

    # build image from Docker Hub
    build_image: shippableimages/ubuntu1404_python
    language: python
    python:
      - "2.7"
    services:
      - neo4j
    # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
    install:
        - pip install -r requirements.txt
    before_script:
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - mkdir -p shippable/testresults
        - mkdir -p shippable/codecoverage
    # command to run tests, e.g. python setup.py test
    script:
        - python misc/py2neo_2.0_samples/seed_database.py test'

**Comment by manishas** [comment]
@MarneeDear you're using the python specific base image which does not come with any services or tools preinstalled. You'll need to install neo4j in your yml and then start it. 

If this drives up your build time, you can consider turning on caching with a cache: true in your shippable.yml so that the installs get cached for subsequent builds.

**Comment by MarneeDear** [comment]
Ok I understand.  It seems to be ok now.  I will try caching as well.  Thank you.
