### ISSUE TITLE
Can't cd to folder

### ISSUE THREAD

**Issue by pcullin-ratio** [Shippable/support#1270]
I'm attempting to build a NodeJS project that uses npm scripts to generate a "deploy" folder and copies content into it for eventual scripted deployment to a service (Iron.io). However, once the folder is created the build fails because it can't cd into the newly created folder. Is there something specific I have to do in my npm scripts to enable this? I'm using the mkdirp and ncp npm modules for folder creation and file copying in my project. They are both installed locally in the project via npm install prior to running my custom npm scripts from package.json. The scripts work fine on my local machine, but I'm using Windows.

**Comment by manishas** [comment]
@pcullin-ratio can you share your shippable.yml? Thanks!

**Comment by pcullin-ratio** [comment]
Sure, here it is along with my NodeJS project’s package.json file. I’ve been making a lot of changes to these two files lately, so they may not be in the best state…but hopefully enough to provide context into what I’m attempting to do.

I looked into similar issues in your Github issues list that allude to the fact that a “cd” in one stage of a Shippable build doesn’t persist to further steps. But I’m trying to “cd” in a single npm script, so am hoping this isn’t the case for me. That would make my npm scripts really tough to write…

-Paul

**Comment by pcullin-ratio** [comment]
Unfortunately this has become a blocking issue for me. Is there any way to prioritize assistance?

**Comment by manishas** [comment]
I'll ask someone to take a look as soon as they can.

**Comment by manishas** [comment]
@pcullin-ratio i dont see your yml or json files. can you please send them to me at manisha@shippable.com?

**Comment by rageshkrishna** [comment]
Hi @pcullin-ratio! Can you point me to a build on Shippable where this is happening? I tried to find a similar failure in your recent builds but I can't seem to find any with the failures that you've described. A build ID would be very helpful to debug this quickly. Thanks!

**Comment by rageshkrishna** [comment]
@pcullin-ratio, I missed the part where you said you were running Windows! It looks like the problem is that `&` works differently in cmd and bash.

In cmd, `&` separates commands but they only run one after the other, whereas in bash it causes the preceeding command to run in the background and the next command launches immediately.

I suspect that your `cd ./deploy/core` is running before the `ncp core ./deploy/core` even begins to copy things.

Please try replacing all the single ampersands with double ampersands in your package.json file's `scripts` section.

**Comment by pcullin-ratio** [comment]
You're correct, that appears to be the issue - thanks!
