### ISSUE TITLE
Not able to start cassandra service

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#1288]
I mentioned 'cassandra' as service in shippable.yml and having trouble in running 
cassandra-cli -host 127.0.0.1 -port 9160 -f schema.txt

It says cassandra-cli command not found.

Build id - 55259fa5bd14530c001ebab5

**Comment by manishas** [comment]
@phagunbaya we do not preinstall tools or services on language specific images. Docs at http://docs.shippable.com/en/latest/custom_images.html#language-specific-images

You will need to install cassandra in your shippable.yml to use it.

**Comment by phagunbaya** [comment]
@manishas : 
1. What will be the setup cmd look like ? Will yum work or anything that is shippable specific ?
2. Then whats the use of mentioning service in yml file. I can just remove it right ?

**Comment by manishas** [comment]
I will ask someone to help with the install command. 
As for the services tag in the yml, you can use it with our default image since all tools and services are preinstalled on it. If you're specifying a different build image in the yml, you will need to install the tools and services you need for your builds and tests.

**Comment by phagunbaya** [comment]
@manishas : Waiting for the help.

**Comment by manishas** [comment]
@phagunbaya sorry for the delay on this.... did you still need help with installing cassandra?

**Comment by phagunbaya** [comment]
@manishas : No Thanks, we moved to something else. Closing the request.
