### ISSUE TITLE
Heroku deploy fails because of old Ruby version

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1305]
My build is configured to deploy to Heroku using the suggested method:

```
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.heroku
heroku keys:add ~/.ssh/id_rsa.heroku
heroku git:remote --ssh-git --app $APP_NAME
git push --force heroku $HEAD_BRANCH:master
```

Upon adding the key, the build results in this error message and fails:

> Heroku Toolbelt requires Ruby 1.9+.

How can I get a newer version of Ruby for my builds?  I am developing in Node and not using a special image to build off of.

Thank you.

**Comment by manishas** [comment]
@jeffkole  This is happening because the language set in the yml is node, so the right version of Ruby isn't being invoked.

Can you try the following suggestion -
Use rvm to switch to the supported ruby version and then run the commands. So, add the following line to the `before_install` section : 
```. $HOME/.rvm/scripts/rvm && rvm use ruby-2.0.0-p598 --default && ruby --version```

The heroku push will use ruby 2.0 later in the script

**Comment by jeffkole** [comment]
That did the trick.  Thank you.
