### ISSUE TITLE
Enable cache in travis config

### ISSUE THREAD

**Issue by philipp-spiess** [Shippable/support#1318]
Shippable can run my travis config very smoothly, yay! But I'd like to enable the image cache so I added the `cache: true` to my newly created `sippable.yml`. Turns out that it's completely ignoring my `.travis.yml` now.

Is there a way to mark a build as cacheable without losing the ability to use my `.travis.yml` file?

**Comment by manishas** [comment]
@philipp-spiess we use the shippable.yml if we find it, and travis yml if there is no shippable.yml. So there is no way to 'combine' the two since the configs aren't additive.

However, I can suggest a workaround for your scenario since we have a 'cache' option in the UI as well.

You can do the following -
- Go to Settings tab for the project
- Use the following settings 
    * build image - custom image
    * custom image action - pull
    * custom image name - shippable/minv2
    * check the 'cache build container' option

This should do what you need.

**Comment by manishas** [comment]
Closing this issue. Please let us know if we can help further.
