### ISSUE TITLE
repos list does not include private repos

### ISSUE THREAD

**Issue by hackerhasid** [Shippable/support#1334]
i just signed up for shippable using my github account. i have a private repo that i'd like to build. it belongs to an organization (which i have admin access over) and i've also forked it under my personal account.

i would expect the repo to display in shippable's list of repos for both myself and my organization. however it does not display for either. in fact it seems that only public repositories display on the website for both myself and my organization.

## This list does not include any private repos:

![the list of repos i'm talking about](https://cloud.githubusercontent.com/assets/797379/7236522/7fce5684-e763-11e4-9809-9655afc52252.png)

**Comment by manishas** [comment]
@hackerhasid you will need to authorize shippable for private repo access in order to enable private repos.

Please click on the 'Private repos off' icon on your Shippable dashboard and grant us permissions.
![screen shot 2015-04-20 at 11 07 18 am](https://cloud.githubusercontent.com/assets/2983749/7237040/8d7c99e6-e74d-11e4-8315-46ad45b468b5.png)

**Comment by hackerhasid** [comment]
when i originally signed up (with github) i am pretty sure i gave private permission. it is possible i didn't - there was a long list of perms and i might not have read it completely - but something to look into maybe

**Comment by manishas** [comment]
we'll keep an eye out for similar issues. i hope everything shows up now... closing this issue.
