### ISSUE TITLE
Private repository collaborators cannot view build

### ISSUE THREAD

**Issue by markschaake** [Shippable/support#1335]
We have a private repository allenai/s2-data which builds via Shippable. A collaborator cannot see the build details when logging in with his github account (his GH username is @severian). 

Some more potentially relevant details:

- The collaborator is a member of a team that has Write access, which says: "This team will be able to read its repositories, as well as push to them."

- An example build that he could not view: https://app.shippable.com/builds/55357821b9b42c0b00e2aa5d. He was prompted with "The build you're looking for wasn't found."

- The repository was recently (a couple of weeks ago) renamed. It used to the allenai/s2-crawler, and is now allenai/s2-data

**Comment by manishas** [comment]
@markschaake he cannot see private repos since he hasn't given us permissions for private repos -

![screen shot 2015-04-23 at 11 56 37 am](https://cloud.githubusercontent.com/assets/2983749/7305025/dd01c2e8-e9af-11e4-9f0a-26adccca2c06.png)

He can click on the 'private repos off' icon on the dashboard and go through the flow to give Shippable permission. He can then click on 'sync account' on his dashboard and he should see private repos then.

Please reopen if this doesn't work...
