### ISSUE TITLE
Random time-out in builds 

### ISSUE THREAD

**Issue by marcogario** [Shippable/support#1355]
In the last 2 weeks we have been experiencing random time-outs during our builds.
We have multiple configurations, and usually 1 or 2 configurations will time-out during a build. Restarting the build might lead to a different set of configurations timing out. Sometimes, after a few restarts, we manage to get them all to pass.

This [1] is an example of build that run into timeout. Notice that the build log is empty.

Thanks,
Marco

[1] https://app.shippable.com/builds/553a256dbf6d0a0c00523d56

**Comment by bbradbury** [comment]
Yup, been seeing this since last night. My suspicion would be that docker is borked on one physical host-- I am able to have success by kicking off builds in quick succession, which I bet is getting load balanced onto different physical hosts.

Currently stuck: https://app.shippable.com/builds/553a75fac9831c0c004dac1e
Currently working: https://app.shippable.com/builds/553a76c5c9831c0c004dac32

**Comment by manishas** [comment]
This should not be happening any more. Please re-open if you're still experiencing timeouts.
