### ISSUE TITLE
Cannot pull docker image from Docker hub

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1372]
For some reason the image can no longer be pulled from Docker hub on a dedicated host

![screenshot 2015-04-28 15 38 21](https://cloud.githubusercontent.com/assets/2778689/7370837/051ba4fe-edbd-11e4-8f0f-cd4e61691cb7.png)

**Comment by manishas** [comment]
@rogierslag this will be fixed today. sorry for the inconvenience!

**Comment by rogierslag** [comment]
:+1:

**Comment by alexanderlamb** [comment]
+1

**Comment by bradenstenning** [comment]
Hi, I am curious if this issue has been resolved because I am seeing something similar in the buildimage step. If this has been resolved, or it looks like a separate issue, please let me know and I can move my comment.

Output at line that fails:

    sudo docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag="companyrepo/firepit:master.17" .;
        |1431101887
        Sending build context to Docker daemon 557.1 kB
        Sending build context to Docker daemon 780.3 kB
        Sending build context to Docker daemon 
        Step 0 : FROM companyrepo/nginx:cutting
        Pulling repository companyrepo/nginx
        time="2015-05-08T16:18:07Z" level=info msg="Error: image companyrepo/nginx:cutting not found" 

It could just be that I am using this wrong or in a way that is not intended.

In this case I am trying to follow the Post CI Dockerbuild process and I have three private docker repos involved. 

1. ```companyrepo/node:rvn``` A repo with the CI environment (with node and various other tools)
2. ```companyrepo/nginx:cutting``` A repo used as a base for the docker image we are trying to build (a custom build of nginx)
3. ```companyrepo/firepit``` A repo where we will push the image we build (custom nginx + production artifacts from CI)

It looks to be failing when trying to pull from 2 as part of the docker build for 3. This step works on my local machine with the same login credentials. And the pull step works for 1 in earlier parts of the Shippable process. Is it possible the credentials aren't reused in the buildimage step?

Really liking the dedicated host functionality so far, nice work! Thanks for your help!

**Comment by manishas** [comment]
@rogierslag this is working now, so closing. 

@bradenstenning sorry for the delay in responding. Are you still running into this? Please open a new support issue if so.

**Comment by bradenstenning** [comment]
@manishas Thanks, whatever you fixed did the trick!
