### ISSUE TITLE
Speeding up Go 1.4 install

### ISSUE THREAD

**Issue by mbrevoort** [Shippable/support#1388]
The longest part of my Go build is installing Go 1.4. How do I speed this up? 

![screen shot 2015-04-29 at 11 02 46 am](https://cloud.githubusercontent.com/assets/30455/7396604/ac9b85e4-ee5f-11e4-90d4-2f77c90b34b0.png)

**Comment by manishas** [comment]
@mbrevoort you can cache your builds - just include ```cache: true``` in your yml. Caching mechanism is explained here - http://blog.shippable.com/container-caching

You can also use our custom go image - shippableImages/ubuntu1404_go. Details on custom images are [here](http://docs.shippable.com/en/latest/custom_images.html#language-specific-images) and the Dockerfile for ubuntu1404_go is [here](https://github.com/shippableImages/ubuntu1404_go/blob/master/Dockerfile)

Please note that with language specific images, you'll need to install any services or tools in the shippable.yml since they are super light weight and only come with the language versions preinstalled.

**Comment by mbrevoort** [comment]
great, I'll try that. Thanks!
