### ISSUE TITLE
Build fails on `npm install --quiet`

### ISSUE THREAD

**Issue by markschaake** [Shippable/support#1412]
We have a build that has now failed in 3 attempts, twice for failure executing `npm install --quiet` and once for failure to resolve a `netty` dependency. Here is the third build: https://app.shippable.com/builds/5549042f42da970c000f2956

**Comment by lekhab** [comment]
Apologies for the delay in getting back on this. I do have some info on this from our engineering team -

This uses multiple languages within a container which is not something we support currently. 

Since this is a scala build on minv2, we don't initialize nvm.  This means the wrong npm is being called (the one that's in /usr/bin/npm). This can only work if either (1) npm is invoked with sudo, or (2) you source nvm and do `nvm use {node-version}` in before_script.

Closing this for now. Please let us know if you have any further issues.
