### ISSUE TITLE
Removed docker from shippable/minv2:latest yesterday?

### ISSUE THREAD

**Issue by mbrevoort** [Shippable/support#1418]
We had been able to `docker build` and `docker push` from within `shippable/minv2:latest` until yesterday. 

Before yesterday:
![screen shot 2015-05-06 at 10 34 56 am](https://cloud.githubusercontent.com/assets/30455/7498094/9a97be18-f3db-11e4-8d53-ca10c9127cdc.png)

Since yesterday:
![screen shot 2015-05-06 at 10 34 34 am](https://cloud.githubusercontent.com/assets/30455/7498101/9f5e135c-f3db-11e4-879b-b747e45537a4.png)

Was this change intentional? Our whole workflow is broken now :(

**Comment by manishas** [comment]
@mbrevoort yes, this is intentional. We do not support dockerbuild from within minv2 and it was working because of an oversight.

Our official support for dockerbuild is through dedicated hosts and is documented here - http://docs.shippable.com/en/latest/docker_build.html#dockerbuild 

We do plan to allow a much easier workflow for dockerbuild in the next few weeks, let me know if you are interested in additional details.

**Comment by mbrevoort** [comment]
@manishas yes, I am interested in those details ASAP. All of our builds are broken right now because of this change, will start down the dedicated host route :/

**Comment by mbrevoort** [comment]
Closing this issue. I have docker builds and pushes working from dedicated hosts.
