### ISSUE TITLE
Handling multiple projects in a single repository

### ISSUE THREAD

**Issue by marcua** [Shippable/support#1420]
It looks like `shippable.yml` must be in the root of the git repo.  Say I have one large repository with multiple codebases (e.g., two django projects, or some python code and some js code), and for concreteness let's say they are in `gitrepo:/python_project1` and `gitrepo:/python_project2`.  The questions that arise for me are:

  - How do I get tests in both directories to run---can I have multiple `script` and `install` tags for each project?
  - Will the coverage and test reports for each project be reported separately?

If you have an example `shippable.yml` that handles this case, I'd be very grateful!

**Comment by manishas** [comment]
@marcua we do not support this case today. Is there a reason you have multiple projects in the same repo?

**Comment by thiagonache** [comment]
I've the same case of use.
The main reason is avoid build a gem server (talking about ruby on rails applications).
We are adopting use of microservices, but until it get on production will take a while.

it would be useful for us too.

**Comment by manishas** [comment]
This is not on our near term radar, so closing as deferred.

**Comment by buckett** [comment]
Could I just say it would be helpful for us to have multiple projects be allowed in a single git repository.

**Comment by trriplejay** [comment]
The best way to do this today would be to create an [assembly line](http://docs.shippable.com/platform/workflow/config/#assembly-lines-configuration). Each project within the repository can have its own [runSh job](http://docs.shippable.com/platform/workflow/job/runsh/) (or one runSh job that handles all projects) using the [gitRepo resource](http://docs.shippable.com/platform/workflow/resource/gitrepo/)  as an input.  You could also utilize the [get_git_changes](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#get_git_changes) shipctl function to determine which directories changed in a commit or PR, so that you know which project to test for any given wehbook.
