### ISSUE TITLE
Deployments Triggered On Pull Request

### ISSUE THREAD

**Issue by leroyjware** [Shippable/support#1424]
We're using the following to restrict deployments so that they only occur when commits are made to master:
branches:
  only:
    - master
after_success:
  - if [ "$BRANCH" == "master" ]; then aws deploy create-deployment --application-name AirClassDev --github-location repository=$REPO_NAME,commitId=$COMMIT --deployment-group-name Dev; fi

Unfortunately, it seems that the deployments are being triggered for ALL pull requests to master, no just for commits to master (which is what we assumed would be the case). Is this a bug on your end?

**Comment by manishas** [comment]
@leroyjware this is because when we build a PR to master, the BRANCH variable is set to master.

We will look into whether this behavior needs to be changed, however the workaround for it is to change the statement above to  -

if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ] ; then aws deploy create-deployment --application-name AirClassDev --github-location repository=$REPO_NAME,commitId=$COMMIT --deployment-group-name Dev; fi

**Comment by manishas** [comment]
Let me know if the above works for you.

**Comment by leroyjware** [comment]
Yes, it does. Thanks.
