### ISSUE TITLE
bundle install running on cached projects

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#1458]
I have a number of projects with cache enabled and a long history of builds, but `bundle install` still runs almost every time.

See the last 6 builds here: https://app.shippable.com/projects/540f3942586ac5d7e36513de

thanks

**Comment by manishas** [comment]
@jamesmk your cache might have been reset and it takes a few builds for it to catch up on all hosts. We also added some hosts recently, so that could be another issue. We just kicked off a build and it used the cache...

Give it a few builds and if you still see problems with caching, we'll take a deeper look.

**Comment by manishas** [comment]
Closing. If the caching doesn't kick in reliably within the next 5 builds, please re-open. Thanks!

**Comment by beydogan** [comment]
Its 6th build in my project and still installing all gems.

**Comment by manishas** [comment]
Closing this issue. I see cache being picked up for the latest builds. Please comment or reopen if you're still seeing issues.

**Comment by jamesmk** [comment]
I'm still seeing this issue in other projects. Here's a project who's latest 6 builds (95-100) have done a full bundle install each time:
https://app.shippable.com/projects/5547b231edd7f2c052df6639

In general about 50% of our builds across multiple projects take 10-20mins due to full bundle installs each build. This isn't acceptable at the rate in which we deploy.
