### ISSUE TITLE
Are build numbers configurable?

### ISSUE THREAD

**Issue by lukehutton** [Shippable/support#1465]
i.e. can I reset a build number for a certain repository to a number or do they always start at 1?

**Comment by manishas** [comment]
No, you cannot specify a build number.. they always start at 1. What is your use case for specifying a build number?

**Comment by KaizenCode** [comment]
We are migrating from another CI tool that already has build numbers in place, and we don't want build numbers to overlap between between the two.

**Comment by manishas** [comment]
@KaizenCode Thanks for the clarification. At this point, you cannot start from a random build number. I'll keep this in mind and if we hear the feedback again, we can revisit.

Thanks and let me know if you have any other questions.

**Comment by peterhav** [comment]
Hello, functionality to configure the build number is also a requirement for me. Use case: possible migration from another CI solution and using build numbers within the version of my releases. Since I'm on build 1006, when migration to Shippable, I would have to launch 1005 builds for nothing, or change my approach of version numbering (which is something that works really well for me).
