### ISSUE TITLE
Google App Engine deployments failing from the minion

### ISSUE THREAD

**Issue by aproxs** [Shippable/support#1481]
I have a deployment script in my repo "build/deploy_app.sh", with the following line:

echo "$SECRET" | $GAE_DIR/google_appengine/appcfg.py -e "$EMAIL" --passin update moduleone1.yaml moduletwo.yaml

where:
 - SECRET and EMAIL are secure variables and GAE_DIR is correct.

If I run exactly that command in my local computer, the deployment goes fine
However, when the minion runs that command I get the following output:

03:15 AM Host: appengine.google.com
03:15 AM Application: applicationID; module: moduleone; version: 1
03:15 AM 
Starting update of app: applicationID, module: moduleone, version: 1
03:15 AM Getting current resource limits. 

an hour after, the deployment times out, but I get nothing else.

I have no clue what's going on... :(. Is this isolated to me? or is it a known issue?

**Comment by aproxs** [comment]
@manishas, more than a question, this is a bug for you folks.

I literally can't deploy to GAE with shippable...

**Comment by aaronwest** [comment]
@aproxs I've been working on getting GAE deployments setup with Shippable using appcfg.py. In short, I've run into many issues all pertaining to attempting to get the website synchs setup without user intervention.

I was actually searching the issues here for anything related to `appcfg.py` hoping someone had solved what I'm running into. I don't see any solutions so I'm going to log an issue in a moment.

In the meantime, I have seen the behavior you are seeing.

>03:15 AM Getting current resource limits.

I ran a few builds which hung on this exact same step for over 20 minutes. I finally cancelled the build(s) on Shippable. When trying to replicate the behavior on my Mac I realized appcfg.py was waiting for user input. In my case, the program was requesting an "verification code" because I was attempting to run appcfg.py with `--noauth_local_webserver` per the Google docs. What GAE was expecting here, was for me to copy the link in the terminal and load it in a browser in order to get an a verification code I could copy and paste into terminal. In other words, `--noauth_local_webserver` doesn't bypass authentication it just forces the end user to load a URL in the browser instead of the program launching the URL on its own.

I explain all of that not because I believe that is what you are experiencing exactly. But I do believe your program is hanging waiting on user input.

For comparison purposes I'm running GAE SDK v1.9.24 on Mac OS X 10.10.4. The Shippable deployment was done with image *shippableimages/ubuntu1404_base*.

**Comment by aaronwest** [comment]
I wrote about my issue getting GAE deployments working here #1756. Posting a reference in case it is helpful to others.

**Comment by aproxs** [comment]
Hmmm,

Were you trying to use oauth2? or were you doing username/password?

My configuration was using username/password that were coming to the deployment phase via encrypted secrets. In that case, there should not be a prompt from appcfg.py as it has everything it needs.

In any case, I'm not passionate about the idea of having the username/password in the script (even if encrypted) so seems that my only option is to create my own docker image and supply it with the necessary authentication tokens.

That said, I'm a bit annoyed that @manishas / Shppable are mute about this...

**Comment by aaronwest** [comment]
@aproxs I tried both methods actually. I was never successful getting un/pw authentication working but I didn't try it long as I don't want deployments tied to my Google Apps account. Our engineering team needs to be able to deploy via Shippable and having my un/pw baked into the deployment process is bad juju™.

I have a workable solution right now using OAuth though I admit it isn't sexy. In fact, it's downright egregious by most dev standards. In short, I copied a working `appcfg_oauth2_tokens` token file from my Mac and put it in my repo. During the Shippable build process I copy the token from my website files which get stored on the Docker container at `$SHIPPABLE_REPO_DIR`. appcfg.py reads the token and allows the update of the site to execute without user intervention.

Awesomely, it doesn't matter how old the oauth2 token is either. GAE sees a token exists, updates it with a new expiry value and allows the update process to work. This is exactly how the same update process would work if you ran it on your own computer with a long series of days in between calls to `appcfg.py update`.

At the end of the process I delete the token for good measure even though the Docker container is destroyed. Just makes me feel better.

The whole solution is less than ideal and not something I want in play long-term. As soon as there's a better way to have unattended GAE site updates, without using a username/password combo, I'll nix what I'm doing.

**Comment by lekhab** [comment]
@aproxs - apologies for the lack of response here. Unfortunately, we haven't had the resources to dig into this a lot. @aaronwest: Thank you so much for your contribution here and hopefully the temporary solution will work for others as well, until we can prioritize this. 

This is something we will have to prioritize internally to allow for deploy to GAE to work natively within Shippable. Tagging this as a feature request.

**Comment by manishas** [comment]
Closing this since there is nothing actionable to do here.
