### ISSUE TITLE
How To Revert To build_image In shippable.yml?

### ISSUE THREAD

**Issue by jchamberlain** [Shippable/support#1515]
The settings panel under a project warns that its settings will override those in the shippable.yml. The build image, however, cannot be left empty. I must have previously set a build image, because I can't get it to use the one specified in my shippable.yml and am instead stuck setting it project-wide in the settings panel. This is a problem because I need to use a different image for one branch of my code, as reflected in its shippable.yml. Thoughts?

**Comment by soby** [comment]
+1, need to revert this to a blank field so the setting in my shippable.yml files will be honored

**Comment by manishas** [comment]
@jchamberlain @soby clicking on the track icon just below project settings should reset them. please let me know if this is not happening.

i tagged this as a feature request since you're asking for a per branch build image setting. We're going to deprecate the build_image tag in the yml so we'll find a way to address this requirement.

**Comment by jchamberlain** [comment]
Yes, that appears to work. The per branch setting would be nice.

**Comment by manishas** [comment]
With our latest upgrade, you will be able to use different build images depending on branch if you configure the yml to handle this case.

New yml is documented at http://docs.shippable.com/ci_configure/. All accounts will be migrated to the new system in the next 72 hours.

**Comment by manishas** [comment]
this is complete. closing.
