### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by hranicka** [Shippable/support#1543]
The first public alpha of PHP 7 was released.
http://php.net/archive/2015.php#id2015-01-11-6

Do you plan support for early PHP 7 versions?
Or waiting for final builds?

Thank you for support!

There is only current stable versions support and HHVM:
http://docs.shippable.com/languages/#php

**Comment by robertboloc** [comment]
I'm also interested in PHP7 support. Thanks!

**Comment by claar** [comment]
Yes please.

**Comment by davidkalosi** [comment]
yes please. php7 is nearing it's debut and now is the right time to start testing our existing apps with the new engine.

**Comment by pogotc** [comment]
PHP 7 please!

**Comment by bigfoot90** [comment]
+1

**Comment by claar** [comment]
Less than 2 months left for PHP 7 to be released, planned for November 12th.

https://wiki.php.net/todo/php70#timetable

**Comment by claar** [comment]
PHP 7 is now released https://news.ycombinator.com/item?id=10661997

**Comment by hranicka** [comment]
Shippable, is any progress or plans for PHP 7 support? Thank you!

**Comment by gielwijgergangs** [comment]
+1

**Comment by mbrodala** [comment]
Now that PHP 7 was released, this should be added to the Shippable build environment as soon as possible.

**Comment by davidkalosi** [comment]
ping ... :)

**Comment by megawubs** [comment]
+1

**Comment by hranicka** [comment]
PHP 7.0 RC1 was released a few months ago (21 Aug 2015),
PHP 7.0 stable a few weeks ago (3 Dec 2015).

Official `shippable/minv2` Docker image (default) does not support PHP 7 even today and I cannot find any information about date when it will be supported.

So [I've made custom Docker image](https://github.com/phpdocker/phpdocker) with PHP 5.6 or PHP 7.0, composer, MariaDB, ...
and [run Shippable on it](https://bitbucket.org/artfocus/composer-sandbox/src/master/shippable.yml?at=master&fileviewer=file-view-default).

**Comment by claar** [comment]
I don't understand why Shippable doesn't update their base image. I've been requesting npm, php, and various other updates to the image for ages.

Their answer is always to use a custom docker image, which makes no sense to me. Why should hundreds (thousands?) of customers spend hours (days?) building custom docker images, rather than Shippable updating the default image? I can't imagine how many customers this loses them. This makes me sad, as I've been a paying customer for a long time, but enough is enough.

**Comment by hranicka** [comment]
Yes, their answers don't sounds good, eg. [old composer version from Nov 2014](https://github.com/Shippable/support/issues/1321). Answer: Do composer self-update and cache container.

Sad.

Shippable, but what about core apps like php, npm etc.?

Do you have any roadmap and should we expect updates? When?

Shippable is awesome service (we use BitBucket and private repositories). But an old Docker image (not-updated indeed) is a huge negative aspect :(

**Comment by manishas** [comment]
@claar @hranicka let me try to provide some insights into why we did not update our base image and what we're doing to address it.

When Shippable started out, we decided to provide an easy way for Travis users to onboard on our platform by accepting a .travis.yml file as-is, and creating a base image (minv2) with all versions of supported languages, services, and tools. At first, this worked great. However, minv2 became very bloated over time and is currently a 15GB image which takes over 20 hours to build. It became very tedious and unwieldy to build it each time there was a new request. So, that is the problem in a nutshell.

We told users to build and use their custom Docker images since it wasn't feasible for us to build specific images for each use case. Docker users love this since they have complete control over their build image. However, since not all of our customers are Docker users, we do understand that this is a big pain point for them.

What are we doing about it? To start with, we are building language specific images which include latest versions of supported services and tools. A typical image like [u14nodall:prod](https://hub.docker.com/r/drydock/u14nodall/tags/) will be ~2GB and isn't as unwieldy as minv2 and hence easier to maintain. We are currently testing these images and making sure they are production ready. You can find the image Dockerfiles in our [dry-dock github repo](https://github.com/dry-dock) and the images in the [dry-dock repo on docker hub](https://hub.docker.com/u/drydock/). Any image marked with the ```prod`` tag is fully tested. We expect all these images to be completely tested by Jan 15.

Moving forward, we will commit to refreshing these images with the latest versions of all languages/tools/services on a Quarterly basis. 

Let me know if this addresses your concerns and if you have any questions. We completely understand your frustration and this is our TOP priority right now.

**Comment by claar** [comment]
@manishas Thank you so much for the information and transparency. That is very helpful.

Hopefully https://github.com/dry-dock/u14phppls will contain php7 and an updated composer; that should be a satisfactory answer to this issue, and January 15th is right around the corner.

Is there any way for the Shippable community to help with this effort? For example, I'm sure PHP users would be glad to suggest helpful tools for our language to be included in this base image if you let us know where to put our suggestions.

**Comment by manishas** [comment]
This is now available.

All new build images are in our [drydock repo](https://hub.docker.com/u/drydock/).

**Comment by hranicka** [comment]
Awesome! Thank you!
