### ISSUE TITLE
Rabbitmq connection refused on port 5672

### ISSUE THREAD

**Issue by mcbridejc** [Shippable/support#1584]
I've enabled rabbitmq service, but it doesn't seem to be listening on the expected port. This used to work, but is now failing on multiple projects. 

In my shippable.yml: 

```
build_image: shippableimages/ubuntu1404_python
language: python
cache: true
archive: true
python:
  - "2.7"
services:
  - rabbitmq 
```

I'm using pika to connect to rabbitMQ service, with the following connection parameters: 

```
self._connection_parameters = pika.ConnectionParameters(
            host='localhost',
            port=5672,
            credentials=pika.PlainCredentials('guest', 'guest'),
            heartbeat_interval=heartbeat_interval
        )
```

But, it throws this exception: `AMQPConnectionError: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused`. 

Seems like something changed with the rabbitmq service?

**Comment by bbradbury** [comment]
+1

**Comment by manishas** [comment]
Is this still an issue? Most of the upgrade related problems should be resolved by now, so let me know if we need to look into this.

**Comment by mcbridejc** [comment]
Just checked back, and even did a `[reset minion]`, but still seeing the same error.

**Comment by lekhab** [comment]
@mcbridejc: We were in the process of migrating some users over to a new orchestration layer, which could have potentially caused this. We have reverted back while we iron the issues. Can you please check if you are still facing the same issue?

Apologies for the trouble here..

**Comment by mcbridejc** [comment]
Re-built the project, and still see same error. Is `shippableimages/ubuntu1404_python` an unusual or perhaps not well-tested image?

**Comment by bbradbury** [comment]
This is still busted, and is a good candidate for the straw that sends us off of Shippable. Any further thoughts? 

Example broken build: https://app.shippable.com/builds/564fca1e0b0f290e00c51833

**Comment by manishas** [comment]
We'll take a look and get back to you.

**Comment by rageshkrishna** [comment]
@bbradbury Our language specific images do not contain any services. The `services` section of the YML file is processed only if you're running builds on our `shippable/minv2` image. If you want to build with shippableimages/ubuntu1404_python and need to use RabbitMQ, you have two options:

1. Update your YML file to include the following:

  ````
before_install:
  - sudo apt-get install wget
  - wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  - sudo apt-key add rabbitmq-signing-key-public.asc
  - sudo echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y rabbitmq-server
  - sudo service rabbitmq-server start
  ````

  Of course, this will impact your build times because every build will end up installing RabbitMQ from scratch. To get around this, your second option is:

1. Create a Docker image with the following Dockerfile and use that to run your builds instead:

  ````
FROM shippableimages/ubuntu1404_python:latest

RUN sudo apt-get install wget && \
    wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc && \
    sudo apt-key add rabbitmq-signing-key-public.asc && \
    sudo echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list && \
    sudo apt-get update && \
    sudo apt-get install -y rabbitmq-server
  ````

If you use the resulting image, then you will need just one line in your YML file to make sure RabbitMQ starts up during your build:

````
before_install:
  - sudo service rabbitmq-server start
````

Having said all this, I completely understand your frustration with the barebones language images like shippableimages/ubuntu1404_python. We are currently creating a completely new set of language-specific images, some of which will include services as well. Until we announce this, I hope one of the suggestions above works for you.

Let me know if you need any more help with this.

**Comment by manishas** [comment]
Our new set of official images are in our [drydock repo on Docker Hub](https://hub.docker.com/u/drydock/)

The `pls` and `all` versions of images have rabbitmq installed on them.
