### ISSUE TITLE
Build not found.

### ISSUE THREAD

**Issue by chechoacosta** [Shippable/support#1595]
Since yesterday I'm trying to manually run a build for a branch of my projects and Shippable return me this error message

`{"id":3000,"message":"No access or object not found for :id 558972cdbd5b2a0c00e0cc08","methodName":"chkPermForId|_getBuildById"}`
Build not found.

**Comment by manishas** [comment]
@chechoacosta can you point me to the project and branch?

Can you check that your branch has a shippable.yml and make sure it is valid? We're seeing some issues where either a branch did not have a yml in there or the yml had some issues and we're not handling this case elegantly.

**Comment by manishas** [comment]
@chechoacosta can you check if your yml is valid? http://www.yamllint.com/

**Comment by chechoacosta** [comment]
@manishas we have been using the same yml for months and I double check and it is valid.

Later after I reported the issue, the builds worked normally, but then later it happened again, so is an intermittent issue on Shippable

**Comment by rept** [comment]
Got the same issue.  I'm trying out shippable but there is no way to start a build (private bitbucket repo) of a branch at this time.  I always get error message.

**Comment by rageshkrishna** [comment]
@rept Which branch are you trying to build? Also, do you mind if I try triggering a build on the same branch to debug this? Thanks!

**Comment by rept** [comment]
@rageshkrishna on the shippable branch, but it's the same result on every branch...
https://app.shippable.com/builds/55f9548819687b0c0066e3b0

What do you mean with: trigger a build on the same branch?  I only have one branch that contains the shippable.yml and that's the one I need to get working in order to merge it :-)

**Comment by rept** [comment]
@rageshkrishna ah sorry I misread, no you can try triggering all you want :-)

**Comment by trriplejay** [comment]
Hi @rept, it looks like there was an error parsing your yaml.

```
message=JS-YAML: bad indentation of a mapping entry at line 7, column 3:
      global:
      ^
```

**Comment by rept** [comment]
@trriplejay great this works!  Thanks.  Anywhere I could have found this out myself?

**Comment by trriplejay** [comment]
@rept Well, investigating your issue did lead us to discovering a bug where the notification was not getting created properly for certain yml errors.  Since that was fixed, if you were to encounter this error again, you would see something like this:

![image](https://cloud.githubusercontent.com/assets/6869398/9940565/7a1f3cc0-5d25-11e5-9ec7-87ed1ce69b47.png)

So if it happen again, you should have some clue as to why.

**Comment by manishas** [comment]
We're now surfacing yml errors in the build logs. Closing this issue, but please let us know if you have any questions.
