### ISSUE TITLE
Command output isn't escaped

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#162]
When displaying command output for a build in the dashboard console, you don't escape  the data which makes it hard to debug scripts that output, e.g., XML.  You should either remove the `to_trusted(commandLine)` call in the template, or escape the output earlier in the process if you want to pass through custom HTML styling that Shippable adds (though I haven't seen anything like that yet).  The lack of escaping may also be a security concern though I can't think of a way to exploit it off the top of my head.

**Comment by pquentin** [comment]
@avinci I stumbled upon something like this today, letting you know as requested.

With Python code that contains `print(type(b'hey'))`, the download logs contain `<class 'bytes'>` (as expected). But the UI creates a `<class>` HTML element: `<class 'bytes'=""></class>` instead of showing `<class 'bytes'>`.

**Comment by avinci** [comment]
thanks @pquentin, I will look into this.
