### ISSUE TITLE
Build failing but where is the logs?

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#1634]
Hello,

We're new to shippable. We've been using travis for a while and thinking of switching. When I read that shippable.yml is a superset of travis, I'm interested to try.

So I added shippable.yml to my project and changed some travis env variables like $TRAVIS_BRANCH to $BRANCH. I push the changes to my repo and shippable started building. But then it failed. 
https://app.shippable.com/builds/5593d4daf7208a0c008d0e2e

I tried finding what caused the build to fail from the console. But all of them don't have an error. So I want to know, how does shippable categorized build as "failure"? I simply cannot find the error log. Can you help?

Thanks
-Oby

**Comment by avinci** [comment]
@osumampouw we switched to a new way of handling console output to get fine grain control and we might be losing some logs or late arriving. There is an open issue internally we are tracking as we might have one 1 faulty console processor micro-service. We are trying to pin that down. 

Shippable basically looks at the execution return code and decides whether a build step failed or not. So there are two micro-services, 1 for console processing which are in 50 replication units and 1 for status processing which is about 5. These depend on load and queues and scale in and out. 

Since they are handled separately, we saw an error code return on 1 of the steps and hence the system marked it failed. Console logs are lost and we need to be trace it...

Hope that makes sense.

**Comment by osumampouw** [comment]
@avinci oh ok, so in my case, it's possible that this step is the culprit because 'after failure' is executed right after this step:
test "$BRANCH" != "master" && gulp ciBumpRequireJS

So test "$BRANCH" should be a valid syntax right? That means the culprit maybe ciBumpRequireJS task from gulp. So as long as gulp ciBumpRequireJS return 0, it should assume that there is no failure?

**Comment by rageshkrishna** [comment]
@osumampouw Your build is running on master, so `test "$BRANCH" != "master"` is returning an exit code of 1. This is why the build is failing. Try changing that to:
````
if [ "$BRANCH" != "master" ]; then gulp ciBumpRequireJS; fi
````
This should allow your build to continue.

I don't think there is any console output missing in this case as `test` doesn't print anything. That being said, we should probably write a line right there stating that the build is being terminated because the last command returned a non-zero exit code.

**Comment by osumampouw** [comment]
AH, yea I used the "test" as a workaround for if. Lemme try that. Thanks @rageshkrishna

**Comment by osumampouw** [comment]
Cool, it works now. Thanks. Yea it'd be useful to know the reason why the build is failing. But thanks for your prompt reply. Much appreciated.

**Comment by osumampouw** [comment]
reopening, if you guys want to add extra info so ppl can know why the build failed.

**Comment by manishas** [comment]
Closing this issue since there is no more work from our side. We'll document this as an FAQ.
