### ISSUE TITLE
Is it possible to get the committer in git as env variable?

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#1635]
Basically I want to do something like this:

if ($BRANCH != master && $COMMITTER != some-user), stop the whole thing. Don't build/test this commit. 

Our use case is as follows:
- we have a post commit hook that bumps our app's version. The post commit hook will then commit and push again to our branch.
- So we want to prevent the build if the the committer is not from our post commit hook otherwise we'll run the build twice for every commit. We just want to build once the version number has been bumped. 

My question:
1.) Is there an env variable for the COMMITTER
2.) What's the best way to tell shippable to just abort the build (but not make the status as "failed" but just "aborted")

Thanks
-Oby

**Comment by rageshkrishna** [comment]
We will skip builds that have `[skip ci]` anywhere in the commit message. I'd recommend using this instead of allowing a build to start running just to short-circuit it.

Would this work for you?

To answer your original question, the committer is not exposed as an env variable, but you should be able get that directly with `git --no-pager show -s --format="%an" $COMMIT`. We expose the SHA of the commit that triggered the build in `$COMMIT`.

**Comment by manishas** [comment]
Closing this issue since the question was answered. Thanks!
