### ISSUE TITLE
Non-deterministic error messages in tests

### ISSUE THREAD

**Issue by hcarver** [Shippable/support#1651]
I'm getting random error messages in my tests about end-of-files and broken pipes. When the error occurs, there'll be a whole bunch of subsequent tests that fail (maybe 20% of the total). They often seem to start with integration tests that use Capybara, though they also seem to then affect database access from functional tests that don't use Capybara.

They almost always take the form of
`EOFError: end of file reached` or
`Errno::EPIPE: Broken pipe`.

It's very annoying. It's happening in about 25% of our builds, and means we have to manually re-run builds a lot of the time, which is a pain for our whole CD process.

**Comment by hcarver** [comment]
I've done a few trials to get more reliable numbers, and it's actually happening in over 50% of builds. If I want anything to be reliably tested, I have to queue up 5 builds of it to be fairly certain that one will succeed.

I'd really appreciate some action on this, Shippable just isn't a viable CD tool for us as it stands.

**Comment by manishas** [comment]
this issue is now in our internal system. one of our devs will soon take a look and we'll update you as soon as we know more.

in the meantime, can you share a specific build link where this error happens and also your shippable.yml?
You can send your yml to manisha@shippable.com if you dont want to paste it here. 

Thanks!

**Comment by hcarver** [comment]
Great, thanks @manishas

Here are a couple of build links showing the error:
https://app.shippable.com/builds/559d5a534dd79a0b0043aadf
https://app.shippable.com/builds/559bf26c381dfb10005a327d

And our shippable.yml with some bits redacted that ought to be irrelevant:

language: ruby
rvm: 2.2.0
env:
  global:
    - PROJECT=redacted
    - secure: redacted==
    - secure: redacted==
    - secure: redacted==
services:
  - redis
install:
  - bundle install --jobs 4 --retry 10 --without development production staging
before_script:
  - psql -c "DROP DATABASE IF EXISTS redacted_test;" -U postgres
  - psql -c "DROP USER IF EXISTS redacted;" -U postgres
  - psql -c "CREATE USER redacted WITH PASSWORD 'redacted';" -U postgres
  - psql -c "ALTER USER redacted WITH SUPERUSER;" -U postgres
  - psql -c "CREATE DATABASE redacted_test WITH OWNER redacted;" -U postgres
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"
script:
  - RAILS_ENV=test bundle exec rake db:migrate db:seed
  - bundle exec rake test:all
after_failure:
  - python lib/scripts/slack_notifier.py --project $PROJECT
after_success:
  - redacted
  - redacted
  - redacted
  - redacted

**Comment by lekhab** [comment]
@hcarver: Apologies for the delay in getting back to you. 

Our devs did some research on this. Looks like ```xvfb``` not booting up before the actual tests start running appears to be causing this issue. Since the project uses Capybara, the probability of selenium or xvfb causing this issue is even more. 

Can you add a sleep of 5 seconds after starting xvfb and selenium and see if that alleviates this issue? You can also add an additional check in the script section to log xvfb status before running any test suite, so we can determine if there is a pattern to the failures.

**Comment by manishas** [comment]
Closing due to lack of follow up.

@hcarver if you're still running into this, please let us know and we will reopen.
