### ISSUE TITLE
recentBuilds API no longer reports in-progress builds

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#1666]
Before last month's announcement, Shippable would report in-progress builds, but that is no longer the case. We now only get finished builds.

I'd be happy to elaborate if needed.

**Comment by lekhab** [comment]
@pquentin: Apologies for the lack of communication here. 

We are working on adding better API routes and updated some of the API routes since they were misnomers. Instead of using recentBuilds, you can use ```searchBuilds``` and this will give you all the builds for a project across all states (waiting, queued, processing and completed).

GET  /projects/:projectId/searchBuilds 

You can also search for builds across a subscription and account by using the new searchBuilds API:

```
/subscriptions/:subscriptionId/searchBuilds
/accounts/:id/searchBuilds
```

You can use the ```limit``` string to limit the number of builds returned on searchBuilds.

```/projects/:projectId/searchBuilds/?limit=100```

Hope this helps. Please let me know if you have additional questions.

**Comment by pquentin** [comment]
Thank you @lekhab, this helps a lot!

I've modified my code to use the searchBuilds API, and this is much better since I only need 2 API calls to know our build status instead of n+1 before. And this also solves the in-progress build issue.

:clap:
