### ISSUE TITLE
Worker won't resolve Docker Hub registry

### ISSUE THREAD

**Issue by buley** [Shippable/support#1672]
I'm trying to get up and running for the first time with a Docker image build. Similar to https://github.com/Shippable/support/issues/1386 and https://github.com/Shippable/support/issues/1390 I'm seeing my [builds](https://app.shippable.com/builds/55a3e2bb51e4f50b0006a7e7) error out with an "unable to resolve host" message.

Based on what I've read on the problem, I believe this may be a Shippable error vs. my usage of the platform. Can anyone confirm?

![screen shot 2015-07-13 at 9 12 24 am](https://cloud.githubusercontent.com/assets/86985/8654458/4cca1dd6-293f-11e5-8019-e39cee613eb7.png)

**Comment by manishas** [comment]
@buley You need to configure the following -

- Since you're pulling from docker hub, you will need to set up an account integration by clicking on the gear icon on the top menu. This will take you to account settings, click on 'Integrations' and add one for Docker Hub by entering your credentials. This is documented here - http://docs.shippable.com/integrations/#docker-hub

- In your project settings, you need to enable the integration you just added for your project. To do this, go to project settings and click on 'No hub integration added' and select your integration -
![screen shot 2015-07-13 at 9 18 18 am](https://cloud.githubusercontent.com/assets/2983749/8654642/916e93c6-2940-11e5-8a47-af3dcdffbb09.png)

- If you want to push the container you build to your registry, Push build needs to be Yes
![screen shot 2015-07-13 at 9 23 33 am](https://cloud.githubusercontent.com/assets/2983749/8654686/d9b95d64-2940-11e5-80e3-ad97bd141682.png)
.
Please let me know if this works.

**Comment by buley** [comment]
I had added the integrations and wired the deploy but I was indeed missing the HUB step. Thank you for the support.

**Comment by manishas** [comment]
@buley if you're trying to pull or push to gcr, you need to specify images names like this -
gcr.io/gcr_project_id/image_name

**Comment by buley** [comment]
Thanks @manishas - I seem to be OK w/Docker Hub but haven't gotten GCR to resolve yet

![screen shot 2015-07-13 at 9 33 16 am](https://cloud.githubusercontent.com/assets/86985/8654891/43c78d56-2942-11e5-89fe-4686fdc3ea28.png)
