### ISSUE TITLE
Issue with docker image pull from quay.io

### ISSUE THREAD

**Issue by glachesis** [Shippable/support#1716]
I'm using the Pre-CI docker integration with a base image pull from quay.io.

The pull only works every other time and often breaks with a 403 error.

From the logs  :

Sending build context to Docker daemon
Step 0 : FROM quay.io/xxx/xxxx
Pulling repository quay.io/xxx/xxxx
Error: Status 403 trying to pull repository xxx/xxxx: "{\"error\": \"Permission Denied\"}"

Any advice ?

**Comment by lekhab** [comment]
@glachesis: can you please point me to a project or a build id with the error? I can't pull up anything with your @glachesis id..

**Comment by glachesis** [comment]
@lekhab here an exemple failed build : https://app.shippable.com/builds/55b10887be4ac90b00d30434

**Comment by manishas** [comment]
We seem to have completely dropped the ball on this one. Sorry about this and we're working on revamping our entire support process.

I will close this issue since we want to start with a cleaner slate and address any issues promptly moving forward. Please let us know if you would like us to take a look at this and we'll be happy to.
