### ISSUE TITLE
dedicated nodes are not in the menu

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1731]
Hi, 

I tried to replace one of my dedicated hosts by a new one; after deleting my current host the menu option is gone. Please enable this option since I am not able to do any deployment without a dedicated host!

Please help,
Ron

**Comment by lekhab** [comment]
@rvdwijngaard: you should be able to see a "custom nodes" tab under your subscription like below? You can add a new node by clicking on the (+) on the screen.

To get to your subscription page - click on the CI dropdown on the home page and select your subscription. 

![screen shot 2015-07-28 at 10 05 19 am](https://cloud.githubusercontent.com/assets/9526532/8937963/76bf3be4-3510-11e5-837e-9af6c03e83b0.png)

**Comment by rvdwijngaard** [comment]
yes that is exactly how it was working; for some reason I don't see that menu option anymore. 

![image](https://cloud.githubusercontent.com/assets/7237796/8938116/ed0d2e72-355c-11e5-8df2-0be6ad5161e1.png)

**Comment by lekhab** [comment]
apologies, @rvdwijngaard. Following up on this..

**Comment by lekhab** [comment]
@rvdwijngaard: while we look into this, can you please send me the details of the host you need added to lekha@shippable.com and we will manually update the backend, so you can be unblocked?

**Comment by lekhab** [comment]
@rvdwijngaard: are you able to see the custom nodes tab in your subscription now?

**Comment by gegere** [comment]
Same issue. I had a dedicated host listed, I can't find the UI button to display my dedicated noded. The current dedicated node is erroring out builds because the disk is full. I need to remove it a start again. Please help1

I am reading all the convsation in this thread and following [this post](http://blog.shippable.com/dedicated-hosts-?__hstc=253494166.97e4247b0ebee1b3f5a02a86d5090293.1438133561969.1438133561969.1438133561969.1&__hssc=253494166.2.1438133561969&__hsfp=704126382).

**Comment by rvdwijngaard** [comment]
@lekhab : fixed

**Comment by gsvijayraajaa** [comment]
Where do we find the dedicated host menu in the new UI?

Regards,
Vijay Raajaa G S
