### ISSUE TITLE
Strange fail

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#1755]
https://app.shippable.com/builds/55c1efd99f6e5e0b000974d8

**Comment by lekhab** [comment]
@luckyraul: it looks like this is failing because it is looking for a specific version that's not installed. Are you able to get this to succeed locally? 

checking a more recent build - since the older build logs were purged.

https://app.shippable.com/builds/55d6e819b882970c00b4f364

Is this still an issue?

**Comment by lekhab** [comment]
@luckyraul - is this still an issue? If not, I will go ahead and close it..
