### ISSUE TITLE
[ci skip] flag is being ignored

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1787]
![image](https://cloud.githubusercontent.com/assets/245435/9280851/8d706680-4297-11e5-872d-e4967f96130e.png)

I saw two commits with the `[ci skip]` "flag" were processed anyway...

Build: https://app.shippable.com/builds/55ce233ac9fa8d0b00293627

**Comment by lekhab** [comment]
@caarlos0: 
PR builds need the [ci skip] or [skip ci] to be in the PR title (since that's what the webhook passes to us). For Commit builds, the commit message is what is parsed.

For this one, I see these are PR builds and hence the issue. Can you confirm the commit builds did not run with this message?

I will also update our FAQ with this info - thanks for bringing this to our attention.

**Comment by caarlos0** [comment]
ah, you`re right.

Thanks!

**Comment by ronjouch** [comment]
@lekhab (or anyone at Shippable, not sure you still work there; cc to other Shippable folks I see active in other issues: @trriplejay @manishas @a-murphy) can you document this in http://docs.shippable.com/ci/skip-builds/? (Rather than in a FAQ). The current version, quoted below, fails to mention it:

> Any changes to your source code will trigger a build automatically on Shippable. So if you do not want to run build for a particular commit, then add [ci skip] or [skip ci] to your commit message.
>
> Our webhook processor will look for the string [ci skip] or [skip ci] in the commit message and if it exists, then that particular webhook build will not be executed.
