### ISSUE TITLE
Native Beanstalk Deploy Not Working

### ISSUE THREAD

**Issue by segfly** [Shippable/support#1792]
@lekhab @manishas I saw your comments in #1778 and I seem to be having the same issue. I am following the guide at http://docs.shippable.com/autodeploy-to-ebs/ but similar to #1778 the build stops at the image push step - without any apparent attempt to deploy to EBS.

I followed parts of the guide for predefined runtime environments. I have a branch in my repo working where I execute all the EBS commands manually via the CLI in shippable.yml. However, I would prefer to use the native support in Shippable rather than running the ebs commands and putting in all the env variables into the shippable.yml

Thanks.

**Comment by manishas** [comment]
@segfly can you try again?

**Comment by segfly** [comment]
@manishas It is still stopping at push container (and reports success).

**Comment by ragsden** [comment]
@segfly I tried running your project and EBS deploying is currently failing with "NoSuchBucket" error. Can you please take a look at your deployment settings?

**Comment by segfly** [comment]
@ragsden This was due to my troubleshooting earlier. I now have it set for the correct bucket and the build completes and successfully deploys.

However, is this a one-time fix? E.g. If I create other projects, will they now deploy correctly? What about other accounts my team may have? I ask because it looks like something may have changed with my account as there are changed/new build steps (e.g. "hub login" and "hub push" rather than "push container" that I saw earlier)

Thanks!

**Comment by manishas** [comment]
@segfly the short answer is - for the next couple weeks, you'll need to inform us which accounts want to deploy natively to EBS.

We tried to move to a new build system a couple of weeks ago but discovered some issues that were only obvious at the scale we're running on production, so we had to revert back to our original one. The EBS deploy feature was implemented during this time to work with the new build system. When we reverted, the feature stopped working. 

We're working on making this work with the old build system, but in the meantime if someone wants to deploy to EBS, we're moving them to the new build system temporarily. Since this is relatively a smaller number of users, we're not running into scale issues there. Once EBS works with the old system, we will move everyone back there. 

Let me know if you have any questions. If you let us know which accounts need to deploy to EBS, we'll move them so they can deploy.

**Comment by segfly** [comment]
@manishas I appreciate the full explanation. It helps me understand when I need to request support for this. For now, the change to my account seems to work fine even for projects created from repos in my github organization (I'm guessing the catch is I must create them) since my account is on the new build system. So I don't think I will need other accounts moved at this time. Thanks!
