### ISSUE TITLE
An owner must log in to delete this repo.

### ISSUE THREAD

**Issue by jgregors** [Shippable/support#1809]
If you first delete a repository in Bitbucket, you cannot delete the corresponding shippable project afterwards and the error "An owner must log in to delete this repo." is displayed.

As a workaround, I recreated a repository with the same name in bitbucket, deleted the shippable project and then deleted the bitbucket repository.

No big dramas here but thought it was worth reporting.

**Comment by lekhab** [comment]
@jgregors: This is usually because we only sync periodically with the SCM or when you log in. The project page is looking for an owner token which it can no longer find.. 

After deleting a repo from Bitbucket, you can force sync your account so we get the latest set of projects by going to your Shippable home, click on account settings and doing a force sync. That removes the project from Shippable.
