### ISSUE TITLE
Cannot enable private repository

### ISSUE THREAD

**Issue by deploymc** [Shippable/support#1858]
User: deploymc
When trying to enable a private repository (under organization CI), I get the following error. The user has access to the repository and I have enabled private repositories from the Settings.

{"id":3000,"message":"Not Authorized to perform this action","methodName":"caller:55ed4f27688f320c0040d7dd|projects|chkPermForId:55ed503d1895ca4474135af6|_chkPermForId"}

**Comment by lekhab** [comment]
@deploymc: This is now fixed. Can you please try again and let me know if you are facing any issues?

**Comment by deploymc** [comment]
It now say {"id":3300,"message":"Owner not found for projectId::55ed503d1895ca4474135af6","methodName":"caller:55ed4f27688f320c0040d7dd|projects|enableById:55ed503d1895ca4474135af6|_getValidOwner"}

**Comment by kanthchandra** [comment]
@deploymc : Enabling the project involves setting up of webhooks and deploy keys on github/bitbucket so that we will be able to automatically trigger a build when you push to the repository. 

In order to set up webhooks and deploy keys we will require the owner of the project to login into shippable. Can you please ask the owner of the project/organization to login and try? If that doesn't work we will investigate this further.

**Comment by jawaid** [comment]
@deploymc  Is this fixed for you?

**Comment by DavidMont** [comment]
I have the same problem, im using gitalb-CE is this possible?

**Comment by kanthchandra** [comment]
Hi @DavidMont can you please open a new issue describing the problem that you are facing ?

**Comment by dhensen** [comment]
I'm also having the same problem. Over the last few days we have been doing a try-out and we like your product. But having our repo owner to login to shippable really is a deal breaker for us. When will this be fixed?
