### ISSUE TITLE
Use nodejs version 0.12?

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#1896]
We've started getting the following error during our script when using version 0.11, causing builds to fail:

```
node: ../src/smalloc.cc:280: void node::smalloc::SliceOnto(const v8::FunctionCallbackInfo&): Assertion `end <= source_len' failed.
Aborted (core dumped)
```

A quick search suggests it may have been fixed in a later node version (0.12.2)

When I change the node version to 0.12 in our shippable.yml it attempts to use the binary, however fails and starts compiling from source instead (I won't leave that running as it'll take too long)

```
mv: cannot move `/home/shippable/.nvm/bin/node-v0.12.7-linux-x64' to `/home/shippable/.nvm/versions/v0.12.7': No such file or directory
Binary download failed, trying source.
```

Any way we can fix this to get a newer version?

**Comment by jawaid** [comment]
@tomsterritt  We will look inti it and get back to you

**Comment by tomsterritt** [comment]
@jawaid any progress here? Builds are taking a really long time & I tried pushing to docker hub to speed things up but that didn't seem to do anything... :confused:

**Comment by manishas** [comment]
@tomsterritt sorry for the delay on this. We are in the process of creating standard images, and the base image for node is ready... you can specify pull from drydock/u14nod:prod or drydock/u12nod:prod in your project settings.

Please note that these only have language versions and do not have any services installed, so you'll need to install those yourself.

**Comment by tomsterritt** [comment]
@manishas @avinci this still appears to be building node from scratch on the regular image? 5649f7d73a1ff80d00b92899

**Comment by avinci** [comment]
yes, the regular image has not been updated. The problem with the regular image is it has everything under the sun under one image. this is taking 12-14 hrs to build and its not sustainable as folks want regular updates which we have not been doing for the same reason.

We are moving into language based images which will be broken into the following 
* base - this has only the languages but no services. It will always have a flavor of node, ruby, java & python no matter what language it is so that you can do cross language commands
* pls - this has most frequently used services like MySQL, Mongo, Redis etc. We will publish the list in the next couple of weeks
* all - which will have all the services preinstalled which is similar to what we use but only for 1 language.

We will have full docs, blogs and also how the community could get involved in maintaining this too along with upgrade process etc. Stay tuned..

**Comment by tomsterritt** [comment]
@avinci do you have an image I can use now that has a newer node version along with other languages (in particular ruby)?
