### ISSUE TITLE
Language support for NodeJS v4.0 ?

### ISSUE THREAD

**Issue by gerardmrk** [Shippable/support#1917]
The currently-listed Node versions are 0.12 and under.

**Comment by lekhab** [comment]
@gerardmrk: This is already on our radar. There is a duplicate support issue on this: https://github.com/Shippable/support/issues/1881. Please track updates to language specific images there.

One of the alternatives explained in that issue is to build a custom Docker image for your needs. You could use one of the node specific [Docker File]((https://github.com/shippableImages/ubuntu1404_nodejs/blob/master/Dockerfile), customize it, push it to a free Docker Hub account and use it for your builds.  Anyone can use a custom Docker image for their Shippable builds. 

The doc below explains how to use Docker registries on Shippable.
http://docs.shippable.com/docker_registries/

**Comment by tudvari** [comment]
Hi,

I use shippable with node 4.1.1. I show use my shippable.yml snippet, maybe you can try this:

node_js:
    - 4.1.1

**Comment by avinci** [comment]
We are going to be moving to these images. Its fully updated an we are productionalizing it. In the meantime you could use it 
`build_image : drydock/u14` or `build_image : drydock/u12` please note that this image has no services yet and does not start anything. 

The versions pre-installed are
- 0.1
- 0.12
- 4.0.0

Docker files for this are here
https://github.com/dry-dock/u14nod
https://github.com/dry-dock/u12nod

I have a sample that install mongo and runs on this new image if you want to refer to it. Once this is productionalized, nvm stuff will be automatically done. 
https://github.com/avinci/sample_node
