### ISSUE TITLE
Granular control over which messages post to slack

### ISSUE THREAD

**Issue by bobeagan** [Shippable/support#1922]
I don't care about knowing when a build starts or passes.  I really only want to have the slack notification send for failures.  Is it possible to add some more controls to the configuration of the slack notification to allow selecting which of these notifications should send?

**Comment by pquentin** [comment]
+1

This is the reason why we stuck to the old way of integrating with Slack, by using the Slack API in after_failure. This no longer works for us because we now build our Docker images from Shippable, and build_image happens after `after_failure`, so we can't report Docker build failures to Slack.

And since Shippable notifications go in our main Slack developer channel, seeing all passes would add too much noise.

Thanks!

**Comment by rvrignaud** [comment]
a big +1 for @pquentin !

**Comment by avinci** [comment]
acknowledged. We are going to move all these settings into YML. Our direction is to set integration in the UI so that your keys are not in the YML. But moving all the configs to YML should give more control. Please stay tuned...

**Comment by pquentin** [comment]
@avinci Any progress on this?

**Comment by avinci** [comment]
This was just pushed to beta today. Can you let me know what events would you like to have control over?

**Comment by pquentin** [comment]
@avinci We would be happy to receive notifications for failures only.

**Comment by manishas** [comment]
Slack config now supports control over which messages are sent, as well as sending to multiple rooms, etc. More details in docs at http://docs.shippable.com/ci_configure/#slack-notifications

Please note that you'll need to move your subscription to the new plan (Continuous delivery) if it has not already been migrated to that. Also you'll need to use the new yml format.
