### ISSUE TITLE
Job is failing to push to private docker.io repository

### ISSUE THREAD

**Issue by svo** [Shippable/support#1924]
Hi,

I am attempting to configure a project that uses custom (public) docker images to test and build an image for a private docker hub repository.

At the moment everything seems to be working as expected apart from the final "hub push" step.

I have configured the "docker.io" integration in my "Account Settings -> Integrations" and configured that as the "Hub" integration in my "Project Integrations". In the project setting I have also flagged the project as "Docker Build: On", "Docker Build Order: Post-CI", "Push Build: Yes", "Push Image to: `the private docker hub repository`", "Push Image Tag: commitsha" and "Pull Image Name: <public CI repository>". 

The error I'm encountering is:

```
sudo docker push [...] 2>/tmp/push-error.txt
The push refers to a repository [...] (len: 1)
[...]: Buffering to Disk
[...]: Image push failed

Please login prior to push:
Username: EOF
```

Where `[...]` is relevant project details.

I have noted the "hub login" step is reporting: `Docker login successful with username [...] and email [...]`.

Any assistance with getting the image pushed would be greatly appreciated.

Thanks in advance.

**Comment by rageshkrishna** [comment]
@svo There are a couple of things I'd like to confirm:

1. Does pushing new tags work for you locally using the same credentials?
1. If it does work, can you please let me know the docker version you are running locally?

We have seen a similar issue a couple of times before this and both times it turned out to be some issue within docker hub. For example, https://github.com/docker/docker/issues/12910 is an issue that was reported against docker version 1.6.0 but if you scroll towards the bottom you'll see it was also reported by a user with docker 1.7.1 and the suggestion was to contact docker hub support.

Both the times we saw this happening on shippable, the problem went away after the user deleted and re-created the image on docker hub.

**Comment by svo** [comment]
@rageshkrishna 

I have managed to push new tags to that repository from my local machine using the same credentials; I'm using `Docker version 1.7.1, build 786b29d` on Ubuntu and `Docker version 1.8.2, build 0a8c2e3` on my Mac.

I have tried deleting the repository on a few occasions and have additionally tried having no tags versus having a primed repository with no success.

Apologies if I'm missing something obvious.

Thanks for your assistance.

**Comment by rageshkrishna** [comment]
Thanks for the details. We are also running docker version `1.7.1/786b29d` so I think we're running in to something else.

Looking a little deeper, I noticed that you have added a "Private docker registry" integration but what you are really trying to do is to push a private image to the Docker Hub registry. For this, you should really use the "Docker" integration and not "Private docker registry". Adding an integration for "Docker" and using that should get you around this issue.

"Private docker registry" is meant to be used when you are running your _own_ instance of a registry.

Having said that, I believe your push _should_ also work if you change your project settings to match the registry name that you configured in your "Private docker registry" integration. That is, specify `docker.io/s******/w*****-*****` instead of just `s******/w*****-*****`.

Either one of these approaches should get it to work, although I would suggest using the "docker" integration as that's much more straightforward.

**Comment by svo** [comment]
Thanks @rageshkrishna,

It would appear it was my misunderstanding in regards to the difference between the "Docker" and the "Private docker registry" integrations that was to blame.

I have changed the configuration over to using the "Docker" integration and all is now behaving as expect.

Many thanks for your time... apologies for any inconvenience.

**Comment by rageshkrishna** [comment]
Happy to help! I guess we should improve our documentation or provide some more explanation in-line to make the difference clear.
