### ISSUE TITLE
cache: true option not working with ruby environment

### ISSUE THREAD

**Issue by pschrammel** [Shippable/support#1930]
Hi,
see e.g. build 56160ba0be57100b0035d46d.
the install step is always reinstalling rubygems which takes more than 50% of the test time.

**Comment by avinci** [comment]
Have your tried turing cache on?
http://docs.shippable.com/project_settings/

**Comment by pquentin** [comment]
@avinci: @pschrammel explicitly mentions "cache: true" in the title of the issue.

(By the way, the blog post is more explicit than the docs. "Before the build, we will check for the cache flag and if it is ON, the entire minion will be cached if the build succeeds and the cached minion will be reused for further builds." It's not clear if it's in .shippable.yml, and at what level. "cache: true" in the blog post is better, I think.)

**Comment by avinci** [comment]
Sorry, I misread it. We are standardizing everything to YML in the coming days and we will make docs better. Appreciate the feedback. 

`cache:true` needs to be at the highest level in YML. 

This will cache the container only the first time you run it. We run on multiple hosts and hence you might see a few run where it might be slow. We try to run the builds on the same hosts so that cache is present on it, but depending on loads thats not guaranteed. 

Now if you need to reset the minion so that it recaches it, use `[reset_minion]` text in your commit message and it should reset it and recache.
