### ISSUE TITLE
Using multiple Dockerfiles

### ISSUE THREAD

**Issue by cduzan** [Shippable/support#1955]
Is there a way to point at a specific Docker build file when using the Pre-CI build order? I would like to have multiple Dockerfiles (ie. Dockerfile.dev, Dockerfile.prod, etc.). I see you can do this in docker using the -f flag in the docker build command. Is there anything in shippable that mimics this capability?

**Comment by manishas** [comment]
As of today, we just pick up the file called Dockerfile and build for for Pre-CI workflow.

Can you share a little about why you're using different dockerfiles for dev, test, prod? We are reworking some of the docker related functionality so would be good to know if this is a common scenario we should address...

**Comment by cduzan** [comment]
For the dev version we have all our projects pulled down locally in a common folder so we use a docker-compose.yml file to actually build up the containers (shippable not used for dev setup), the Dockerfile files in this case are pretty minimal. For the test and prod versions the containers are built through shippable and have several more working pieces in them and therefore are different from the dev version (copying src files, setting up db's, installing dependencies). Also, the test version has certain ports exposed for debugging that the prod version won't have.

**Comment by avinci** [comment]
@cduzan we are starting a beta program starting in a couple of weeks that will allow you to do this. Would be interested to try that out. Currently we don't expose docker build command natively. We are working opening that up and allow you to define these commands in the YML and let you have full control of it. Let me know if that works for you

**Comment by cduzan** [comment]
That would be great! Thanks @avinci  My team and I are new to both Docker and Shippable so we are quickly learning as we go but I believe this would be very helpful to us.

**Comment by chriskinsman** [comment]
We are considering docker and hitting this also.  We have a repository today with 25 or so microservices in it.  We don't want to transform that into 25 repos just to build each service in it's own dockerfile.  Seems like overkill and brutal given githubs per repo pricing.  Love to be able to have a directory structure where each subdirectory has a dockerfile and it builds up it's service.

**Comment by avinci** [comment]
We will have this ready in the next couple of weeks. totally understand the scenario and the need for this

**Comment by chriskinsman** [comment]
One concern we have with this scenario is triggering the build of all the services on each commit to the repo.  Since we are all nodejs having to npm install 25 times instead of 1 is going to blow out our build times.  Ideally shippable would be smart enough to only build the changed services/dockerfiles

Happy to chat more @avinci if I am thinking about this wrong...

**Comment by 9len** [comment]
Just wanted to add a +1 to @chriskinsman's use-case. We have a monorepo with multiple projects, each of which has a separate Dockerfile. I'd like to be able to compile and test the whole tree, and then build each Dockerfile. Ideally I'd just specify the location of each Dockerfile in shippable.yml:

```
dockerfiles:
  - foo/bar/Dockerfile
  - baz/Dockerfile
  - blegga/blar/bloop/Dockerfile
```

**Comment by manishas** [comment]
This is now available with our updated build system!

Your subscription needs to be on the Continuous Delivery plan in order to work with the new yml format which supports this use case. If not already migrated, you can update your plan by going to the billing tab of your subscription and choosing the CD plan.

With the [new yml format](http://docs.shippable.com/ci_configure/), you can do something like this:

```
env:
    - IMAGE_NAME = "drydock/u12nod"
    - IMAGE_NAME = "drydock/u14nod"

build:
    pre_ci_boot:
      imageName: $IMAGE_NAME
      tag: prod
      pull: true
```

This should kick off 2 builds - one with drydock/u12nod:prod as CI build container and other with drydock/u14nod:prod as CI build container.

**Comment by manishas** [comment]
Closing this issue since this is addressed. Let us know if you have any questions.
