### ISSUE TITLE
Build stuck on "waiting"

### ISSUE THREAD

**Issue by zwang1** [Shippable/support#1958]
Hi , My builds today all stuck on waiting and has no logs. Now it get even worse that I cannot cancel a waiting build.
My shippable file looks good to me. and I don't know what's wrong here. Can someone take a look? Thanks very much!

account: zwang1
private repository :cmusv-fse/FSE-SA3

**Comment by jawaid** [comment]
Will look into it and get back to you

**Comment by manishas** [comment]
@zwang1 you should be able to cancel now... we just pushed a fix for that issue. We're still looking into why the builds are stuck in waiting, so will update this when I know more...

**Comment by ramdasskevin** [comment]
Same here. I am in the same organization but different project.

**Comment by manishas** [comment]
With the free plan, you get one parallel build at a time for all repos across the org. Your builds were waiting (queued) because another build was processing at the time. 

Let me know if you have any questions.

**Comment by manishas** [comment]
Please see my explanation in https://github.com/Shippable/support/issues/1961 -

Our billing plans are per GitHub organization and not per repo. The org cmusv-fse has 35+ repos, including your repo. All these repos share one build container, so if anyone else's build is running at some point of time, your build will be queued until the container is available.

The reason you do not see all these other repos and their builds on Shippable is because you do not have access to them on GitHub. (likely because this is a class assignment and each team is working in its own repo).
