### ISSUE TITLE
Pushes to bitbucket not getting picked up

### ISSUE THREAD

**Issue by mgladdish** [Shippable/support#1959]
Sometimes Shippable just doesn't notice when I push to a repo.

E.g. this project should have built this morning, but did nothing.
https://app.shippable.com/projects/561fbd8b1895ca44741dff9d

Also, I get 2 of these errors out of the blue when looking at my project list:
{"id":1005,"message":"Internal API error : getProjectById","methodName":"chkPermProjectId|_getProjectById"}

The UI's error reporting really needs to be better so we can see what's going wrong.

**Comment by rageshkrishna** [comment]
Hi @mgladdish! BitBucket has been having issues with webhooks since yesterday. Although their status page currently says webhooks are green, our tests are still showing that webhooks are coming in after a long delay or not at all.

I've raised an internal issue to look in to the errors you're seeing on the projects list. We'll get back to you soon on this.

**Comment by avinci** [comment]
@mgladdish We are seeing that bitbucket is dropping multiple web hooks. We are monitoring this closely to see if we can do anything at this time other than ping BB. Let me know if you are still seeing this issue

**Comment by mgladdish** [comment]
Yes, still having problems with commits not being noticed.

**Comment by manishas** [comment]
@mgladdish bitbucket is still experiencing issues - http://status.bitbucket.org/ - which might be leading to this. We will follow up with them and if this happens after they are fully functional we can take a closer look.

**Comment by mgladdish** [comment]
Can you at least make the UI show when there's a problem?

My home screen, https://app.shippable.com/, now says "No builds have been triggered yet" and doesn't think that bitbucket even exists.

Surely my account on Shippable says that I have a bitbucket integration set up? An error message on the screen saying "Sorry, bitbucket is unavailable" would be so much better, rather than it just vanishing?

Unless, of course, you really have managed to delete my BitBucket integration, in which case you've got bigger problems.

**Comment by rageshkrishna** [comment]
@mgladdish This is a new issue with BitBucket that has started happening this morning. From around 4 hours ago, a couple of the APIs that we call on BitBucket to synchronize permissions have started reporting errors.

As a result of this error, we are unable to synchronize permissions from BitBucket teams and repositories. All of your data is still present in the system but because the permissions aren't coming through from BitBucket our security module isn't allowing you to get to it.

We have notified BitBucket about the issue and I will share more details here as soon as I hear from them.

**Comment by mgladdish** [comment]
Can you at least agree to change your UI to show the error? 

I'm getting more and more frustrated with silent failures on Shippable's side.
 - mysteriously vanishing projects
 - internal API errors that come and go (see above - any news?)
 - builds failing for no good reason
 - UIs that should auto-refresh but then silently stop updating themselves (has my build finished, has it hung, should I refresh the page to see what's going on?)

**Comment by avinci** [comment]
@mgladdish we have started to surface all error into the UI. Thats the first step. We are then going to add a docs FAQ page and which help you debug the issue.

Bitbucket going down for 2-3 days is not something our system is planned for. I understand you frustration and we are making it become more resilient. Please stay tuned..

**Comment by avinci** [comment]
Since bitbucket has stabilized, can you please check if this is still happening.
