### ISSUE TITLE
Build dda61d4 waiting

### ISSUE THREAD

**Issue by AlfredAria** [Shippable/support#1961]
The build requests for repository FSE-F15-SA1-SSNoC are stuck for waiting (for more than an hour) since Build request 81.

https://app.shippable.com/projects/5621a4071895ca44741e546b

**Comment by manishas** [comment]
@AlfredAria your org is on the free plan, which means you have one build container which lets you run one build at a time. Any subsequent build that are triggered are queued until the container is available. 

This build is currently running which is why other builds are queued https://app.shippable.com/projects/5626af851895ca44741f15c7

**Comment by AlfredAria** [comment]
HI

The link cannot be opened, and I really don’t see any builds “in progress” here. I have cancelled all requests between 82 - 85, and 86 keeps in “waiting” state. Could it be because some previous attempts left as “in progress” on the server?

Please help me remove any “in progress” builds thanks…

**Comment by manishas** [comment]
Do you have access to the FSE-F15-SB6-SSNoC repo on GitHub? It's a repo in your org.

**Comment by manishas** [comment]
Build 11 for this repo is in progress. The reason you might not see this on Shippable is possibly because you don't have access to the repo in my comment above.

**Comment by manishas** [comment]
@AlfredAria Our billing plans are per GitHub organization and not per repo. The org cmusv-fse has 35+ repos, including your repo. All these repos share one build container, so if anyone else's build is running at some point of time, your build will be queued until the container is available. 

The reason you do not see all these other repos is because you do not have access to them on GitHub. (likely because this is a class assignment and each team is working in its own repo).

I cannot remove the in progress builds since that will likely affect other students who are working in their own repo within the same organization.
