### ISSUE TITLE
Push to multiple dockerhub repos for each branch

### ISSUE THREAD

**Issue by rmossuk** [Shippable/support#1966]
Hi 

I have multiple environments of my app repo that i have created a branch for each.  dev, qa, staging, uat, .... etc.

From the project settings page it seems like i can only set one docker hub repo location to push to and also only select on deployment to Elastic Beanstalk where i have to state application name and environment name.

How do i deploy to a different docker hub repo for each branch and different AWS ELB environment for each branch ?

Thank you.
Richard

**Comment by avinci** [comment]
@rmossuk We are moving this setting to YML in the next couple of weeks. We made a wrong choice of moving these things to UI and it caused us to restrict ourselves. I will write a blog around this and hopefully that should help. Its going to be in Beta and would you like to try it our there? If not, I will let you once it stabilizes and move to prod.

**Comment by rmossuk** [comment]
yes please i would love to try it asap in Beta. Please let me know how.   thanks

**Comment by rmossuk** [comment]
is there a way of changing the EBS environment name in the YML file now ? or by ENV variable ?    Or is the only way to deploy to a new environment by deleting the deployment and creating a new one with a different environment name everytime?

thanks
Richard

**Comment by avinci** [comment]
you cannot change EBS environment in the YML as the EBS push is occurring outside the build container. We are going to be making a few changes very soon and you should be able to do this. But for now its not possible.

We have a new product called Deploy with which you can do these sorts of things very easily and its meant to manage Docker containers. Let me know if you want more info around that

**Comment by manishas** [comment]
Support for pushing to multiple docker hub repositories is now available. Check out docs at http://docs.shippable.com/ci_configure/#pushing-an-image-to-a-registry

This workflow and yml syntax is only available with our new build platform. To find out if you're on the new build platform, you can go to the Billing tab for your organization and ensure that plan name is 'Continuous Delivery'. If it is not, you can update the plan and choose Continuous Delivery.

Closing this since this is implemented.
