### ISSUE TITLE
My account has gone all curropted

### ISSUE THREAD

**Issue by hemantgoswami** [Shippable/support#1968]
I had bit bucket as well as github linked to Shippable. I just came back from holiday to find that builds are no longer working and also I cannot unlink and relink the account back.

Can you please look into this ?

Thank you,
Hemant

**Comment by leonfs** [comment]
+1. Experiencing the same issue here.

**Comment by rageshkrishna** [comment]
@hemantgoswami @leonfs Are you both primarily using bitbucket repositories?

**Comment by hemantgoswami** [comment]
Yes, at this point in time my primary repo is Bitbucket but might use github in future.

**Comment by rageshkrishna** [comment]
Bitbucket has been having massive outages over the past few days. From earlier today, a couple of the BitBucket APIs that we rely on for synchronizing team and repository permissions in to our system have started failing with strange errors. As a result, we're now unable to sync permissions from BitBucket, which is why you are not able to view any of your projects. All the data still exists in the system but the missing permissions mean you can't see them in the dashboard.

Please follow https://github.com/Shippable/support/issues/1967 for updates on this.

**Comment by hemantgoswami** [comment]
Thanks Ragesh,

I'll follow it in that thread but do you have any ETA when it will be fixed? otherwise I'll have to move my repos to github as an alternative??

Also, if I wanted to unlink github or bitbucket from my account how can I achieve that?

Thank you,
Hemant

**Comment by rageshkrishna** [comment]
We have opened a level 1 issue with BitBucket support for this. I will update https://github.com/Shippable/support/issues/1967 as soon as I hear from them.

At the moment, it isn't possible to unlink accounts from our UI. Please let me know which one you want to retain and we can get it done internally.

**Comment by hemantgoswami** [comment]
Thanks Ragesh for letting me know,

I'll leave both there for now, if I need to remove one, I'll give you a shout again! Though, having this feature in UI will be a big plus.

Thanks for your help,
Cheers,
Hemant

**Comment by avinci** [comment]
This should be resolved as bitbucket has fixed the problem.

 We are making the account relinking be super easy now with a few changes coming soon.

For now closing this and will track another issue for feature change

**Comment by hemantgoswami** [comment]
Thanks!!!
