### ISSUE TITLE
Shippable always getting HEAD from github.

### ISSUE THREAD

**Issue by fabiocarneiro** [Shippable/support#1978]
I did two commits, a push for each of them and shippable generated two builds for them, theoretically it should run one build for each commit, but since my second commit was faster than the git pull of the first build (which always pull the HEAD), it ran the build for the second commit in both builds.

Please replace `FETCH_HEAD` on  `git checkout -f FETCH_HEAD` with commit id.

**Comment by rageshkrishna** [comment]
@fabiocarneiro We currently do this only for pull request builds. Earlier, we used to do exactly what you said and checkout the commit ID but we had a few customers complain that their workflow involves forced pushes which was causing queued builds to fail because the commit ID that triggered the build would have been wiped out by a more recent force push.

The rationale behind always building the HEAD of the PR branch is that it is the HEAD that is going to be ultimately merged and that's what should always be setting the commit status on GitHub.

I hope this clarifies things.

**Comment by rageshkrishna** [comment]
On normal commits (not PR builds), we always build only the exact commit SHA that triggered the build.

**Comment by fabiocarneiro** [comment]
1. place the commit id only when build starts (not when queued)
2. automatically cancel running build, if already running and create a new build with the new HEAD.

It doesn't make any sense to run two builds for the same commit id unless intentionally.

**Comment by manishas** [comment]
We'll change behavior if we hear more feedback around this. Closing as won't fix.
