### ISSUE TITLE
Error when trying to remove a subscription

### ISSUE THREAD

**Issue by ingopansa** [Shippable/support#1985]
I was playing around a bit with shippable, ended up in removing and re-adding my bitbucket integration. Now I cannot (re-)run any builds any more, and when trying to remove/re-add the repository subscription, I get the following error:

"{"id":3300,"message":"Owner not found for projectId::56337fc91895ca4474223393","methodName":"caller:56337fc7046d220c0032791e|projects|syncById:56337fc91895ca4474223393|_getValidOwner"}
"

Any clue how to fix/solve this?

**Comment by kanthchandra** [comment]
Hi @ingopansa , the bitbucket integration is very much essential for us to make http calls to bitbucket. This can be fixed by following the steps given below.

I have assumed that you have a linked both your github and bitbucket accounts and proposing this solution.

1. Delete the existing bitbucket integration that you re-added in the account settings.
2. Click on the logout button.
3. Next login back with bitbucket and everything should get re created.

please let me know if this works.

**Comment by ingopansa** [comment]
Hi,

that seem to have worked - thanks!

Ingo

**Comment by kanthchandra** [comment]
Glad that it worked :) Closing the issue.
