### ISSUE TITLE
Login problems with a private docker registry

### ISSUE THREAD

**Issue by woglinde** [Shippable/support#2005]
Hello,

we have the login problem with a self setup private docker registry.
The registry runs at version 2.2 and pushes from my local computers with the credentials
are working.

The output fromm the push step on shippable is (I had to censor some details with xx):

The push refers to a repository [xx/xxxxxxx] (len: 1)
d06aa47a8d6e: Buffering to Disk
d06aa47a8d6e: Image push failed

Please login prior to push:
Username: EOF

The out put from hub login is:
echo 'Docker login successful with username xx and email xx@xx-xx.de'

To me it looks like docker login or preparing the .docker/config.json was never done.

**Comment by avinci** [comment]
@woglinde, is the registry publicly accessible to push to? When you are trying to do this from your laptop, is it on some intranet or are you able to do this from internet too?

**Comment by manishas** [comment]
@woglinde can you try using the following syntax for the 'push image to' setting -
[REGISTRY_HOSTNAME:REGISTRY_PORT]/image_name

The docker login is happening correctly since you've set up an account integration with a path to the registry and supplied creds. However, your 'push image to' setting specifies xx/xxxx without specifying a port for the private registry, so we're trying to push the image to docker hub, hence the login error.

From https://blog.docker.com/2013/07/how-to-use-your-own-registry/ -
It’s important to note that we’re using a domain containing a “.” here, i.e. localhost.domain. Docker looks for either a “.” (domain separator) or “:” (port separator) to learn that the first part of the repository name is a location and not a user name. If you just had localhost without either .localdomain or :5000 (either one would do) then Docker would believe that localhost is a username, as in localhost/ubuntu or samalba/hipache. It would then try to push to the default Central Registry. Having a dot or colon in the first part tells Docker that this name contains a hostname and that it should push to your specified location instead.

**Comment by woglinde** [comment]
Hi,

I got it working now. It was my fault to assume when setting the docker registry in the hub option that the image get tagged right and I failed to look up in docker build logs how the image get tagged.

Thanks for the hints.
