### ISSUE TITLE
please display actual image ID being pulled from Docker Hub

### ISSUE THREAD

**Issue by n0mer** [Shippable/support#2010]
to help troubleshoot issues like #1461 , please display actual image ID being pulled (or used, if it has been already pulled)

**Comment by avinci** [comment]
@ric03uec refactoring CDM change

**Comment by n0mer** [comment]
@avinci how to understand your last comment? and what does CDM stands for?

**Comment by avinci** [comment]
Thats an internal micro-service that we use to run a build. To handle our support better, we have started to work on these issues publicly so that folks know the status. This component was not well designed and there is a focused effort on making sure that its rock solid. 

Our goal is to become more transparent. Hope that helps

**Comment by n0mer** [comment]
okay, thanks for explanation.

How to find out whether this feature is deployed or not yet?

**Comment by avinci** [comment]
we will update the issue as we make progress

**Comment by manishas** [comment]
@n0mer we're planning to wrap this up today or latest by tomorrow. We're making our support more transparent, so we will mark the issue in progress as soon as we pick it up and provide EOD updates.

**Comment by ric03uec** [comment]
@n0mer you should now be able to see the ID of the image being pulled from hub

**Comment by n0mer** [comment]
@ric03uec wow, that was fast - thank you!

**Comment by n0mer** [comment]
okay, now i see 'echo "image <image> (id: <id>) pulled successfully."'

**Comment by n0mer** [comment]
linking https://github.com/docker/hub-feedback/issues/458
