### ISSUE TITLE
why image is pulled from the hub, if there were no recent uploads to the hub

### ISSUE THREAD

**Issue by n0mer** [Shippable/support#2015]
/builds/564100150f3caf0c00fa0b03

without #2010 it is impossible to troubleshoot what's actually going on

**Comment by manishas** [comment]
Please see resolution for https://github.com/Shippable/support/issues/2008

We pull custom images every time since we do not want to store customers' images on our build hosts. You can cache your container in case you do want to store your image on our hosts. An overview of how caching works is here - http://blog.shippable.com/container-caching

**Comment by manishas** [comment]
closing this since the question was answered. please let me know if you have any more questions.

**Comment by n0mer** [comment]
this is not the case -pull happens on all consecutive builds

**Comment by manishas** [comment]
pull should happen on all builds...is this not happening?

**Comment by n0mer** [comment]
it happends, but i'm wondering how to use advertized feature of incremental build.

you're doing 'git reset --hard' to HEAD - this is just to cleanup workspace.

but this 'npm install' / 'bower install' takes a lot of time, downloading the same packages every time build is happening. This is both waste of your bandwidth and my time :)
