### ISSUE TITLE
Cannot find project directory

### ISSUE THREAD

**Issue by RonXS** [Shippable/support#2017]
I cannot find the project directory, i've tried many things, but in my docker instance it just does not seem to be there.

$SHIPPABLE_REPO_DIR seems to point to /

Should'nt it have been mounted in there?

I would like to prevent having to git clone again inside the docker instance, when i already should have everything available

(User: InsightYou, build: 56419fd08369bd0d00dbd2b2)

**Comment by RonXS** [comment]
I was able to find that $SHIPPABLE_REPO_DIR is actually set in the configuration of shippable settings of the project, but will it automatically mount there? 

Can't find anything about that.

**Comment by RonXS** [comment]
Another thing, can you create the $SHIPPABLE_REPO_DIR if it not exists?

I set it to /webroot/platform-api and now it complains the directory does not exist. I am now working on getting it created in the Dockerfile, however i think auto creating it makes sense right?

**Comment by avinci** [comment]
There is a path called source in the docker settings. You will need to provide the path where you push the code in your Dockerfile as you are doing a PreCI build. Can you verify you have the right path there?

**Comment by avinci** [comment]
I mean in project settings

**Comment by RonXS** [comment]
Well, i've set it to /webroot/platform-api, but since you already have a checkout step of the code, i would assume you already mount it somewhere in the docker image, or make it available somehow. Otherwise that step would make no sense there right? Maybe i'm just seeing this all wrong though.

**Comment by avinci** [comment]
We are not cloning the repo as we ask where you have the git repo cloned. This is true for Dockerbuild and `git checkout` is done to make sure the right change-set is being tested. Its not cloning or fetching before checkout, just `cd source_code_folder`.

**Comment by RonXS** [comment]
Aha i understand what you're saying, i wanted to prevent doing a double clone as taht seemed unnescesary for me. Wouldnt it be logical to mount the $SHIPPABLE_REPO_DIR inside docker?
It would certainly save me a lot of troubles with having to work with a new public/private keypair inside the docker instance. 

I can just copy data from the mount to a permanent folder if i want to then.

Just a thought, but i get what you're saying.

**Comment by avinci** [comment]
actually, there are 2 things happening here. 
- 1, Docker build
- 2, run that newly built image and then test it.

To do the Dockerbuild, we automatically clone your repo without you having to do any key management etc. as we need to get the Dockerfile. So you have whole source code in the sidecar container which is building your docker file. Now what we don't know is what you are doing in your Dockerfile. for you to put the source code in the right folder, all you need to do is put this command into your docker file `ADD . /some_src_folder`. What we are asking you is, what that `/some_src_folder` is so that in step 2, when we spin your newly built container for CI, we know which folder to `cd` into and then do a `git checkout`

Hope this helps.

**Comment by RonXS** [comment]
Awesome, i understand what you mean there. I'll work that out and hope that fixes my issues.

Thanks!
