### ISSUE TITLE
not able to remove pull image from project settings

### ISSUE THREAD

**Issue by ric03uec** [Shippable/support#2028]
- once `Pull image from` field has been set in project settings, its not possible to remove it
- trying to remove the contents from the field and saving it, shows following error

![image](https://cloud.githubusercontent.com/assets/1110988/11160446/f440bb3e-8a1e-11e5-93bb-4da36032ed71.png)

- the only way to then remove it is re-enabling the project

**Comment by manishas** [comment]
@ric03uec what if you click on the trash icon to throw away settings and do it again?

**Comment by ric03uec** [comment]
ah. it wasn't too evident.
still, i think it should be clear from the error message what action a user needs to take. if a field is empy, the pull image should be reset to using the default value

**Comment by avinci** [comment]
UI is being re-designed and we should look into this when we get to that page. @DavidGDragon

**Comment by bryanvaz** [comment]
We just encountered this issue. A few suggestions for the next release:

1. Have an option to just pull the default image down from shippable (shippable/minv2) if the build is not based on a docker image. I had to go dig this out of the first build I accidentally ran without configuring anything.
2. Confine the Trash button functionality (icon after the cache container section) to only delete the settings in that panel. The UI has that icon grouped with only the Docker build options, however it also deleted our custom AWS deployment settings as well. Very inconvenient, and redundant given you have a delete button at the bottom of the page that clears everything.
3. Consider disconnecting the "cache builds" functionality from the rest of the options above it. Being able to cache between builds without having to create a custom docker image would be great in increasing the frequency of our "nightly" development builds.

Cheers,

**Comment by manishas** [comment]
@bryanvaz thanks for the great suggestions!

By default, we do pull minv2 if nothing is specified in the settings. Not sure why this didn't work for you... it'll be great if you delete the settings and try running another build and let us know if it doesn't work.

Second one looks like a bug. We'll test this out and fix.

Third one is already an open issue while we're reworking the UI and will be addressed soon.

**Comment by bryanvaz** [comment]
@manishas With reference to 1. the "bug"/"feature" is that if you turn on image caching you HAVE to specify an image name, even if you've specified to not pull an image. What we essentially wanted was fast builds, but we don't want to have to maintain a docker image. In an ideal world, I would select "default shippable" for the image since I am not pulling a custom docker image, then select caching, so that our environment is already configured from the last time we built the app. Then as Shippable updates and improves the default image to match updated commands and build processes, our builds would just automatically roll those in as well (without us having to specify or build a new docker image with those same improvements).

**Comment by DavidGDragon** [comment]
This issue should be resolved with the next deployment. https://github.com/Shippable/pm/issues/4929

**Comment by bryanvaz** [comment]
Cheers @DavidGDragon !
