### ISSUE TITLE
Add support for Python 3.5

### ISSUE THREAD

**Issue by brendan-rius** [Shippable/support#2044]
Could you please add support for Python 3.5?

**Comment by pquentin** [comment]
+1

Any ETA on this?

**Comment by manishas** [comment]
We're actively working on being able to add language specific images which will be updated with latest language versions and services. We can prioritize Python and the ETA is 12/4 at the very latest. I will try to shoot for 12/2 though.

**Comment by manishas** [comment]
@quentinpradet @brendan-rius can you share some information about what you need in the image so I can make sure we address that?

I.e. Python 3.5 and any services or tools?

**Comment by pquentin** [comment]
@manishas I got a bit confused and it turns out our team does not need Python 3.5 support from Shippable.

To ensure all our environments (dev, test, staging, prod) are as close as possible, we use a custom image based on Ubuntu 15.04 where the services we use (Elasticsearch and RabbitMQ) are pre-installed. If I understand correctly, Shippable applies a bash script on top of this custom image. This script (shown in the script tab of all builds) calls the `setup_ve` bash function which creates a virtual environment using the correct Python version. The version is inferred from $SHIPPABLE_PYTHON wich is itself inferred from the `python` setting in the yaml file.

This means two things:
  * We don't need to create the virtual environment ourselves since Shippable is doing it now. And sure enough, the [Python-specific Shippable docs](http://docs.shippable.com/languages/#python) no longer recommends this.
  * As soon as we install Python 3.5 in our custom image in /usr/bin/python3.5, we will be able to use Python 3.5 to run Shippable tests. We won't need to wait for 12/4.

**Comment by brendan-rius** [comment]
I currently do not use my own image, but the default [Ubuntu 14.04 + Python image](https://github.com/shippableImages/ubuntu1404_python) (assuming this is what you use internally when there's no specific image in the `shippable.yml` and when the language is set to Python) like: 

```
language: python
python:
  - "3.4"
install:
  - blabla
script: blabla
```

The solution would then be to install Python 3.5 in [the default image](https://github.com/shippableImages/ubuntu1404_python). [I just opened a pull request to install it}(https://github.com/shippableImages/ubuntu1404_python/pull/2).

**Comment by manishas** [comment]
our new build images are in the [drydock repo on Docker Hub](https://hub.docker.com/u/drydock/)

The python images have python 3.5 on them.
