### ISSUE TITLE
Multiple Transient CI Containers

### ISSUE THREAD

**Issue by cschlegelmilch** [Shippable/support#2070]
Hello,

I've looked at a number of previous support tickets and still can't quite figure out the answer:  is there a way to create transient containers that hold test data as part of the CI build cycle?  Currently, we have JUnit managing container lifecycle to support a number of different tests in our build.  These containers are specific to each testing context and are spun up and destroyed multiple times in a test run.

My best guess is that this is NOT a use case for Formations which appears to be optimized for persistent containers.  Is this correct?  And if so, is there a way within a CI build cycle to run other containers as part of the build that will ultimately be destroyed once the build is complete?

Thanks,
Craig

**Comment by cschlegelmilch** [comment]
@manishas Can I assume from the feature request label that this is currently not supported?

Thanks,

Craig

**Comment by manishas** [comment]
@cschlegelmilch sorry i tagged it as a feature request without really explaining.

You're correct... at the moment, we do not have a way to run transient containers during the CI workflow. This is mainly because we run all builds in docker containers and for security reasons on a multi-tenant platform , we do not want to allow docker in docker scenarios.

However, we've recently introduced a single tenant CI plan that lets you run builds on dedicated hosts. We plan to open this plan up very soon to scenarios like using docker compose, etc which will address your needs.

**Comment by cschlegelmilch** [comment]
You mention you support single tenant CI.  You have any pricing details published?  Can't seem to find anything on your website.

**Comment by manishas** [comment]
We just launched it and it's in preview, so it's free to use while in preview. 

Details will be published on our website soon... but if you choose st-ci-beta on your billing page, it will give you an estimated price at launch. Pricing is for parallel builds, and we'll offer a freemium plan with the first parallel build free.

For more information, shoot me an email at manisha@shippable.com and I will send you more details.
