### ISSUE TITLE
Inconsistent build times

### ISSUE THREAD

**Issue by fabiocarneiro** [Shippable/support#2113]
I've noticed that the build times are very inconsistent. Yesterday I had 11 PR builds, with absolutely no changes in configuration and they ranged from 4 to 19 minutes.

I would like to know why this happens. My guess is that you are using instances of different types to run those builds or not reserving resources to a specific build, and then when the instance load differs you have different performance. 

If my guess is correct, that is a good behavior for the free plans, but if we are paying for our minions, they should have dedicated resources.

Its also strange that it depends on time, in the morning the build is very fast, and after 12 GMT+2 it starts to get slower and slower. The funny thing is I can achieve the same speed with one free minion in the morning that I can achieve with 3  minions after 12, because it takes 3, 4 times more time for each build.

**Comment by chriskinsman** [comment]
I have noticed this also.  My guess is that as the day progresses their kubernetes cluster is running more minions per host thereby decreasing performance.

**Comment by fabiocarneiro** [comment]
@chriskinsman Yes, this is what I meant.

**Comment by manishas** [comment]
looking into this... we didn't find any hosts running near capacity, but will dig in deeper and add more if needed.

**Comment by manishas** [comment]
@fabiocarneiro one solution if you do not want to depend on multi-tenant minions is to switch to our single tenant ci plan. you should see it as an option on your billing page plan dropdown. 

With this, you can attach any DIgital Ocean or EC2 machine to your subscription and only your builds will run on that machine(s). We still limit number of parallel builds so a huge advantage of this approach is that you can attach a big machine and we will run your builds in containers without memory constraints.... so potentially much faster. Also, you can SSH into the machine since its your build node.

Single Tenant CI is free right now and will be launched fully in January at which point you'll pay around  estimated price you'll see when you sign up for the plan. 

Let me know if you're interested or have any questions :) same for you @chriskinsman

**Comment by fabiocarneiro** [comment]
@manishas why do you limit the number of parallel builds on single tenant CI? Just because you have no other way to charge? Its kinda strange to pay for minions and also pay amazon for the ec2.

Btw, the problem is not the memory limit, but the build times being inconsistent.

**Comment by goosetav** [comment]
hi @manishas also seeing this problem right now on one of our builds. Looks almost like a bandwidth issue... we're running a matrix build with 2 combos. installing ruby 2.1.6 is taking wildly different times for the 2 legs of the matrix:

matrix 1: https://gist.github.com/goosetav/3f28407bb29089a54313 -- download is still running (over 15 minutes)
matrix 2: https://gist.github.com/goosetav/383e9cf424cbfbe6010f -- downloaded in about 3 seconds

Build ID 5670ecde24ad970d00288e80

**Comment by fabiocarneiro** [comment]
@goosetav Yes, I got the same conclusion. It really seems to be bandwith issue.

**Comment by chriskinsman** [comment]
I am interested @manishas

**Comment by manishas** [comment]
We have upgraded the build system and this should not happen any more because of the new architecture. Closing.
