### ISSUE TITLE
Receiving email build alerts for no good reason

### ISSUE THREAD

**Issue by mgladdish** [Shippable/support#2117]
A few days back I started receiving build notifications via email for all my projects on Shippable. This is new - I didn't get these alerts previously. 

None of my `shippable.yml`s have email notifications turned on, and none of the build UIs do either. (I prefer to get notifications into a dedicated slack channel instead).

1) Why did I suddenly start getting these emails
2) How can I turn them off

**Comment by kanthchandra** [comment]
Hi @mgladdish recently we upgraded our notification system and I think this may be a side effect of this. in order to debug this further can you please provide us the following details.

1. The shippable.yml notification config (if there is any)
2. Can you also please forward email which you received?

You can send the details to chandrakanth@shippable.com

**Comment by mgladdish** [comment]
Hi,

Here’s a shippable.yml

branches:
  only:
    - master

language: scala

scala:
    - 2.11.7

jdk:
   - oraclejdk8

services:
	- mysql

before_install:
  - shippable_retry sbt update

before_script:
   - mysql -u root -e "create database if not exists deployertest; grant all privileges on deployertest.* to 'deployertest'@'localhost' identified by 'deployertest'; flush privileges;"

script:
   - sbt ';test;it:test'

after_script:
   - mkdir -p shippable/testresults
   - mv target/test-reports/*.xml shippable/testresults/

cache: true


And here’s an email alert I got for this project.

**Comment by kanthchandra** [comment]
Hi @mgladdish ,

I'm able to see you shippable.yml but for some reason I'm not able to see any emails from you.

**Comment by oratthumzap** [comment]
hi,
this is also happening to us.
we've been getting BUILD SUCCEEDED emails even though we set our .yml file to send emails on state change.
the relevant section on the .yml file is as follows:

notifications:
    email:
        recipients:
            - test@example.com
        on_success: change
        on_failure: always

**Comment by chriskinsman** [comment]
We are also seeing this.  Our config is:

notifications:
     email:
         recipients:
             - xxxx@pushspring.com
         on_success: change
         on_failure: always

We are now getting emails on every build success instead of just on state change.

**Comment by mgladdish** [comment]
And it's still happening for me.

It's pretty tedious getting spammed by your own builds :(

**Comment by kanthchandra** [comment]
Hi Everyone,

We apologize for the inconvenience caused. The new yml structure is designed to give you finer control over when you want to get notified. But if that is not working as expected I will definitely take a look at this the first thing tomorrow morning. 

I will need more info in order to debug this. Can you please provide the link to the build for which you got notified (although you had not configured to get notified for that particular scenario). You can find the link for the build in the email or It would be of great help if you can forward one such email to chandrakanth@shippable.com

**Comment by mgladdish** [comment]
But the _old_ yml structure wasn't working as expected.
Neither is the new one.

https://app.shippable.com/builds/56d5bc65f42d580c007eea7d

**Comment by kanthchandra** [comment]
A few things came up today morning and I'm starting to look at this now. BTW @mgladdish and @chriskinsman both the builds ran on the old system so you would have got the notification from old engine. I'll see what's wrong and get back to you as soon as I have more info.

**Comment by manishas** [comment]
Closing this since it should not happen with the new build system. Please let us know if you still run into this after migration.
