### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by marinsicavirdol** [Shippable/support#2120]
This is my [build](https://app.shippable.com/builds/5669c97434eda80d0018ea8b)

And this is my shippable.yml:
```json
# language setting
language: node_js


# version numbers
node_js:
  - 4.1.1
  
before_install:
  - node --version
  
after_success:
  - npm run postinstall
```

My postinstall script is defined in package.json:
```json
"scripts": {
    "postinstall": "node ./node_modules/gulp/bin/gulp.js compile"
  }
```
This script compiles my coffee and sass files and puts the new files into a /build folder. In my Dockerfile I have a command: COPY build/ /app/public . The problem is that the build folder is not found. 

What can be the problem here?

**Comment by avinci** [comment]
are you doing a POST Docker Build?

**Comment by andredantasrocha** [comment]
Same problem happens with my project. I'm using POST Docker build.

The `script` step runs successfully and creates the `dist` directory (it seems at least).
The `build image` step fails:
```
Step 1 : COPY dist/ /var/www/html/
dist/: no such file or directory
```

**Comment by marinsicavirdol** [comment]
I'm doing a post npm install

**Comment by manishas** [comment]
@marinsicavirdol sorry this fell off the radar. We have completely revamped our build system and you can now run docker commands like `docker build` and `docker push` from your yml. yml configuration is explained at http://docs.shippable.com/ci_configure/

I am closing this issue since it is from before the upgrade. let us know if you need help with this.
