### ISSUE TITLE
no active subscription

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#2123]
I tried to up https://app.shippable.com/subscriptions/546a8c11d46935d5fbbddbed to 2 containers and saw an error message after adding a saved credit card. Now the billing page won't load at all and if I try to build a project I get:

```
No active subscription plan for: 546a8c11d46935d5fbbddbed
```

**Comment by trriplejay** [comment]
Hello, 

Sorry about that.  It looks like there was an issue processing the card that you tried to use.  Can you double check that it is valid? I'm also opening an internal issue for this since we don't seem to be handling this situation very well.

For now, I've restored the free plan to your subscription.

**Comment by jamesmk** [comment]
Thanks for restoring the account.
