### ISSUE TITLE
Env entry kills script processing

### ISSUE THREAD

**Issue by kkarski** [Shippable/support#2130]
Please look at builds

https://app.shippable.com/builds/56705dd3f5d42b0d00727eeb

vs

https://app.shippable.com/builds/56705e259664d10e00bd5994

The only difference between the two is the presence of an env section in the yml file. However, in the first case, proper script processing is broken while in the second everything works fine when the env section is removed.

**Comment by trriplejay** [comment]
looks like your environment variable names are not valid bash variable names.  The `.` is likely causing the build script to exit before it has a chance to take any actions.

We should be handling this situation better, but in the meantime, I'd suggest trying again with different variable names, perhaps using `_` instead of `.`

**Comment by manishas** [comment]
closing this issue. please let us know if you need further help with this.
