### ISSUE TITLE
Incorrect MySQL client library version

### ISSUE THREAD

**Issue by kaspernj** [Shippable/support#2163]
Please see this build:
https://app.shippable.com/builds/5684216bb7aa190d00aa2227

Maybe the virtual machines have gotten their MySQL client updated to a new version, but the pre-cached gems hasn't?

```
Incorrect MySQL client library version! This gem was compiled for 5.6.15 but the client library is 5.5.40.
```

**Comment by sushantbajra** [comment]
@kaspernj , found any solutions? I am stuck on that too ..
`Incorrect MySQL client library version! This gem was compiled for 5.6.15 but the client library is 5.5.40.`

Here is my shippable.yml file

```
# language setting
language: ruby

# version numbers
rvm: 2.3.0
cache: true

# env:
#   - CI_REPORTS=shippable/testresults

# before_script:
#   - mkdir -p shippable/testresults

# activate rvm
before_install:
  - source ~/.rvm/scripts/rvm
  - rvm install $SHIPPABLE_RUBY --verify-downloads 1
  - source ~/.bashrc && ~/.rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY

#install the dependencies
install:
  # - sudo apt-get update
  # - sudo apt-get -y install python-software-properties libmysqlclient-dev
  # - gem install mysql2
  - bundle install --gemfile="Gemfile"
  - ruby -v
  - node -v
  - gem -v
script:
  - bundle exec rake --trace
```

**Comment by kaspernj** [comment]
@sushantbajra Nope. I have tried many things like deleting the project from Shippable and creating it again without any luck. I actually ended up switching this project to Travis, even though I am a paying customer of Shippable :-/

**Comment by avinci** [comment]
@kaspernj I am super sorry about no one getting back to you on this. We have completely revamped our build system from ground up to address these issues. We also have updated all our images to make sure they are 100% current. 

If you are running cache, one thing you could do is do a reset cache either from the UI or through the commit message and it should nuke your cache. 

On the new system, we are revamping cache to do it at a folder level and this should keep the cache updated for every build. This should resolve the limitation we have with docker containers and the layering limit due to which we cache only the first build. 

Hope this helps.

**Comment by avinci** [comment]
Also, we have not upgraded on the customers to new plan as we are stabilizing the system before we move everyone over. Migrations should be completed by end of this month.
