### ISSUE TITLE
Formation: ECS service deploy fails

### ISSUE THREAD

**Issue by cavis** [Shippable/support#2180]
Deployment to ECS fails whenever I have the "Load Balanced" checkbox checked in the Routing section.  Error message is simply "Deployment has failed."

Looking through AWS after failure - the ELB seems to be setup correctly.  But no Services are created within the ECS cluster.

It deploys the service just fine if I uncheck "Load Balanced", or remove the load balancer entirely.

Any ideas?  I'm at a loss.

**Comment by trriplejay** [comment]
It looks like shippable can't find a proper role to use when creating your service.

Currently to deploy a service with a load balancer Amazon requires that a role be specified that allows the container agent to talk to that load balancer.

To allow this, we're searching for a role that contains both "ecs" and "ec2" principals in the trust relationship.

If you have an existing role, you can edit the trust relationship to look like this:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

This will allow us to find that role and then use it to deploy your service.

We implemented this originally based on some Amazon documentation, but now I'm having a hard time finding it.  I'm wondering if it has changed a bit since we added that piece.  I'll continue to investigate this, but if you want your service to work immediately, adding what I described above will accomplish that.

**Comment by cavis** [comment]
Added to our `ecsServiceRole`, and all seems to be working now.  Thanks.

**Comment by manishas** [comment]
closing.
