### ISSUE TITLE
Deploy fails after deploying new LB with same name in ECS cluster

### ISSUE THREAD

**Issue by ttrahan** [Shippable/support#2204]
When an ELB in AWS is changed (either directly in AWS or via Terraform via the Destroy button in Deploy Settings), you can't deploy a service in Shippable that uses that load balancer without performing the workaround below.  The reason appears to be that the new ELB does not have Host Port set up in a Listener rule.

Scenario:
* I have an ELB in AWS named 'demoWWWlb" being used by an ECS cluster successfully (services successfully deployed, services functioning and accessible)
* Stop the service using the Load Balancer in Shippable
* Destroy the ELB in AWS
* Create a new ELB with the same name ('demoWWWlb') in AWS
* In Service Settings, switch to use the new Load Balancer by deleting the previous reference to the old one and adding the new one.
* Click Deploy

Result:
* Deployment failed.

Workaround:
* Delete the previous Load Balancer from the Service Settings
* Deploy the service without a Load Balancer (result: Deployment successful.)
* Add the new Load Balancer with same name in Service Settings.
* Deploy the service (result: Deployment successful).

**Comment by trriplejay** [comment]
Failure occurs because we don't verify that the loadbalancer has the listeners that it needs before trying to deploy.  ECS complains that the loadbalancer doesn't have a listener that it expects.  We don't check in this case because we see that the load balancer name hasn't changed, so we assume the listeners haven't changed.

Ideally, we should check in every deployment that the required listener(s) are present, even if no settings have changed within Shippable.

**Comment by cratz** [comment]
@trriplejay plz don't implement this check until you implemented SSL support otherwise this workaround ( https://github.com/Shippable/support/issues/2184#issuecomment-170070164 ) will no longer work ;)

**Comment by trriplejay** [comment]
@cratz It won't break that scenario.  Basically, during deployment, we will check if the load balancer has a listener with an 'instance port' that matches the 'host port' of your exposed container.  If it does not, then we will add that listener based on your settings.

This is OK, because if the load balancer did not contain a listener with that instance port, ECS would have failed the deployment anyway.  We will only check the 'instance port', since that is the only setting that ECS cares about.

**Comment by cratz** [comment]
@trriplejay 
Thanks for clarification!!! 
I thought you would check the whole LB configuration including Protocol, etc.

**Comment by manishas** [comment]
@trriplejay should this be closed?

**Comment by trriplejay** [comment]
yes, this functionality is in production now. closing.
