### ISSUE TITLE
Is it possible to run build matrix using different images?

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#2210]
Hello,

I develop an app that is a native C app for linux.

I need to ensure that it compiles and works on several supported ubuntu & debian releases.

Is there any option or hack that allows me to trigger build of the same commit using different build images? All of them are all located at docker hub.

**Comment by manishas** [comment]
currently, a single image has to be used for all builds in a matrix. We're in the process of making the yml much more powerful and this is something we will address in an upcoming update soon.

**Comment by manishas** [comment]
This should now be possible with our updated build system. Your subscription needs to be on the Continuous Delivery plan in order to work with the new yml format. If not already migrated, you can update your plan by going to the billing tab of your subscription and choosing the CD plan.

With the [new yml format](http://docs.shippable.com/ci_configure/), you can do something like setting environment variables in your `env` tab pointing to different docker images, and then in the `pre_ci_boot
