### ISSUE TITLE
Pre-CI Dockerbuild builds an image but still a timeout

### ISSUE THREAD

**Issue by realAkhmed** [Shippable/support#2212]
Trying out Shippable and it looks like I am missing something.

I am using a Pre-CI Dockerbuild and building a custom Docker image just for testing purposes. The image is not to be deployed anywhere.

https://app.shippable.com/builds/5699f0d49188220d00ba394b

The Docker image is built correctly, however, Shippable does not detect that the docker build is complete. It waits for couple hours until it times out.

This sounds somewhat like #2040 and #2065 except that I have only registered very recently (Dec 8, 2015) so I assume I am on the newest platform.

My shippable.yml is just
```
script:
  - true
```

Tried the solution based on the procedure described in #2040 with switching back and forth between "Multi-Tenant" and "Single Tenant" subscription plan.

**No luck**

**Comment by realAkhmed** [comment]
Tried the solution based on the procedure described in #2040 with switching back and forth between "Multi-Tenant" and "Single Tenant" subscription plan. 

**No luck**

**Comment by trriplejay** [comment]
It looks like the build step isn't finishing.  How long does it usually take your image to build? could one of the steps be getting stuck? The last step I see in the logs is Step 28, is that the final step?

**Comment by realAkhmed** [comment]
@trriplejay Yes, step 28 is the last step. This is the last line of the Dockerfile. Based on the logs step 28 succeeds and finishes correctly.

Some extra information: if there is any errors during Dockerbuild: those seem to be detected correctly: https://app.shippable.com/builds/569eb345ad224e0c000dcb1c

It is the success that is not detected.

**Comment by trriplejay** [comment]
It looks to me like your build is actually timing out before the docker-build finishes.  It looks like it finishes because in the event of a timeout the active command in the script will still finish, but anything that comes after it will not execute.

If the speed of the internet connection is the main limiting factor in your build, then I'd say that's likely the limiting factor on Shippable as well.  On our multi-tenant system, builds that rely heavily on the network for downloading packages might experience more slowness than that same build run on a dedicated local system.  We're in the process of updating our build flow to correct this problem, but I'd say the fix is a few weeks out still.

Let me know if you have any questions.

**Comment by realAkhmed** [comment]
@trriplejay Unfortunately, I am pretty confident that docker build finishes first and the successful build is just not being detected for one reason or another.

It definitely looks like a bug the more I learn about it

- I monitored the Dockerbuild multiple times in real time -- it is finished within 30 minutes and is just literally hanging there for 1 hour 30 minutes more until it time outs.
     - the last command executes and completes successfully within the first 30 minutes. This is certain.

- the same project with the same Dockerfile works on my machine with the exact same `sudo docker build` command
- the same project with the same Dockerfile works on another CI platform without problems

**Comment by realAkhmed** [comment]
Closing. Unfortunately, it still won't work on Shippable.
Moved to another CI platform - the same Dockerfile worked fine there.
