### ISSUE TITLE
Access to testresults and codecoverage folder from Docker container

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2228]
Is it possible to access the shippable/testresults and shippable/codecoverage from within a Docker container? I would like to build and run the unit tests within the docker container and copy the output to the respective folders. Thanks

**Comment by cratz** [comment]
@jeppefrandsen yes this is possible. Check out this http://docs.shippable.com/languages/

I use it like this:
in shippable.yml
```
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/buildoutput
after_script: 
  - cp -r %BUILD_OUT_PUT/% ./shippable/buildoutput
script:
  - %TEST_COMMAND%  shippable/testresults/results.xml
```
Codecoverage folder config is somewhere else

And in my Dockerfile:
```
ADD ./buildoutput/ %BUILD_OUT_PUT_DESTINATION_IN_DOCKER_IMAGE%
```

**Comment by jeppefrandsen** [comment]
@cratz Thanks. This is for copying the buildoutput content to the Docker image right? Is it also possible to copy from within the Docker container to the shippable/buildoutput folder?

**Comment by cratz** [comment]
@jeppefrandsen yes this is to copy buildoutput (build-artifacts) in to the Docker image.
Sorry I don't get your point :(

My current setup is this:
- I use shippable's default image to build the job and run tests (can't use my custom image because of reasons ;) )
- this generates testresults, codecoverage and buildoutput (build-artifacts)
- and copies this stuff to the "shippable/" folder
- Than I build my custom image according to my Dockerfile and in my Dockerfile I have access to the "shippable/" folder 
- last step is push new image to docker hub

It should work similar if you are using a custom docker image to run the build.

**Comment by jeppefrandsen** [comment]
@cratz Thank you very much for the info. I have changed to use pre CI flow and do the commands in the shippable.yml file instead and now it works.
