### ISSUE TITLE
Random Could not parse object errors

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#2229]
Recently I started to get the following errors in the git_sync phase. They happen randomly on multiple repositories. Usually next commit works fine.

```
git checkout -f master --
  git reset --hard 935c7c1cd196d3e67d50dfde1fc15a6b84a93b07
fatal: Could not parse object '935c7c1cd196d3e67d50dfde1fc15a6b84a93b07'.
```

**Comment by trriplejay** [comment]
One possibility is that the commit was amended before the build started.

When a webhook is triggered, we use the commit sha from the hook body.  When a commit is amended, a new sha is created for it, replacing the old one.  If your webhook build was waiting in a queue for any length of time, it is possible that the sha changed before the build ran, so that when the build eventually tried to pull the code, it could no longer find that sha.

**Comment by mspanc** [comment]
I do not amend commits. It can't be this reason.

**Comment by manishas** [comment]
@mspanc can you provide us with a build link so we can take a look?

**Comment by manishas** [comment]
Closing this issue. Please let us know if this is still happening and we will reopen and take a look.

Thanks!
