### ISSUE TITLE
Formation service container port entry not working

### ISSUE THREAD

**Issue by paololim** [Shippable/support#2243]
I am trying to set a "container port : host port" string of "6041:9000", but the UI wouldn't let me.

Here are the settings for my image: https://app.shippable.com/formationServices/56bcfd8d99c4010d00cc940f/settings

Note that the container image somehow defaulted to the port mapping: `6041:29258`. I click on "edit" and try to update it to `6041:9000`, but the UI wouldn't allow me.

**Comment by trriplejay** [comment]
Actually the UI is a bit misleading here. It's really just the container port that we want.  Currently we're assigning a randomly generated port as the hostPort.

If you plan to expose your service through a load balancer, you can specify a different external port in the routing section, once you select a load balancer to use.

**Comment by paololim** [comment]
Thanks for clarifying that. Any chance that users could specify both container and host ports any time soon?

**Comment by trriplejay** [comment]
I think it's something we would allow in the future, but I'm not exactly sure when.  The best workaround for now is to use a load balancer, which will allow you to specify any 'external port' that you want, and it will automatically connect it to the generated host port.

**Comment by npahucki** [comment]
+1 on this feature. Not having this prevents me from doing ELB terminated SSL, because only the HTTP port is mapped. For ELB SSL termination, I need to manually create an ELB listener with the certs configured. To get this to work, I need the host port to always be the same as to which the ELB listener is forwarding. I realize that this means that only one instance of the task can be run at a time, but in my case that is fine (a dev/integration testing server). 

In AWS's ECS console you can specify the host port to map to, so seems like it wouldn't be a big deal to implement, just accepting and sending another param to ECS.

**Comment by manishas** [comment]
Formations has now been deprecated and you can use pipelines instead - http://docs.shippable.com/pipelines_overview/

We have fixed this issue and you can now specify host port and container port both. Try it out :)
