### ISSUE TITLE
Push to multiple repository

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#2282]
The new set of features look awesome. Great job ! I have one question - If I create multiple hub integrations, will the docker image with multiple tags be pushed to all configured docker repositories ?

**Comment by manishas** [comment]
@phagunbaya thanks :)

You should be able to push your docker image with multiple tags to all docker repositories as long as you have the right config in the yml. 

However, we are fixing a bug that limits you to one Docker registry since project settings does not let you add more than one hub integration. ETA for fix is EOD tomorrow.

**Comment by manishas** [comment]
@rageshkrishna we need to pick this up today.

**Comment by pranaypareek** [comment]
@phagunbaya this feature is live now. Would you please check it out and let us know?

The docs here `http://docs.shippable.com/ci_configure/#pushing-to-multiple-registries` should be helpful.

Thanks!

**Comment by pranaypareek** [comment]
This is complete.
