### ISSUE TITLE
No obvious way to disable/unsubscribe from emails

### ISSUE THREAD

**Issue by lukesandberg** [Shippable/support#2285]
Shippable has started emailing me about github projects i don't contribute to.  They appear to have forked a project i do contribute to...  

How do i make it stop?  Should i just start marking these emails as spam?

**Comment by manishas** [comment]
@lukesandberg if a project is enabled for CI on Shippable, the owners of the original project do get a one time notification.  This is because we follow GitHub's permissions, so just like GitHub notifies you when someone forks a project you contribute to, you also get notified when someone enables it for CI.

We will investigate whether we have tighter control over this. In the meantime, marking it spam should be okay since you should only see one email per fork that was enabled for CI.

**Comment by lukesandberg** [comment]
That isn't what happened.  I got 4 emails for a build breakage in a project i have never heard of

The project is: https://github.com/mooneygr/guava.git

**Comment by lukesandberg** [comment]
but ok.  will mark as spam

**Comment by manishas** [comment]
I think it's because you're shown as last committer for the project. I am going to reopen this and see if we can fix this somehow.

**Comment by manishas** [comment]
We should verify that --last committer and --last author are collaborators on the project and only send emails if they are collaborators.

**Comment by ankul-shippable** [comment]
@lukesandberg We have fixed this bug. Please sync your account once. Let us know if you are still getting those emails. Thanks.

**Comment by manishas** [comment]
Closing this issue. Emails should not be sent to last committer or author if they are not collaborators on the current repo.
