### ISSUE TITLE
Docker hub login fail

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#2289]
https://app.shippable.com/runs/56d5474bdf0cf40c00a83df2

Even after re-entering password

**Comment by luckyraul** [comment]
Still the same https://app.shippable.com/runs/56d5ebca2277580c0013afb4

**Comment by luckyraul** [comment]
@manishas whole day this problem

**Comment by manishas** [comment]
looking into this...

**Comment by manishas** [comment]
@luckyraul what is your scenario? Can you share your shippable.yml?

**Comment by luckyraul** [comment]
@manishas I asked you here https://github.com/Shippable/support/issues/2022but finaly come up with

**Comment by manishas** [comment]
@luckyraul this is a bug at our end. We'll work on a fix today.

**Comment by ric03uec** [comment]
@luckyraul this is happening because the custom image you're using does not have `sudo` installed in it. and the command `sudo docker login ....` is failing. 
can you try to add the line
```
RUN apt-get install sudo
```
in the dockerfile and try again.
if the problem still persists, we can get on a  call and debug this. Let me know what works for you

**Comment by luckyraul** [comment]
Firstly I don't want to docker push from my image. I just want to build and push, as it was before
Secondly I can't see my image run output in ci section
Thirdly fix please escaping of console output

**Comment by luckyraul** [comment]
after adding ```agent_only: true```
https://app.shippable.com/runs/56d69166ebf58d0b00800bcd

Much better - hovewer docker push did not have success

**Comment by ric03uec** [comment]
@luckyraul 
- we're working on a fix for the docker login issue. this will be deployed by end of day. i'll update you as soon as its done
- fixing the console escaping is a known issue and we'll be picking it up shortly after we get past more critical bugs

**Comment by ric03uec** [comment]
@luckyraul your builds should work correctly now after removing the `agent_only:true` line. 
can you please try this again.

**Comment by luckyraul** [comment]
same thing https://app.shippable.com/runs/56d87e795356400c00f98734

**Comment by ric03uec** [comment]
i see the issue with this build now.
- the image you're using is not one one we officially support (ubuntu 12.04 and ubuntu 14.04), because of which the `sudo` part fails, more specifically(`sudo docker login ...`). We are handling the missing `sudo` for supported images correctly right now.
- I agree that we should not care about what is installed on the image when we only have to push it to a registry endpoint. So it makes sense when you say you don't want to install anything on your custom image
- To fix this, we're adding support for another section in the yml, called `push`, that will run **outside** of the CI container. That should take away the `sudo` (or any other) dependency for the use case like yours. The feature is being tested in beta right now and will be pushed out within a day. 
I apologize for the delay in fixing this

**Comment by luckyraul** [comment]
any updates?

**Comment by ric03uec** [comment]
@luckyraul 
- the `push` section is now available in the yml. you can now put the `docker push ...` command in that. here's the syntax

```
  push:
    - docker push <your image name>
```
- this section of the yml runs **outside** the ci container so there is no dependency on the image you're using. HTH

**Comment by luckyraul** [comment]
1) https://github.com/mygento/docker-puppet/blob/9e55707d070da4d2327252bbff0e53e0554943d0/.shippable.yml - same problem - https://app.shippable.com/runs/56df24b436784b0c009d5697
2) https://github.com/mygento/docker-puppet/blob/master/.shippable.yml - same problem - https://app.shippable.com/runs/56df25e99227720c0079941d

**Comment by ric03uec** [comment]
- you need to keep the `agent_only: true` flag in the yml. sorry forgot to mention that earlier

**Comment by luckyraul** [comment]
It worked well https://app.shippable.com/runs/56df28409227720c0079f385

Update docs please

**Comment by luckyraul** [comment]
@ric03uec except second build failed

**Comment by ric03uec** [comment]
- the error is happening because the ci container does not have `GLIBC_2.14` (see logs in `wait_for_exit`-> `sudo docker logs ...` section)
- the shippable ci runner module expects certain dependencies that are installed by default on the official images. so you can either install the dependency(in the dockerfile for `wheezy`) or use one of our official images
- we will be supporting additional images (including debian) but this is not an urgent feature as of now

**Comment by luckyraul** [comment]
Can you lower dependency for libc6 for supporting wheezy? 
Is it hard dependency for features or you just took the ubuntu ones?

**Comment by ric03uec** [comment]
we can try to compile our build runner with a lower version of `GLIBC`. but for now this is not a critical fix for us. Im updating the tags on this and will let you know once we pick this up.
@abhijitkini i'm marking this as deferred. This will help us increase the number of images we support.

**Comment by luckyraul** [comment]
@ric03uec 
I also got noticed that your build runner change custom image locale variables (for ex from ru_RU.UTF-8 to en_US.UTF-8)  and it can case problems if such locale is not generated.

**Comment by manishas** [comment]
Closing as deferred for the original request. Pls open another issue for the locale.
