### ISSUE TITLE
API broken

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#2292]
Hello,

It seems that the new release come with a brand new API. Is the old one still accessible ?

**Comment by himanshu0503** [comment]
@rvrignaud : We apologize for the inconvenience, this comes as a major revamp where in we cleared up some of our API's to give you better results.
Can you please tell us any specific API that you were trying to access?

**Comment by manishas** [comment]
@rvrignaud please let us know what APIs you were using and we can send you the updates.

**Comment by pquentin** [comment]
Well, the fundamental issue is that you broke nearly all your routes so we needed to rewrite all our scripts that used the API. It's nice to "send updates", but that still requires a lot of work on our end. Could you at least start versioning the APIs so that things don't break overnight?

We'll create issues about specifics API routes.

**Comment by manishas** [comment]
@pquentin we will definitely version APIs now that we have a clean place to start from. 

I apologize for the changes and agree that they should have been communicated far in advance.

**Comment by rvrignaud** [comment]
Closing this one. We will open specific issues if needed.
