### ISSUE TITLE
COMPOSER_AUTH as secure environment variable

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2328]
I am currently trying to figure out how to provide [`COMPOSER_AUTH`](https://getcomposer.org/doc/03-cli.md#composer-auth) as secure environment variable within builds.

This environment variable is supposed to contain a JSON-encoded string like this:

`{"http-basic": {"example.org": {"username": "username", "password": "password"}}}`

None of these work however:

* `COMPOSER_AUTH={"http-basic": {"example.org": {"username": "username", "password": "password"}}}` ([build](https://app.shippable.com/runs/56d9b69edd978f0c00c3ee20))
* `COMPOSER_AUTH='{"http-basic": {"example.org": {"username": "username", "password": "password"}}}'` ([build](https://app.shippable.com/runs/56d9b76ed66f350e005f4ef9))
* `COMPOSER_AUTH="{\"http-basic\": {\"example.org\": {\"username\": \"username\", \"password\": \"password\"}}}"` ([build](https://app.shippable.com/runs/56d9b852dd978f0c00c449b4))

At least the last two work on a regular shell however. Any idea how to do this or if this is a bug actually?

**Comment by manishas** [comment]
We'll take a look and get back to you...

**Comment by stephanielingwood** [comment]
Hi @mbrodala,

Sorry to take so long to get back to you. This was indeed a bug on our part - however, the good news is that the fix for this is now in production. Either of the latter two methods (the ones that would work in a regular shell) will give you access to your JSON-encoded string as a secure environment variable.

Hope this helps! Let us know if you have any further problems with this.

**Comment by manishas** [comment]
This is deployed to prod, so closing. Please let us know if you run into any problems.

**Comment by mbrodala** [comment]
Thanks for fixing, [works as expected now](https://app.shippable.com/runs/56e27d891852dc0c00984b19).
