### ISSUE TITLE
Newly Enabled Project no Options to Pull Image

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2335]
Our subscription doesn't appear to have been moved to the new infrastructure yet.

I enabled a new project on our account however and it looks like perhaps it came up on the new system as the settings UI is different for the new project from our old projects.

Specifically I am missing the docker options section so that I can indicate the base image to pull for the build.

Is that the case? I need to go in an use the new shippable.yml for new projects even though subscription hasn't been moved?

**Comment by chriskinsman** [comment]
Just tried to use the new yml format and it is ignored so I am going to guess we are still on old platform but for some reason the UX I need isn't showing up...

**Comment by chriskinsman** [comment]
@manishas Any ideas on this?  We are blocked spinning up this new project until we can figure out how to point it at our base build image...

**Comment by manishas** [comment]
@chriskinsman I am looking into how we can handle this. We are shutting down Docker options in a couple of weeks and require everyone using them to move to the new yml format. Since it's being deprecated, docker options are currently disabled for any project not already using them.

We have a couple of options-
- move your subscription to the new plan. since your projects are using docker, you might need to convert to new yml depending on how the translator handles your projects. 
- temporarily enter some data in Docker options for your projects at the backend so the UI starts showing it and lets you change it. I *think* this should work but need to check.

**Comment by chriskinsman** [comment]
Prefer the latter if possible for now.  Don't want to rush the subscription move until you are ready...

Would like to get this project building today though...

**Comment by manishas** [comment]
@chriskinsman can you check now? Docker options should be visible for your new project.

**Comment by chriskinsman** [comment]
Working
