### ISSUE TITLE
Help with migration

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2348]
I am stuck here so needed some help with the following

1. Running build with tests
2. Pushing docker image to AWS EBS

My shippable.yml and Dockefile is attached
[shippable-sample.txt](https://github.com/Shippable/support/files/165210/shippable-sample.txt)
[Dockerfile.txt](https://github.com/Shippable/support/files/165211/Dockerfile.txt)

Current issues I am using the deafult java image from shippable

1. Once i setup the DB and run a mvn install, my build fails as the triggers dont work on the database, did not face these issues with the older version.
2. If i disable tests the build goes through, image is created and pushed to hub. After this the process of deployment to AWS EBS fails due to some zip error on the Dockerrun.run.json file.

Would like to complete this migration ASAP.

**Comment by ttrahan** [comment]
@sheldon-sminq : 

The issue you're seeing about a zip error indicates that Shippable is treating it as a source code deployment instead of a Docker deployment.  Remove the .ebextensions file as part of this deployment and that should eliminate the zip error.

Secondly, for your EBS deployment, there are a few different variations that can affect it.  First thing to double-check is that the Docker image name and tag information is being properly passed to the EBS deployment integration.  With the move of Docker functionality to the shippable.yml, the EBS deployment needs to be told what these values are now.  So, you'll need to export three values as part of your yml.  Based on the yml you provided, you should add them after your docker commands in the post_ci section, as follows:

```
    post_ci:
       - docker commit $SHIPPABLE_CONTAINER_NAME sminq/baseimage:$BUILD_NUMBER
       - docker push sminq/baseimage:$BUILD_NUMBER
       - export EBS_IMAGE_TAG=$BUILD_NUMBER
       - export EBS_IMAGE_NAME=sminq/baseimage
       - export EBS_VERSION=shippable.sminq.baseimage.$BRANCH.$BUILD_NUMBER
```

Note, if you're running into any other issues, you can handle all EBS commands directly in the yml to get it working.  Here's [a sample project](https://github.com/ttrahan/micro-api/tree/amazon-eb-cli-beta) that takes that approach.  Make sure you're looking at branch 'amazon-eb-cli-beta'.

**Comment by sheldon-sminq** [comment]
I am still confused as to how to go about this,

check this build https://app.shippable.com/runs/56e0d5a99c434f0d00996f29

Also attached the Dockerfile and shippable.yml file

When does my dockerfile get read? I am using the default image from
shippable for Java.

**Comment by ttrahan** [comment]
@sheldon-sminq : can you jump on a Hangout at 9:00p PST to discuss?  I think it would help to walk through your scenario.  if so, please email me at tom@shippable.com and I'll send the invite.

**Comment by sheldon-sminq** [comment]
is that 11:30 AM IST?

**Comment by ttrahan** [comment]
Actually, I believe that would be 10:30a IST

**Comment by sheldon-sminq** [comment]
I finally managed to get it to work with the EBS UI setup. Just need to
check on why the mysql DB does not load triggers during the CI test process.

**Comment by trriplejay** [comment]
@sheldon-sminq are you still having issues with the mysql triggers?

**Comment by sheldon-sminq** [comment]
I haven't yet checked will try today

**Comment by sheldon-sminq** [comment]
Still facing the issue my mysql triggers dont fire when my tests runs as a
result there are failures.

**Comment by sheldon-sminq** [comment]
When i shifted to the older shippqble container minv2 my tests started running successfully.

But in the post_ci process i get the following error

docker build -t sminq/baseimage:$BRANCH.$BUILD_NUMBER .
WARNING: Error loading config file:stat /home/shippable/.docker/config.json: permission denied
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by rageshkrishna** [comment]
@sheldon-sminq Please try running the docker commands with `sudo`.

**Comment by sheldon-sminq** [comment]
Works @rageshkrishna thanks for the quick update

**Comment by manishas** [comment]
Closing since this was resolved.
