### ISSUE TITLE
"Host key verification failed" during git_sync step

### ISSUE THREAD

**Issue by sblaz** [Shippable/support#2352]
This started suddenly yesterday

**Comment by manishas** [comment]
@a-murphy can you take a look at this?

**Comment by manishas** [comment]
@sblaz can you point us to a failed build?

**Comment by a-murphy** [comment]
It looks like your project was public and then was made private on GitHub after it was enabled.  We use SSH keys to clone private projects, but not public ones because we need additional permissions to add the keys.  There's a "Reset" button on the project settings tab that will create a new deploy key for your project and add it to the GitHub repository now that it's private so that it can be cloned again.

**Comment by sblaz** [comment]
I think our project was private to begin with and was cloning successfully up until yesterday.  All the private projects for our organization are failing at the git_sync step actually.  Tried the "Reset" button, was notified about a new public key added to github, still seeing same behavior.

**Comment by rageshkrishna** [comment]
@sblaz I think I know what's going on here... in the new build system, we no longer automatically inject the `$HOME` environment variable. We try to update the current user's `~/.ssh/config` file to insert `StrictHostKeyChecking no`. In the new build system, $HOME is not set when we start the build, and it appears your custom image doesn't define it either. This causes ssh config to end up in the wrong place, and trips up the git sync because the server's fingerprint is not recognized.

I can think of two ways to fix this:

1. Update your image's Dockerfile to include `ENV HOME /root`

1. If you're using the new YML format, you can pass a docker option in the `pre_ci_boot` section, like this:

````
build:
  pre_ci_boot:
    image_name: your/image
    image_tag: your_tag
    options: "-e HOME=/root"
````

**Comment by sblaz** [comment]
Thanks @rageshkrishna! We changed our Dockerfile to based on drydock/u14nod:prod instead of shippableimages/ubuntu1404_nodejs and that seems to have cleared up the $HOME=/root issue: git_sync step now successfully clones our repo. Thanks for the help.

**Comment by manishas** [comment]
:+1: 

Closing.
