### ISSUE TITLE
Cache hangs forever, blocking builds

### ISSUE THREAD

**Issue by bbradbury** [Shippable/support#2362]
https://app.shippable.com/runs/56e1c4a9bb39610c0090fda7 ...been stuck for an hourish

**Comment by manishas** [comment]
@bbradbury There are some issues with caching on the new build system, mainly that we're flattening images before pushing them and this is taking too much time. This is especially bad since you're using minv2 which is a 15gb+ image.

We are working on addressing this with folder level caching which will be available next week.
 
At this point, we have the following options:
- Turn off caching for your builds. This should be much faster right now than caching your builds.
- We can revert your subscription to the old build system until the new cache implementation is available.

**Comment by bbradbury** [comment]
Thanks Manisha. We'll turn off caching for the moment.

**Comment by jamesmk** [comment]
@manishas I'm having a similar issue where builds are running smoothly, but it's hanging on the `build_on_success` stage. Has there been any progress with this? If I turn off caching, I'm looking at 15 minute builds.

https://app.shippable.com/runs/56eac96572dbf80c00bbfabe

thanks

**Comment by manishas** [comment]
@jamesmk we will definitely have the new implementation of caching available tomorrow. It's being tested as we speak. 

Can you please turn off caching today and I will update this issue as soon as the new caching is deployed to prod.

**Comment by manishas** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
The first build you run with cache turned on might show an error during the upload cache step but the cache should be successfully pushed during the second build and be available thereafter.
