### ISSUE TITLE
BUG - BRANCH environment variable incorrectly reporting Target Branch on Pull Requests 

### ISSUE THREAD

**Issue by hunt3ri** [Shippable/support#2366]
When I create a Pull Request on Github, Shippable is incorrectly setting the BRANCH environment variable to the same value as the BASE_BRANCH, as can be seen from this debug statement

echo Target Branch is $BASE_BRANCH
echo Running MapStore API Deploy, current branch is $BRANCH

results in

Target Branch is **develop**
Running MapStore API Deploy, current branch is **develop**

It shoud read

Target Branch is **develop**
Running MapStore API Deploy, current branch is **my-pull-request-branch**

This is causing a big problem with our deployment scripts as I only want to deploy from the develop branch

**Comment by a-murphy** [comment]
There is a $HEAD_BRANCH environment variable set for pull requests that contains the name of the branch from which the pull request was opened (my-pull-request-branch in your example).  Additionally, $IS_PULL_REQUEST can be used to determine if the build is for a pull request or a commit if you need to know if $HEAD_BRANCH will be available or not.

**Comment by hunt3ri** [comment]
Thanks for the reply that really helped.

Having looked at the build a bit closer it appears shippable starts two builds for a Pull Request, it builds the PR branch, eg BRANCH, and the Target Branch, eg BASE_BRANCH.

Is this expected behaviour, as I don't see it documented anywhere?

Thanks
Iain

**Comment by a-murphy** [comment]
One of those builds should be the pull request, where it is building ```BASE_BRANCH``` with the changes in the pull request included (so that the result should be what it would be if the pull request is merged).  And if the pull request is between two branches in the same repository, there is often a second build for the commit made to the other branch.

The easiest way to tell which builds are pull requests and which aren't is to look at the symbols next to the numbers.
Commit: 
![screenshot from 2016-03-14 08 58 44](https://cloud.githubusercontent.com/assets/5492015/13750565/4fa401c6-e9c3-11e5-8015-c92bb60823b0.png)
Pull Request: 
![screenshot from 2016-03-14 08 59 34](https://cloud.githubusercontent.com/assets/5492015/13750570/56398eb6-e9c3-11e5-9bdd-0416b85aff3b.png)

The pull request number is also displayed next to the SHA for the pull request builds:
![screenshot from 2016-03-14 09 00 19](https://cloud.githubusercontent.com/assets/5492015/13750609/6feffb92-e9c3-11e5-826a-292a93ab4024.png)

There won't usually be multiple pull request builds unless there are multiple pull requests or the pull request is updated, but it's not unusual to see a build for the commit and a build for the pull request, and then another build for the new commit when it is merged.

**Comment by hunt3ri** [comment]
Thanks @a-murphy really helpful, please consider this ticket closed :+1:
