### ISSUE TITLE
SSH-agent error

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#2375]
1) new conf - via custom image - https://app.shippable.com/runs/56e57c6a7e1e620b005c00b7
2) old conf - your image https://app.shippable.com/runs/56e575c7a1af5d0c00cc691a

last success build https://app.shippable.com/builds/56e34cc0faa2a30c00981470 - same as 2nd

**Comment by manishas** [comment]
@rageshkrishna can you look into this?

**Comment by rageshkrishna** [comment]
@luckyraul With the new build system, you no longer need to invoke `ssh-agent` or `ssh-add` -- your build commands are already running within an ssh-agent session that contains your subscription keys already loaded.

The reason your build is failing is because ssh-add is unable to find any keys in ~/.ssh. We no longer store any keys there. They are placed at /tmp/ssh and we inject them in to ssh-agent at the start of the build. You can verify this by doing `ssh-add -l` to list all the loaded keys.

Please remove the `ssh-agent` and `ssh-add` lines from your YML. Your build should work fine after this.

**Comment by luckyraul** [comment]
thanks

**Comment by bittner** [comment]
If you need to **find out the public keys** available for deployment see [issue #2431](https://github.com/Shippable/support/issues/2431#issuecomment-219215719).

This used to be conveniently available from the builds UI (project page) in the beginnings of Shippable.

**Comment by avinci** [comment]
The public part of the key is available in the UI. if you go to `subscriptions` page and then go to `setting` tab, you will see this.

![screen shot 2016-05-14 at 8 10 20 pm](https://cloud.githubusercontent.com/assets/1302035/15269026/e8c9b0e0-1a0f-11e6-938d-9f8fb6db69b8.jpg)

**Comment by bittner** [comment]
@avinci Dammit! I knew this was somewhere. This is not easy to find when you mainly deal with the builds. Why isn't this in the project settings? It used to be in a box in a column to the right of the build status list more than a year ago.
