### ISSUE TITLE
Pipeline not deleted after project was deleted

### ISSUE THREAD

**Issue by jgregors** [Shippable/support#2381]
I deleted a project (micro-sample) but its pipeline still exists. I now want to delete the pipeline but when I try to view the "status" tab in order to stop it, I'm getting a browser console error: "GET https://api.shippable.com/passthrough/services/56e0ca9c516d220c007cb014/tasks 500 (Internal Server Error)" and the status tab hangs.

I assumed the delete would cascade. The problem is occurring in  osden-io / aws-catalogue-env / demo-app .

**Comment by jgregors** [comment]
Actually, when trying to view any project I am getting the http 500 response as above.  When I tried to go to the home view I was taken to a "Getting Started" view (attached)
![image](https://cloud.githubusercontent.com/assets/1077918/13768515/2ce19f0a-eacb-11e5-99f3-46a989a8ae2b.png) 

You can also see another error in the console in the attached image.

**Comment by manishas** [comment]
@rageshkrishna can we look into this?

**Comment by jgregors** [comment]
I've since refreshed the page and I can see all my projects again. The problem with not being able to view the status of the cell / pipeline still exists.

**Comment by stephanielingwood** [comment]
@jgregors There are a few things going on here:

When you tried to view the cell in a given environment, and got the ` "GET https://api.shippable.com/passthrough/services/56e0ca9c516d220c007cb014/tasks 500 (Internal Server Error)"` error, you indeed ran into a bug. A fix for that was pushed a few hours ago - can you refresh and see if that problem still persists?

Ditto for the "getting started" view (and 504 error) on the home page: are you still seeing this? 

It's also worth noting that projects and pipelines are not tightly coupled in our system. When a project is added as a pipeline trigger, it is only used to trigger checks for new image tags. Because a pipeline can exist without a project trigger, or have multiple triggers, we don't delete the pipeline upon project deletion.

If you have deleted a project, and you want to stop seeing it in your pipelines, you can remove it from the pipeline triggers for that pipeline. You can find that remove option in the pipeline triggers section of pipeline settings page. 

Hope this helps. Let us know if you're still seeing those errors, or if you have any other questions.

**Comment by jgregors** [comment]
@stephanielingwood all good! Thanks for your help.

**Comment by jgregors** [comment]
@stephanielingwood apologies, the project problems are fixed but I can't stop the "demo-app" pipeline and hence cannot delete the environment it is in. Getting console error: api.shippable.com/passthrough/services/56e0ca9c516d220c007cb014/tasks:1 GET https://api.shippable.com/passthrough/services/56e0ca9c516d220c007cb014/tasks 500 (Internal Server Error)

I am trying to delete this "aws-catalogue env" environment and "demo-app" pipeline completely.

**Comment by stephanielingwood** [comment]
@jgregors Aha. It looks like you deleted your cluster before stopping the pipeline - which means we have no way to issue a "stop" command to aws. We're working on a fix right now that will keep this situation from occurring in the future. In the meantime, there are a couple options:

1.) In the environment, you can re-enter your deploy integration, and re-select your cluster. Then, you will be able to stop the pipeline, delete the environment, and delete the pipeline. This will also stop and delete any services you have running in your aws cluster.
2.) We can change your status to stopped, and then you will be free to delete the environment and pipeline. This will not stop and delete any services you have running in your aws cluster - you'll need to do that on your own.

Thanks for bringing this to our attention - and sorry you had to be the one to find them. ;)

**Comment by jgregors** [comment]
@stephanielingwood please change the status to stopped - I have deleted the cluster and it was only for learning purposes anyway. Thanks!

**Comment by stephanielingwood** [comment]
@jgregors Done! You should now be able to delete your pipeline and environment. If we can help you with anything else, just let us know.

**Comment by jgregors** [comment]
It's done. Thanks. Will now close.
