### ISSUE TITLE
Less performance on new build setup

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2414]
With the old setup our builds took around one and a half our to complete. Now all builds timeout. It seems as there are less performance with the new setup. Have you changes something regarding this? Thanks.

**Comment by manishas** [comment]
@jeppefrandsen we are looking into your builds and trying to figure out why they are timing out. 

One problem has been addressed - timeouts for paid plans should be 120 mins but this was set to 90 mins. We have changed this back to 120 mins.I am hoping that this will stop your builds from timing out.

Second - the new build platform no longer runs multiple build containers on a single machine. We have switched to a new model of running one container per machine since this avoids a lot of other issues caused due to noisy neighbors which were making build times unpredictable. With the new platform, your build will always get exactly 2 cores and 3.75GB build containers.
This has an impact of very resource intensive builds since on the old platform, the larger machines allowed for build containers getting more than 2 cores, but this is no longer possible on the new one due to each build being isolated in its own machine.

If you want bigger containers, you have the option of using your own infrastructure to run builds. With this approach, you can attach larger build machines to your subscription and your builds will be routed to those machines. This is explained more here - http://docs.shippable.com/ci_byoh/

**Comment by manishas** [comment]
Also, do we have your permission to trigger a couple of builds for your project to help debug?

**Comment by jeppefrandsen** [comment]
@manishas yes, sure. Just go ahead.

**Comment by rageshkrishna** [comment]
@jeppefrandsen I'm looking in to this issue now. I'll have some updates for you a little later today.

**Comment by rageshkrishna** [comment]
I'm going to close this now because the performance issues have been discussed as part of the investigations on https://github.com/Shippable/support/issues/2413#issuecomment-199235646
