### ISSUE TITLE
Clojure compilation issue only happening within shippable environment

### ISSUE THREAD

**Issue by svo** [Shippable/support#2415]
Hi,

I'm using a custom build image on a new clojure [project](https://app.shippable.com/projects/56ef2a899d043da07beed777) and I am having a weird compilation issue that only seems to occur within the shippable ecosystem:
```
Exception in thread "main" java.lang.ClassNotFoundException: clojurewerkz.neocons.rest.records.Node, compiling:(linking_service/repository/neo4j/transformer.clj:1:1)
```

Using the same image locally the tests run as expected.

Any assistance as always would be greatly appreciated.

Many thanks.

**Comment by manishas** [comment]
We have investigated this but have not been able to repro this or find out what is happening with your builds. Also, it looks like your last build did not run into this specific issue (but did have some other failure). Can you share what you did to fix it?

At this point, I am closing this issue since your last build did not experience this problem. Please open a new issue if you need help and we'll take a look.

**Comment by svo** [comment]
Hi @manishas,

Thanks for getting back to me.

Unfortunately the issue persisted, it was merely hidden by an early exit in the final builds.

We have since stopped developing this specific project, but I will let you know if I encounter similar issues in the future.

Many thanks for your time.
