### ISSUE TITLE
Duration doesn't match sum of build step times

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2423]
Love that you added back durations to the build steps.  I am frequently however seeing total durations that do not add to the sum of the build steps.  

Frequently this happens when a node is provisioned but have seen other scenarios...

**Comment by avinci** [comment]
The way the system is designed is that it has two core types of objects that get created. The RUN and the JOB/s. Run duration is the total length during which it was in a non terminal state. Job length is the total duration it took the YML to process. Adding this and making them tie up is not the right thing as one is a super set of the other. Hence this is by design.

Hope this helps.

**Comment by chriskinsman** [comment]
What I am trying to reconcile is I look in my job history and see a job that took 7 minutes. That is longer than I want my builds to take so time to optimize.  Why did it take 7 minutes?

So I drill into the history and see the build_ci: step took the longest at 2m 31s.  I look at all the other steps and see they took 1-2s.   I can't figure out why the build took 7 minutes when the stuff I see run in the logs total around 3m.  There is ~4minutes I can't account for and as such can't understand if there is a way to optimize this.

This is why I was trying to make things add up.

I take away from your explanation above that the rest of the time is just "overhead" in the system that I can't affect so ultimately I shouldn't be worried about tracking the time it takes.  The things I can affect are the the things you call out with timings.

**Comment by manishas** [comment]
@chriskinsman the extra overhead also includes the time it takes to provision a node. You can control this if you move to dedicated nodes, i.e. using your own nodes which will always stay up and not need to be provisioned each time. Of course, you'll end up paying for the nodes so that's the tradeoff.

We will investigate ways of speeding up this step for Shippable nodes in the future. Our build nodes already stay up for a while after the build finishes, so if you have builds waiting in the queue they get picked up immediately without needing to provision another node.
