### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2425]
A few weeks ago, more than 10% of Shippable support issues were still open, but it's now down to 2%. Thanks for your dedication towards fixing this! This statistic makes a real difference to us.

And while I'm at it, even if the UI is still slow, the builds run much faster and that's really, really appreciated.

Thank you Shippable!

**Comment by manishas** [comment]
@pquentin thank you for the words of appreciation. It really means a lot to the entire team!

**Comment by avinci** [comment]
Thank you very much for noticing and as @manishas said, it means a lot to the team as they were relentless for the last 2 months to make this happen. 

In the middle of last December, we had a 'sit-down`internally and tried to come up with a plan to resolve this problem of ever increasing support issues. We wanted to resolve every support issue BUT the problem was that our core platform did not allow us to do this. 

There were 2 fundamental problems with our architecture
* separation of concerns between micro services
* monolithic images

The only way to solve this was to completely re-write the entire platform and we embarked on this journey on Jan 4th. Thanks to the team, we got everything re-written and launched on Feb 29th and the sheer amount of work that got done by our team is mind boggling. Most importantly we tried to `not` break existing functionality as much as possible. I think we achieved this barring a few exceptions. Of course we are working on making UI faster too :-)

Now our philosophy `support first` can be true, and we are committed to keep it this way. We will do our best to address every single issue as soon as possible. 

Thank you once again. With your help, I hope we can make this the best platform for CI/CD
