### ISSUE TITLE
Increased build times and timeouts after conversion to new .yml format

### ISSUE THREAD

**Issue by mnexo** [Shippable/support#2430]
Hello,

Since switching to the new Shippable format (or possibly due to the changes performed by Shippable on 3/18), we've been observing significantly slower build times and many timeouts due to the build not starting at all. We don't believe any changes in our code base could have caused this.

Project ID: 560837cd1895ca4474186b2a

_This is a sample of builds just before the switch 3/18. Build no. 782 is where we successfully switched to the new shippable.yml format._

![screen shot 2016-03-23 at 13 55 30](https://cloud.githubusercontent.com/assets/727788/13985962/046054be-f100-11e5-82e9-40947c025f71.png)

_This is how it looks after 3/18_

![screen shot 2016-03-23 at 13 52 52](https://cloud.githubusercontent.com/assets/727788/13985970/110131a2-f100-11e5-910c-14fd1735b6ab.png)

**Comment by manishas** [comment]
@mnexo one of your team members already reported this and here is the issue and discussion - https://github.com/Shippable/support/issues/2413

To summarize, our new build platform runs one build per machine. Each machine is 2 cores, 3.75GB. This is a change from the old platform which ran multiple builds per machine in a multi-tenant fashion and so the machines were much bigger and each build container could get more resources if needed. 
Since your builds are limited wrt resources on the new platform, it's taking longer for each build. 

One possible solution discussed with @jeppefrandsen was to use dedicated hosts - i.e. attach your build machines to your subscription. This gives you the ability to attach larger machines and this should solve your issue. While debugging we tried with a 4 core, 8GB machine and a build took 38 mins. So you should try going this route and this should address all issues you're running into.

Let me know if you need more information or want to do a hangout and discuss more. Thanks!

**Comment by manishas** [comment]
@mnexo Let me know if you have any more questions or want to discuss further. 

Closing this since there is nothing actionable for us to do here.
