### ISSUE TITLE
[gcloud] Install kubectl with gcloud sdk

### ISSUE THREAD

**Issue by mikaelh** [Shippable/support#2442]
It wouuld be great if kubectl would also be installed with the default gcloud sdk packages.

**Comment by manishas** [comment]
@mikaelh you can install anything you need in your CI container using shippable.yml and then use caching to avoid re-installing each time. At this time, our supported use cases include pushing an image to GCR, which is why we included the gcloud sdk package in official images. 

We will consider adding kubectl in the future if there are multiple requests around this.

**Comment by javiercr** [comment]
Hi,

I also need to install kubectl, I've tried adding this to my `shippable.yml`:
```
build:
  ci:
    - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
    - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
    - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install google-cloud-sdk
    - sudo gcloud components install kubectl
```

But the last command fails with this message:

```
You cannot perform this action because this Cloud SDK installation is 
managed by an external package manager.  If you would like to get the 
latest version, please see our main download page at:
  
https://cloud.google.com/sdk/

ERROR: (gcloud.components.install) The component manager is disabled for this installation
```

Is there a way to overwrite the existing gcloud SDK installation so that we can use `gcloud components install kubectl`?

Thanks!

**Comment by huysamen** [comment]
+1 getting the same error

**Comment by a-murphy** [comment]
One option is to install `kubectl` directly instead of through `gcloud`, as documented here:
http://kubernetes.io/docs/user-guide/prereqs/
Then a shippable.yml section like this will install `kubectl`:
```YML
  - curl -L  https://github.com/kubernetes/kubernetes/releases/download/v<Kubernetes version./kubernetes.tar.gz > kubernetes.tar.gz
  - tar -xf kubernetes.tar.gz
  - cp kubernetes/platforms/linux/amd64/kubectl /usr/local/bin/kubectl
  - chmod +x /usr/local/bin/kubectl
  - kubectl --version
```

Caching the binary would probably be a good idea because it takes a few minutes to download.  Documentation about that is [here](http://docs.shippable.com/ci_configure/#caching).

Otherwise, it looks like the error is a result of installing `gcloud` with `apt-get` and you could try [another installation method](https://cloud.google.com/sdk/downloads#versioned) to install `gcloud`.  If you need to remove the existing `gcloud`, `apt-get remove google-cloud-sdk` will remove it because it was installed with apt-get.
