### ISSUE TITLE
Build stuck in node provisioning phase

### ISSUE THREAD

**Issue by simock85** [Shippable/support#2455]
We're having build timeouts for all builds in `kuldat` account, subscription-id `555eec00edd7f2c052f86e01`, since April 25. The builds are stuck in node provisioning phase and nothing happens until the build timeout is triggered.
<img width="993" alt="screen shot 2016-03-30 at 10 21 42" src="https://cloud.githubusercontent.com/assets/785899/14136092/53c16c44-f661-11e5-84a0-ff82c05f64a7.png">

**Comment by kanthchandra** [comment]
- @simock85 This is happening because of CPU saturation. A few minutes in to the build maybe because of the nosetests that are consuming a lot of resources, CPU load hits the saturation limit and the machine completely locks up.

Recommendation:  You may need to use custom hosts for your subscription which will have higher resources. We use AWS (c3.large, 2 cores, 3.75gb) machines for all the builds. 

I also think that this is what is causing the issues with jobs getting stuck at "provisioning node". The system believes the node should be free after the job times out, but the node is so overwhelmed by the CPU load that the runner is unable to terminate the build and pick up any new jobs.

**Comment by kanthchandra** [comment]
@simock85 Here are the links for setting up your custom hosts.
- [Overview of running builds on your own machines](http://docs.shippable.com/ci_byoh/)
- [Instructions showing how to attach build nodes to your subscription](http://docs.shippable.com/ci_subscriptions/#adding-your-own-build-infrastructure-byoh)

**Comment by erykwarren** [comment]
Since this morning, all our builds have been timing out after a few hours, and it is still happening. Here's a link to the latest one:
https://app.shippable.com/runs/56fbf77f1368e80c00c437b7
Please advise.

**Comment by trriplejay** [comment]
@erykwarren looks like it was related to our outage this morning.  Your builds should be running now.

**Comment by mhzajac** [comment]
[This build](https://app.shippable.com/runs/56fc9bd547bb010c00a198f2) has been continually timing out for the past 8-12 hours. It gets stuck at the "Provisioning job node" phase, and might make it a few steps further than that, but it never actually reaches running tests or even compiling code.

**Comment by trriplejay** [comment]
@mhzajac we've been having some issues with AWS provisioning today.  It should be back to normal now.  Please let us know if you continue to experience this and we can take a closer look.
