### ISSUE TITLE
Having a git sync issue on some branches and not others.

### ISSUE THREAD

**Issue by twillms07** [Shippable/support#2462]
Hey, I'm having an issue with git sync. There are some branches which do no have this issue whereas others do. 

Failed build on git_sync looks like this 
```
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone git@github.com:PiiQ-Personas/personas-server.git //src/github.com/PiiQ-Personas/personas-server'
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '//src/github.com/PiiQ-Personas/personas-server'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Why would this happen for one branch and not another? Also how do I fix it?

**Comment by manishas** [comment]
@twillms07 your subscription was recently moved to the new build platform. This problem happens if you're using an image from the shippable images repo or your own custom image that doesn't have the $HOME env variable defined.

Please check out our FAQ http://docs.shippable.com/ci_faq/#my-builds-are-failing-at-git_sync-with-error-host-key-verification-failed-why which explains how to fix this issue. 

You will need to migrate to the new yml format and use the default image (drydock/u14sca:prod in your case) and your builds should work as expected. Migration guide is [here](http://blog.shippable.com/migrating-to-the-new-build-platform) and we've also put together some tips to help with the migration [here](http://blog.shippable.com/5-tips-for-a-successful-migration).

Let me know if you need help and we can dig in deeper.

**Comment by twillms07** [comment]
I attempted to update my `shippable.yml` file which now included 

```
build:
  pre_ci_boot:
    image_name: drydock/u14sca
    image_tag: prod
    options: "-e HOME=/root"

  integrations:
    hub:
      - integrationName: DockerHub
        type: docker
```

In addition I added the `ENV HOME /root` to my `Dockerfile` just in case but I'm still experiencing the git_sync error. Am I missing something?

**Comment by manishas** [comment]
@twillms07 can you try the following - Go to your Project's Settings tab and Reset your project. This will reset the webhook and deploy keys. Trigger a new build and you should not hit the issue again.

**Comment by twillms07** [comment]
Fixed

**Comment by manishas** [comment]
Thanks for confirming! Closing this issue.
