### ISSUE TITLE
GKE Kubernetes deployment fails to create service

### ISSUE THREAD

**Issue by adhuysamen** [Shippable/support#2467]
Everything in our pipeline seems to be working perfectly, up until the point where Shippable deploys our Docker image (from GCE) into Kubernetes (GKE).  The deployment happens successfully, and the pod can be seen running, but no service is created.

We have set up the routing in the configuration, and specified that it should be accessible externally, however no service is created and therefore the application is not accessible externally.

We are running a new Kubernetes 1.2 cluster in GKE.

**Comment by trriplejay** [comment]
One common problem is that by default, k8s restricts the nodePort on a service to be in the range of 30000-32767, so you'll want to make sure that the 'hostPort' you choose for your routing is in that range (unless you've manually configured your cluster to accept a wider range).

we're working on making some improvements to this flow, but in the meantime, here is a workaround:

1. uncheck the box in your routing section (this will delete your routing settings)
2. from the configuration tab, deploy your pipeline
3. after the pipeline successfully deploys, go back to routing, check the box, and set up your routing again (make sure to specify a hostPort within the range I mentioned above)
4. deploy your pipeline again.  Typically this deploy should take up to 2 minutes as we wait for gke to provision the load balancer so that we can update our state with the IP that is assigned to it.

Let me know if you still have trouble after following these steps.

**Comment by adhuysamen** [comment]
Yeah perfect, seems it was the port range issue.  Thanks!

**Comment by manishas** [comment]
@abhijitkini we should add this as an FAQ for pipelines.

**Comment by abhijitkini** [comment]
Tracked here: https://github.com/Shippable/docsv2/issues/254

**Comment by abhijitkini** [comment]
Documentation updated at http://docs.shippable.com/pipelines_faq/#why-is-my-application-not-accessible-externally-even-though-my-pipeline-is-working-perfectly
