### ISSUE TITLE
Coverage includes skipped files

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2499]
The coverage status of Shippable currently includes files which have been marked to be ignored from code coverage. E.g. in PHPUnit via `@codeCoverageIgnore`. This distorts the coverage percentage and distracts from parts which really have no coverage.

Is it possible to have Shippable exclude these from the coverage status/display/listing?

Here's an [example build](https://app.shippable.com/runs/57060bdac72afc0c00bef2f0) which currently reports a coverage of ~71% which doesn't match what PHPUnit reports:

```
$ bin/phpunit --coverage-text
PHPUnit 5.2.12 by Sebastian Bergmann and contributors.

...............................................................  63 / 123 ( 51%)
............................................................    123 / 123 (100%)

Time: 18.89 seconds, Memory: 40.50Mb

OK (123 tests, 229 assertions)


Code Coverage Report:
  2016-04-07 09:37:29

 Summary:
  Classes: 100.00% (40/40)
  Methods: 100.00% (67/67)
  Lines:   100.00% (501/501)
```

As noted above, this report is not about the numbers but discovering code which is not covered. ;-)

**Comment by ric03uec** [comment]
@mbrodala you're right, the ignored files should be excluded from distorting the coverage numbers. we'll look into this

**Comment by harryi3t** [comment]
@mbrodala I tried reproducing this. I am using the project [sample_php][1]

 - started with 100% coverage
 - First I removed some test cases so that the coverage would go down (went 75%).
   - See the [commit_url][4] and the [build_url][2]
 - Then I added `@codeCoverageIgnore` to the test file. The coverage went up again to 100%
    - See the [commit_url][5] and the [build_url][3]

Seems to be working as expected.
Can you help me with this. What am I missing here?

[1]:https://github.com/harryi3t/sample_php
[2]:https://beta.shippable.com/runs/57129da19a09d91200b191bc
[3]:https://beta.shippable.com/runs/57129e7dd004cf12006ef9ad
[4]:https://github.com/harryi3t/sample_php/commit/c0089e8445e17f045ba0ccacb3262e7be5986e7d
[5]:https://github.com/harryi3t/sample_php/commit/bf92582c3159d626ec15eba84eefbc210ef7840a

**Comment by mbrodala** [comment]
@harryi3t have a look at the example build I posted. One difference I see is that you excluded only a few methods from coverage instead of a whole class. Can you try that too?

**Comment by harryi3t** [comment]
@mbrodala You were right, we are not correctly parsing if the whole class is being ignored. 
Will start on the fix now and keep you updated about the progress.
Thanks for the help.

**Comment by domitian** [comment]
@ric03uec 
On further investigation, reference [build_url](https://app.shippable.com/runs/571a0028808bdd0d00d5352f) and [branch_url](https://github.com/domitian/sample_php/tree/generate_bug_with_full_coverage) of a demo project, it revealed this

1. Total coverage is average of percentages of sequence coverages of individual files, and since our parser is including the file which is supposed to be ignored with zero percent coverage, the total coverage is distorted. 

The approach I am taking is to fix this is to ignore the file from parser and also not show in the UI and our average of all file coverages will be same as PHPUnit report.

Opening the issue in our repo.

**Comment by ric03uec** [comment]
@domitian the approach looks good to me, lets push these out one at a time

**Comment by domitian** [comment]
@mbrodala 
The coverage status of Shippable doesn't include files which have been marked to be ignored from code coverage from now.
We had verified it on our end, can you also please verify the same if files which are marked for ignore are ignored from coverage or not.

**Comment by mbrodala** [comment]
[Looks great](https://app.shippable.com/runs/5721bda975be0e0b0019d96f), thanks a lot!
