### ISSUE TITLE
Unable to use a customer docker image based on `drydock/u14ruball:prod`

### ISSUE THREAD

**Issue by DaHoopster** [Shippable/support#2573]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure: https://app.shippable.com/runs/5721ab970ccf0b0c008c1c48
- Scripts called from the yml (optional)

So I have a couple of questions and a problem. 

- **Question 1** My image is based on one of the official shippable images, I'd like to start `postgresql`, `redis` and `ElasticSearch` as services every time the build runs. What's the best way to achieve this?

- **Question 2** In the `boot_container` step, it takes about 30 minutes to start a container from my custom image hosted at Docker Hub. How can I speed up this part of the build?

- **The Problem** In the Dockerfile for my custom image, I have added path for binary of `rvm` and `bundle` with `RUN /bin/bash -l -c "export PATH=$HOME/bin:$PATH:$HOME/usr/local/bin:/usr/local/bin:/usr/local/rvm/bin:/usr/local/rvm/gems/ruby-2.2.3/bin"` This works if I just start a local container with the same image. But as you can see from the build failure link, `bundle` is not found. How can I fix this?

**Comment by rageshkrishna** [comment]
Hi @DaHoopster. 

> Question 1 My image is based on one of the official shippable images, I'd like to start postgresql, redis and ElasticSearch as services every time the build runs. What's the best way to achieve this?

We typically do something similar to the following in the official images to start services:

````
## Postgres
export SHIPPABLE_POSTGRES_BINARY="/usr/lib/postgresql/$SHIPPABLE_POSTGRES_VERSION/bin/postgres";
sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c config_file=/etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf &

## ElasticSearch
/usr/share/elasticsearch/bin/elasticsearch --cluster.name=$SHIPPABLE_ES_CLUSTER_NAME &

## Redis
/usr/bin/redis-server &
````

We also use `nc` to wait until we're sure the service is listening on the configured ports before allowing the build to continue. You may want to do the same thing or add a `sleep` to allow everything to get up and running.

Admittedly, this is a simplified explanation. You can take a look at the `run` section of the "Script" tab on the run's page to see _exactly_ what we do.

> In the boot_container step, it takes about 30 minutes to start a container from my custom image hosted at Docker Hub. How can I speed up this part of the build?

I think that time is spent in downloading and extracting the docker image. Because the build host is transient, that time will need to be spent every time you get a new host to build on. Currently, the only way I can think of to make this faster is to you use a custom host. Your custom host will be permanent so you'll have the advantage of having the image already available for all builds.


> But as you can see from the build failure link, bundle is not found. How can I fix this?

At the moment, I'm not sure why it's not getting picked up when we run a build, but the quickest way I can think of to fix this would be to add a PATH env to your shippable.yml file.

**Comment by DaHoopster** [comment]
Thanks @rageshkrishna.

Do you know the path that bundler stores all the ruby gems in the official image? I am trying to cache that directory in order to speed up the build in another project.

**Comment by chetantarale** [comment]
@DaHoopster In our official images all gems are stored under `/usr/local/rvm/gems/(ruby-version)/gems`. So if you are using say `ruby-2.2.1` then all the gems will be stored in `/usr/local/rvm/gems/ruby-2.2.1/gems/` directory.

**Comment by abhijitkini** [comment]
Closing the issue. Please let us know if you have further questions.
