### ISSUE TITLE
How to best troubleshoot

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2580]
Hi, I have a situation where my unit test hangs ONLY on the build machine. It has something to do with the mocked mongo library we are using. However, this will not happen outside the build machine. I have tried pulling the docker image used in the build locally and running all the steps that happen in the build, and no matter how many times I try it will not fail locally like it does when run on docker. 

I'm not saying that this is a problem with Shippable, what I am doing is pleading for some tips on how to troubleshoot this. I have been putting in console log statements, committing to and pushing to GitHub and then checking these in the build logs, but this is VERY slow process (and the nature of the bug makes it behave differently with the console logs messages). 

I have tried putting some statements in my YML to commit and publish an snapshot of the build machine on failure, but the on_failure does not execute when I cancel the build, and I can't wait two hours (timeout) each time I make a change to explore the image.  Is there some way to ssh into an instance of a build container to see what's going on with it? Do you have any other tips that would speed up the troubleshooting process?

Thank you in advance.

**Comment by a-murphy** [comment]
SSH isn't an option.  If you want a shorter timeout, that can be configured in the project settings.  However, you won't be able to push the image after it times out anyway because the on_failure step will not be executed.  Your best chance of pushing the image would be to modify your script to time out that command, but not the whole build.  One of these methods might work for you: http://stackoverflow.com/questions/687948/timeout-a-command-in-bash-without-unnecessary-delay

Some other projects that got stuck running tests and timed out were found to require resources greater than the build host could provide.  Our build hosts have 2 cores and 3.75GB RAM and run one build at a time.  Information on the space available is in the "Job node info" section of the build logs.  If you think that this is a possibility for your project, you may want to try running the image locally with constraints (https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources).

**Comment by npahucki** [comment]
Thanks for the info. Is there a place that I can copy files where they will be available via the download button, like the logs are?

**Comment by a-murphy** [comment]
Artifact storage is not available right now.  Our current recommendation is upload them to your own S3 bucket: http://docs.shippable.com/ci_configure/#build-artifacts

**Comment by npahucki** [comment]
ok, SO the build hangs, and it's only after the hanging that the files would be available. Is there some section of the YML that can be used to run something AFTER the timeout?

**Comment by a-murphy** [comment]
Nothing in the YML will run after timeout.  Avoiding the timeout by stopping the command that will time out is probably your only choice.

**Comment by a-murphy** [comment]
We have one more suggestion for you: to add a dedicated host temporarily that's the same size as ours.  Then you would be able to SSH into that build host and access the container.  Our build hosts are running on AWS.  Dedicated hosts can be added from the subscription settings tab.

**Comment by manishas** [comment]
Instructions for adding a dedicated host are here - http://docs.shippable.com/ci_subscriptions/#adding-your-own-build-infrastructure-byoh

Our standard hosts are 2 core, 3.76GB (equivalent would be c4.large on EC2).

**Comment by abhijitkini** [comment]
Closing the issue as resolved. Do let us know if you have further questions.
