### ISSUE TITLE
Shippable build not pulling the latest code on a renamed git repo.

### ISSUE THREAD

**Issue by nmarshall-cst** [Shippable/support#2586]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
After renaming a BitBucket repository tied to an active Shippable project the builds are triggered, but are not pulling the latest code from a branch that had successful builds previous to the repo rename (branch: master). New branches are building as expected in the same Shippable project (i.e. branch: develop). Since this is a relatively new git repository I thought I would delete the Shippable project and recreate. When trying to delete the project I receive the following error: 

(Id: 2000) No access or object not found for id: 5710ff1a2a8192902e1c2250
warn: common|validateProjs|callerId:57113dbf53b5d30c00105f1d|_checkProjectPermissions

- Link to the build failure -- https://app.shippable.com/runs/5727bcf699e6210c0088df88

Thank you for your help on this! 
Nate

**Comment by a-murphy** [comment]
The build linked appears to have been triggered by clicking a "Rebuild" button.  These builds pull the same commit as the build being rebuilt (except for rebuilding pull request builds; those rebuild the pull request number).  A "Build" button will build the latest commit, as should a webhook from Bitbucket.  Let us know if it was in fact the previous build that was the wrong commit or if it wasn't a "Rebuild" button.

The error while trying to delete the project is most likely because the account attempting to delete it does not have admin permissions on Bitbucket.  Only project owners can delete.

**Comment by nmarshall-cst** [comment]
Thanks @a-murphy. After further research we found that the latest commit did indeed kick off a shippable build. The build failed which in turn the docker image was not created. We were pulling from "latest" in our docker registry which was the actually the previous successful build/docker image. Thanks for the quick response on this!
