### ISSUE TITLE
Pulling from private git repo

### ISSUE THREAD

**Issue by clounie** [Shippable/support#2646]
### Description of your issue:
I'm trying to pull a private Github repo as part of my build. 

1. I created a Github deploy key, and tested it locally, with the exact command that the git_sync step uses (`ssh-agent bash -c 'ssh-add...`), so I know the key works.

Try 1: I first tried to use an encrypted environmental variable, encodingthe key into base64 before encryption and then decoding in the shippable.yml. However, I'm unsure if the variable is even being set. I tried [encrypting](http://docs.shippable.com/ci_projects/#encrypting-your-environment-variables) both with and without quotes around the variable's value, since the docs have quotes but the UI doesn't. 
 * (Is there a field in the project settings that lets you know the variable at least got set? Wercker has this...it's at least nice to see/know what variables ARE set even if you can't/shouldn't see their values again.)

Try 2: Add SSH integration. I added the deploy key as an SSH integration, but don't see it getting added to an ssh-agent, don't see it in the `/tmp/ssh` with the normal one, and it didn't allow me to clone the repository it belongs to.

What am I doing wrong? I feel like I'm playing battleship and have nailed every spot where the ships aren't! Haha.

Try 1: https://app.shippable.com/runs/5744d4115575ee0d007d5c2f
Try 2: https://app.shippable.com/runs/5744db935575ee0d007ee320

**Comment by a-murphy** [comment]
For the SSH integration, it doesn't look like you've added the key integration to the `integrations` section in your shippable.yml.  The SSH key integration should look like this in shippable.yml (as well as be added in the project settings):
```
integrations:
   key:
      - integrationName: MySSHKeyIntegration
        type: ssh-key
```

For the encrypted environment variable, it doesn't appear to be in your shippable.yml either.  We don't store the encrypted environment variables, just the keys that can decrypt them.  The encrypted variables should also be in the shippable.yml file (after `secure:` in `env` so that we know to decrypt them.  See [this documentation](http://docs.shippable.com/ci_projects/#encrypting-your-environment-variables).

**Comment by clounie** [comment]
Yep, I couldn't find anything in the [ssh integration docs](http://docs.shippable.com/int_keys/) or build docs telling me what the `type` or category of the integration was. Would be really helpful to have a central list of those somewhere.

Anyway, got that to work, thanks!

---

Still would like to know about encrypted vars since we'll almost certainly be using them in the future.

As far as the encrypted env var, I put this into the UI:
VAR_NAME=<base64value>

Then pressed Copy, and pasted the `  - secure: <encrypted_key>` value into my yaml but took out the dash, so it looks like:
```
env:
  secure: <key>
```

I should be able to reference the variable as `$VAR_NAME` in any of the build sections, correct? Or at least `pre_ci`?

Also, should I put quotes or no quotes for the encrypted env vars? Or does it not matter? The docs which both of us linked to say one thing, but the example in the UI console says another. (Pic: http://i67.tinypic.com/28cprgn.png )

**Comment by a-murphy** [comment]
The dash before "secure" is because it's part of ``env`` (and ``env`` is an array).  So keep the dash.  Then it should be available in the different build sections, including `pre_ci`.  

Quotes don't matter in most cases.  If there are spaces in the value, then you should use quotes.  If it's just a string without any spaces, then you don't need to.  It's usually best to match what you would use in Bash.

**Comment by clounie** [comment]
Thanks! Both ways are working now. 

I don't feel familiar enough with YAML to do a proper job on a PR for the docs here [environmental variables](http://docs.shippable.com/ci_configure/#secure-variables), but it looks like the example(s) could use an update.

**Comment by abhijitkini** [comment]
@clounie Thanks again for updating the documentation. Closing this issue as resolved.
