### ISSUE TITLE
Trying to pull in mysql, EnvironmentError: mysql_config not found

### ISSUE THREAD

**Issue by griffinkelly** [Shippable/support#2648]
### Description of your issue:
Build fails reading EnvironmentError: mysql_config not found
NOTE: If you are experiencing a build failure, please include:

https://app.shippable.com/runs/5745d93074e4d00d00ccc04a
in requirements/test.txt the following is run:
`coverage==4.0b2
django-nose==1.4.1
nose-exclude==0.4.1
funcsigs==0.4
mock==1.3.0
mock-django==0.6.9
nose==1.3.7
pbr==1.6.0
MySQL-python==1.2.5`

**Comment by a-murphy** [comment]
This looks related: http://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found

Could you try installing the packages suggested there with `apt-get install` commands before your `pip install` command?

**Comment by griffinkelly** [comment]
This leads to the following issue when actually trying to create the testdb. I run the following command:
`mysql -e 'create database testdb;'`

and am returned the following error: 
/root/e473a680-21ff-4199-a9a4-0825c1327a10.sh: line 58: mysql: command not found

**Comment by a-murphy** [comment]
The default python image doesn't have `mysql` since most builds using MySQL will add "mysql" in the [`services` section of shippable.yml](http://docs.shippable.com/ci_configure/#services) to automatically start a database in the build container (and we use a different default image for those that has MySQL).  Since you appear to be starting your own database, you may want to just [specify `drydock/u14pytpls:prod` for your build image](http://docs.shippable.com/ci_configure/#setting-your-build-image).  The `drydock/u14pytpls` image has `mysql` available.

**Comment by manishas** [comment]
@griffinkelly you'll need to include the following in your yml:

```
build:
  pre_ci_boot:
    image_name: drydock/u14pytpls
    image_tag: prod
    pull: true
    options: "-e HOME=/root"

```
