### ISSUE TITLE
Build Stuck in "Processing"

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2651]
One of my repositories is stuck in "Processing". I've tried canceling and rebuilding, cleanup shippable script back to a successful state. Nothing seems to get it out of this "Processing" mode. 

Too builds currently stuck: 
https://app.shippable.com/runs/5746910977e6a50c0039777f
https://app.shippable.com/runs/574693667594ed0f0094e695

Not sure if this has to do with it, but I've enabled the subscription earlier today and looks like the node is not responsive.. 
https://app.shippable.com/clusterNodes/57469369e1b6860d007b4dd3

**Comment by deanmraz** [comment]
Looks like it might be up and running now. We can close this ticket but just curious what caused the delay?

**Comment by manishas** [comment]
@deanmraz we had a brief interruption and your build was triggered during that time. Sorry about this and we've fixed the issue that caused the nodes to be temporarily stuck.

**Comment by deanmraz** [comment]
@manishas thanks.

**Comment by deanmraz** [comment]
@manishas looks like I keep running into issues with this. I think its due to the node shutting off or sleeping... Anyway to improve this experience? I would like the builds to happen in minutes.

**Comment by manishas** [comment]
@deanmraz we spin up machines on demand when a build is triggered for your projects. This can take up to 3 mins. After the build finishes, we keep the machine up for some time, so if a subsequent build comes in while the machine is still up, it runs very fast since a new machine doesn't have to be spun up.

There is one way to improve this - if you attach your own build nodes to your subscription. If you choose to do this, builds for your projects will always be routed to your nodes. Since they are always up and running, you'll save the spin up time for every build. You also have the ability to attach bigger nodes if your builds need more memory or CPU.

More on this is explained here - http://docs.shippable.com/ci_byoh/ and instructions for adding your nodes are here - http://docs.shippable.com/ci_subscriptions/#adding-your-own-build-infrastructure-byoh

Let me know if you have any questions or want to see a demo. I'm happy to jump on a hangout and discuss.

**Comment by deanmraz** [comment]
@manishas got it makes sense. I'll definitely explore the byoh, Thanks!
