### ISSUE TITLE
shippable can't access to repository bitbucket

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#2660]
even if key is allowed
this project
https://app.shippable.com/projects/5559ac67edd7f2c052f1d952

**Comment by manishas** [comment]
@luckyraul can you reset your project by going to Settings and clicking on the `Reset` button? You will need to scroll down all the way since the Reset action is just above the delete project action. Also, if you're using any encrypted variables for this project, you'll need to reencrypt since this recreates the webhook and keys.

Let me know if this doesn't work.
