### ISSUE TITLE
build chain in the cloud

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2662]
from stack overflow (http://stackoverflow.com/questions/37521272/build-chain-in-the-cloud) asked by @magwas :

I have some open source projects depending in each other. The code resides in github, the builds happen in shippable, using docker images which in turn are built on docker hub. I have set up an artifact repo and a debian repository where shippable builds put the packages, and docker builds use them. The build chain looks like this in terms of deliverables:

pre-zenta docker image
zenta docker image (two steps of docker build because it would time out otherwise)
zenta debian package
zenta-tools docker image
zenta-tools debian package
xslt docker image
adadocs artifacts
Currently I am triggering the builds by pushing to github and sometimes rerunning failed builds on shippable after the docker build ran.

I am looking for solutions for the following problems:

Where to put Dockerfiles? Now they are in the repo of the package needing the resulting docker image for build. This way all information to build the package are in one place, but sometimes I have to trigger an extra build to have the package actually built.
How to trigger build automatically?
..., in a way supporting git-flow? For example if I change the code in zenta develop branch, I want to make sure that zenta-tools will build and test with the development version of it, before merging with master.
Are there a tool with which I can overview the health of the whole build chain?

**Comment by magwas** [comment]
This will be long, and contains numerous shippable related feature requests and questions. I mark them with numbers in parentheses
This is what I am trying now:
- build docker images both from develop and master branches, using the software from the respective branch
- in the CI run the build and tests on both images. Is there a syntax supporting it in shippable.yml? I know that with drone.io you can use the matrix variables in the image name.

(1)Do you support something similar, like

   build_image: magwas/zenta-tools:$branch
   env:
       - branch=master
       - branch=develop

I want to keep build time as short as possible, so I would like to skip the docker build if the Dockerfile AND the image it is based on did not change, AND the dependencies did not build since the last succesful docker build in the same branch.

I guess for that I would need to (2) declare dependencies in shippable.yml, and (3)have a command or environment variable to figure out whether they have built since the last succesful docker build.
(4)I would also need a way to figure out whether a file has changed since the last succesful build.
With this approach I should be able to (5) paralellize the image build, and push a dockr image from each run. (6) a way to figure out whether a docker image is updated since the last build is a nice-to-have, since a)  in a complex build chain we are aiming at, most probably the build images have some packages on top of a vanilla image, so one can build it in a dependency project, and b) if we use vanilla images as base, they won't change too often.

I would also like to be able to trigger the dependent builds. There is a way to do it AFAIK, but once we have declared dependencies in shippable.yml (7) it would be nice if the dependent runs would be triggered by a succesful build. The question is: which branch? There are three branches which could be important: master, develop, and same (if exists). Maybe (8) when declaring dependencies, we should also be able to declare which branches the build should be triggered on.

After all of this, (9) a view to see the status of a build chain would be a nice-to-have. The current overview is mostly enough.

**Comment by manishas** [comment]
@magwas we are currently in the process of building some enhancements that will address your scenario. I will reach out to you in a couple of weeks and we can show you a demo of how your scenario can be possible with Shippable.

**Comment by avinci** [comment]
this has been implemented in the form of pipelines for a while now. Here is the documentation link for this. http://docs.shippable.com/pipelines/overview/

The whole idea here is to create workflows based on different cases and scenarios one could chain multiple CI jobs, deploy and various other things into a continuous streamlined workflow.

**Comment by avinci** [comment]
please let me know if you have any further questions.
