### ISSUE TITLE
status for project is outdated

### ISSUE THREAD

**Issue by magwas** [Shippable/support#2669]
The status overview of my project show only an old failed build of master, while the history clearly shows that the latest build is green on both master and develop branches.

the page
https://app.shippable.com/projects/5721d9eb2a8192902e1e3ae0
shows build 34 only. Clicking on history show builds up to build 37,
where 37 is green on master and 36 is green on develop.

**Comment by a-murphy** [comment]
By default, the project status summary will show the latest commit builds.  37 is a pull request build, so that's why it wasn't shown.  If you would like it to display pull request builds, you can set this on the project settings tab in the "Dashboard Settings" panel.

The missing develop branch is most likely because your project hasn't been synchronized since the branch was created.  This can also be done on the project settings tab, in the "Synchronize" panel.  Just click the green "sync" button.

**Comment by abhijitkini** [comment]
Closing the issue. Let us know if you need further help.
