### ISSUE TITLE
"Get latest run for a branch" API call returns more than one run per branch

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2672]
Hello,

calling "/projects/559e7fddedd7f2c05264626c/branchRunStatus" for subscription 547c792bd46935d5fbbf0b11 returns 2 runs for the project for "develop" branch:

- One successful build : 408
- One failed build : 331

Is it expected? In the absence of documentation it is hard to tell, but from "Get latest run for a branch" I would expect to get the latest run for each project branch.

**Comment by a-murphy** [comment]
331 failed in such a way that it doesn't actually know which branch it should have built.  So, as far as `/projects/:id/branchRunStatus` is concerned, it's not the same branch.  The error that caused this was not expected, but it's an older build and I believe we have addressed that error since then.

**Comment by pmezard** [comment]
Oh right, I missed that because my client falls back to parsing the commit id when the branch is not defined, which sometimes default to the remote name. I will handle that too, thanks.
