### ISSUE TITLE
Project visibility/permissions and sync

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2679]
When a user from a GH project connects to Shippable for the first time using their GH account, is it normal for that user to not be able to access their projects without first having to sync the account?

I've had reports from two different users who were unable to access our account on Shippable with the full privileges they should have had until after syncing the account. The first was unable to use the rebuild button on PRs, the other couldn't see our builds listed on the Shippable site (but could see the project was enabled).

**Comment by manishas** [comment]
@mattclay The short answer is no. However, there are specific situations where the user will have to sync their account. If a user was added as a collaborator or their permissions changed recently, it might take up to 4 hours for the permissions to be reflected on Shippable unless the account is synced.

Please let us know if this happens again and we'll follow up on the specific scenario and see if we need to address something at our end.

**Comment by mattclay** [comment]
@manishas When you say "added as a collaborator" does that count an existing collaborator on a project who logs into Shippable for the first time? I just had another collaborator whose permissions haven't changed log into Shippable for the first time. They had to manually sync their account to see the rebuild button in the UI.

I would have thought the first time a user logs into Shippable their permissions would automatically sync. I can understand the delay though if they had been previously synced and their permissions had since changed.

**Comment by mattclay** [comment]
bcoca

**Comment by manishas** [comment]
The first time anyone signs in, we do sync permissions so we'll need to look into this. If you share the collaborator's username they used to sign in, we can see if there were errors etc during sync.

**Comment by manishas** [comment]
Ok thanks!

**Comment by mattclay** [comment]
Was there ever any resolution to this? We've had another user (nitzmahone) encounter the same problem.

**Comment by trriplejay** [comment]
We haven't been able to find any specific errors pertaining to this user's permissions sync, and we have been unable to reproduce this problem.  Maybe you can help us out with some additional info:

1. had this user logged into Shippable before being a collaborator on the project?
2. After logging in, did the user navigate to the project page via UI dropdown or via direct project link? If the user could see the project in their dropdown, it implies permissions were synced.  If the user clicked a direct link (given to them by another collaborator perhaps), then since the project is public, they might have seen the page without the build button if their account had not yet finished syncing.
3. How long between login and visiting the project page? sync can occasionally take a minute or two, which can seem like a long time for a user who has just logged in.
4. Did the user ever try a hard refresh of the page or just internal page navigation?
5. About how long was it between first login and forcing sync via account settings page?

**Comment by nitzmahone** [comment]
1. No- I've been a collaborator for almost a year, and logged into Shippable for the first time yesterday.
2. I navigated to a specific build via a GitHub PR status (then asked Matt to enable me for Shippable access so I could restart that build)
3. When clicking back to the project page from the build, I'd get ```(Id: 2000) No access or object not found for :subscriptionId 573f79ce2a8192902e20e349
warn: runs|chkPermSubscriptionId|callerId:573fa8b52a8192902e20e999|subscriptionId:573f79ce2a8192902e20e349|_getSubscriptionPermsBySubscriptionId``` with a Sync button underneath it.
4. I moved back and forth several times between GitHub and Shippable via the PR build status, but don't recall ever actually hitting refresh.
5. Probably less than 5 min.

Hope that's useful!

**Comment by trriplejay** [comment]
@nitzmahone 

When you say you've been a collaborator for almost a year, do you mean that you were actually added to the team in github? or just that you worked on the project as a public user? when you say that you asked Matt to enable you for Shippable, did he actually need to do something? (add you to a specific internal team for that particular project or something?)

The error you saw seems to imply that your account did not yet have permissions on the subscription.  It could be because our sync process had not finished yet. 5 minutes is a long time, but it's hard to say the exact conditions at the time.... we'll continue to try and track it down.

**Comment by nitzmahone** [comment]
I've been part of the Ansible GitHub org for over a year. At the time I didn't realize how it worked, so I asked Matt to enable me and he sent me the project URL (but turns out he didn't actually *do* anything, which I didn't know at the time).

**Comment by nitzmahone** [comment]
Would it make any difference that I initially came at it from a build status page?

**Comment by trriplejay** [comment]
:D I was afraid you'd say that.

OK, so you came at it from build status page, you got a login prompt, you clicked github, logged in, then the page continued on to the build status page, at which point you couldn't see the rebuild button? does that sound about right?

**Comment by nitzmahone** [comment]
Yep, pretty much. There was a "Sync" button underneath the error message, which is what I eventually ended up clicking on to get things working, but no explanation of what that was or why I should click it- just the error message and the button.

**Comment by avinci** [comment]
I am not sure if there is any other action on our part. Its been open for a while and we have improved our sync process quite a bit to make it more robust. Please reopen if the issue still persists.
