### ISSUE TITLE
Caching of docker images

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#2684]
This is a technical question, as a new customer setting up an account.

I'm interested to know if there's anything I can do specifically to increase the chance of docker images that I pull from Docker Hub being cached. I've noticed that for many builds, images that I've used previously are already found and reused, but in other cases the build machine needs to pull from docker hub again. The difference in build times in these two cases is quite dramatic.

So my question is: Is there anything about the order of my shippable.yml that I can change to improve this? e.g. pulling all images as part of pre_ci_boot or pre_ci, instead of implicitly pulling them as part of `docker run`, etc?

**Comment by rageshkrishna** [comment]
@rarkins The nodes that run your builds are spun up on demand. We keep them running for a while after your builds terminate and any new builds in this interval will be picked up by the same node. Because previous builds would have pulled the image on this box, your builds benefit from the local cache.

There's nothing you can do in your YML file to optimize this.

You can, however, use custom hosts to make this better. That way, your builds can all run on the same box(es). You should take a look at http://docs.shippable.com/ci_byoh/ for more details on how this works.

**Comment by rarkins** [comment]
@rageshkrishna I'm afraid that running my own nodes (BYOH) for the same price takes the service from good value to poor value, so it's not an option.

This wouldn't be so bad if it weren't for horribly slow pull times from Docker Hub. I will raise that as a separate issue though.
