### ISSUE TITLE
Proper way to make deployment key available in Docker build

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#2688]
My `shippable.yml` performs `docker build, tag, push...` to ECR.

What is the proper way to include *npm* dependencies from private repositories (e.g. Bitbucket)?

From the documentation, I understand the build container has a deployment key that I can add to Bitbucket, but how do I make the private key available within the container being built where `npm install` is run in the context of the production environment? 

Is there a better alternative? I'd like to avoid incurring additional cost and complexity of NPM private modules, GemFury, etc.

**Comment by trriplejay** [comment]
well, your deploy key can be found at `/tmp/ssh/01_deploy` during the CI execution.  

are you saying you want the key to be added to your image, or are you saying you want the docker build to be able to use the key to install a private module for the image, without the key itself becoming part of the image?

If the former, you can just `ADD` the key in your Dockerfile.  If the latter, one possibility would be this:
- run npm install before running docker build, so that private key can be used to pull the dependencies
- in Dockerfile, add the existing node_modules directory that was the result of the previous step. This way the key stays on the build machine, but your image contains the private module source.

Is that helpful? I found some other resources online that had some other options, but it sounds like Docker doesn't officially have a way to accomplish this during a build yet.

**Comment by pwarnock** [comment]
@trriplejay **Thanks!** 

My only concern with the latter approach is installing _native_ modules. I might try a variation of your approach by using `npm pack`, passing the tarball of dependencies to the Docker build context, and installing that instead of _package.json_.

**Comment by abhijitkini** [comment]
@pwarnock Let us know if you need further help on this topic. Closing the issue.
