### ISSUE TITLE
Can't run builds on some branches

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2699]
I'm trying to run a build on branch deploy/beta. I've tried through the shippable UI as well as calling the API. 
```
POST 'https://api.shippable.com/projects/575a15582a8192902e232717/newBuild?branch=deploy/beta
```
This is the run log https://app.shippable.com/runs/575cb688e15b480c00cba94d

This is the error log
```
common|bitbucket|normalizeBranchSha|callerId:5480a3bd0f168213009d2ecc|projectId:575a15582a8192902e232717|_getCommit Empty repository
```

Looks like shippable can't find the branch "deploy/beta"... Is this because of the "/" in the name?

**Comment by manishas** [comment]
@deanmraz you're right, this is because of the / in the branch name. The Bitbucket API doesn't support this as of now.. we opened a bug with them over a year ago and they haven't addressed it - https://bitbucket.org/site/master/issues/9969/get-commit-revision-api-does-not-accept

http://docs.shippable.com/ci_faq/#i-cannot-start-a-manual-build-for-my-bitbucket-project-why-is-it-not-working

**Comment by manishas** [comment]
I am going to close this issue since it isn't a Shippable bug, but it would be great if you chime in on the Bitbucket bug above and add a +1 :)
