### ISSUE TITLE
Is it possible to set directory for deployment when using elastic beanstalk (eb_paas)?

### ISSUE THREAD

**Issue by designreact** [Shippable/support#2704]
I'd like to deploy the contents of shippable/buildoutput to my elastic beanstalk application rather than everything checked out from the git repo. Is there a way to do this? I've been searching around for a while.

> integrations:
>   deploy:
>     - integrationName: "name-AWS"
>       type: "aws"
>       target: "eb_paas"
>       platform: "Node.js"
>       application_name: "appName"
>       env_name: "envName"
>       region: "eu-west-1"

**Comment by trriplejay** [comment]
Unfortunately we don't currently support that scenario.  I'll mark it as a feature request.

**Comment by designreact** [comment]
Ah - I thought that might be the case. It would be nice to have.

In the meantime I'll sort out a docker image. Thanks

**Comment by LoganArnett** [comment]
I assume that this was never integrated? I have a nodejs application that utilizes ES6 and needs the babel-cli in order to build for deployment. All of our projects are built this way to take advantage of the newest features for code reuse. It would be very useful to be able to dictate which directory should be deployed

**Comment by manishas** [comment]
The recommended approach to deploy to Elastic Beanstalk is with the [runSh job](http://docs.shippabl.com/platform/job/runsh). Closing this as deferred.
