### ISSUE TITLE
Waiting for node more than 2 hours

### ISSUE THREAD

**Issue by ibratoev** [Shippable/support#2707]
### Description of your issue:
A build is waiting for node more than 2 hours and counting. See: https://app.shippable.com/runs/57611c4f5a31ce0d00f99546

**Comment by kanthchandra** [comment]
Hi @ibratoev , in order to debug this issue can I know if you changed the machine image or something very recently in the subscription settings?

**Comment by ibratoev** [comment]
Hi @kanthchandra, I have not changed anything.

**Comment by ibratoev** [comment]
It seems now it is OK - a new build started running properly. Let me know if I can help with something to investigate the issue.

**Comment by ibratoev** [comment]
OK, still not everything works as expected. See https://app.shippable.com/runs/57611c4f5a31ce0d00f99546 for a strange error...

**Comment by designreact** [comment]
I've been having a similar issue waiting for ruby gems to install on the node image... not sure if that's related or not... 25 minutes and counting https://app.shippable.com/runs/57614e026a58d80d00cab6df normally done within 10

**Comment by ibratoev** [comment]
It seems fixed now.

**Comment by designreact** [comment]
@kanthchandra I'm now up to 1 hour - would you like me to raise a new issue?

**Comment by kanthchandra** [comment]
Hi @designreact, I don't think your issue is related to node not being provisioned. Your build number 52 is running and I see that there is node that is actively running your build. You can see these details in the subscription settings page.

**Comment by kanthchandra** [comment]
@ibratoev I need some time to investigate what went wrong. At this point I don't have any information as to why a node was not provisioned for your sub for the first time. 

1. One way to see if there is a service disruption or not is by looking if node is shown in the subscription settings page as soon as the build goes to processing state. 
2.  One more thing to note is that our build system is designed in such a way that in case for some reason a node was not provisioned for a build, you trigger a second build for the same sub a new node will get provisioned and it will start running any earlier queued build. So that's why when you triggered another build it started to work again (if that makes sense). 
3. I think yours was a one off case and we will definitely investigate what went wrong so that it will help improve the product.

**Comment by kanthchandra** [comment]
Hi @ibratoev we have opened an internal issue to track this down. We will get back to you when we have more info on this one.

**Comment by ibratoev** [comment]
Thanks @kanthchandra .
I remember that I check 1. and it was OK. I tried canceling and starting a new build once.

**Comment by bobbydeveaux** [comment]
This is happening to me a lot today @kanthchandra .

https://app.shippable.com/runs/5762c7c382cd0b0c00f7968d

**Comment by kanthchandra** [comment]
Hi @bobbydeveaux , thanks to your comment we were able to identify the problem. We had exceeded the EBS volume storage as we were running at peak capacity. As a result the nodes were not coming up and failing silently. We have requested for an increase and this should be resolved as soon as our request is processed by AWS.

**Comment by manishas** [comment]
AWS team has increased EBS volume storage, so this should no longer be a problem. I am closing this issue, but please let us know if you see this again and we will reopen.

**Comment by bobbydeveaux** [comment]
Thanks guys
