### ISSUE TITLE
Build started notification in Slack when on_start set to never

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2744]
Build https://app.shippable.com/runs/576cd0e723e2800e00121a55 sent a started notification to our configured Slack channel. However, we have on_start set to never.

This wasn't a problem for the previous builds for which Slack was enabled, which only reported.

Why was a started notification sent for the build when it's configured not to?

**Comment by manishas** [comment]
@rageshkrishna can we look at this?

**Comment by rageshkrishna** [comment]
Hi @mattclay. I've investigated this and here's what I've found:

1. The branch that build is running on does not have any configuration for slack in the YML file
1. When there are no slack settings in the YML and we see a Slack integration configured on the project, we fallback to "legacy mode" where we send Slack notifications for all events.

I believe we're ready to retire this legacy mode now, so this will be fixed in the next few days.

If you need an immediate fix, updating the YML files in all the branches will silence it right away.

**Comment by ankul-shippable** [comment]
@mattclay The change is live, now you shouldn't see any `on_start` notifications if you haven't configured it in your yml.

**Comment by manishas** [comment]
Closing since this is complete. Let us know if you run into any issues.
