### ISSUE TITLE
How to push build back to git repo

### ISSUE THREAD

**Issue by ivanoats** [Shippable/support#2750]
I am trying to push my built files back to the origin repo, but I get an error:

```
conq: repository access denied. access via a deployment key is read-only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have an SSH key on bitbucket that has full access set up via a Shippable integration, but it doesn't seem to be using that.

https://app.shippable.com/runs/576ea993d7b8e20c00776049

**Comment by a-murphy** [comment]
In what way did you set up the key on Bitbucket?  Is it the public key from the subscription settings page or your own key?  It looks like it's trying to use the deployment key for the project, which means that it either didn't find your key or the subscription key doesn't have permission.

If it's your own key, the documentation on [key integrations](http://docs.shippable.com/int_keys/) is available here.  If it's from the subscription settings, then it should work if you gave the key write access to the repository.  Would you mind letting us know which key it is (your own, subscription, or projectand where you added it (Bitbucket project or account) so that we can try to reproduce the error?

**Comment by ivanoats** [comment]
It's a key integration. I tried adding it to shippable.yml but I still get the same error. They key has permissions on the repo.

**Comment by a-murphy** [comment]
It looks like it really wants to use the deploy key in that case for some reason, and unfortunately the deploy key is valid with read access so it stops there.  I've found one way to tell ssh-agent to use your key instead though.  Adding `- echo -e "Host bitbucket.org \n\tIdentityFile /tmp/ssh/MyKeyIntegrationName \n\tIdentitiesOnly yes" > ~/.ssh/config ` to your shippable.yml before the `git push` (substituting your integration name for "MyKeyIntegrationName") will get it to use the right key by adding Bitbucket to the SSH config with the SSH key from the integration specified.

And, you're pushing to a repository that will trigger another build.  So you might want to add [[skip ci]](http://docs.shippable.com/ci_configure/#skipping-a-build) to your commit message to avoid building in a loop.

**Comment by ivanoats** [comment]
That looks like a good solution, but I'm still getting an error: `no such identity: /tmp/ssh/my-actual-integration-name: No such file or directory`

**Comment by a-murphy** [comment]
It's probably the dashes.  I forgot to mention to leave out any characters that aren't letters or numbers in the integration name when specifying the SSH key file.

**Comment by ivanoats** [comment]
That was it, thank you! Looking good!
