### ISSUE TITLE
Is it possible to have unit tests in multiple languages?

### ISSUE THREAD

**Issue by gappleto97** [Shippable/support#2753]
I have a [package](https://github.com/gappleto97/p2p-project) which groups together a javascript implementation and a python implementation. Is it possible to have unit tests on your platform in both of these languages, or do I need to have them in separate repositories for this to work?

**Comment by stephanielingwood** [comment]
Hi @gappleto97,

Yes, you can have both your JavaScript and Python unit tests in the same repo, and run in the same build on Shippable.

The easiest way to do this would be to specify node_js as your language, since python already comes installed on our node images by default. Your yml would then look like this:

```
language: node_js

# specify node version(s)
node_js:
  - "0.12"

build:
  ci:
    # check the python version; it will be 2.7 by default
    - python --version
    # check the node version; it will be whatever you specified under node_js, above
    - node --version
    - npm install
    - pip install -r requirements.txt
    # now run your tests
```
That should cover a lot of scenarios. 

If you want a more tailor-made set-up, you can always create a custom image, install what you want in that image, and then use that for your build. Feel free to use our [drydock images](https://github.com/dry-dock) as a starting place; these are our build images. For more info on how to use custom images with a build, check out our [docs](http://docs.shippable.com/ci_configure/#pulling-your-ci-image-from-a-docker-registry).

**Comment by abhijitkini** [comment]
@gappleto97 let us know if you need further help with this issue.
