### ISSUE TITLE
build fails but no output in console after "bash --version"

### ISSUE THREAD

**Issue by FelixSchwarz** [Shippable/support#2762]
Tests for a project of mine always fail but there is no output in console after "bash --version" so I'm not sure what is wrong there.

Project URL: https://app.shippable.com/projects/57743d953be4f4faa56b4308
Build URL: https://app.shippable.com/runs/57743db3d7b8e20c004d8ffd

After clearing the cache or resetting the project I see a lot of error messages from shippable like:

    (Id: 2000) No access or object not found for id: 57727f193be4f4faa56b116f
    warn: common|validateProjs|callerId:564c61348bfbdb0d00819146|_checkProjectPermissions

Also in BitBucket the "Shippable_Webhooks request logs" for this project are empty.

I guess I'm just tired and missing something obvious but I can't figure it out...

**Comment by a-murphy** [comment]
We've been able to reproduce the sudden build failure; it's the function name in double quotes in your commit message.  We'll fix that.

For the empty webhook request logs, have there been any commits to the repository since it was last enabled or reset?  If the project's been reset, the webhook will have been replaced.

**Comment by a-murphy** [comment]
We've fixed the error with the double quotes in the commit message.  If you re-run your build, it should run.  Let us know if you have any more problems, or if builds aren't being created for commits.

**Comment by FelixSchwarz** [comment]
Thank you very much for the fast bug fix. It is working fine now .-)
