### ISSUE TITLE
Shippable Yml merge for PR failed

### ISSUE THREAD

**Issue by ramasamymohan** [Shippable/support#2768]
I'm getting the following error,

<img width="977" alt="screen shot 2016-07-01 at 1 49 43 pm" src="https://cloud.githubusercontent.com/assets/7361904/16531599/e2caa980-3f92-11e6-8147-853d1b234cc7.png">

Note: I have added a setting on shippable to build only on PR.

What could be the reason?

Please let me know if you need any further information.

Thank you.

**Comment by a-murphy** [comment]
It looks like you've updated your shippable.yml file in the pull request and we couldn't merge it.  In order to get the shippable.yml for a pull request, we start with the YML from the base branch and apply the changes in the pull request.  A likely cause of this error would be if there are changes to shippable.yml in the base branch that are not in the pull request branch.

**Comment by manishas** [comment]
@ramasamymohan let us know if you need further help with this.
