### ISSUE TITLE
Slack integration fails since last Scheduled Maintenance

### ISSUE THREAD

**Issue by txuslee** [Shippable/support#2771]
I have been using for a while a Slack integration for a project (https://app.shippable.com/projects/56fc39939d043da07b0960ba) and receiving notifications successfully until last Jul 1, Scheduled Maintenance.
Even though we have not updated webhooks or changed any configuration, we are not receiving any notification.

**Comment by kanthchandra** [comment]
@txuslee can you please paste the yml of the project here so that I can debug this further?

At a highlevel it looks like you haven't configured the notifications in your YML and we have moved away from our fallback of sending slack notifications for all events since the last update. More information on how to configure notification through your yml can be found here http://docs.shippable.com/ci_configure/#slack-notifications and here is a blog post explaining that http://blog.shippable.com/notifying-ci-failure/success-status-on-email-slack

**Comment by mbrodala** [comment]
@kanthchandra Can you add a public notice for this, for example on your blog? I'd expect this to affect the majority of subscribers.

**Comment by txuslee** [comment]
Thanks, I wasn't aware of the change!

Once I configured our YML to link with slack notifications it got back on the next build.

**Comment by abhijitkini** [comment]
[Docs updated](http://docs.shippable.com/ci_troubleshoot/#slack-notifications-do-not-occur-after-the-july-1st-service-maintenance) to reflect the change in behavior. @mbrodala Thanks for the suggestion.

**Comment by mbrodala** [comment]
@abhijitkini Thanks a lot. Can you add `on_success: always`? I noticed this was missing yesterday. With this the previous behavior is fully restored.

**Comment by abhijitkini** [comment]
@mbrodala Thanks. I have updated [the docs](http://docs.shippable.com/ci_troubleshoot/#slack-notifications-do-not-occur-after-the-july-1st-service-maintenance) to include `on_success: always`.
