### ISSUE TITLE
ssh-agent failed

### ISSUE THREAD

**Issue by jcgcecilia** [Shippable/support#2777]
Hi
Building without cache yields a succesful build. Building with cache yields a failed build.
The error log looks as follows
....
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/dd5d33ab-7e7c-4c06-afe9-9089e904305e.sh'
Exception Script failure tag received 
.....

https://app.shippable.com/runs/577b5fe4a7ce310c0039e4e6

Br 
JC

**Comment by rageshkrishna** [comment]
Hi @jcgcecilia. The message `Exception Script failure tag received` usually means something in the build returned with a non-zero exit code. Unfortunately, I'm unable to figure out exactly what could be causing that because you are using a custom script to run all the steps in your build.

Would you mind sharing your `shippable.sh` script with me so I can debug this further? You can email me at ragesh@shippable.com if you'd rather not share it here. Thanks!

**Comment by rageshkrishna** [comment]
@jcgcecilia I'm going to close this issue now because we've resolved it over email.
