### ISSUE TITLE
Slack integration no longer posting any notifications

### ISSUE THREAD

**Issue by asans** [Shippable/support#2782]
### Description of your issue:

On July 1st, 2016, Slack notifications are no longer working for us.  Nothing was changed on our end.  The last successful slack build notifications was on 10:42am PST on July 1st.  Later that afternoon, another build was initiated but no notifications were received on the slack side.  

Since the build jobs, projects, etc all didn't change, the only thing I can think of is that something was updated on your Shippable side that caused slack notification to no longer be sent. 

Did something change to cause this?

To give you an example, a build that went through not too long ago didn't post any slack notifications:

Build ID: 577d2e97ea8eb30c00154f6c

Btw, you guys should really consider not using github for support requests as it is entirely public and sometimes it's difficult that we can't include certain private information that may be helpful for dealing with the issue.

Thanks,
Alex

**Comment by abhijitkini** [comment]
@asans Until the service maintenance on July 1, users who configured Slack notifications through UI only, had notifications triggered for all events. Since the service maintenance, the notifications are now being triggered for the default configuration. 

To reinitiate the Slack notification, use the following code in your `shippable.yml` file:
```
integrations:
  notifications:
    - integrationName: foobar-slack
      type: slack
      recipients:
        - "#shippable"
      on_start: always
```
The `integrationName` is the Slack Integration name you have configured in your Project's Notification Integration settings.

You can also read more about this change in [our documentation](http://docs.shippable.com/ci_troubleshoot/#slack-notifications-do-not-occur-after-the-july-1st-service-maintenance). 

Regarding using GitHub for support requests, we are evaluating options. For private information required in troubleshooting, we ask it to be emailed to the engineer working the issue. 

Let me know if this resolved your Slack notification issue.
