### ISSUE TITLE
Can't enable repository from BitBucket with a TeamID as Owner

### ISSUE THREAD

**Issue by Funkygeek** [Shippable/support#2792]
Hi, I'm trying to create my first project using BitBucket.  I have tried to 'Enable' a repo from BitBucket but I get the error 

> (Id: 2002) Owner not found for projectId::5780337f3be4f4faa56c4634
> warn: caller:578033766519cb0c0057cd20|projects|enableById:5780337f3be4f4faa56c4634|_getValidOwner

The repo's owner is the Team.

I'm not sure if this is a bug, or a limitation.

TIA

**Comment by a-murphy** [comment]
In this case, "owner" means Bitbucket's "admin" permissions.  An account with admin permissions on the repository is needed in order to create the webhook that will trigger builds for commits to the repository.  Based on the error, it looks like you don't have admin permissions.  Could you ask someone who does to enable the project?

**Comment by Funkygeek** [comment]
Thanks.
