### ISSUE TITLE
Failed test marked build as "UNSTABLE" but still ran on_success

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#2805]
https://app.shippable.com/runs/5786576b9ca7ed0c0020228e/1/console

This build failed a test, but still ran our on_success scripts. It’s been marked UNSTABLE which is a new status to me - is this is a recent change?

Previously it would fail if even 1 test failed - is there a configuration option to retain this behaviour?

Thanks

**Comment by a-murphy** [comment]
Unstable isn't a new status; it means that your script's exit code was 0, but a test failed.  Whether failed tests result in a failed or unstable build depends on what is running the tests within the build.

Since `on_success` is before the test reports are parsed, we don't yet know that a test has failed.  The script has reported a success.
