### ISSUE TITLE
Unable to download build failure logs

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#2816]
Unable to download build failure logs. Get the following when attempting to download the logs:

    {
      "logType":"error"
      ,"methodName":"jobConsoles|getSByJobIdDownload|callerId:55d549ca6ed0590b008bba40|jobId:5788b99fe4d6a30c00e4f9ac|_getSByJobIdDownload"
      ,"id":666
      ,"message":"JobConsolesModel.find for jobId: 5788b99fe4d6a30c00e4f9ac"
      ,"link":{"name":"MongoError","$err":"Runner error: Overflow sort stage buffered data usage of 33554594 bytes exceeds internal limit of 33554432 bytes","code":17144}
    }

The build ID is embedded in the message.

**Comment by manishas** [comment]
@manish-in-java unfortunately the size of logs for your job exceed our maximum limit of 10mb. This is a limitation due to our backend database.  

We are revisiting console logs in the next 2-3 weeks and also moving to Postgres which should address this issue. 

I am going to close this issue since there is nothing actionable for us to do at this point.
