### ISSUE TITLE
Invalid RUN language: php

### ISSUE THREAD

**Issue by rorteg** [Shippable/support#2825]
### Description of your issue:
My shippable.ym:

`
language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - mkdir -p shippable/codecoverage
  - mkdir -p shippable/testresults

script:
 - phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage

notifications:
  email: false
`

- https://app.shippable.com/runs/57900640e377970c001b9129/1/console
- 
<img width="1360" alt="captura de tela 2016-07-20 as 20 16 25" src="https://cloud.githubusercontent.com/assets/142829/17006436/3b29bc32-4eb7-11e6-8e6d-421f87df2ce7.png">

**Comment by a-murphy** [comment]
You've enabled your project under "Infra" instead of "CI".  PHP is a valid language for CI projects, but not for Infra projects, which are used for Terraform deployments.  Please delete your project on the project settings tab, go back to the subscription page, and enable the project from the CI tab.

**Comment by rorteg** [comment]
Thanks!

**Comment by abhijitkini** [comment]
@rorteg Closing the issue. Let us know if you need further help.
