### ISSUE TITLE
False positive deploy status on ECS

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#2852]
Creating a new cell revision and trying to deploy that to ECS reports success and send off notifications of success, while it is actually failing because:

Today at 1:29 PM
(service Test) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance 9424d11e-59cc-4868-b175-b6d45dd07ced) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.

The only port busy is 80 from previous cell version. I would expect it would get along.
For now i need to go to ECS console, stop old running task version, the i can do a deployment from Shippable UI.

**Comment by trriplejay** [comment]
yeah, basically the way ECS deployments work, is that it tries to eliminate down time by bringing up the new copy of your task and making sure it is stable before removing the old one.  If you only have one container instance, then it can't bring up the new one at all due to port conflict, so eventually it posts that error event.

One way to get around this is to go to the shippable pipeline status page, change the "scale" number to 0 and press the 'scale' button.  This will stop your running container on ecs, then you can deploy the new version and scale it back up to 1.

The other solution is to provision a second node so that ECS has a place where it can start your new service without encountering that port conflict.

We're planning some pipeline upgrades within the next few weeks that should allow you to get around this more easily.

**Comment by KarolAdamiec** [comment]
Ok. Makes sense. Wish i knew that before. Maybe some caution bubble on ecs integration? :)

Still reporting successful deployment while in fact it failed is not ok in my opinion.
I do not expect it to always WORK, but after a success message i expect it to BE there.

Thanks for help!

**Comment by trriplejay** [comment]
yeah, I agree it's a bit misleading. Basically the 'success' is saying that we successfully created a new task definition on ECS and updated your service with it, but the ECS service takes over after that and it may or may not work, depending on your configuration.  We're working on some enhancements that will actually monitor the deployment and let you know if there's a problem.

**Comment by manishas** [comment]
closing this. @KarolAdamiec as mentioned, we're making some changes to pipelines that will address the core issue.
