### ISSUE TITLE
`go get` fails with private repositories

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#2858]
### Description of your issue:

`go get` is failing because some of the packages needed are from a private repo. It's returning me an error of `invalid username or password` which is odd because it should be ok right since I gave shippable access to the my private repos?

- Link to the build failure
    https://app.shippable.com/runs/57a5edf35aa7620d009046ea/1/console
- Scripts called from the yml (optional)

**Comment by stephanielingwood** [comment]
Thanks for your question. To clarify how we handle private repos: when you enable a private repo as a project on Shippable, we set up a deploy key to connect to that private repo on GitHub. Because of this, builds don't have access to any of your other private repos unless you specifically grant access (which is a good thing). 

To grant access, you'll need to add the deploy key from your subscription on Shippable to the project containing your packages on GitHub. To find your deploy key on Shippable, go to your subscription, then to the "settings" tab. Copy that key, and add it to your GitHub project, under settings/deploy keys. That gives the subscription access to the repo with the packages, and will allow them to be used during the build.

**Comment by magicalbanana** [comment]
Actually no, the one that worked was when I added a `.netrc` file with my github username and a token.

**Comment by manishas** [comment]
closing this since it is resolved. @magicalbanana we'll keep your solution in mind if anyone else runs into this. thanks!
