### ISSUE TITLE
Unable to enable project

### ISSUE THREAD

**Issue by gharish2000** [Shippable/support#2859]
### Description of your issue:
Hello, 
The documentation says " Enable project from subscriptions page on top right corner". Its actually on top left corner.

**Comment by manishas** [comment]
@gharish2000 you will need to go into one of your subscriptions in order to enable a project.

Click on the menu on the top left of your Shippable dashboard to see a list of your subscriptions. Select the subscription you want and you will be redirected to the Subscription's page. Click on Enable Project in the sidebar menu. 

Docs are at http://docs.shippable.com/ci_subscriptions/#enabling-a-project

**Comment by manishas** [comment]
closing this issue since it is answered. let us know if you have any other questions.
