### ISSUE TITLE
Can't work out how to get caching working on a nodejs build

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2861]
https://app.shippable.com/runs/57a880e06a05380c00b92148/1/console

Trying to enable caching and I can't see how to do it. Your tutorials and examples seem to use the old yml format.

I'm expecting pre_ci to only run once, and be loaded from cache next time. It seems to run every time.
PATH changes in pre_ci aren't present in ci?

What I want to do is npm install certain libraries once, and have them cached next time.

**Comment by a-murphy** [comment]
The up-to-date caching documentation is available [here](http://docs.shippable.com/ci_configure/#caching).  Caching will save the contents of directories and restore them in later builds, not change the scripts that you run.  However, `npm` will usually find any cached modules and the installation won't have to download them again.  So `npm install` will still be there, but will be faster.

Changes made in `pre_ci` will not typically be present in `ci` because those steps run in different containers and clone the repository separately.  The `pre_ci` step is intended for building images or other actions that must be done before the build container is started.  In your case, it looks like everything in the `pre_ci` step could be moved into the `ci` step, which would make caching easier.

**Comment by BryanCrotaz** [comment]
So why do I get

  restore_cache 0s
  echo 'cache file not found, ignoring cache' 0s  
cache file not found, ignoring cache

in my builds?
https://app.shippable.com/runs/57a88ed66a05380c00b92754/1/console

**Comment by a-murphy** [comment]
That would be expected on the first build with cache enabled, but not for the second.  Do you have `cache: true` in the `build` section of your shippable.yml?  (At the same level as `ci` and `cache_dir_list`.)

**Comment by BryanCrotaz** [comment]
language: node_js

env:
  - CI=true COVERAGE=true

node_js:
  - "4.3"

build:
  ci:
  - node --version
  - npm config set spin false
  - npm config set progress false
  - export PATH=$PATH:node_modules/.bin
  - npm install
  - npm install ember-cli-code-coverage
  - bower --allow-root install
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - echo "module.exports = function() { return { coverageFolder:'shippable/codecoverage' }; };" > config/coverage.js
  - cat "config/coverage.js"
  - COVERAGE=true ember test ci --silent -r xunit > shippable/testresults/result.xml

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/bower_components

  on_success:

  on_failure:

**Comment by BryanCrotaz** [comment]
and I get this at the end of the build:
upload_cache 2s
  aws s3api put-object --profile shippable --bucket 576097c02a8192902e23b05a --key cache/576097c22a8192902e23b07e.tar.gz --body /home/shippable/cache/576097c22a8192902e23b07e.tar.gz

**Comment by a-murphy** [comment]
For some reason, your builds appear to think that the cache should be reset each time they run.  Could you try clicking the "Clear" button under "Clear Cache" on the project settings tab once?  That should reset it so that the second build following the reset will use the cache.  We'll have to look into why your project keeps trying to clear the cache.

**Comment by BryanCrotaz** [comment]
did that, still getting
```
echo 'Resetting cache for the build'
```

**Comment by BryanCrotaz** [comment]
ah - second build seems to have worked. thanks

**Comment by manishas** [comment]
closing since this is resolved.
