### ISSUE TITLE
How to test Shippable>DTR integration with self signed cert?

### ISSUE THREAD

**Issue by ezeeetm** [Shippable/support#2887]
### Description of your issue:
We are doing our PoC test of Shippable CI/CD functionality to our own Docker Trusted Registry.
DTR is set up using a self-signed cert, producing the error below when doing a docker push.

Is there a way to force shippable docker push to trust the self signed cert, just for testing purposes?

EDIT: it may just be quicker to grab a quick lets encrypt cert, but would still like to know if this is possible.  Thanks.

```
docker push dtr.mydomain.com/admin/cdtest:$BRANCH.$BUILD_NUMBER 1s  
The push refers to a repository [dtr.mydomain.com/admin/cdtest] (len: 1)
unable to ping registry endpoint https://dtr.mydomain.com/v0/
v2 ping attempt failed with error: Get https://dtr.mydomain.com/v2/: x509: certificate signed by unknown authority
```

- Link to the build failure
https://app.shippable.com/runs/57b9b5b34d7c050e008356a2/1/console

**Comment by rageshkrishna** [comment]
Trusting unknown certs is currently possible only if you're using a dedicated node. Because of the way the docker daemon works, trusting new certs requires a restart of the docker daemon and it isn't possible for us to do this while a build is running.

With a dedicated node, you can set up the daemon to trust your certs and make it work.

Perhaps LetsEncrypt would be more convenient, but it's not something I've tried out myself.

**Comment by ezeeetm** [comment]
Thanks, @rageshkrishna .  Will try the cert and if that doesn't work will set up a dedicated node.
If anybody esle finds this issue, you can enable your dedicated node to trust unsigned certs

https://docs.docker.com/registry/insecure/
