### ISSUE TITLE
Pipelines: Re-Use Service and Task Definition in ECS

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2920]
## Problem
* ECS services are deleted on every deploy. There are a few problems with this:
  * There is no reasonable way to do service auto-scaling as the auto-scaling configuration is deleted with the service.
  * We're forced to manage the scale of a service via Shippable's `replicas` resource. Scaling up or down requires a git commit to the pipeline. The does not allow the infra team to quickly respond to manual scaling needs and have those changes persist across deploys.
* Shippable creates a new task definition on every deploy and fails to delete the old copies.

## Proposed Solution
Use ECS as it was intended.
* Re-use the existing service and create a new task definition revision for each new deployment.
* Only modify the scale of the existing service if no `replicas` resource is input to deploy.
* Recreate the service only if immutable configuration is changed. Adding or removing a load balancer should trigger this.

So far the new pipelines are very well thought out. They bring a lot of flexibility to our deployment process and mesh nicely with the infrastructure automation we've deployed at [Zenreach](http://www.zenreach.com/). There are still minor gaps like this which cause undue stress in the deployment process. We've been exploring new CI pipelines to replace our existing service and have decided to go with Shippable. I'd be happy to discuss on a call some of the use cases we're trying to fill.

**Comment by trriplejay** [comment]
Hello,

thanks for all the comments and suggestions!

One of your points can be addressed by updating your deploy job's `deployMethod`.  By default, we enable this "blueGreen" deploy method, where we bring up a second service and make sure it is running properly before shutting down the original, but if you prefer the more ecs-native method of just posting a new task definition, you can update your deploy job to look something like this:

```yml
steps:
  - IN: mymanifest
  - IN myCluster
  - TASK: managed
    deployMethod: upgrade
```

The upgrade method will just post a new task definition to the existing service, and let Amazon ECS handle the transition.  With upgrade method, changing a loadBalancer should destroy/recreate the service, as you mentioned, due to the immutable nature of the service load balancers.

This doesn't address your replicas/auto-scaling use-cases. I'll mark that as a feature request!

**Comment by trriplejay** [comment]
If you'd like to get on a call to discuss, you can send an email to manisha@shippable.com with your availability, and we'll set something up.

**Comment by manishas** [comment]
@BlueDragonX Please let me know when you're available for a call to discuss your scenarios and how Shippable can help. I am available anytime tomorrow through Friday from 10am-5pm PST. Thanks!

**Comment by BlueDragonX** [comment]
Hey, sorry I don't have a lot of time right now due to various...things...going down over here. I'll let ya'll know!

**Comment by manishas** [comment]
@BlueDragonX ok, please send me an email when you're available. Thanks!

**Comment by Kirtap** [comment]
why was this closed? what is the solution or at leat the workaround?

**Comment by BlueDragonX** [comment]
@Kirtap the solution was to use `deployMethod: upgrade` as described above. The replicas feature request is covered by another open issue.
