### ISSUE TITLE
How to force a deployment?

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#2930]
Currently my deploy job is not always deploying (I don't increase the image version number all the time cause I'm just trying things out). In the job logging I read 
'Force deployment is: false' when it doesn't deploy anything and 'Force deployment is: true' when it does.

So just some questions:
- Is there an option to set 'Force deployment' to always true? 
- And what triggers 'Force deployment' to be true.

**Comment by trriplejay** [comment]
If you run the job manually from the UI, either by right-click->run or from the jobs page, that is considered a "force".

Normally when a deploy job is triggered, we only deploy the manifests that have some kind of change since the last time they were deployed. A force overrides this and says deploy all manifests no matter what.

Currently there is no way to set it to always force, but that sounds like a feature that would be useful for some cases, so I'll mark this as a feature request.

**Comment by jplimpens** [comment]
Let me know when ETA of this feature is clear
