### ISSUE TITLE
failing deployments when having two images

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#2946]
Old pipeline works fine if there is one image only in the manifest. When i add second image the first deploy works well, ELB sets up. All OK.

Subsequent deployments are failing with:
`Container names must be unique within a Task Definition`

Failed to register task definition for fifarafa_57c3fc7ac5fc420f00c39fa2_task. Provider response: { [ClientException: Container names must be unique within a Task Definition.] message: 'Container names must be unique within a Task Definition.', code: 'ClientException', time: Wed Sep 07 2016 11:44:42 GMT+0000 (UTC), requestId: '7735dbc5-74f0-11e6-b701-993eb70883eb', statusCode: 400, retryable: false, retryDelay: 33.88582949992269 }

Link to pipeline:
https://app.shippable.com/cellConfigs/57c3fc7ac5fc420f00c39fa2/status

**Comment by manishas** [comment]
@KarolAdamiec you should see an email from us today about the old Pipelines implementation - we are deprecating it on Sept 30.2016. You will need to migrate to the new pipelines before this date. Your issue is already fixed in the new pipelines. 

Let me know how we can help with the migration. Always happy to jump on a hangout and answer any questions.

Some useful docs links:
Continuous Delivery Pipelines - http://docs.shippable.com/pipelines/overview/
Getting started: http://docs.shippable.com/pipelines/gettingStarted/
Sample pipeline: http://docs.shippable.com/tutorials/pipelines/samplePipeline/
