### ISSUE TITLE
GitHub releases/tags not always triggering builds

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#2979]
Hi, I enabled builds triggered by releases and tags, but apparently only some tags actually trigger a build (https://app.shippable.com/projects/57dbe9e10aacef0f00355c4b/status/history), while most of them do not have any effect (https://github.com/jacopo-chevallard/test-shippable/releases)

Am I doing something wrong?

**Comment by a-murphy** [comment]
Your tag builds aren't being created because of the `branches: only` in your `shippable.yml` file.  The tag builds don't really belong to a branch, so the `branches: only` is comparing the tag to `master` and skipping the builds.  If you remove the `branches` section of your `shippable.yml`, future tags should all trigger builds.

**Comment by jacopo-chevallard** [comment]
Great, thanks for the prompt reply! Shippable is just an incredible tool! :) 

Related to this question, is there any way to trigger builds only for tags/releases and for commits to specific branches (e.g. "master")?

**Comment by a-murphy** [comment]
There isn't currently a way to differentiate between tags and branches in the `branches` section, but if your branch names happen to follow a pattern, you may be able to exclude all branches that aren't master.  Documentation about `branches: except` is [here](http://docs.shippable.com/ci/advancedOptions/branches/), which includes examples of using wildcards to exclude all branches that match a pattern.  Basically, a `*` in your branch name will match any sequence of characters.
