### ISSUE TITLE
Deploy on ECS not working with one instance in the cluster

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2980]
As I mentioned here https://github.com/Shippable/support/issues/2612 deploy on ECS through shippable was / is not working when only one instance is present in the cluster because of e.g. port conflict.
The new pipelines doesn't seem to solve this or better they make it even worse since I can't set `scale=0` for one task.
How should I configure the pipelines to be able to `stop` a task and than `start` again without having more than one instance e.g for a staging system?

**Comment by trriplejay** [comment]
we're working on a deployMethod for stopping a service before deploying the new version of it, which is what you're looking for.

In the meantime, have you heard about Amazon's recent release of [application load balancers] (https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/)? this would also be a solution to your problem.  Use an ALB and the hostPort can be generated dynamically so that there is never a conflict on the same machine.

Unfortunately, there is no easier workaround for your scenario right now. the other option is to make a commit with replica count: 0, then another commit with replica count: 1, which is obviously not ideal...

We'll notify you via this issue when the new deploy method is in place.

**Comment by cratz** [comment]
@trriplejay 
Thanks.
> In the meantime, have you heard about Amazon's recent release of application load balancers? this would also be a solution to your problem. Use an ALB and the hostPort can be generated dynamically so that there is never a conflict on the same machine.

Issue with the port is related to the exposed port of docker container (service) and I can't see a way to set this port dynamically since I have to specify the port mapping in resources. So the part for the load balancer is only interesting once the task is running which never happen currently.

> Unfortunately, there is no easier workaround for your scenario right now. the other option is to make a commit with replica count: 0, then another commit with replica count: 1, which is obviously not ideal...

How can I achieve this? Do I have to change this setting in the sync repository by changing count for replicas? (I hope not ;) )

**Comment by trriplejay** [comment]
with the ECS port mapping in the dockerOptions resource, you can say `0:80`.  The `0` indicates to ecs that your host port should be dynamically generated when a task is started, while 80 in this example is the port that your container is listening to.

This doesn't work for classic load balancer, because the load balancer already must have the correct listener in place, and if it's being generated dynamically, there is no way to know what the listener will be, but with ALB, it will automatically set up a listener on that dynamically generated port. This would even allow you to run multiple copies of your same container on the same machine, all behind the same ALB.  I recommend giving it a try; it seems like it's what you're looking for.

and unfortunately, I did mean by changing your sync repo replica count.... as I said, certainly not ideal!

**Comment by cratz** [comment]
Thanks again.

I will give the ALB a try but this will not solve all issues since we have services running without load balancer were other services have to know the port and I don't wanna pay for an not needed load balancer or a second ECS instance.

> we're working on a deployMethod for stopping a service before deploying the new version of it, which is what you're looking for.

Any idea if this will be in place before you shut down "Pipelines V1"?

**Comment by trriplejay** [comment]
yes, we plan to make this available before pipelines v1 is gone. we'll update this issue once it is released.

**Comment by Kirtap** [comment]
Do you have some kind of rough idea when this will be available? Weeks, months? I am running in the same issue on my staging environment where I really just want to run one server. 

thanks

**Comment by trriplejay** [comment]
It's on the scale of weeks, for sure. I'd estimate by the end of next week.

**Comment by cratz** [comment]
@trriplejay  by the end of the week?
So we have some hours to migrate old pipelines to new pipelines.
Sorry but this is not nice, forcing users to migrate to something (btw new pipeline are very nice) without the possibility to use it in a similar way.
I'm very happy that we don't use shippable to deploy to production env currently.

**Comment by trriplejay** [comment]
@cratz you make some good points, since we'd essentially be taking away key functionality that you rely on. After some discussion, we're going to release this enhancement sooner than originally planned. We will plan to make it available before the end of the week, so that you have a couple days to try it out and give feedback. Perhaps as soon as tomorrow, but I'll post here when it's available.

**Comment by trriplejay** [comment]
We've made this functionality available now.  You can try it by modifying the yml of your deploy job.

```yml
jobs:
  
  - name: myDeploy
    type: deploy
    steps:
      - IN: myEcsCluster
      - IN: myManifest
      - TASK: managed
        deployMethod: replace
```

with `deployMethod: replace`, shippable will actually wait for your old container to stop before trying to deploy your new one. This should allow you to avoid any port collisions that would prevent the new container from coming up.

**Comment by cratz** [comment]
@trriplejay 
Awesome work like a charm and we can finally migrate to new pipelines.
Thanks a lot for this quick fix!!!

**Comment by Kirtap** [comment]
Works great, just took it for a spin.. Thanks a lot
