### ISSUE TITLE
Error while running apt-get update Ubuntu 14.04

### ISSUE THREAD

**Issue by sendyhalim** [Shippable/support#2986]
### Description of your issue:
Hi, our shippable builds suddenly failed, it seems that there's an error while running `apt-get update` operation

```
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Fetched 3,708 kB in 16s (232 kB/s)
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-security_restricted_binary-amd64_Packages.gz is not what the server reported 20228 20231
W: Failed to fetch http://deb.opera.com/opera/dists/stable/non-free/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I know that the issue happens on the package provider side, but is there anything that we can do to ignore this error?

- Link to the build failure
https://app.shippable.com/runs/57e3529d236e510f001b74e5/1/console

**Comment by sendyhalim** [comment]
Meanwhile I'm using `sudo apt-get update || true` Based on #2983

**Comment by manishas** [comment]
Is there a reason you're pulling the u14nodpls image in your pre_ci_boot section? We fixed this issue today in u14nodall, which is the image that would be used by default by the build system if you did not have a pre_ci_boot section in your yml.

**Comment by trriplejay** [comment]
There are a couple ways around this. as manishas mentioned, the problem is fixed in the `u14nodall` image, but I notice that you're also using caching, and that will likely prevent the fix from being pulled. Until we can get our updated images deployed, here are the options:

1. turn off caching and use `u14nodall`
2. stick with the `|| true` workaround
3. remove the bad source before issuing the apt-get update: `rm /etc/apt/sources.list.d/opera.list /etc/apt/sources.list.d/opera.list.save` This will at least allow apt-get update to finish successfully.

**Comment by sendyhalim** [comment]
@manishas @trriplejay yep I'll try to use u14nodall, thanks for the response :beers:
