### ISSUE TITLE
Deploy job successful but nothing gets updated in my ECS cluster

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#2997]
I have a CI build that pushes a docker image to my ECS Repository and then triggers a CD pipeline that ultimately should update my staging cluster with the new image generated in the CI process.

I validated that the CI ran fine, pushed the generated image to my repository and that all CD jobs ran successfully.

Problem us that nothing was updated on my ECS cluster and it is still the same task running with the old image. I did look into the deploy job logs but it does not indicate much in there that points me to an issue.

I confirmed the image is fine by pulling it in and run it locally. Then I looked at the Events for the my service, nothing was deployed/restarted in there.

Any help would be appreciated. Job version is 18547 and i ran it again manually in 18574.

thanjs

**Comment by trriplejay** [comment]
by default, deploy jobs will only deploy manifests that have some detected change. Since you're using the "latest" tag on your image, we don't detect a change from your previous deployments.  Typically we like to recommend tagging your image in CI with $BRANCH.$BUILD_NUMBER so that you can easily trace the image back to the job that produced it.

However, if you want to stick with latest, the other option is to add a `force: true` option to your deploy job.  This will mean that for a particular manifest, it will always be deployed when the job is triggered, whether it changed or not.  There an example of how to do this in this support issue: https://github.com/Shippable/support/issues/2977

**Comment by Kirtap** [comment]
Thanks, that would explain why ;)

I will add $BRANCH.$BUILD_NUMBER as a tag on top of latest and take it for a spin.

**Comment by manishas** [comment]
closing.
