### ISSUE TITLE
Releases/Tags Webhook Events not Triggering Builds

### ISSUE THREAD

**Issue by ramasamymohan** [Shippable/support#3002]
I'm using GitHub. I configured shippable to trigger builds on GitHub Releases. I did enable the Tags and Releases in 'Configure Webhook Events for Triggering Builds' section. But it's not triggering the builds. Any ideas?

Thank you.

**Comment by a-murphy** [comment]
Do you have a `branches` section in your shippable.yml with `except` or `only`?  If so, the release name will be compared to the "branches" in those lists.  Depending on your branch and release naming conventions, you may be able to use wildcards with `except` and `only` to include the releases and branches you wish to build while excluding others.  Documentation on the `branches` section is available [here](http://docs.shippable.com/ci/advancedOptions/branches/).

**Comment by ramasamymohan** [comment]
Yes, I have `branches` section in shippable.yml with `only`. So the release title should be same as the branch name in the lists?

**Comment by a-murphy** [comment]
Sorry, it should be the tag name that matches a branch in `only`.  Which will most likely mean using wildcards to specify a pattern that will match your tags but not your branches so that you won't have to keep updating the branches list.

**Comment by ramasamymohan** [comment]
Got it. Works fine Thank you.

Closing this.

**Comment by ramasamymohan** [comment]
@a-murphy quick question is it possible to setup webhooks to trigger builds specific to branches. That is trigger builds for `master` branch on Release/Tags only and other branches trigger builds on PR and Commits only. Any idea?

**Comment by a-murphy** [comment]
It's not possible to identify that a tag belongs to a particular branch, just a commit.  But, you could potentially put `master` in the `except` section of `branches` so it won't be built.  The "branch" names in the `branches` section are compared to branch names for commits and pull requests and the tag names for releases and tags.

**Comment by ramasamymohan** [comment]
```
branches:
  only:
    - dev
    - inno
    - v*
  except:
    - master

```

Now the master is not building on commits and PR as I have added to `except`. But "Release" with tag name starting with 'v' to master should trigger the build right? It's not triggering the build on "Releases" to master for me. 
Is my code right?

Thank you.

**Comment by a-murphy** [comment]
It looks like it should work to me.  You don't actually need the `except` in this case because `master` won't match anything in `only`, but it shouldn't cause any problems.

Since you specifically mentioned releases to master, are you getting builds for other releases in that project?  Some projects enabled before releases were supported may not have webhooks set up on GitHub with releases.  If this is the case, the webhook (under "Settings", then "Webhooks" on GitHub) won't have the box for "Release" checked.  It should look like this:
![screenshot from 2016-09-29 08 34 11](https://cloud.githubusercontent.com/assets/5492015/18960946/3f831cc4-8620-11e6-8732-e919d52b3c5c.png)
If the "Release" box isn't checked, either checking the box and clicking "Update webhook" or clicking "Reset" in the Shippable project settings will enable release webhooks.

It may also be worth double-checking that you don't have two `branches` sections in your shippable.yml.  It's happened to other people before.
