### ISSUE TITLE
shippable_adapter:Exception POSTing to....  ...invalid continuation byte

### ISSUE THREAD

**Issue by spencerwi** [Shippable/support#3011]
### Description of your issue:

I had a build hang for >30 minutes before I killed it. After a certain point, the log is just filled with 10,000 lines of this error repeatedly:

```
ERROR:shippable_adapter - shippable_adapter:Exception POSTing to https://api.shippable.com/jobs/57ee5ea73dfd0a0f000b7e8d/postConsoles: 'utf8' codec can't decode bytes in position 4-5: invalid continuation byte: Traceback (most recent call last):
  File "shippable_adapter.py", line 54, in __post
    data=json.dumps(body),
  File "json/__init__.py", line 243, in dumps
  File "json/encoder.py", line 207, in encode
  File "json/encoder.py", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 4-5: invalid continuation byte
```

The build that failed is this: https://app.shippable.com/runs/57ee5ea78c20f5100016fa33/1/console

Our shippable.yml file looks like this:

``` yml
language: none
build:
    pre_ci:
        - docker build -t orderly-build-image:latest .
    pre_ci_boot:
        image_name: orderly-build-image
        image_tag: latest
        pull: false

    ci:
        - cd SiftOrder && mvn clean package && cd ..
        - cd RestaurantUI && npm install && bower install --allow-root && gulp ci && cd ..
        - cd SiftAdminUI  && npm install && bower install --allow-root && gulp ci && cd ..
        - cd Registration && npm install && gulp ci && cd ..

    on_success:
        - cp SiftOrder/target/SiftOrder.war .
        - cd RestaurantUI/output && zip -r ../../restaurantui.zip *
        - cd SiftAdminUI/output  && zip -r ../../adminui.zip *
        - cd Registration/output && zip -r ../../registration.zip *
```

The custom image we're using has Jdk8+maven+nodejs+gulp installed.

**Comment by spencerwi** [comment]
Any suggestions on what to do? This still happens to about 20% to 25% of builds, causing them to randomly time out.

**Comment by kanthchandra** [comment]
We have a theory as to why this is happening but we haven't been able to reproduce this at our end

Here is our theory - Our Build runner which streams the console output to your browser maintains a buffer which gets flushed at certain time intervals. So while flushing the buffer the encoded string from the stdout could be an invalid UTF-8 because it was cut in half or something like that and as a result the json parser is not able to decode it. 

I have seen this happen to a couple of other nodejs projects. So can you try running npm install and the commands whose debug output is not really helpful to you in silent mode (like set the log level to warn or something)??

**Comment by kanthchandra** [comment]
Looks like both are related https://github.com/Shippable/support/issues/2942

**Comment by rageshkrishna** [comment]
This has been fixed. You should not see this issue anymore if you're using the "Stable" image. The "Unstable" image will be updated later today after which this problem should be completely eliminated.
