### ISSUE TITLE
AWS CLI instead of EB CLI?

### ISSUE THREAD

**Issue by jamesalton** [Shippable/support#3029]
I just read through your documentation on getting AWS's Elastic Beanstalk to work. I have all my configs lined up. Then I read something on AWS's webpage telling me that the EB CLI is deprecated and I should be using the AWS CLI instead.

Do you have plans to make this switch? I've read documentation from 2016 on your website that tells me to use the EB CLI even though it appears to be a deprecated tool.

http://docs.shippable.com/integrations/deploy/eb/

http://blog.shippable.com/how-to-deploy-to-elastic-beanstalk-part-1

I guess I will carry on using EB CLI, but I'm just wondering what your future plans are.

**Comment by trriplejay** [comment]
our automated beanstalk deployment workflow during builds still uses EBCLI, however the AWSCLI is pre-installed on all of our default build images, so you would be able to utilize that if you'd prefer. You would just have to write the specific deployment commands in your shippable.yml directly.

I'm going to mark this as a feature request since you're right about the ebcli being deprecated.

**Comment by trriplejay** [comment]
actually, I take it back!

There are three tools discussed in the Amazon docs
1. AWSCLI
2. elastic beanstalk API CLI
3. EBCLI

number 2 is the one that is deprecated, and we already don't use that.

You can actually see in the deprecation message here that the EBCLI is recommended as an alternative:

![image](https://cloud.githubusercontent.com/assets/6869398/19203097/5efe7dbc-8c8a-11e6-8447-4592b5392cc1.png)

So I don't think we'll plan to switch to pure awscli.

**Comment by trriplejay** [comment]
closing. let me know if you have any questions about ebcli or how it's used on shippable!
