### ISSUE TITLE
colleague can't view job status

### ISSUE THREAD

**Issue by x110dc** [Shippable/support#3032]
### Description of your issue:
We're both part of the same ('texastribune') organization. We both log on through GitHub. Here's what she sees when she clicks on the hamburger icon:

![pasted image at 2016_10_10 05_06 pm](https://cloud.githubusercontent.com/assets/1091864/19253871/dacd4b9a-8f13-11e6-87fb-529aadc86a9d.png)

And here's what I see:

<img width="301" alt="screenshot 2016-10-10 17 04 25" src="https://cloud.githubusercontent.com/assets/1091864/19253855/c5b0d7c2-8f13-11e6-8219-7d810536ed83.png">

**Comment by a-murphy** [comment]
Does she have permissions on any of the projects in that organization?  Shippable won't show subscriptions unless that account has at least one project in the subscription.  (And read access just because it's public doesn't count.)

It may also be because access to private GitHub projects hasn't been enabled.  If the missing projects are private, going to the [account settings](http://docs.shippable.com/navigatingUI/accountSettings/accounts/) and enabling private scopes will allow those to be synchronized.

**Comment by x110dc** [comment]
Yes, she has write access to the same repo and commits to it regularly. 

Shippable has access to my public and private repos:

<img width="480" alt="screenshot 2016-10-10 18 20 07" src="https://cloud.githubusercontent.com/assets/1091864/19254124/2e81f522-8f16-11e6-9a25-59b0b48e52a5.png">

**Comment by a-murphy** [comment]
You've given Shippable access to private repositories, which is why you can see them, but her account doesn't appear to have.  Each account that uses Shippable for private GitHub repositories has to enable that so that those projects will be in the list of projects that the user has access to when synchronizing.  It sounds like asking her to enable private GitHub scopes will fix the problem.

**Comment by x110dc** [comment]
That worked! Thanks!
