### ISSUE TITLE
Custom CI image, aws_eb_deploy: "credentials are incorrect"

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3039]
We are using a custom CI image out of Amazon ECR and then deploying to Amazon Elastic Beanstalk.

When aws_eb_deploy runs, it says the following:

```
echo | eb init "our-application" -r "us-east-1" -p "" 0s  
You have not yet set up your credentials or your credentials are incorrect 
You must provide your credentials.
(aws-access-id): (aws-secret-key): ERROR: EOFError :: EOF when reading a line
```

Can you please look at our run: https://app.shippable.com/runs/57fdc255865a090e00b79b6d/1/console

I'd look through the code of aws_eb_deploy, but I'm having trouble finding where it is at. Where does aws_eb_deploy look for the credentials? We have them entered into the Shippable Integration. (At the "upper left gear" level and also applied to the individual repo.)

Thanks!

**Comment by trriplejay** [comment]
The deployment is expecting that the `aws configure` commands have been run with your integration credentials, but since you're running on a custom image that doesn't have awscli installed, the configure commands fail, causing the subsequent deploy commands to fail.  I see that you're installing awscli in your CI step, but unfortunately the `aws configure` script is run before the ci step occurs, so it will fail unless the image has the cli pre-installed.

**Comment by manishas** [comment]
closing since question is answered. @gitglacier let us know if you have any additional questions.
