### ISSUE TITLE
CI builds are not getting triggered after Bitbucket push or pull request created/updated

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#3047]
After doing a push to Bitbucket or creating/updating a pull request, a CI build is NOT getting triggered. The last time we did a commit and worked was back on Sept 29. I am able to trigger a manual build on our LAG branch. Bitbucket is showing that it successfully sent the webhook. When I try to resend, it says it fails.

Builds were not triggered from a commit last night and today (Oct 13) when I tried again.

This is blocking our development. Help please!

https://app.shippable.com/subscriptions/57059a7b2a8192902e1bb67b/ci/dashboard

**Comment by manishas** [comment]
@trriplejay can we look into this?

**Comment by kileyhykawy** [comment]
Just updating on re-send. Last night the resend of the hook failed. Today, the hook did succeed but didn't trigger a build.

**Comment by kileyhykawy** [comment]
Also adding that around the last time it worked, I was migrating over to Pipelines v2. Some changes there was generating a Shippable API token for triggering pipeline from CI success and adding additional integrations for AWS (since I couldn't use cross-account roles for deploy auth).

**Comment by manishas** [comment]
@kileyhykawy We looked into this and this is a bug on our end. You are using the same repository for your CI yml and pipelines ymls. We created a webhook for the repo on Bitbucket for CI and when you used the same repo for pipelines, one more webhook was created for the same repo. Unfortunately, this new webhook overwrote the CI webhook, so your CI is no longer triggered as a result.

You can do the following to solve this problem:
- Move your pipelines ymls (jobs, resources, triggers) to a separate repository and seed the pipeline again. You will lose version history for your pipeline jobs and resources but it should work as expected moving forward. 
- Reset your CI project so that the CI webhook is created again.

Let me know if that works. We will fix this issue at our end but our fix won't bring back your CI webhook :(

**Comment by kileyhykawy** [comment]
@manishas - what are the implications of resetting the CI project? I assume the reset button I want to click is the one with the comment "Resetting the project will reset the webhook and deploy key associated with the project." When I reset the deploy key, does that also mean all of my encrypted variables need to change?

**Comment by kileyhykawy** [comment]
Never mind -  I found it in the documentation :). Unfortunately have to reencrypt variables again :(.

**Comment by manishas** [comment]
This has now been fixed. Closing.
