### ISSUE TITLE
Console logs not shown on web UI

### ISSUE THREAD

**Issue by gundalow** [Shippable/support#3052]
### Description of your issue:

Hi

I'm getting empty console logs on all repos, for example
https://app.shippable.com/runs/57ffd7346fec770f0038cc85/16/console
https://app.shippable.com/runs/57fffd0add3ce20e00de9cdc/3/console

This was working within the last 24 hours, I don't see any issues on https://github.com/Shippable/support/issues nor anything on status.shippable.com related to this.

**Comment by gundalow** [comment]
@mattclay FYI

**Comment by gundalow** [comment]
The console runs of new logs do appear to be shown, e.g.
https://app.shippable.com/runs/5800aca1024e6f140144b4ae/16/console

**Comment by toshovski** [comment]
same issue. Some of the logs are gone

**Comment by avinci** [comment]
@gundalow @toshovski, I apologize for not creating a ticket. Yesterday evening around 3.00am GMT, our system was flooded with bit coin miners that flooded our block storage. Due to this, response times went way up on loading consoles and starting timing out on the UI. 

We are trying to figure out how to isolate that data and purge so that we can recover the rest of the data. Unfortunately, we don't back up the console logs as its just a huge volume of data that keep only for 30 days anyhow. As a result we have few options to just simply restore from day before. 

To make sure the service is up,  we have created a new block of storage and all the builds after 3am should be good. We also added monitoring for bitcoin traffic signature to block them from doing this which is working so far. So you should not see any issues moving forward. 

All the critical data thats in postgres is intact and hence you build information is safe. Only the console has been taken offline. If you need this urgently, you can rerun the build and it should run exactly as it had run before as a work around while we work on bringing the console history back on line. 

I will update you on progress once the core engg is back today in terms of recovering console history.

Once again, Apologies for not updating the ticket.

**Comment by gundalow** [comment]
@avinci Thank you very much for the open and honest response.

If we need any logs we can just rerun those specific jobs, so no long term loss there.

**Comment by manishas** [comment]
Closing this issue.
