### ISSUE TITLE
Is Git LFS supported by Shippable or can be in future?

### ISSUE THREAD

**Issue by PaulWebbster** [Shippable/support#3053]
In my repo I have few files add using git lfs, however build fails because this files wasn't downloaded but are used in build. Is any way to force shippable to pull repo with the files added to lfs, any integration pre-ci step? If not can be such feature requested?

Best regards

**Comment by PaulWebbster** [comment]
Hey guys, whats about this request. Can you add such feature to Shippable?

**Comment by avinci** [comment]
We will absolutely add this. I have opened a request internally for this. I will get back to you on the dates for this.

**Comment by rageshkrishna** [comment]
Git LFS will be available in the next few days.

**Comment by garth-wells** [comment]
Any news on adding LFS support?

**Comment by rageshkrishna** [comment]
Sorry, folks. I forgot to update this issue. Git LFS has been available for quite a long time now :)

You should switch your subscription to use the 5.4.1 (or later) system machine image. All of our official drydock images since tag v5.4.1 come with Git LFS pre-installed.

See http://docs.shippable.com/reference/machine-images-overview/ for details on how to switch images and what's available where.

**Comment by garth-wells** [comment]
Unfortunately it didn't work for me (https://app.shippable.com/bitbucket/fenics-project/dolfin/runs/4/1/console). I'm using my own image, which does have git lfs pre-installed..

**Comment by rageshkrishna** [comment]
@garth-wells That looks like a limitation from BitBucket's end: https://confluence.atlassian.com/bitbucket/current-limitations-for-git-lfs-with-bitbucket-828781638.html#CurrentlimitationsforGitLFSwithBitbucket-AccesskeysdonotallowaccesstotheGitLFSfiles

It turns out deploy keys cannot be used to access anything from their Git LFS storage. They suggest using app passwords to get around this, but that's not yet a supported scenario on Shippable.

Please open a separate issue around this so we can track it better.
