### ISSUE TITLE
Docker image push failure for non master branch 

### ISSUE THREAD

**Issue by DronMDF** [Shippable/support#3073]
I want push one docker image for each successful master build.

Docker image build and pushed ok.
https://app.shippable.com/runs/580a6294a799120f00f3f1fb/2/console

But if i'm turn on branch filter - build was failed.
https://app.shippable.com/runs/580a60ccf057850f005bc846/1/console

diff from second to first.
https://github.com/DronMDF/vanadis/commit/93aac533cad56ce9f53998ca3c8bf838f026da24

How i can exclude docker build for non-master branch? It should not cause failure...

And second question: How i can exclude docker build from all matrix variants? Once is enough.

Thank's.

**Comment by cratz** [comment]
@DronMDF 
looks like an authentication issue (https://app.shippable.com/runs/580a60ccf057850f005bc846/1/console)

You can simply wrap `docker build ...` command in a condition an check branch name e.g like this
```
post_ci:
    -  if [ "$BRANCH" == 'master' ]; then docker push dronmdf/vanadis:devel; fi
```

**Comment by rageshkrishna** [comment]
@DronMDF The branch filter in https://github.com/DronMDF/vanadis/commit/93aac533cad56ce9f53998ca3c8bf838f026da24 means that the docker hub integration itself will only be available when the master branch gets built. Because you are building another branch, the integration is not available and your push fails.

@cratz is correct about how to do add conditions to the docker push step but to filter based on which job of the matrix you are in, you probably want to use the `SHIPPABLE_JOB_NUMBER` env var.

This will do the docker push only on the first job in the matrix:

```
post_ci:
    -  if [ "$SHIPPABLE_JOB_NUMBER" == '1' ]; then docker push dronmdf/vanadis:devel; fi
```

**Comment by DronMDF** [comment]
Why specify a limitation in the integrations, if the post_ci is still necessary conditions?

With condition it's work once and only for master. Thanks.
https://app.shippable.com/runs/580e5585ffca4b0e004a65d7/summary
