### ISSUE TITLE
Get commit SHA for latest successful build in project

### ISSUE THREAD

**Issue by thelamer** [Shippable/support#3079]
As I currently understand it, in order to achieve this we need to pull the whole blob here: (due to not being able to filter by project) 

https://api.shippable.com/jobs

Then proceed to parse this blob by project key, and loop through the "runNumber" in a descending order until I get a hit on "statusCode" = 80. 

Alternatively I could get this from the bitbucket API, but I am unable to determine the key that you pass for an identifier here: 

https://api.bitbucket.org/2.0/repositories/{owner}/{repo_slug}/commit/{revision}/statuses/build/{key} (the {key} value) 

Ref doc : 

https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/updating-build-status-for-commits.html

Three requests here: 
1. Can the projects path accept the "Fullname" for a project identifier instead of your guid? So I do not need to maintain a mapping ? IE "mybitbucketuser/repo" instead of "56ea772a9d043da07b11f383"
2. Can you simplify job parsing by returning last successful job id or something on the projects endpoint? 
3. What is the key used when you submit job status to the bitbucket API? 

`{
	"state": "<INPROGRESS|SUCCESSFUL|FAILED>",
	"key": "<build-key>", <==Right Here
	"name": "<build-name>",
	"url": "<build-url>",
	"description": "<build-description>"
}`

**Comment by cratz** [comment]
@thelamer 
Where do you wanna use this SHA?
We are generating a file (in shippable.yml) which contains the SHA of the build this file is included in the final docker image. Since we only push succesfully builds to docker registry the SHA of `docker pull xxxx/xxx:latest` will always contain the commit SHA for latest successful build in project.

**Comment by kanthchandra** [comment]
Hi @thelamer 
> Can the projects path accept the "Fullname" for a project identifier instead of your guid? So I do not need to maintain a mapping ? IE "mybitbucketuser/repo" instead of "56ea772a9d043da07b11f383"

* No, at the moment we only accept only the projectId while applying any filters.

>Can you simplify job parsing by returning last successful job id or something on the projects endpoint?

* On Shippable runs are the parents of jobs and each run can have multiple jobs. So API you were hitting earlier should have been `/runs` instead of `/jobs`. 

* There are two API's that are currently documented [here](http://docs.shippable.com/api/run/) and [here](http://docs.shippable.com/api/project/) which I think will suit your requirements. 

* You could use the /runs api which will return the runs that your token has access to after filtering based on your query params. For your case you could use the following request.

  https://api.shippable.com/runs?status=80&projectIds=YOUR_PROJECT_ID&branch=YOUR_PROJECT_BRANCH&maxRunNumber=99999&sortBy=runNumber&limit=1

  Please note that MaxRunNumber is set to a very high number so that you can get the latest run. You can adjust the value based on your needs.

* /projects/:projectId/branchRunStatus - you could use this API, but this one will return the latest run for the branches that you have configured in the project settings page.

> What is the key used when you submit job status to the bitbucket API?

* 'Shippable Run #' + runNumber is the key that we use to set the commit status.

I hope I answered all your questions. Let us know if you still have any more questions.
