### ISSUE TITLE
Formerly working ecs-deploy job just stopped working

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3097]
This job to deploy to ecs was working fine for a month or so, then yesterday, with no changes made to any of the shippable config files, it started reporting failure. The funny thing is that it DOES appear to actually deploy, but reports a failure nonetheless. 

Here is a link to the build. 

https://app.shippable.com/subscriptions/56c5f9fd1895ca4474745dd3/pipelines/builds/581875b2eacaec0e002424d3/consoles

**Comment by trriplejay** [comment]
Hey there,

Based on the logs, it looks like ECS had trouble placing the task (not enough memory).  After awhile, if the task cannot be placed for some resource-related reason, we will consider the deployment a failure, but the ECS service still references the new task definition.

If you notice that the new container is actually running, I would guess it's because your cluster eventually found an instance it could start the task on.

**Comment by npahucki** [comment]
Nothing about the setup has changed, there is only one server in the cluster, so it should not behave any differently than it has for the last month. I saw that message about the memory too, but the Service logs ALWAY show that, then it shuts down the old instance and brings up a new one. What is different now is that this somehow shows up as a failure on the shippable side whereas is did not before.

**Comment by trriplejay** [comment]
I see. We did enhance our deployment workflow to catch errors like that, which is why it is failing now when it didn't before. It didn't seem right to mark a deployment as a success when the new container wasn't actually able to start.  You're saying that the container does eventually start though? 

If this is a typical scenario for your pipeline, you might want to try making use of the `deployMethod: replace` option.  With this method, we scale your existing service to zero, then once the tasks have stopped, we scale it up again (with the new task definition), so that the new container isn't competing for resources with the old.  This tends to work better with single-instance clusters.

**Comment by manishas** [comment]
Closing this since it is resolved. @npahucki let us know if the replace option doesn't work for you.
