### ISSUE TITLE
docker-compose to AWS EB?

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3129]
Can I use the "eb_docker" target/integration to push multiple containers started by docker-compose to go up to AWS Elastic Beanstalk for a multi-container docker service?

(Or would I be better off just copying the functionality that eb_docker does myself? Or should I just have multiple integration names under a main "deploy" section?)

**Comment by trriplejay** [comment]
Using the integration mainly does three things:

1. gives you a place to hold your secure keys without having to manually encrypt and add to the yml.
2. automatically runs `eb deploy` in your project folder after a successful build
3. automatically replaces image name/tag placeholders in a Dockerrun.aws.json file, so that you can dynamically push images in your build while telling beanstalk to deploy them.

numbers 1 and 2 I think would still provide value to you in the case of multi-container docker compose.  During CI, you can make whatever changes you need, keeping in mind that in the end, we will be issuing an `eb deploy` command.

You may need to add some script pieces yourself, as we currently do not natively support the multi-container deploy platform of EB.

Let me know if you have more questions.
