### ISSUE TITLE
Multi-users and multi Github accounts

### ISSUE THREAD

**Issue by Nypias** [Shippable/support#313]
Hello,

I would like to know if you plan to develop the connection of several users to the same Shippable account. Also, is it possible to add several Github accounts so the builds are triggered from multiple users' repositories?

Thanks,
Thomas

**Comment by haf** [comment]
From a single user's perspective, I can't find the button to click to invite more people, even though I'm ready to pay for it.

**Comment by kanthchandra** [comment]
@haf can you please let me know what your requirements are? If you are looking to add more members to your organization, we inherit the same permissions that your organization members has on github. So anyone who is a member of your org should be able to see the builds of your org once they sign in.

In case they are not able to see, you can go to your account settings page and click on sync so that all the permissions get synced and they should be able to see the repos and builds.

If you have a specific use case and you need help with that can you please open a new issue describing your scenario?

**Comment by haf** [comment]
For those sorts of details I would prefer to have a conversation in private rather than in a public issue tracker. I have e-mail henrik at qvitoo dot com.
