### ISSUE TITLE
Can't get ecs-cli working

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3141]
I'd tried several different ways to get ecs-cli to work, but I can't get it to pick up the right variables. Can you please help?

Please see: https://app.shippable.com/runs/5823be561f6f300e005d04c8/1/console and maybe the last dozen runs for my attempts.

This was the closest I've gotten: https://app.shippable.com/runs/5823afdb03ece20e000eb677/1/console
```
msg="Unable to create an instance of ECSParams given the cli context" error="NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" 
```

(After attempts to populate ~/.aws/credentials and ~/.aws/config, which seemed to do nothing. Also tried to populate a few different AWS variables, but that also did nothing.)

**Comment by manishas** [comment]
@gitglacier do you want to jump on a hangout tomorrow and discuss your scenario? We recommend deploying to ECS using [Pipelines](http://docs.shippable.com/pipelines/overview/) since we have greatly simplified that workflow.

I can show you a quick demo tomorrow or you can [try the sample application](http://docs.shippable.com/tutorials/pipelines/samplePipeline/) to see how pipelines work.

Let me know what works for you. I will be available between 10am-3pm PST tomorrow.

**Comment by manishas** [comment]
Demo scheduled for 11/11 at noon PST.

**Comment by manishas** [comment]
@gitglacier I am closing this issue since we walked through a simple pipelines scenario during the call. Please let me know if you or James run into any problems while configuring this and we'll be happy to jump on another call.
