### ISSUE TITLE
Can't push `Conflict: Tag  is already set to image.`

### ISSUE THREAD

**Issue by Rivinek** [Shippable/support#3145]
### Description of your issue:
Hello all,
We have experienced an issue during the push. After success build when we want to push we are getting a following error:
`Error response from daemon: Conflict: Tag <our_name>:latest is already set to image 70e37f2aa785, if you want to replace it, please use -f option`

Our push script:
```#!/bin/sh
set -eux
. scripts/vars

case "$BRANCH" in
    master|develop|qa|feature/shippable)
        docker push $IMAGE
        ;;
    *)
        exit 0
        ;;
esac

case "$BRANCH" in
    develop)
        docker tag  $REPO/$PROJECT:$TAG $REPO/$PROJECT:latest
        docker push $REPO/$PROJECT:latest
        ;;
esac
```

**Comment by rollcat** [comment]
Some of the failed builds:

- https://app.shippable.com/runs/5824691100904d0f00b6399f/1/console
- https://app.shippable.com/runs/58237d2439c36b1000a5d9ee/1/console

The issue seems intermittent.

**Comment by trriplejay** [comment]
When you trigger a build on Shippable, we dynamically provision a host machine to run your build in.  If you run several builds in a row, the subsequent builds will likely be run on the same host machine.  If your first build tags an image with latest, and your second build also tries to tag a newly built image with latest, there will be a conflict, because the image with the latest tag from your previous build still exists on that machine.  

Eventually, the machine will be terminated, so then the next build you run will be on a fresh host that no longer has any image with latest tag.  I would guess this is what you're running into, and why it is intermittent.

If you want to continue adding latest tag, I recommend adding the -f as the warning suggests.

If you want to check this, you can try adding a `docker images` command to your yml and see what images are already on the machine when your build runs.

**Comment by Rivinek** [comment]
@trriplejay thanks for an answer! I think it describes and solves our problem for now. 
Cheers
