### ISSUE TITLE
blueGreen SPOG deploy stuck on "DRAINING"

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3161]
I'm playing around with the Pipeline sample. (http://docs.shippable.com/tutorials/pipelines/samplePipeline/)  Works great, but I've changed it around to replica 2 and trying to test deploys. Do I need a 3 node cluster for a replica 2 or will 2 nodes work?

Please see the following console:
https://app.shippable.com/subscriptions/57f4596bb60e2a0f001627f3/pipelines/builds/582a5a65219b6a0f003240d9/consoles

We get:
```
Service status of dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a : ACTIVE
Desired Tasks: 2, Running Tasks :0, Pending Tasks:0
Service status of dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a : ACTIVE
getting events of failed Service
Desired Tasks: 2, Running Tasks :0, Pending Tasks:0
ddaeedab-df42-4efb-adc1-a5ac109fa546 - (service dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance 9929c6ec-678a-463a-85a9-97e1a6e98794) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide. (Tue Nov 15 2016 00:44:22 GMT+0000 (UTC))
downgrading failed new service dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a
waiting for downgrade of Failed new service dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a
Running Tasks :0, Pending Tasks:0
delete failed new service dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a
waiting for failed new service to become inactive
Service status of dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a : DRAINING
Service status of dv-prod-ecs-dv-man-cf60bf7c-ce29-4b79-b164-b4cf7ce2bb4a : DRAINING
```

And it repeats DRAINING over and over until it fails. If I manually delete the service/task out of the AWS Container view and try to manually re-deploy, it works fine.

I see it mentions "blueGreen". Do I need to have at least 3 nodes for this to work with 2 replicas or will it work with 2 replicas and 2 nodes? (I only have 2 nodes in the cluster right now.)

I can't find much help on the blueGreen deployment. Is this documented somewhere how it works? (Is it like AWS EB?) Is this coming from your script or Amazon? (Hard to know without `set -o xtrace`)

**Comment by trriplejay** [comment]
blueGreen works by bringing up a second copy of your service before removing the original.  If your service utilizes specific host ports, then you will need to have enough hosts to run two copies of your service without port conflicts. For a service with 2 replicas, this would likely mean 4 hosts.

Alternatively, you can use deployMethod `upgrade`, which uses the native ECS deployment flow (ECS will directly handle the transition of your service from one task definition to the next).  In this case, you'll still need at least a 3rd host so that ECS has one extra machine that it can bring a new container up on without conflict.

Finally, you can also get around port conflicts by using Amazon's "application load balancer", which will dynamically assign host ports and map them to your desired external port on the LB.

**Comment by gitglacier** [comment]
This was exactly what we needed to know! Thanks for the awesome support!

**Comment by gitglacier** [comment]
Referencing the documentation for anyone who finds this in the future:
http://docs.shippable.com/pipelines/jobs/deploy/#blue-green-deployments
