### ISSUE TITLE
Shippable can't find GCR integration

### ISSUE THREAD

**Issue by retemaadi** [Shippable/support#3171]
### Description of your issue:
Shippable can't find GCR integration, I've tried all possible combinations, and it didn't work.

Here are samples of the failed builds:
https://app.shippable.com/runs/582c90662bbf381000df90ef/1/console
https://app.shippable.com/runs/582c8e714dac720f008c3816/1/console
https://app.shippable.com/runs/582c8e455a16461000506431/1/console
https://app.shippable.com/runs/582c8e1756f74e0f009b6384/1/console
https://app.shippable.com/runs/582c8c71da9a420f00eb58af/1/console

https://app.shippable.com/projects/580e27fe88401b0e003a9de5/status/history

Here is my shippable.yml:
[shippable.txt](https://github.com/Shippable/support/files/596903/shippable.txt)

![screen shot 2016-11-17 at 09 42 57](https://cloud.githubusercontent.com/assets/1247458/20382005/45e0424e-acaa-11e6-8b80-fb61d63cfc48.png)

**Comment by rageshkrishna** [comment]
@retemaadi Have you added the integration to your subscription? Please have a look at the section titled `Enabling the integration for a Subscription` at http://docs.shippable.com/integrations/overview/

**Comment by retemaadi** [comment]
@rageshkrishna Yes, of course! I followed this doc ( http://docs.shippable.com/integrations/containerServices/gke/ ) step-by-step.

**Comment by manishas** [comment]
@retemaadi can you follow instructions at

http://docs.shippable.com/navigatingUI/subscriptions/settings/#adding-integrations

The error indicates that you've added an account integration but not added it to your subscription.

**Comment by manishas** [comment]
I'll make sure we update the docs to be clearer about how to use this.

**Comment by retemaadi** [comment]
@manishas What do you mean "not added it to your subscription" ? How else I added integration ? Did I add to other company subscription ?

**Comment by rageshkrishna** [comment]
There are two steps required to be able to use an integration in a project.

The first, which you've already done by following the steps at http://docs.shippable.com/integrations/containerServices/gke/. This creates an `Account integration` that is accessible only by your account.

The next step is to "allow" one or more of your subscriptions to use this account integration. This is done by creating a `Subscription integration`, which is what is described at http://docs.shippable.com/navigatingUI/subscriptions/settings/#adding-integrations.

Until you do this, projects will not have access to any of your integrations because you have not explicitly allowed your integration to be used by the subscription.

**Comment by manishas** [comment]
closing. @retemaadi let us know if you could make this work or if you need more information
