### ISSUE TITLE
Pipelines: Help Migrating to New Repo

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3177]
### Description of your issue:
We're attempting to consolidate much of our operations/systems related code into a single repository in Github. This means we'll need to move the contents and history of our `ops-pipeline` repo into this new repo and point the rsync job at the new repo.

I need guidance on how to do this without downtime in our production environment.

Thanks!

**Comment by manishas** [comment]
@BlueDragonX Let me follow up on this and get back to you.

**Comment by BlueDragonX** [comment]
It's been a month. Any response to this? We'd like to consolidate our operations code.

**Comment by manishas** [comment]
Sorry about the long delay on this. I'll definitely have an answer tomorrow.

**Comment by manishas** [comment]
Still following up on this... I've asked the team to respond with recommended steps so you should see that sometime today. Thanks for your patience!

**Comment by avinci** [comment]
Currently, we have an issue with this as it will create downtime if you do it and need history. We are internally working on a feature to be able to do this and launch it end of Jan. 

But if you want to do it now, its a bit convoluted due to the fact that we actually deprovision your deployed manifest on soft-delete. We have gone back and forth on this and it seems the best approach at that time so that we dont leave remnants around as most users never went back to hard delete and they were annoyed that the old services were still sitting around. We might have to revisit that now...

but here goes the convoluted way
1. first add the new rSync repo
1. add your proxy deploy jobs only that you want to migrate here. Just changing the name of the deploy job and adding that to the jobs.shippable.yml should be enough
1. you should see all the proxy deploys get added. Now you might want to manually run all those deploys jobs and your proxy services should get deployed as a placeholder when you move the real jobs. verify that all the services are running and make sure any network routing config etc. is done if you need it (if you have service discovery then this might not be needed)
1. Now migrate all the other resources and jobs from the old repo to the new repo. commit the deletes on the old repo first. This will ensure the rSync job on the new repo will not fail (but if it does fail due to duplicated names since the old ones are not deleted, no biggie, you can run it manually after the old repo entries are deleted)
1. Once you delete the old repo stuff, all the resources will go to soft deleted mode except the proxy deploy jobs. They might get marked inconsistent but that will NOT bring down the deployed services. So you should have no downtime.
1. Now add the deleted resources and jobs YML block from old repo into new repo. This should bring back all the objects from soft deleted mode back to active. You might want to manually run the deploy jobs now to bring up the original deployed services back on. verify routing etc if needed.
1. Now delete all the proxy deploy jobs from the repo. Then you might want to hard delete all the proxy deployed jobs to remove any remnants. 
1. rinse and repeat for other repos you want to consolidate

This should do it. Let me know if you have any questions

**Comment by BlueDragonX** [comment]
@avinci so you're saying following these instructions will incur some down time?

Also, what is a proxy deploy job? You seem to have omitted the part of the explanation that describes what that is.

**Comment by avinci** [comment]
No, if you follow the instructions, there is no downtime.

Lets you have a deploy job that deploys `API` to `ECS` called `deploy-prod-api`. This is defined in `repo1`

Now if you delete this YML block from repo 1, the actual service on ECS will get deleted. So what I am saying is create a placeholder (proxy) service. 

First copy the `deploy-prod-api` YML block into `repoAll` and call it `deploy-prod-api-proxy`. This will bring up and second copy of API service. 

Now if you delete `deploy-prod-api` block, it will soft delete the job on shippable and then remove the service on ECS. Now you have `deploy-prod-api-proxy` still running on ECS and hence you dont have downtime. 

Now add `deploy-prod-api` YML block to `repoAll`. This will remove the soft delete from Shippable and hence the service will get deployed again to ECS. 

Now delete `deploy-prod-api-proxy` from `repoAll` and you have your service migrated. 

I am happy to jump on a quick hangout and talk if it would be easier.
