### ISSUE TITLE
Failed to connect to localhost port 80

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3189]
### Description of your issue:
I am trying to do a quick test after I complete my docker image but I keep getting error when I try to curl the local host

- Link to the build failure => https://app.shippable.com/runs/583671bd7ae6830f00c42e87/1/console
- Scripts called from the yml (optional)
build:
  ci:
    - cd src
    - npm i
    - npm run coverage
    - npm build
    - cd ..
    - docker build -t geoip-app-master --no-cache --force-rm=true --build-arg node_ver=6.1 .
    - docker run --name geoip-app-master -p 9001:9001 -p 80:80 -v /tmp/app.log:/var/log/app.log -e TZ=Pacific/Auckland -e NODE_ENV=dev -e NO_PROXY='localhost, 127.0.0.1, .local, .internal, .internal.bauer-media.net.au' -d geoip-app-master
    - sleep 60 && curl --ipv4 localhost/location

**Comment by a-murphy** [comment]
Docker containers started within the `ci` section run on the host alongside the build container, not in the build container.  The `docker run` command above would correctly map port 80 in the new container to port 80 on the host, but that's not the build container's "localhost."  One option is to add the `--net=host` option in the `pre_ci_boot` section of your `shippable.yml` so that the build container will consider the host machine to be localhost and be able to connect to the new container at `localhost:80`.  Documentation on specifying options for the build container is [available here](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot).

**Comment by asanchezgiraldo** [comment]
@a-murphy thanks that has worked 👍
