### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by swhite-finovertech** [Shippable/support#3198]
### Problem downloading console output

I had a failed build, and was trying to look at the console output:

https://app.shippable.com/runs/583ee06c93db4e1000fa8954/1/console

The console log was too big to view, so I attempted to download the output by clicking on the download button. I was taken to the page:

https://app.shippable.com/download/jobConsoles?jobId=583ee07ab5bc7810005fd972&isOldJobConsole=false

Which was a page with the error message:

Cannot GET /jobs/583ee07ab5bc7810005fd972/consoles?download=true

I need to determine why the build failed, but I cannot because I cannot get access to the console output. What is the problem? And can I get around the problem?

**Comment by a-murphy** [comment]
The error will be fixed in a future update.  In the meantime, you can use the APIs to download the console logs.  The download route is documented [here](http://docs.shippable.com/api/job/#response_2) and information about using an account token (created on the [account settings page](http://docs.shippable.com/navigatingUI/accountSettings/api/)) available [here](http://docs.shippable.com/api/overview/).

**Comment by stephanielingwood** [comment]
Hi @swhite-finovertech,

We released a fix for this last night, so console downloads should be working for you now. Sorry for any inconvenience! Please do let us know if it's not working, or if you run into any other issues.
