### ISSUE TITLE
API gives access denied with all API tokens.

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#3202]
Dear supports,

One of my API tokens has worked successfully for 9 months. The API started giving access denied errors today:
> {
  "logType": "warn",
  "methodName": "/projects|GET|validateAccount|_compareRouteRoles",
  "id": 2000,
  "message": "access denied to route: /projects"
}
The token still seems to exist, so it hasn't been removed by one of my colleagues. I also tried creating a new token and see if it works but I get the same error. I tried my tokens on the /projects and /runs endpoints.

Thanks

**Comment by pax162** [comment]
We have the same problem. If it helps, we noticed that `curl -H "Authorization: apiToken [Token_here]" https://api.shippable.com` still returns ok.

**Comment by a-murphy** [comment]
All tokens were revoked a few weeks ago as a precaution because of a security issue.  It sounds like the new tokens were created by a user who is not a part of any paid subscriptions.  Those users can only create tokens intended to connect CI builds to Pipelines and so are only able to call a few routes.

If this is not the case, would you mind including which account has this problem?  Either the account ID from the account settings page or the GitHub or Bitbucket user name would help us identify the account with failing tokens.

**Comment by pax162** [comment]
Yup, we changed the tokens when the security issue happened, routes like `/projects/:projectid/newBuild` seemed to work ok until yesterday. The shippable ID for our account is 581906449c60390e00f91d6d.

**Comment by HelainSchoonjans** [comment]
The ID for our account is 56f3e046d65cfe0c007fd988. I can confirm that new tokens created with the paid accounts still don't work for the /projects route...

**Comment by pax162** [comment]
Hey @a-murphy, @avinci, is there anything more we can do to help with fixing the issue? Or maybe you could suggest a temporary workaround? Shippable is a core part of our dev process, working without it is quite painful.

**Comment by a-murphy** [comment]
@HelainSchoonjans That account does not have access to any paid subscriptions.  And none of the other accounts with access to the same subscription have access to any other subscriptions with multiple minions.  Could you double-check that the subscription you believe to be paid in fact is?  And that this account has access to that subscription?

**Comment by a-murphy** [comment]
@pax162  The account ID you gave above does not have access to any paid subscriptions.  The `/projects` route will work for tokens created by a user with access to a paid subscription.  Adding a second minion to one of your subscriptions will allow you to create new tokens that will be able to call the `/projects` route (and other routes).

**Comment by pax162** [comment]
@a-murphy, but shouldn't the `/projects` route also work for unpaid accounts/tokens? Everything seemed to work ok until Thursday last week.

**Comment by a-murphy** [comment]
Access to the API for unpaid accounts is only intended to allow CI builds to be connected to Pipelines.  The `/projects` route is not required for that.  Previously, the `/projects` route worked for these tokens, but it was not intended.  Last week's update corrected the permissions so that tokens created by free accounts cannot access `/projects`.

**Comment by pax162** [comment]
Our tokens are working after upgrading to a paid account, thanks @a-murphy for your help!

**Comment by manishas** [comment]
Closing this issue.
