### ISSUE TITLE
Forcing specific BYON node for specific build

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#3222]
As many people know, the network condition in China is very brutal. So we have to place our build system inside China's Great firewall when we decide to have a service in China.
So we need some feature to specify which BYON node to use in Shippable configuration. Is there any feature for that?

**Comment by manishas** [comment]
@Kivol I am marking this a feature request since we do not support specifying a specific build node per build.

However, if you're using BYON, all builds will run on your machines, so if they're hosted in china,  all builds will run there. I am not clear on why you need to specify a particular node for each build.

**Comment by Kivol** [comment]
@manishas I need this feature because we are to serve the same service(git repo) both in China/US. We want to implement push-to-deploy, for example, we want to build and deploy to China when pushed to `china` branch, while pushing to `us` branch triggers the deployment to US. But, with same shippable account, we cannot specify which BYON node to be used for `china` branch.

**Comment by bogotej** [comment]
@manishas This request seems somewhat similar to mine : https://github.com/Shippable/support/issues/3009

**Comment by avinci** [comment]
this is pretty tough thing to implement with our current architecture. We dont have branch or repo specific queues to which builds are fired and hence its not possible to implement this. 

One thing you could do is run 2 different subscriptions, 1 for China and 1 for US and keep them in sync. they could be forks so that you could do PRs between them etc. Its exactly the same as a branch but in different orgs.
