### ISSUE TITLE
Custom docker image not caching

### ISSUE THREAD

**Issue by david-anyvan** [Shippable/support#3223]
We created a custom docker image for our builds, as due to the number of composer modules and the size of the project, it runs much quicker with an image that contains most of it already. This allowed our builds to complete in around 2-4mins.

Lately however, it appears that the docker image is no longer getting cached, and so is being pulled every single time! This adds around 12mins to the build each time.

Is there something that we are missing here? or have you stopped caching custom docker images?

**Comment by rageshkrishna** [comment]
@david-anyvan This should be back to normal now. Please let me know if you're still seeing this problem.

**Comment by desoukya** [comment]
@rageshkrishna @david-anyvan what is the proper configuration gor caching the custom docker image used for each build? In my case, I'm using ECR, and it also pulls the image every time despite having `cache: true` inside of the build block.

**Comment by manishas** [comment]
@desoukya there is no real configuration to cache docker images. Our caching support is described at 
so you can cache specific artifacts from the build.

However, there are 2 ways custom docker images do get cached and to understand this, you need to also understand Shippable nodes vs [BYON](http://docs.shippable.com/ci/advancedOptions/byon/): 

- By default, all your builds run on build machines hosted on Shippable's infrastructure. When a build is triggered, we check to see if any machines are already running in your subscription.
    - If there is no idle machine, we spin up a new machine. This machine does not have your custom docker image, so it will be pulled as part of your build. 
    - If we find a machine that is already up and idle, we will run your build on that machine. If your custom docker image was pulled on this machine for a previous build, it will not be pulled again and you'll get an effect of caching. 

- With [BYON](http://docs.shippable.com/ci/advancedOptions/byon/), you attach your own machines to your Shippable subscription. All your builds run on your machines and since these machines are always up, the custom docker image is pulled for the first build and doesn't need to be pulled for subsequent builds.

**Comment by manishas** [comment]
Closing.

**Comment by desoukya** [comment]
got it, thanks @manishas!

**Comment by buzinas** [comment]
@manishas I know this is closed, but I would like to make a question: couldn't Shippable have a shared drive between all machines you spin up? The idea is: once you have a place to keep all the Docker images caches, you will reduce a lot of inbound gigabytes, while saving lots of CI minutes for all your users.
