### ISSUE TITLE
Build's are all timing out

### ISSUE THREAD

**Issue by christopherlongden** [Shippable/support#3229]
last failed build error:
Error response from daemon: no such id: c.exec.oneshoo.3140.1
Error: failed to remove containers: [c.exec.oneshoo.3140.1]
pending builds have empty consoles, just black screens.

https://app.shippable.com/runs/584e836fac4a911000ec7c43/1/console

**Comment by kanthchandra** [comment]
Hi @christopherlongden, I think your build is trying to dump some unicode character other than utf-8 and our system is not able to parse it and it's getting stuck. You can download the logs of one of your timedout builds and you will see it. 

Unfortunately we are not able to repro this at our end, since the output seems to be from npm install, would you mind emailing us your package.json and your shippable.yml?? We will investigate this and get back to you. You can email me chandrakanth@shippable.com.

**Comment by christopherlongden** [comment]
Hi,

My developer, Alex (copied), will send this to you.

Many thanks
Chris

On 12 Dec 2016, at 15:36, Chandrakanth <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @christopherlongden<https://github.com/christopherlongden>, I think your build is trying to dump some unicode character other than utf-8 and our system is not able to parse it and it's getting stuck. You can download the logs of one of your timedout builds and you will see it.

Unfortunately we are not able to repro this at our end, since the output seems to be from npm install, would you mind emailing us your package.json and your shippable.yml?? We will investigate this and get back to you. You can email me chandrakanth@shippable.com<mailto:chandrakanth@shippable.com>.

**Comment by kanthchandra** [comment]
@christopherlongden We have opened an internal issue to fix this problem and I will let you know when the fix is available. Since we also have another issue https://github.com/Shippable/support/issues/3011 with the same problem I'll close this to keep the list clean.
