### ISSUE TITLE
Postgres 9.5 or greater

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#3246]
### Description of your issue:
How do you install or use Postgres 9.5 or greater with the builds? Without using docker.

**Comment by magicalbanana** [comment]
Anyone?

**Comment by magicalbanana** [comment]
Is 9.5 supported? Beause this issue #2682 seems to indicate that it should've been supported since June of 2016.

**Comment by magicalbanana** [comment]
Still no answer? 😢

**Comment by a-murphy** [comment]
There are images with Postgres 9.6 installed, but they have not yet been fully tested.  Until they are fully tested, they aren't considered official images and not all options will work.  However, the images can be specified in the `pre_ci_boot` section of the `shippable.yml` file and services can be started from the `ci` section.  For example, to use the newest version of the Node.js image, add this `pre_ci_boot` section to the `build` section of your `shippable.yml`:
```YML
  pre_ci_boot:
    image_name: drydock/u14nodall
    image_tag: tip
    pull: true
```
And start Postgres in the `ci` section with a command like this instead of listing `postgres` in the `services` section:
```YML
 - sudo su -c "sudo -u postgres /usr/lib/postgresql/9.6/bin/postgres -c config_file=/etc/postgresql/9.6/main/postgresql.conf > /dev/null 2>&1 &"
```

The other languages that currently have default images also have at least a Ubuntu 14 image with a `tip` tag.  All of the Dockerfiles for these images are available [here](https://github.com/dry-dock/) and the images are under the drydock organization on [Docker Hub](https://hub.docker.com/u/drydock/).  The first three characters of the image name represent the version of Ubuntu (u14 is 14.04 and u16 is 16.04), the next three are the first three letters of the language name, and the image names ending with "all" are the ones that will have Postgres installed.

Since you don't want to build a new Docker image, your other choice would be to install and start Postgres yourself by including the appropriate commands in your `shippable.yml` file, which should also work.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.

**Comment by mustela** [comment]
Hey guys how do I know the supported postgres versions (Im using runtime version 6.1.4)? I dont see anything here http://docs.shippable.com/ci/postgresql/

I have `9.6` in my shippable file, but the logs says 
``` 
  sudo su -c "sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c config_file=/etc/postgresql/9.3/main/postgresql.conf > /dev/null 2>&1 &"
```

**Comment by a-murphy** [comment]
The Postgres version in each image is listed [here](http://docs.shippable.com/platform/runtime/machine-image/services-versions/#postgres).  Since it is using 9.3, it doesn't sound like you are using a v6.1.4 image.  Projects enabled before machine images were introduced will continue to use the older images, so that may be the case here.  You can add `image_name` and `image_tag` to the `pre_ci_boot` section as described [here](http://docs.shippable.com/ci/custom-docker-image/#pulling-a-public-image) to specify an image for the build.
