### ISSUE TITLE
Multiple commits per build

### ISSUE THREAD

**Issue by craig-berry** [Shippable/support#3247]
If I make numerous commit and then push them (in my case to Bitbucket) can the build register all the commits? Currently I only see the last commit against the build.

**Comment by rageshkrishna** [comment]
We only build the latest commit on each push. If you really need a build for each commit, you will need to push them one by one.

**Comment by mjs2020** [comment]
I am experiencing this when in a single push i push commits to different branches (all of which include shippable.yaml).
I understand building only the latest commit (makes sense) but it would be much better if it were only the latest commit per branch.

**Comment by lassemaatta** [comment]
Is there any chance you might reconsider this use case? We use BitBucket and often have several commits per pull request and it requires a bit too much care and manual work to construct the PR just right so that shippable will register each commit individually. Especially when other CI systems (e.g. gerrit + jenkins) don't suffer from this issue.
