### ISSUE TITLE
Builds hangs in git_sync step

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#3251]
We have seen the last couple of days that many builds starts to hang in the git_sync step:

```
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '/root/src/github.com/bang-olufsen/<name>'...
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
```

The output form one of these builds can be seen here: https://app.shippable.com/runs/585d290de18a291000c1bb33/1/console

Thank you very much in advance.

**Comment by jeppefrandsen** [comment]
Any news on this issue? Just had it again (on two builds): https://app.shippable.com/runs/586aa23307d537130074b057/1/console

**Comment by rageshkrishna** [comment]
@jeppefrandsen I took a look at the build history and noticed that you are also seeing builds timing out because the git clone is taking close to 2 hours to complete. However, the same project gets cloned in around 30 seconds at other times.

It also seems to happen on different machines at different times, so I don't think the problem is localized to any particular custom host that you have.

Some questions off the top of my mind:

- Is there anything about your network that might cause this?
- Has there been a significant change in the size of your repository recently?
- Do you see this happening only during certain times of the day?

I can confirm that we have not made any changes to the way we clone projects in a very, very long time, so I can't really point to a root cause for this problem yet.

**Comment by jeppefrandsen** [comment]
@rageshkrishna We are using Linode build servers but have not checked if there has been some network issues in this timeframe. Will check. 

I will also investigate if it happens during special periods of the day.

**Comment by jeppefrandsen** [comment]
@rageshkrishna seems to be an issue at Linode. Closing the issues. Thanks a lot.
