### ISSUE TITLE
BYON - Hangs on "Running job on customer's build node"

### ISSUE THREAD

**Issue by knowredev** [Shippable/support#3252]
Hello, I'm trying to set up my BYON build, but it hangs on `Running job on customer's build node` stage. Actually my BYON node doesn't even seem to be up. FYI, the node is inside China's GFW, while I completed the BYON installation manually (with a little tweak).

https://app.shippable.com/runs/585f5c96e18a291000c20bcb/1/console

```
# docker logs --tail=1000 -f c55e7d4eaa5b
```

```
Booting up MEXEC..
INFO:listen - listen:Inside MEXEC listener
INFO:listen - listen:MEXEC boot successful
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.shippable.com
ERROR:listen - listen:Error setting node status: 404
INFO:listen - listen:Removing mexec PID file
INFO:listen - listen:Restarting mexec...
INFO:listen - listen:Executing docker restart -t=0 shippable-mexec-585b60a1a572ff1000314011
```

**Comment by kanthchandra** [comment]
Hmmm, the error says that node status that mexec is trying to update is not
found. So probably the node was deleted and then the script was run or
something like that must have happened.

So since you have initialized the node by yourself I can't reset the node
from my end. So I'll let you know the list of steps that needs to be
followed. Can you please try them and let us know if it works for you.

1. Delete the existing node from your subscription settings tab.
2. Remove all the running shippable containers on your node ("docker rm -f
`docker ps -aq`" will remove all the containers assuming you are running
only shippable containers on the node)
3. Go and add the same node again in your subscription settings and
download the script and run the script again.
4. Let us know if you still run into the same error. We will investigate
this further if this doesn't work.


On 25-Dec-2016 11:23 AM, "knowredev" <notifications@github.com> wrote:

Hello, I'm trying to set up my BYON build, but it hangs on Running job on
customer's build node stage. Actually my BYON node doesn't even seem to be
up. FYI, the node is inside China's GFW, while I completed the BYON
installation manually (with a little tweak).

https://app.shippable.com/runs/585f5c96e18a291000c20bcb/1/console

# docker logs --tail=1000 -f c55e7d4eaa5b

Booting up MEXEC..
INFO:listen - listen:Inside MEXEC listener
INFO:listen - listen:MEXEC boot successful
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS
connection (1): api.shippable.com
ERROR:listen - listen:Error setting node status: 404
INFO:listen - listen:Removing mexec PID file
INFO:listen - listen:Restarting mexec...
INFO:listen - listen:Executing docker restart -t=0
shippable-mexec-585b60a1a572ff1000314011

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Shippable/support/issues/3252>, or mute the thread

**Comment by knowredev** [comment]
Yeah, I tried it several times back and forth, but does not work with the same error.

**Comment by shrivara** [comment]
@knowredev, could you mention the changes that you made to the script and check if the build machine has access to https://api.shippable.com?

**Comment by manishas** [comment]
@knowredev I am closing this issue but if you still need help with this, happy to reopen. Let us know.
