### ISSUE TITLE
Why does build assume language is ruby when I did not specify it. 

### ISSUE THREAD

**Issue by Khalian** [Shippable/support#3255]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure : https://app.shippable.com/runs/58635f98b1bb441000bae0f7/1/console
- Scripts called from the yml (optional) : https://github.com/Khalian/docker-swift/blob/docker/shippable.yml

**Comment by Khalian** [comment]
So I got it to work with this hack : https://github.com/Khalian/docker-swift/blob/shippable/shippable.yml. 

But this is still a bug you need to address.

**Comment by manishas** [comment]
@Khalian when we started Shippable, we wanted to support Travis ymls as is to make it easy for people to try out our service. Travis assumes language to be Ruby if the tag is missing.  So this is legacy behavior and difficult to change at this point since many folks assume this to be true. 

However you can set language: none tag If you want to use a custom image and dont  want Shippable to do anything language specific while running your build.

**Comment by Khalian** [comment]
@manishas That is an odd sort of technical debt(travis has a bug, but shippable should not assume it as a feature). I was able to get it to work with just printing the commit sha1 hash.

**Comment by manishas** [comment]
Closing this issue. Please let us know if you need more help with anything.
