### ISSUE TITLE
API Usage: Get status for latest commit on main branch on Bitbucket

### ISSUE THREAD

**Issue by elssar** [Shippable/support#3257]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

We use the Shippable API to report the build status for our projects. We use the branchRunStatus endpoint for each project: https://api.shippable.com/projects/:projectId/branchRunStatus

The problem with this API is that it also considers results of tests for pending PRs on the main branch. So if there is a PR with failing tests, it looks like the main branch is failing tests, which isn't the case.

Is there a way to get branchRunStatus just for commits to the main branch?

**Comment by kanthchandra** [comment]
Hi @elssar , 
1. The branchRunStatus API gives you the latest run for each branch in your repository on shippable and by default it gives you all the result for PRs as well as commits. So if you just want commits then you can try, https://api.shippable.com/projects/:projectId/branchRunStatus?isGitTag=false&isPullRequest=false . This will give you the latest run for each branch that was triggered because of a commit.

**Comment by kanthchandra** [comment]
You could also use the generic GET /runs API to get runs based on the filters provided. For your case you can use https://api.shippable.com/runs?projectIds=projectId&isGitTag=false&isPullRequest=false&branch=YOUR_BRANCH_NAME&maxRunNumber=100000&limit=1

Please note that to get the latest run I have given some high maxRunNumber and set the limit = 1. This API is documented here http://docs.shippable.com/api/run/ along with parameters supported.

**Comment by elssar** [comment]
Thanks @kanthchandra
