### ISSUE TITLE
pull_job_image: Tag latest not found in repository

### ISSUE THREAD

**Issue by magwas** [Shippable/support#3264]
https://app.shippable.com/runs/586e6bc39a67460f009526c9/1/console

the tag does exists. builds both before and after this one are green.
This is the second time I see this problem, among some 30 builds in multiple repos.

**Comment by a-murphy** [comment]
This particular Docker error message doesn't necessarily mean that the tag doesn't exist.  Quite often it appears when credentials aren't valid or response times are slow.  In your case, since it's a public image and had been partially pulled before getting an error, it's likely that a request to Docker Hub timed out.  It's unusual that you've seen this error twice, but unfortunately we are unable to determine why the image could not be pulled.

**Comment by manishas** [comment]
closing this issue since there is nothing actionable for us to do. This could be due to docker hub response time.

Are you continuing to see this?
