### ISSUE TITLE
Cancel Should call on_failure case

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3275]
In my logs, it looks like when a build is cancelled, it doesn't actually call on_failure (however, it does email for a failure). I need to clean up things on a cancelled build, and I need a way to do it.  Maybe add an on_cancelled section?

**Comment by avinci** [comment]
Cancel is not a failure for the system. Its a manual intervention to the workflow. In the current architecture, cancel just kills the build in a brute way. 

What you are looking for is force end the build which is not possible today. 

Can you try and move the clean scripts to before_script and make it idempotent so that it does the clean when the build starts. This will remove all the remnants from the prior build before starting a fresh one?

**Comment by herriojr** [comment]
The only difficulty with this we basically spin up a docker-compose environment to run tests, so when a test starts up from a completely different application, it means I need to basically nuke everything docker-related instead of running docker-compose to shutdown the environment.

I mean, it's doable, but I might as well ask to have the entire docker environment cleaned up between runs by default (note: we are using our own provisioned nodes for building).  Obviously, if we run the hosted node solution, things will all automatically get cleaned up but we moved away from that since it was having difficulties with timely builds.

**Comment by avinci** [comment]
I think we will add a feature request that will run a tear down command on cancel. This should resolve it. I am adding it to our prioritization list and will let you know once its done.

**Comment by avinci** [comment]
https://github.com/Shippable/heap/issues/574
