### ISSUE TITLE
Job fails before pulling job image

### ISSUE THREAD

**Issue by aedades** [Shippable/support#3277]
A particular job appears to fail during the "Job node info" section, before it runs "pull_job_image".  Rerunning the build fails, though other builds have been successful during this time.

Link to failed build:
https://app.shippable.com/runs/5876babaeda6bc0f007f3faf/1/console

**Comment by stephanielingwood** [comment]
Hi @aedades,

Looks like the problem is that the branch name for the job contains parenthesis; removing the parenthesis from the branch name should solve the immediate problem and get your jobs running again. We'll also open a bug internally to escape parenthesis in branch names. 

Thanks for letting us know.

**Comment by aedades** [comment]
Ah ok, thank you for the quick response!
