### ISSUE TITLE
shippable shows "Project sync currently in progress"  and build failure due to normalizeRunYml problem

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#3291]
### Description of your issue:
I had build failure like this:
common|github|normalizeRunYml|callerId:552c7ed05ab6cc1352c30105|projectId:552c7ec75ab6cc1352c300d8|__getYmlString could not fetch run yml file path/sha: .shippable.yml/a1d8098f0cbd23535b667661c00f8f4cd14485b1

and since 1 hour ago, when I go to the CI page, there this message
"Project sync currently in progress" and I didn't do anything. Earlier today, there was nothing wrong, everything seems to work fine

- Link to the build failure:
https://app.shippable.com/runs/587f15646fb9b00f00983307/1/console
- Scripts called from the yml (optional)

-----

Is shippable having issues right now?

**Comment by kanthchandra** [comment]
Hi @osumampouw , I'm looking into this. Will get back to you with my findings.

**Comment by kanthchandra** [comment]
Hi @osumampouw 
> since 1 hour ago, when I go to the CI page, there this message
"Project sync currently in progress" and I didn't do anything. Earlier today, there was nothing wrong, everything seems to work fine

This message is because of a bug at our end where we were not handling the case when the call to github fails. I have fixed this manually for you for now. Next week we will roll out a fix for this. 

> I had build failure like this:
common|github|normalizeRunYml|callerId:552c7ed05ab6cc1352c30105|projectId:552c7ec75ab6cc1352c300d8|__getYmlString could not fetch run yml file path/sha: .shippable.yml/a1d8098f0cbd23535b667661c00f8f4cd14485b1

2. I think github is having some issues today and our call to get the latest yml for your repository failed. Since we couldn't get the required data to generate your build scripts from github we failed the build. We are seeing many such errors on the other projects as well although github status says everything is wroking fine.

**Comment by osumampouw** [comment]
Thanks for your fast reply. 

I tried rebuilding again, and I got this error:
```
(Id: 1005) postRun for :projectId 552c7ec75ab6cc1352c300d8 returned error: POST /runs returned 504
error: projects|triggerNewBuildRequest|projectId:552c7ec75ab6cc1352c300d8|_queueRun```

**Comment by osumampouw** [comment]
the error when rebuilding:
```
common|github|normalizeRunYml|callerId:552c7ed05ab6cc1352c30105|projectId:552c7ec75ab6cc1352c300d8|__getYmlString could not fetch run yml file path/sha: .shippable.yml/a1d8098f0cbd23535b667661c00f8f4cd14485b1
```

https://app.shippable.com/runs/587f15646fb9b00f00983307/1/console

lemme try a dummy commit

**Comment by osumampouw** [comment]
dummy commit also failed
https://app.shippable.com/runs/587f25722dc01310002c7c48/1/console

**Comment by PaulWebbster** [comment]
@kanthchandra We have exactly the same problem here:
https://app.shippable.com/projects/5823ed402bd9170f00a6d2c2/status/
If you can fix this manually we will be nice.

Thanks

**Comment by kanthchandra** [comment]
@PaulWebbster , sorry for the inconvenience. I have reset it manually for you.

**Comment by kanthchandra** [comment]
@osumampouw Yes, if github API calls are erroring out/timing out I'm afraid any build that you try will fail and there is not really anything that we can do without getting the data from github.

**Comment by manishas** [comment]
@kanthchandra can you update the issue when the fix for failed github calls is deployed?

**Comment by kanthchandra** [comment]
@manishas this is fixed. Closing this.
