### ISSUE TITLE
filtered /runs api does not return runs that are in `status 0`

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#3300]
`/runs?projectIds=${id}&branch=${branchName}&limit=1&maxRunNumber=999999`
does not return runs that are in `status 0`

**Comment by a-murphy** [comment]
The default `/runs` sort order is by `startedAt`, which puts the runs with status `0` at the bottom of the list because they haven't started yet.  You can add a different sort order, such as `sortBy=createdAt`, to your query.  I would suggest sorting by `createdAt` or `runNumber` in your case.  The default sort direction is descending, so sorting by `createdAt` or `runNumber` will return the most recently created run or the run with the highest `runNumber`.

**Comment by kanthchandra** [comment]
Hi @BryanCrotaz did the above solution work for you?

**Comment by BryanCrotaz** [comment]
sorting by createdAt solves this.

However it's not restful so it requires a lot of queries every few seconds to get the current set of runs for all our 100+ branches. For example if the latest run id was listed on the branch then I'd know there was no need to send a search for a newer run. Equally if the run is ended then there's no need to query for the run state.

**Comment by avinci** [comment]
I am not sure why this is about restfulness. The issue is we dont store branch level objects and hence extra queries. I do agree that the data modeling is sub-optimal in this case and we should probably do another object called projectBranches which will solve this problem. Definitely something that worth doing as it reduces the number of calls. point taken!

But I disagree on the fact that another object does not exist makes it any less Restful. That being said, we will add this in the next sprint.

**Comment by BryanCrotaz** [comment]
> But I disagree on the fact that another object does not exist makes it any less Restful. 
It's less restful because it's a query - the user is asking a question about runs, not downloading the state of a run.

**Comment by avinci** [comment]
I think you are right. I take back my statement. This will be fixed.

**Comment by BryanCrotaz** [comment]
When you think about branches becoming first class citizens please also consider being able to delete them when the git branch is deleted (what we'd like) or having the option to keep them (as others might desire)

**Comment by BryanCrotaz** [comment]
I think the object should be a single branch not all branches for a project. That gives the option to include all the runs for a single branch when GETting a branch. The project object would then include the ids of the branches. That would make it easy as a user to detect a new branch just by polling the state of the project.

**Comment by avinci** [comment]
yup, will try and make it as simple as possible. But, i dont think we can keep branches that are not on SCM on shippable. this will create various complexities like manual builds etc. The system is designed to stay in sync with SCM from permissions, users, repos and orgs. I will see if this can work but no promises on that.

**Comment by BryanCrotaz** [comment]
... or a new run by polling the state of a branch

**Comment by BryanCrotaz** [comment]
To be clear we don't need you to keep branches on shippable that are not on  scm but you seem to do this today with runs?
