### ISSUE TITLE
app.shippable.com cannot be used without circumventing security warnings

### ISSUE THREAD

**Issue by haf** [Shippable/support#3305]
### Description of your issue:

<img width="1066" alt="screen shot 2017-01-20 at 09 20 27" src="https://cloud.githubusercontent.com/assets/193115/22141357/fa978c3c-def1-11e6-96c7-a4888c9df093.png">

**Comment by kanthchandra** [comment]
Hi @haf , Can you please let us know since when did you start running into this issue? and also the browser and the version.

I'm running chrome and firefox on linux but my browser doesn't say broken https.
![selection_337](https://cloud.githubusercontent.com/assets/1583444/22143294/8d0814d8-df1f-11e6-8bce-322a160e4052.png)

**Comment by haf** [comment]
It's chromium, the newest version of chrome but without the telemetry to google.

**Comment by harryi3t** [comment]
@haf we have fixed this issue. This fix will be available in the next production deployment.

**Comment by harryi3t** [comment]
@haf the fix is live now.
Closing this. Please reopen if you are still facing the issue.

**Comment by haf** [comment]
Works for me now.
