### ISSUE TITLE
new build failure with on docker call: AttributeError: 'module' object has no attribute 'get_config_header'

### ISSUE THREAD

**Issue by TheFarmer1** [Shippable/support#3309]
We're getting a build failure that just started in the last day or two.  Looks like it's related to https://github.com/docker/docker-py/issues/1353  

https://app.shippable.com/runs/58828f88384d1f1000961b78/1/console

**Comment by a-murphy** [comment]
Since a [new version of docker-compose](https://github.com/docker/compose/blob/master/CHANGELOG.md) was recently released, you may want to try specifying the previous version in your `shippable.yml` to see if that helps.  A `pip install` command specifying the previous version would be `pip install docker-compose==1.9.0`.

**Comment by TheFarmer1** [comment]
Thanks!   Docker-compose has acknowledged the problem and will fix it.  Resorting to earlier version works for us for now.
