### ISSUE TITLE
Team member access

### ISSUE THREAD

**Issue by shaned-maplight** [Shippable/support#3315]
After reviewing ticket #2898 , I am still having trouble setting up other colleagues in Shippable.  I have a project setup in Shippable that builds a repo.  Multiple team members have access to that repo in Github.  However, when they login to Shippable with their GitHub credentials, they cannot see my project.  I could not find a link in the docs that described how to add other users to my project.

Can you please help?  

Cheers,
Shane

**Comment by a-murphy** [comment]
If this is a private GitHub repository, the other users may not have enabled private GitHub repositories on Shippable.  Each user must enable access to private repositories in order to see private projects on Shippable.  This may be done by clicking "enable" next to GitHub on the [account settings page](http://docs.shippable.com/navigatingUI/accountSettings/accounts/).  There isn't any way to add users to a project on Shippable, all user access is configured with the source provider (in your case, GitHub).

**Comment by shaned-maplight** [comment]
Thanks @a-murphy , but this is a public repo.

**Comment by a-murphy** [comment]
In that case, do the users have read or write permissions on GitHub?  Or can they access the GitHub repository simply because it's public?

The users will only have permissions on Shippable if they have the same permissions on GitHub.  So, the subscription won't be in their list of subscriptions if they weren't granted at least read access to the repository.  However, if they click a link to a public build or project, they should still be able to see it.

If the repository belongs to an organization, the users should be a part of the organization with at least read permission on the project.  And if the repository belongs to an individual, they should be added as collaborators on GitHub to see the project on Shippable without a link to click.

After changing permissions on GitHub, clicking "sync" on the account settings page will make sure that a user's permissions are updated on Shippable.

**Comment by shaned-maplight** [comment]
The users belong to the repo, and the repo belongs to an org.  The users are also a part of that org.

**Comment by a-murphy** [comment]
In what way do they users belong to the repo?  Were they added individually as collaborators, or as part of a team?

**Comment by shaned-maplight** [comment]
They are not part of a team, but are listed as collaborators with Write access.

**Comment by a-murphy** [comment]
We've tried that setup, and it appears to work.  Could you double-check that these users are in fact listed under "collaborators" on GitHub's repository settings page?  And are listed as "owners" on the GitHub organization people tab?   It may also be worth asking them to click the "sync" button on their Shippable account settings page, just in case.

**Comment by kanthchandra** [comment]
Hi @shaned-maplight can you please give me the following details so that I can check some things at our end and see if there is an issue?

1. Id of the project in question. - You will get this from the url in the projects page.
2. usernames of the your colleagues who are not able to see the projects.

**Comment by avinci** [comment]
@shaned-maplight are you still having issues with this?
