### ISSUE TITLE
Sync repo always fails for the first time

### ISSUE THREAD

**Issue by ykrevnyi** [Shippable/support#3324]
Hi guys,

If you add new Sync repo into the empty project (empty SPOG) - for some reason it fails with strange errors `Failed to postResource ...`.

But if you just rerun that job (click **Run Job** one more time) - the error magically disappears.

- Red build https://app.shippable.com/download/buildJobConsoles?buildJobId=588875e49702340f0001d603
- Green build https://app.shippable.com/download/buildJobConsoles?buildJobId=588876139702340f0001d60f

Thanks

**Comment by manishas** [comment]
@trriplejay we need to look into this.

**Comment by trriplejay** [comment]
@ykrevnyi we're looking into your issues. hopefully we'll have an update for you soon.

**Comment by ric03uec** [comment]
@ykrevnyi we've identified the issue because of which your jobs are failing. This turned out to be a parsing bug for resource and job names
while we push out the fix, you should rename the jobs and resources in your yml to remove all dots (and probably replace them with dashes) which should fix your jobs. we'll keep you posted when the fix is deployed

**Comment by ykrevnyi** [comment]
Great! Will rename titles and get rid of dots then.
Thanks @ric03uec  👍

**Comment by ykrevnyi** [comment]
Just tested and it works.

What I've done:
- changed jobs and resources names
- renamed resource sources (`pointer.sourceName`)

**Comment by rageshkrishna** [comment]
@ykrevnyi This has been fixed. Resources with dots in the name will now be rejected with an appropriate error instead of failing in strange ways.
