### ISSUE TITLE
All tests pass but branch marked as "Unstable"

### ISSUE THREAD

**Issue by staffe** [Shippable/support#3328]
Build: https://app.shippable.com/runs/5889ff1bf35d500f0014e144/1/console

shippable.yml:
language: node_js

env:
  - CI=true COVERAGE=true

node_js:
  - "6.9.1"

build:
  ci:
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - node --version
  - npm config set spin false
  - npm install broccoli-clext
  - npm install bower
  - npm install ember-cli
  - npm install phantomjs-prebuilt
  - export PATH=$PATH:node_modules/.bin
  - npm install
  - bower --allow-root install
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - ember test ci --silent -r xunit > shippable/testresults/result.xml

  cache: true

  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
    - $SHIPPABLE_BUILD_DIR/bower_components

  on_success:

  on_failure:

**Comment by a-murphy** [comment]
In the  project settings, that project has been configured with a "low coverage alert" to mark the build unstable and send a message when the code coverage falls below a certain percentage.  And, the linked build does not have any code coverage.  If you do not intend to have code coverage, you may want to remove the low coverage alert in project settings.  Otherwise, I would suggest setting up [code coverage](http://docs.shippable.com/ci/advancedOptions/testCoverage/) or making sure that the report is in the correct directory.  The code coverage report should be in the `shippable/codecoverage` directory in a cobertura format.

**Comment by manishas** [comment]
@staffe let us know if adjusting the code coverage alert doesn't work for you. Closing this issue since the question has been answered.
