### ISSUE TITLE
Build failure for docker swift. 

### ISSUE THREAD

**Issue by Khalian** [Shippable/support#3348]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure - https://app.shippable.com/runs/588fe13469174c0f000c1be8/summary
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
The error message "failed to obtain yml from provider" means that we couldn't get the `shippable.yml` file from GitHub.  Since the call to GitHub must have somehow failed last time this pull request triggered a build, could you try rebuilding it?  Clicking the "rebuild" button on the linked build should work.  Other options to rebuild a pull request include closing and reopening the pull request and adding a commit to the pull request.
