### ISSUE TITLE
AWS Application Load Balancer Targets

### ISSUE THREAD

**Issue by battlecow** [Shippable/support#3354]
In trying to use an Amazon application load balancer I cannot seem to get it working with defining two (or more) targets.  I have a container that exposes two ports and would like to have it routed via an ALB.  Currently I am just getting the following error when trying to use two targets for deployment: `error creating service InvalidParameterException: load balancers can have at most 1 items.`
My resources look like: 
`  - name: microservice-elb
    type: loadBalancer
    integration: ECS
    pointer:
      sourceName: "ARN:target-1"
      method: application
      clusterName: ecs-test-cluster
      region: "us-east-1"
      
  - name: microservice-mgmt-elb
    type: loadBalancer
    integration: ECS
    pointer:
      sourceName: "ARN:target-2"
      method: application
      clusterName: ecs-test-cluster
      region: "us-east-1"
`

while my jobs have: 
`      - IN: microservice-elb
        applyTo:
          - manifest: microservice-manifest
            image: microservice-img
            port: 80
      - IN: microservice-mgmt-elb
        applyTo:
          - manifest: microservice-manifest
            image: microservice-img
            port: 8888`

I am not sure what I am doing incorrectly here and I cannot seem to get it working from the docs.  Please let me know any information you need to assist me in getting this running correctly.

**Comment by a-murphy** [comment]
Amazon EC2 Container Service (ECS) only allows [one load balancer per service](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_paramters.html).  Each manifest on Shippable creates (or updates) one ECS service so that multiple images can be deployed together, so it's not working with two load balancers.  If you have multiple images in your manifest that you are trying to apply different load balancers to, you may want to try splitting your manifest into two manifests, one for each load balancer.  However, if it's only one image, it looks like you'll be limited to one load balancer; there isn't a way to put the same container in two different services on ECS.

**Comment by battlecow** [comment]
I guess I was trying to figure out if I could use the single ALB but different target groups?

**Comment by a-murphy** [comment]
Unfortunately, it doesn't look like multiple target groups in a service is an option either.  AWS mentions that limitation [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html#load-balancing-concepts).  And suggests using a classic load balancer [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-load-balancer.html).

**Comment by abhijitkini** [comment]
closing as resolved. Let us know if you have additional questions.
