### ISSUE TITLE
Permission for process to write a file when in ci

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3365]
Hello,

I'm sure there is a best practise for this, but I would need to run the following:

  ci:
    - "sudo python enterlot/manage.py test"
    - "sudo python enterlot/manage.py check --deploy"

and part of my settings setup requires writing to a file and reading from it, but this does not seem to happen in shippable (works both locally and in aws).

Fails here:
https://app.shippable.com/runs/58a33ba8b195740f00e18066/1/console

So, how should I do it?

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
There shouldn't be any reason that you couldn't create a file in Shippable.  Have you checked if your setup expects the file to already exist?  It's not unusual for things to work locally but not on Shippable because of files that were never committed to the repository.  And, would you mind mentioning where you expect the file to be created?  It's not very clear from your logs.

**Comment by mikkopori** [comment]
You are correct, I had a simple path-issue. Thank you for pointing that out!
