### ISSUE TITLE
Django unitetsts with testclient failing on all post -requests

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3370]
Hello,

https://app.shippable.com/runs/58a4c3adb195740f00e2632d/1/console

for some strange reason django testclient fails in all post requests inside shibbale, as the forms are never sent.

Any idea what might be causing this?

Mikko 

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
I can't be sure why it's failing, but a common reason would be if the request is made to the wrong address or whatever should be processing the requests isn't running.

Since your tests are running in a Dockerfile, it might be relevant that each step runs in a different container.  If you're starting a service in one step, it's unlikely to be running in the next.  However, I don't see any obvious service start commands in the earlier steps in your logs.  

Do your tests pass when you build the Dockerfile locally?  And where are these post requests sent?

**Comment by mikkopori** [comment]
This is also failing locally in a container so is not a shippable-issue, as you guessed. I'll keep on investigating and will close this one now.

Thank you!
