### ISSUE TITLE
Build Failure While Zipping

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3373]
https://app.shippable.com/runs/58a4eeba031d631000be27b6/1/console

We attempted to zip up our node module and it appears to fail. I pulled down the drydock/u14nod:prod image used to execute the build and attempted the build locally and everything succeeds. We are at a loss as to why it would fail when running via shippable.

**Comment by herriojr** [comment]
I'm guessing this is some kind of memory issue. I'm going to run a few more tests at this point.

**Comment by herriojr** [comment]
I even attempted on a shippable provisioned node instead of our own nodes and the same thing happens:

https://app.shippable.com/runs/58a5ec9a031d631000bec754/1/console

**Comment by herriojr** [comment]
Interestingly, if I do:

zip -r -y myzip.zip ./* || true

It still fails, which to me says the container is crashing out since the exit status should be wiped by the || true

**Comment by trriplejay** [comment]
Just a hunch: could you try adding a `-q` flag to your zip command? I'm wondering if the speed at which it dumps logs is causing trouble with our build runner.

**Comment by herriojr** [comment]
Yup, that fixed it.  Can I ask why that is an issue?

**Comment by trriplejay** [comment]
It's something we've only seen happen a few times, under certain conditions, and we're still investigating the root cause, but it seems to have something to do with the way we capture the build logs.  Some shell commands spit lots of lines very quickly. In your case, zip can log several hundred files almost instantly, and our agent seems to have trouble keeping up.

The other case where we saw this happen was with an `npm install` that had an unusually large dependency tree that got printed suddenly at the end of the installation.

However, it doesn't *always* seem to happen like that.. in some cases, I can `cat` an entire novel with no problem... as I said, we're still investigating. Hopefully we'll have this resolved soon and you won't have cause for concern.

**Comment by avinci** [comment]
@herriojr the main problem we were having was that there were runaway queries that were not exciting in the right way. This was causing memory leaks on API and causing it to become unresponsive. This further exacerbated the problem with builds not being able to post console logs. This was the core problem. 

We have resolved the issue and please let us know if it happens again.
