### ISSUE TITLE
postgres database does not start after upgrade

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#3380]
When I pull your build image at my local machine: 
`
 docker run -it drydock/u14all:prod /bin/bash    
`

and execute this command 
`
sudo -u postgres /usr/lib/postgresql/9.4/bin/postgres -c config_file=/etc/postgresql/9.4/main/postgresql.conf
`

_postgres is started without any problem_

If I repeat these steps on our custom shippable build nodes, postgres cannot be started because 
`
could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key 
`

this seems to be related to [this issue](https://github.com/nimiq/docker-postgresql93/issues/2)

For now I got my build working by adding this dirty hack to my shippable.yml
`
mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private
`
This was working fine until Friday afternoon. 

Can you explain this?

**Comment by a-murphy** [comment]
Would you mind including either a link to a build that failed with this error or your `shippable.yml`?  I haven't been able to reproduce this error and the exact steps in your build may help.  It sounds like the key file might be missing from the error, but it's definitely in the image you mentioned.

**Comment by rvdwijngaard** [comment]
[the failed build](https://app.shippable.com/runs/58aacf55044ca00f00ebd9d0/1/console)

**Comment by a-murphy** [comment]
I still haven't been able to get any errors related to keys.  What exactly were the steps you followed to get the error above?  I didn't see that message in your logs, just one that I assume is from your script.

Since you're using a custom image, I'm assuming that `drydock/u14all:prod` is the base image for that image.  Could you make sure that your image was built from the latest `drydock/u14all:prod` by pulling the base image before building your image?  An old version of the base image could explain why you are getting different results.  And, are there any Postgres-related changes in your Dockerfile?  

Finally, have you tried running your commands locally on your own image, like you said worked with `drydock/u14all:prod`, and did they work?
