### ISSUE TITLE
Builds failing in the "Initializing Job" phase (404 while getting node)

### ISSUE THREAD

**Issue by AndreCimander** [Shippable/support#3385]
### Description of your issue:
Most of our automatic builds are failing in the "Initiliazing Job"-phase while getting the node:
Getting node 0s  
404

Manually issuing a rebuild works as expected. Any idea what might be the cause? 

Example build:
https://app.shippable.com/runs/58ad90a2ef3f430f00430b16/1/console

**Comment by a-murphy** [comment]
It looks like this was the result of an account with access to your project not having permission on the subscription on Shippable, most likely because the project had been moved between subscriptions and the account had not been synchronized.  We've updated your project to use your account for webhooks so this should no longer be a problem.
