### ISSUE TITLE
Bitbucket (private) - pull request builds fail on integration settings, succeed on merge

### ISSUE THREAD

**Issue by tzar** [Shippable/support#3427]
### Description of your issue:

Every build of a pull request done on our bitbucket private repo fails with a message like:

> Integration name specified in yml does not match integrations present in Subscription settings

In this case, a slack integration. It also updates the status on the pull request to "failed". However, once the pull request is merged, it then builds correctly.

[Example failed build](https://app.shippable.com/runs/58bf0bf5edea84050031853e/1/console) - note that this build has been made on a fork, the integration is configured on the repo it is PRd to which is where it should be built.

However, I have also noticed that it is also building against the branch it is PRd to. So lets say I did a PR from foo/bar to bar/bar and bar/bar is the one with the shippable account and integrations configured. I would now have a failed build under foo/bar which shows up on the PR status, and a successful build of bar/bar which does not.

Requiring every fork to go to shippable and set up an account/plan and identical integration seems untenable as a solution, so this seems like a bug?

**Comment by a-murphy** [comment]
In most cases, everyone opens their pull requests to one repository, and only that repository is enabled on Shippable.  Then builds run for both pull requests and commits in that enabled project.  If you want to run builds on the forks without opening a pull request, then you will need to set up the integrations under each subscription (which will also allow you to use different values in different subscriptions).  However, would you mind letting us know why you are building the forks instead of using the pull request builds?  The pull request builds will more accurately reflect the state of the repository after it's merged.

Do you have a link to one of the successful builds mentioned above?  There might be something in your project configuration affecting pull request builds.

**Comment by tzar** [comment]
Hi, that is an accurate description of our setup - everyone opens their pull requests to one repository, and only that repository is enabled on shippable. We don't want to run builds on the forks, but they're running anyway.

[Here is a build from an un-merged PR appearing on master](https://app.shippable.com/runs/58bf9a95c2fe010500982ea8/1/console) - there is a failed test on there, but it built properly

**Comment by a-murphy** [comment]
The forks won't build unless someone enabled them on Shippable.  Not enabling them (and disabling the existing one(s) by clicking the [delete button](http://docs.shippable.com/navigatingUI/projects/settings/#deleting-the-project) on those projects) is the easiest solution.  And if you want the forks enabled for some reason, but don't want them to build automatically, you can turn off the webhook builds on the forks by clicking "disable" for each webhook type on the [project settings pages](http://docs.shippable.com/navigatingUI/projects/settings/#configure-webhook-events-for-triggering-builds).

And the reason you're seeing the failed result on the pull request on Bitbucket is because it's displaying the status by commit SHA, and both builds are for the same SHA.  There's not much that we can do about that.  Disabling the failing fork will avoid this.

**Comment by tzar** [comment]
Hmm, I guess they must have thought that it was necessary to enable the project when they first clicked through to a shippable build - I'll let them know to remove the config, hopefully that'll do it. Thanks for your help.
