### ISSUE TITLE
Skipped: You do not have minions to run this job

### ISSUE THREAD

**Issue by romani** [Shippable/support#3428]
### Description of issue:
```
Job skipped 0s
  Info  
     You do not have minions to run this job. Please contact Shippable if you think this is a mistake.
```

I did not found what this mean.
We recently got a lot of PR (spike of changes to our repo from outside), so it might be related.

- Link to the build failure: https://app.shippable.com/runs/58c0a296c2fe010500992603/1/console

**Comment by avinci** [comment]
@romani we have monitors that automatically shut you off if we see builds constantly firing. The minion on your sub was for 24 hrs and our auto shut off trigger mechanism caused this. I have updated the setting and you should see builds processing again. Let me know if you see any issues. 

This exists due to various bitcoin miners abusing the system.
