### ISSUE TITLE
How Do I Point to Current PHP Binary?

### ISSUE THREAD

**Issue by krispy1298** [Shippable/support#3429]
Looking to run a command like `export PATH=${SHIPPABLE_PHP_BINARY}:$PATH` for a [wordpress  build](https://make.wordpress.org/cli/handbook/plugin-unit-tests/) before executing phpunit.

How would I point to the current PHP binary location?

**Comment by rageshkrishna** [comment]
`export PATH=$(which php):$PATH` should do it. Does that solve your problem?

**Comment by krispy1298** [comment]
Thank you. While the command worked, my phpunit command is still not executing because of a "cannot connect to database" issue.

**Comment by rageshkrishna** [comment]
OK, can you send me your project id so I can take a look at what's going on?

**Comment by krispy1298** [comment]
`58b5ecf1ddd8e8070045e595`

**Comment by rageshkrishna** [comment]
Your tests seem to be failing with `require_once(/tmp/wordpress-tests-lib/includes/functions.php): failed to open stream`. I don't see any database connection errors in the latest builds, and the mysql command you're running as the first step in your `ci` section seems to run without any complaints.

I'm not really sure why it's looking for `/tmp/wordpress-tests-lib/includes/functions.php`, though. That `require` seems to be coming from one of your test scripts.

**Comment by krispy1298** [comment]
Sorry, I was playing around with the script. Please check out build 68 / build_ci.

**Comment by rageshkrishna** [comment]
The database is definitely working and accepting connections because the mysqladmin command that runs to create your test database is definitely working with the credentials you've set. My guess is that there is something about the way the tests are reading the credentials that is not working, but I don't really know anything about the Wordpress unit test plugins to know where to start looking.

I'll see if I can find something more, but I think we can at least rule out that the connectivity error is because of a mysql issue.

**Comment by krispy1298** [comment]
Locally, in order for this to work, I needed to do the following:
```
PHP_VERSION=$(ls /Applications/MAMP/bin/php/ | sort -n | tail -1)
export PATH=/Applications/MAMP/bin/php/${PHP_VERSION}/bin:$PATH
```
