### ISSUE TITLE
Sharing the build directory with a docker container fails

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#3438]
I'm trying to use a container to build python wheels.

Locally I run it like this: `docker run --rm -v $(pwd):/io <repo>/wheelbuilder` and it works just fine.
It works by taking the requirements.txt file in the repo and build wheels from them, which is stored in /io/wheelhouse. When trying this on shippable I'm told that requirements.txt is not found. I've tried with ${SHIPPABLE_BUILD_DIR} as a replacement for $(pwd) as well to no avail.

As is evident from the build logs, requirements.txt is really there. So what am I missing?

My failing build is here: https://app.shippable.com/bitbucket/uberresearch/np_service/runs/17/1/console

Perhaps this is not possible due to already running in a container?

**Comment by rageshkrishna** [comment]
@sdlarsen You are correct, this is a side-effect of the build already running inside a container. There is a way to get around this, but you will unfortunately need to copy your files around to make it work

In your `pre_ci_boot`, you can pass options to the docker command that spins up your build container:

````
pre_ci_boot:
  image_name: something
  tag_name: something
  options: "-v /tmp/shared:/tmp/shared"
````

This will get `/tmp/shared` on the host to be mounted in to your CI container. Now, before your `docker run`, copy what you need to `/tmp/shared` and then mount `/tmp/shared` instead of `$(pwd)`. This will actually mount `/tmp/shared` from the host in to your new container.

I hope this helps.

**Comment by sdlarsen** [comment]
@rageshkrishna It did, thanks!
