### ISSUE TITLE
Using drydock/u16nodall can be /very/ slow

### ISSUE THREAD

**Issue by Nicholaiii** [Shippable/support#3449]
boot_container takes 0-3 seconds when using drydock/u14nodall (read: when not defining an image)
When setting drydock/u16nodall in the configuration it can take up to more than 30 minutes to boot the image.
I don't know if I'm doing it wrong or it really is unreasonably slow.

**Comment by niranjan92** [comment]
@Nicholaiii  we have opened an internal bug to fix this, will keep you about the status of the same.

**Comment by rageshkrishna** [comment]
u16nodall is available locally if you use the v5.3.2 machine image. Please go to your subscription's settings tab and select it from the "Machine Images" dropdown.

**Comment by Nicholaiii** [comment]
Thank you for the speedy response.
I tried it out, first it failed, then i used the image_tag v5.3.2  and it worked beautifully, but I /do/ get this error (on the sudo docker etc command):
`sudo: unable to resolve host ip-172-31-9-192
4c64326180746a201bb819a9b914cd6c0eb13d8c965f2a1af0d54be10cf9b12a`

That I figured I might just report right away :)

**Comment by rageshkrishna** [comment]
That message is because /etc/hosts doesn't contain an entry for the hostname of the system. Unfortunately, that's how new machines on EC2 are configured out of the box. It's not really an error, but just an indication from sudo to let you know that it may not be able to apply all of the rules in your sudoers file, especially the ones that rely on hostnames.

You can safely ignore the error.

On the other hand, you don't _really_ need sudo to do things in the CI container because your scripts are running as `root` anyway. You should be able to get away without using sudo at all.

**Comment by Nicholaiii** [comment]
Yes, I was assuming root since npm i -g works out of the box sans-sudo. :) Okay, it's safe to close this thread now. Thank you once again!
