### ISSUE TITLE
Builds fail for no apparent reason on npm install. 

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3450]
Related to #3284 

Now 100% of my builds fail upon `npm install` with no error message or exit code at all. It looks like npm install succeeds, but the build just exits for no apparent reason. 

Here are two examples, but basically everything since Friday fails : 

https://app.shippable.com/github/ExecThread/ExecThread/runs/3201/1/console
https://app.shippable.com/github/ExecThread/ExecThread/runs/3200/1/console

This is 100% reproducible now, I hope that we can act on this faster than the response we got on #3284 now that this is no longer random but 100% of the time. 

The most concerning part is that there is no error indication whatsoever - it just exits.

What can I do to troubleshoot this? You guys mentioned some time back that you were going to allow ssh access to the instances running the builds, has this come to fruition?

**Comment by manishas** [comment]
@a-murphy can you look into this?

**Comment by npahucki** [comment]
Here are some diagnostics I added before and after the `npm install`. In this example, it happened to complete the `npm install`:
```
  ulimit -a 1s  
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 14972
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 524288
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

  lsof | wc -l 0s  
105

  ls -1d /proc/*/task/* | wc -l 0s  
14

  free -m 0s  
             total       used       free     shared    buffers     cached
Mem:          3763       2679       1083          0        118       2195
-/+ buffers/cache:        365       3398
Swap:            0          0          0

  npm install --quiet 1m 45s  

  lsof | wc -l 0s  
99

  ls -1d /proc/*/task/* | wc -l 0s  
13

  free -m 0s  
             total       used       free     shared    buffers     cached
Mem:          3763       2420       1342          1        135       1748
-/+ buffers/cache:        537       3226
Swap:            0          0          0

```

Of course when `npm install` is running, I'm sure it's a different picture.

**Comment by a-murphy** [comment]
Since it may be that this is related to the previous problem with console logs when there is suddenly a lot of output, could you try redirecting the `npm install` tree to `/dev/null`? `npm install --quiet >> /dev/null` should redirect standard out and not print the tree.  Unfortunately, there is no `npm` flag that will not print that tree.  If the builds once again continue past `npm install` without the tree, then it will narrow down the search.

Have you changed your base image recently?  I noticed that it's a custom image, so I'm wondering if anything in that could have changed as well.  And, you you mind letting us know what it's based on?  We've been testing with Ubuntu-based images because that what all of the official images are.

I don't see anything obvious in the diagnostics.  We asked for those for the previous error because it was continuing past the `npm install` and reaching one of these limits is known to cause similar errors.  Unless you have a lot of strange processes running in the background just during `npm install`, I doubt that these limits will be the problem here.

**Comment by a-murphy** [comment]
And, which version of `npm` are you using?  I couldn't find it in your logs.

**Comment by npahucki** [comment]
It's node 6.2, so I think it's npm 3.8.9

**Comment by stephanielingwood** [comment]
Hi @npahucki,

Thanks for sharing your npm version. That helps. Let us know when you get a chance to redirect the output of the npm install to /dev/null - that'll go a long way towards our debugging. Basically, it'll help us confirm or eliminate our logging buffer as a potential source of the problem. Looks like you've been able to get some builds past the npm install, though, so that's (somewhat) promising.

**Comment by npahucki** [comment]
Here is an interesting one that dies shortly after npm install, mid way into the output of ulimit. 

https://app.shippable.com/github/ExecThread/ExecThread/runs/3224/1/console

**Comment by npahucki** [comment]
So doing the redirection seems to have worked around it (well, at least wth sample set equals 1). I'll try a few more builds like that.

**Comment by npahucki** [comment]
K, we are 5 of 5 good ones since redirecting to /dev/null, so I think we can say that your hunch is correct.

**Comment by a-murphy** [comment]
Great.  Then we have a pretty good theory about what's causing a console buffer problem.  We'll let you know when we think we have that fixed.

**Comment by evanbrumley** [comment]
Just for added data, we also recently experienced a consistent build failure while running a large django collectstatic command (approx. 1100 lines of output in a few seconds). As reported on this ticket, it looked like the task was just cut off, with no error code raised, and turning off console output allowed the command to complete successfully.

Oddly enough, on one run of the command we did get an actual python exception:

`BlockingIOError: [Errno 35] write could not complete without blocking`

Googling this exception showed a couple of issues on other projects around buffering of console output, which led us to the workaround.

**Comment by stephanielingwood** [comment]
@evanbrumley Thanks for letting us know about your build. If you could share a couple links where the failure happened, we'd appreciate it.

@npahucki so you have an end-of-week update on this: we have made a change to our processing of console logs and will likely have it in production sometime next week. We're also still looking into other possible causes.

**Comment by npahucki** [comment]
Thank you. I'm just happy we found a work around that let's the builds pass!

**Comment by evanbrumley** [comment]
@stephanielingwood Here's a good clean example:

https://app.shippable.com/bitbucket/wspdigital/myro-control-centre/runs/141/1/console

Look for the cutoff in `build_ci -> ./manage.py collectstatic --noinput`

We also noticed this happened when the command was run as part of a larger script, for instance in this:

https://app.shippable.com/bitbucket/wspdigital/myro-control-centre/runs/136/1/console

The cutoff happens in `build_ci -> ./run_tests --unittest --harvest --for-shippable`, though it's harder to see there because our test script kept running after the collectstatic failed.

Finally, the exception we caught was in this run:

https://app.shippable.com/bitbucket/wspdigital/myro-control-centre/runs/139/1/console

Search for BlockingIOError in `build_ci -> ./run_tests --unittest --harvest --for-shippable` and you'll find the spot.

Hope that helps with your debugging :-)

**Comment by manishas** [comment]
Closing this since it's a stale issue. If anyone is still running into this, please let us know.
