### ISSUE TITLE
Builds failing on MySQL (ERROR 1133 (42000) at line 1: Can't find any matching row in the user table)

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3459]
Builds are suddenly failing on MySQL suddenly. Cannot create the shippable user as specified in the docs.

```
mysql -e "GRANT ALL ON *.* TO shippable@localhost IDENTIFIED BY ''; FLUSH PRIVILEGES;"
ERROR 1133 (42000) at line 1: Can't find any matching row in the user table
```
Image: `drydock/u16phpall:v5.3.2`
[Link to the build](https://app.shippable.com/bitbucket/swisnl/lismanflow/runs/280/1/console)

We have tried using different users, flushing before the command etc. Any idea whythis is happening?

**Comment by bbrala** [comment]
(ping @barryvanveen)

**Comment by niranjan92** [comment]
Hi Bjorn, we are looking into and we'll keep you informed.

**Comment by bbrala** [comment]
Any progress on this issue?

**Comment by rageshkrishna** [comment]
@bbrala Sorry for the delay in getting back to you on this. I took a look at what is going on here, and it turns out that MySQL behaviour around GRANT has changed in 5.7.7+. As documented at https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_auto_create_user, `GRANT` will no longer automatically create a user for you.

I shall update our documentation to reflect this change. In the mean time, please use the following command instead that will create the user first:

````
mysql -e "CREATE USER shippable@localhost IDENTIFIED BY ''; GRANT ALL ON *.* TO shippable@localhost; FLUSH PRIVILEGES;"
````

I hope this helps.

**Comment by barryvanveen** [comment]
Thank you  @rageshkrishna, I can confirm that this solves the issue.

**Comment by manishas** [comment]
@chetantarale can we add this to the docs page for MySQL?

**Comment by rageshkrishna** [comment]
Docs have been updated to include the updated command. http://docs.shippable.com/ci/services/mySQL/
