### ISSUE TITLE
Five of Seven Nodes Stopped - Foreign Key Constraint Violated when Removing

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3463]
Five of our seven build nodes are reported as "stopped" in the dashboard. There is no indication as to why this is, but they're not processing builds. When I attempted to remove one so I can add a new node I got this:
![2017-03-24-104122_1498x111_scrot](https://cloud.githubusercontent.com/assets/465340/24306692/aef5c3c0-107e-11e7-811c-7e4720c4fae8.png)

Halp?

**Comment by stephanielingwood** [comment]
Hi @BlueDragonX, 

We'll take a look. Can you please send us a link to your subscription?

**Comment by BlueDragonX** [comment]
Subscription? What does that mean?

I was able to get them removed. I'm replacing all of my nodes now.

**Comment by stephanielingwood** [comment]
Good. Glad you were able to get them removed. 

FWIW, your "subscription" translates to your organization or user name on your source provider. It's what you see in this view:

![subscription](https://cloud.githubusercontent.com/assets/7757711/24306919/7ea49c9a-107f-11e7-945c-461fa6a5653f.png)

So here, my subscription is stephanielingwood. 

As to why your nodes stopped...when we see nodes just stop, often it's because they ran out of space. Might be worth taking a look at that.

**Comment by BlueDragonX** [comment]
Aha, I think I see what you've done. Your initialization scripts have changed significantly since we've deployed these nodes. To make matters worse, your init scripts are node specific now. This means we can no longer use an autoscaling group to automatically deploy and/or replace nodes. This is brutal and unhelpful. Given our scale this _must_ be automatic. The whole point of CI/CD is to avoid manual process - but your product is forcing manual process on our team.

I voiced a similar concern previously: https://github.com/Shippable/support/issues/2888

Theoretically there should be docs which cover this API but I don't see them.

**Comment by BlueDragonX** [comment]
Our subscription is "zenreach" then.

**Comment by stephanielingwood** [comment]
Hmmm. That's interesting. The node initialization scripts have always been node-specific. Now, that's not to say you couldn't run a script for one node on others....that probably would have worked, albeit perhaps not correctly. But maybe it worked enough that you never noticed the difference.

Which brings us to your point about the API and managing your nodes via autoscaling: that makes sense. I read through the issue that you linked - if we've got the problem (above) sorted out, would you be okay closing this issue so we can track the conversation regarding the API in the original support issue (https://github.com/Shippable/support/issues/2888)?

**Comment by ttrahan** [comment]
@BlueDragonX : sorry for the confusion here. We have updated the init scripts and APIs, but you can certainly fully automate this. We'll get the steps documented and posted here this afternoon. Stay tuned.

**Comment by BlueDragonX** [comment]
That's all well and good, but it still doesn't address the error messages I received in the UI as a result of attempting to replace nodes. It's going to be hard to automate this if the API is receiving these errors. I suppose I can just have it retry a handful of times, but I'm not sure you'd appreciate the additional API load. It doesn't help that the UI is rather slow.

**Comment by ttrahan** [comment]
@BlueDragonX : I suspect the error you're seeing may be a result of running the same init script on multiple nodes, but we're going to look further into that. Most functionality does not consider the "nodeId" value, but deleting the nodes does use that value. When initializing multiple nodes with the same script, you'll have duplicate nodeId's, which may cause complications. Please let us know if you see this occur again.

Here's the instructions you should follow for automating your node initialization:
1. Provision your node and SSH into it
2. POST to https://api.shippable.com/clusterNodes with the following body in order to register the custom node with Shippable and retrieve necessary metadata:
```
{
  "subscriptionId": "12345678901234567890abcd",
  "friendlyName": "My node",
  "location": "0.0.0.0",
  "nodeInitScript": "ubu_14.04_docker_1.11.sh",
  "initializeSwap": false,
  "nodeTypeCode": 7000,
  "isShippableInitialized": false
}
```
3. GET from https://api.shippable.com/clusterNodes/{yourClusterNodeID}/initScript in order to download the initialization script for that node from Shippable.
4. Make the downloaded script executable
5. Run the script on the node.

Here's an initialization script I tested on a newly provisioned Ubuntu node. The script takes four parameters (I haven't automated retrieving the IP address of the node, but you'll want to do that). 

To execute the script on the node:
```
. ./initShippableNode.sh YOUR_API_TOKEN YOUR_SUBSCRIPTION_ID FRIENDLY_NAME_FOR_NODE IP_ADDRESS_FOR_NODE
```

initShippableNode.sh
```sh
#! /bin/bash -e

API_TOKEN=$1
SUBSCRIPTION_ID=$2
FRIENDLY_NAME=$3
IP_ADDRESS=$4

# register the new node with Shippable via POST route
export RESPONSE=$(curl --request POST \
  --url https://api.shippable.com/clusterNodes \
  --header "authorization: apiToken $API_TOKEN" \
  --header "cache-control: no-cache" \
  --header "content-type: application/json" \
  --data "{\"subscriptionId\": \"$SUBSCRIPTION_ID\",\"friendlyName\": \"$FRIENDLY_NAME\",\"location\": \"$IP_ADDRESS\",\"nodeInitScript\": \"ubu_16.04_docker_1.13.sh\",\"initializeSwap\": false,\"nodeTypeCode\": 7000,\"isShippableInitialized\": false}")

# install jq to parse the response
sudo apt-get install jq

# extract the cluster node id from the response
CLUSTER_NODE_ID=$(echo $RESPONSE | jq -r '.id')

# download the initialization script from Shippable for this node
curl -o ./shipInit.sh --request GET https://api.shippable.com/clusterNodes/$CLUSTER_NODE_ID/initScript \
  --header "authorization: apiToken $API_TOKEN" \
  --header "cache-control: no-cache" \
  --header "content-type: application/json"

# make the init script executable
sudo chmod +x shipInit.sh

# run the init script
sudo . ./shipInit.sh
```

To retrieve your SubscriptionID, you can run a GET against:  
https://api.shippable.com/subscriptions/:subscriptionId

Find the "id" for the appropriate "orgName", this is your SubscriptionID to use above (do not use the value for "subscriptionId"):
```
  {
    ...
    "id": "54934d03d46935d5fbc099ed",
    ...
    "orgName": "ttrahan",
    ...
  }
```

Note that the above isn't a formally supported solution for this. We will be formally documenting these APIs soon and looking at ways to make this easier to manage. We'll let you know when those are available and if any changes are introduced.

**Comment by ankul-shippable** [comment]
@BlueDragonX we have added the docs for clusterNodes. You can check them [here](http://docs.shippable.com/api/docs/#/ClusterNodes). 
We have also created a [nodejs project](https://github.com/shippableSamples/provision-custom-nodes) to provision custom nodes. You can follow the instructions in README.md.
Please let us know if you have any issues/doubts. Thanks
