### ISSUE TITLE
How to use files not in version control that are necessary for deployment

### ISSUE THREAD

**Issue by aergener** [Shippable/support#3472]
Hi,

I have a `.ebextensions` folder that is necessary for deploying my application to ElasticBeanstalk. This folder is NOT included in version control. Furthermore, I cannot include it in version control because it contains sensitive information, things like database passwords and other important credentials. I use the files in `.ebextensions` to create environment variables with these values, so it is crucial for deployment.

Is there a pattern for dealing with this? Is there a way to store this somewhere that shippable can access at deploy time?

I have read through the continuous deployment tutorials involving ElasticBeanstalk, but have not seen any mention of this issue.

Thanks!

**Comment by trriplejay** [comment]
There are a couple things you could try.

1. Shippable supports secure encrypted environment variables as documented [here](http://docs.shippable.com/ci/advancedOptions/environmentVariables/#secure-variables).  This would allow you to add the necessary key/value pairs to your yml in source control without exposing the values, at which point you could recreate your ebextensions files during CI step, so that the deploy step would pick it up.  The downside is that this might not be realistic if you have a lot of key/value pairs, and you'd have to change the encrypted var in the yml whenever something changed. Also you'd have to manually reconstruct the folder via bash script...
2. store the .ebextensions folder in a private s3 bucket, and pull it down during CI.  The awscli should already be configured with your credentials during CI because of the EB integration, so you should just have to add a line for the s3 command.  Downside is that you'd have to maintain an up-to-date copy in s3 in addition to wherever you're keeping it now.

Let me know if you have other questions!

**Comment by aergener** [comment]
Option 2 actually works quite well for my use case. Thanks for the advice!
