### ISSUE TITLE
build_pre_ci doesn't stop with exit code 1

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#3477]
https://app.shippable.com/github/luckyraul/docker-php/runs/128/2/console

**Comment by ambarish2012** [comment]
The command docker build --image-name mygento/php:$PHP_TAG, which is executed by puppet, returned a non zero exit code to puppet. 

However, Shippable is capturing the return code of the `puppet docker build...` command, which appears to be 0, since puppet is most likely swallowing the non zero return code. 

To address this issue, you will have to run puppet in a manner that it bubbles up the error to Shippable.
