### ISSUE TITLE
Builds for golang failing

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#3493]
Our builds for golang application are failing. This what I see in the logs
```
gvm install go1.7.5 --prefer-binary 17s  
Installing go1.7.5 from binary source
ERROR: Failed to download binary go from http://golang.org. Trying https://go.googlecode.com
ERROR: Failed to download binary go
```

**Comment by ambarish2012** [comment]
Please can you send a link to your console.

**Comment by phagunbaya** [comment]
@ambarish2012 https://app.shippable.com/github/Falkonry/falkonryagent/runs/17/1/console

**Comment by phagunbaya** [comment]
Even this build is stuck https://app.shippable.com/github/Falkonry/falkonryagent/runs/18/1/console

**Comment by ambarish2012** [comment]
Thanks, we are investigating.

**Comment by ambarish2012** [comment]
1) I suggest you upgrade to the latest version of the u14golall image, which has the version of golang already preinstalled.

To do so, add the following to your shippable.yml file:

build:
  pre_ci_boot:
    image_name: drydock/u14golall
    image_tag: v5.4.1
    pull: true

2) I would also recommend that you change the machine image in your subscription settings to v5.4.1. You are currently using stable. This will avoid pulling the docker image every time. If you change this setting, you will not need to add a pre_ci_boot section in your yml file (assuming you don't have this section specified in your yml file already).

3) We think the problem you are facing is some temporary glitch, since your build ran in the morning successfully with the same version of go. We did not change anything since your last successful build in the morning.

**Comment by phagunbaya** [comment]
I set the image to v5.4.1 but still it's failing https://app.shippable.com/github/Falkonry/falkonryagent/runs/24/1/console

**Comment by a-murphy** [comment]
The v5.4.1 images have Go 1.7.5 installed, not Go 1.8.  You may want to switch back to 1.7.5 until the error installing new versions of Go is resolved.

**Comment by phagunbaya** [comment]
@a-murphy That works. Thanks !

**Comment by avinci** [comment]
closing this as it seems to have been resolved.
