### ISSUE TITLE
Looking to spin down an AWS EC2 instance after canceling a build

### ISSUE THREAD

**Issue by pavanbelagatti** [Shippable/support#3507]
### Description of your issue:
The customer is looking to spin down an AWS EC2 instance after canceling a build and how do they do this without an on_cancel.

- https://twitter.com/SamBantner/status/851496561909608448

**Comment by BinaryBeard** [comment]
Our use case is super weird/unique because of the low level linux utils we require during the build. We're using a default Shippable docker to kick off and ssh in to an EC2 image (this better supports our need for super low level block device mapping). This entire process takes a bit of time, and sometimes we have four to ten builds going. Priorities change on a momentary basis here and we need to cancel builds to spin up new ones. 

The problem we have happens when we try to cancel this build. When we cancel the build, we instantly free up another minion to do our bidding which is absolutely awesome! The rub is that it doesn't inform our EC2 that it has been cancelled. This leaves us with an orphan EC2 consuming our available resources. So far, it looks like no additional hooks are fired when a build is cancelled, it just stops dead in it's tracks. We were looking in to the **on_failure** hook, but it never gets fired. (We are assuming that cancelling a build has a non-zero exit code).

The interesting thing is that when we cancel the build, we get an email notification. We're hoping this is a super easy feature to implement because of the aforementioned notification that is being processed by some internal system. 

I hope this provides a little bit more guidance for the specifics of this feature request. :)

**Comment by manishas** [comment]
I am consolidating all related requests, so closing this in favor of https://github.com/Shippable/support/issues/3017

Please track that issue for updates on on_cancel or always sections for CI.
