### ISSUE TITLE
PR build status does not show on GitHub PR page

### ISSUE THREAD

**Issue by manishas** [Shippable/support#3514]
### Description of your issue:

The status for [this PR build](https://app.shippable.com/github/pypyr/pypyr-cli/runs/4/1/console) is not showing up on the [PR page on GitHub](https://github.com/pypyr/pypyr-cli/pull/7)

**Comment by 345thomas** [comment]
Found it. Shippable didn't have access granted to org for user account under https://github.com/settings/connections/applications/

This wasn't set-up, I guess, because it looks like once you've added your github account to shippable, you can't just add other organizations after the 1st setup, you have to disable "Third-party application access policy" protection first. You can then add the the new org + repos to shippable, but it looks like shippable still doesn't take you through the OAuth process of requesting scope to the new organization -  it just adds the webhooks.
