### ISSUE TITLE
Easy way to remove broken resources?

### ISSUE THREAD

**Issue by Jsgoller1** [Shippable/support#3522]
### Description of your issue
We just finished removing a ton of our legacy pipelines and replacing them with our new pipelines that we're currently using. As a result, our SPOG is littered with broken resources: 
![broken_resources_spog](https://cloud.githubusercontent.com/assets/1567977/25105097/1e7ebd12-2378-11e7-94cf-2dec5c353cd1.png)

We want to remove these resources so that our build environment isn't confusing to work with for our developers. The SPOG is impossibly slow to work with for this task, as right clicking any of these resources to delete them routinely pegs my CPU (whichever core is running the browser thread) at 100%
and causes the whole UI to hang (this is the case for every machine I've done this with, including my gaming machine at home, which has a Broadwell Core-i7 CPU and 32GB of RAM). Is there any easier way to delete these broken resources, or am I going to have to go through every single one and click to delete them (assuming they are even delete-able, which most aren't, given the dependency hierarchy and the fact that you can't delete resources that have dependencies)?

**Comment by ambarish2012** [comment]
@Jsgoller1 there is a way to get rid of your soft deleted resources using API and a while loop. Give me a few minutes to post detailed instructions.

**Comment by ambarish2012** [comment]
Prior to calling the API, you would need to -

1) Get your API token by following the instructions [here](http://docs.shippable.com/navigatingUI/accountSettings/api/).

2) Provide these tokens on every API call by following the examples [here](http://docs.shippable.com/api/overview/).

3) Get the subscription id of your subscription from the subscription settings in your dashboard.

**Steps** -

1) Make an API call to get the resource id of all your soft deleted resources.

**API** - https://api.shippable.com/resources?isDeleted=true&subscriptionIds=<your subscription id>
**Operation**: GET
**Headers**: Authentication header

2) Extract all the resource ids from the response JSON, which are in the "id" property and capture them in any collection of your choice.

Here is an example of a response for a single soft deleted resource -

{
    "propertyBag": {
      "yml": {
        "name": "outrunsh",
        "type": "runSh",
        "steps": [
          {
            "IN": "nginx-image"
          },
          {
            "TASK": [
              {
                "script": "mkdir -p /build/state/"
              },
              {
                "script": "touch /build/state/nginx-image.env"
              },
              {
                "script": "echo 'versionName=2' >>  /build/state/nginx-image.env"
              },
              {
                "script": "cat /build/state/nginx-image.env"
              }
            ]
          }
        ]
      }
    },
    "id": 1502,
    "name": "outrunsh",
    "sourceName": null,
    "subscriptionIntegrationId": null,
    "typeCode": 2007,
    "lastVersionId": null,
    "lastVersionName": null,
    "lastVersionNumber": 0,
    "subscriptionId": "54c023bb5ab6cc13528956b7",
    "projectId": "575f45c82a8192902e238ada",
    "parentResourceId": 1478,
    "isJob": true,
    "isDeleted": true,
    "isConsistent": true,
    "nextTriggerTime": null,
    "createdBy": "540e55445e5bad6f98764522",
    "updatedBy": "54c023ea24bcec0e005a1b02",
    "createdAt": "2016-09-08T18:05:51.412Z",
    "updatedAt": "2017-03-01T20:24:39.467Z"
  },

The resource id is 1502 for the above response JSON.

3) Delete the resource using the **DELETE** method on this route -

**API**: https://api.shippable.com/resources/<id>?hard=true
**Operation**: DELETE
**Headers**: Authentication header

Since your resources have dependencies, you will need multiple passes on your list of resource ids, with each pass deleting resources that have no dependencies, thereby freeing up further resources for deletion in the next pass.

**Comment by Jsgoller1** [comment]
Thanks for your help @ambarish2012 , will give this a shot.

**Comment by ambarish2012** [comment]
Thanks @Jsgoller1, please let me know if you need any help.

**Comment by avinci** [comment]
I think the easier way is to migrate the rSync temporarily to another repo and delete the original rSync repo and then migrate it back. You cannot make API calls unless you are a paid user. Using API directly is not the right thing here as there might be other internal calls the UI is making which might put this to a bad state.

**Comment by manishas** [comment]
@Jsgoller1 we can also delete the soft deleted jobs and resources for you from our backend. Please let me know if you need us to do this. Might be the easiest solution :)

**Comment by Jsgoller1** [comment]
@manishas that would be the most preferable solution, as long as you can *guarantee* that no actively used resources will be deleted - our production infrastructure depends on Shippable, and as we have seen previously, deleting resources will cause Shippable to remove them from AWS (which will result in downtime for us).

**Comment by manishas** [comment]
We can delete only soft deleted resources, so only the 'pink' resources. Let me know if that works.

**Comment by Jsgoller1** [comment]
@manishas Perfect - we do not want any grey, green, or red resources being deleted; please delete the soft-deleted (i.e. pink) ones.

**Comment by ambarish2012** [comment]
@Jsgoller1 we have deleted all but two soft deleted resources. Those resources are inputs to a job and we thought it best for you to investigate those two resources, since forcefully deleting them might cause some side effects on the downstream job.

**Comment by manishas** [comment]
@Jsgoller1 I am closing this issue, but please let us know if you need any more help with this and we can reopen. Thanks
