### ISSUE TITLE
Shippable is not attempting to deploy despite successful build

### ISSUE THREAD

**Issue by aergener** [Shippable/support#3533]
I followed the docs (http://docs.shippable.com/integrations/deploy/eb/) to add EB deployment integration to my shippable.yml. Despite successful builds, Shippable is not triggering deployment to EB.

Here is the build for reference:
https://app.shippable.com/github/aergener/linknest/runs/21/1/console

**Comment by manishas** [comment]
@aergener I see an error in the logs regarding security token. Can you please verify that the credentials in your AWS integration are correct?

**Comment by aergener** [comment]
Oh I see the `aws_eb_deploy` section now in the build... I made sure the Access Key/Secret Key were correct. What permissions are needed in AWS? The account associated with that access key already has full access to Elastic Beanstalk.

Also... why is `aws_eb_deploy` happening before the code in the `push` section of my `shippable.yml`? This seems backwards, as EB is supposed to be using the image in docker repo pushed up in the push section.

**Comment by trriplejay** [comment]
Today the eb deploy section happens inside the build container, while the push section is after the build container has exited. It can be used if you push your image during the ci section.  I agree it would make sense to move that after the push section. We'll have to look into that enhancement.

If you can't push during ci to get around this, we can provide an example using shippable pipelines that will accomplish your scenario.

We're investigating the token issue.

**Comment by ambarish2012** [comment]
@aergener please open a new issue if you need help setting up a pipeline or reopen this issue if you still are facing any issues.

**Comment by aergener** [comment]
@ambarish2012 Please reopen... @trriplejay never got back to me about the token issue...

**Comment by trriplejay** [comment]
Sorry for the delay. I think I see the problem here.  I noticed this in the downloaded logs:
```
/root/637b69fb-c04c-4180-87c3-3bd6b2571895.sh: line 299: aws: command not found
/root/637b69fb-c04c-4180-87c3-3bd6b2571895.sh: line 301: aws: command not found
/root/637b69fb-c04c-4180-87c3-3bd6b2571895.sh: line 303: aws: command not found
echo 'Successfully configured aws cli credentials'
Successfully configured aws cli credentials
```

You're running CI on a custom image which doesn't have the aws cli installed. Shippable tries to configure the awscli with your credentials before your CI runs, but it can't since the cli is not installed.

In this case it would probably need to be installed on your image during docker build for the shippable scripts to work, since they happen just before the CI step, after pre_ci_boot.

One alternative if you don't want the cli baked into your image, is to install the CLI during the CI section, and then configure it yourself using the credentials provided in the environment.  Since you're using an ECR integration, certain environment variables are set during your build that would allow you to use the ECR keys. It would look something like this:

```
ci: 
  - sudo pip install 'awscli==1.11.44'
  - aws configure set aws_access_key_id $ECR_AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $ECR_AWS_SECRET_ACCESS_KEY
  - aws configure set region us-east-1
```

but this would assume that your ECR keys have the access to run the EB commands.

**Comment by trriplejay** [comment]
given your scenario, I actually think the cleanest way for you to do this is to use Shippable Pipelines to deploy to beanstalk, instead of the CI deployment you have set up right now.  We're in the process of making official documentation for how to do this, but you can have a look at this sample project:
https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk

Basically, the flow would look something like this:
- build/test/push image in ci just as you are today
- ci triggers a `runCLI` pipeline job that deploys the newly pushed image to EB

one advantage is that your CI only needs your ECR credentials so it can push the image. you can get rid of your deploy integration there, and it eliminates the need to install the awscli in your image.

If you have any questions, feel free to ask here.

**Comment by ambarish2012** [comment]
@aergener we are happy to consult with you in a zoom / hangout to design the pipeline. You can email me @ ambarish@shippable.com if you need further assistance building your pipeline. I am closing this issue.
