### ISSUE TITLE
Need help converting to runCI

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3543]
I'm trying to follow the instructions, but they don't map up to my environment. I'd like someone to call me and walk me through this as I have wasted enough time with this today. 

Specifically: 

There is no Hook Pipeline section in my settings. 
And, there are not runCI resources shown for one of my projects, and I can find no way to add it. It Fails on the rsync with : 
```
Creating resource: develop-admin-app_runCI
Cannot add runCI job, please enable the project before adding job: develop-admin-app_runCI
```

**Comment by ambarish2012** [comment]
@npahucki if you have created your pipeline after 02/28, you won't need to follow the instructions for hooking your CI project, as this takes place automatically.

Please let me know if I have permission to look at your project so that I can take a quick look first before we get into a call. Also, I am assuming your intent is to connect your develop-admin-app CI project to your pipeline.

**Comment by npahucki** [comment]
It was created way before that date. I ended up deleting the ExecThread_develop resource and then restoring it, and the the Hook Option appeared in the settings. 

I think it'a ll worked out now. I'll close this in just a few minutes once I confirm that everything works ok now.

**Comment by npahucki** [comment]
Yeah, I'm good now, thanks for the response.
