### ISSUE TITLE
Deploy Key can only be added to one private repo

### ISSUE THREAD

**Issue by djenriquez** [Shippable/support#3553]
Hi guys,

It seems that I can only add the shippable `deploy key` to one repo. Every other repo I try to add it to gives me: 

<img width="735" alt="screen shot 2017-04-28 at 2 34 42 pm" src="https://cloud.githubusercontent.com/assets/4636740/25548169/f39c540a-2c1f-11e7-9d22-4ef3a9823d3f.png">

I have a repo with submodules to two other repos, but only one of them has access because of this. Thoughts on how to get around this?

Also, your docs on submodules has an image that does not load, making it difficult to follow the steps: http://docs.shippable.com/ci/advancedOptions/gitSubmodules/

<img width="981" alt="screen shot 2017-04-28 at 2 36 32 pm" src="https://cloud.githubusercontent.com/assets/4636740/25548197/1c5332d8-2c20-11e7-8acc-d3ce0b3c4a83.png">

**Comment by ambarish2012** [comment]
@djenriquez the simplest approach is to add the deploy key to your account and not the repo, since GitHub will not allow two repo's to have the same key as you have discovered.

I suggest first removing the key from the repo where you were able to add it, going to your github account settings and adding it in the SSH keys section.

**Comment by ambarish2012** [comment]
@djenriquez please reopen if you need any further assistance.
