### ISSUE TITLE
shippable updating PR build state when shippable.yml doesnt exist

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3554]
Same problem reported years ago in #552

I'm testing shippable on a project, and have specific specific branches being tested.

No other branches have shippable.yml files.

Commits to other branches (without the shippable.yml) trigger build attempts - which error. 

If those branches are tied to PRs, the PR state is updated to failed.

![image](https://cloud.githubusercontent.com/assets/1108844/25556457/db6fc8b6-2cca-11e7-9e7c-3eb7762ecbdd.png)

![image](https://cloud.githubusercontent.com/assets/1108844/25556494/920f80fc-2ccb-11e7-9012-68658aebe4aa.png)

Shippable should NOT "fail" a PR just because it doesnt have a shippable.yml.   It's entirely valid to have different branches with completely different functionality, and to use different CI tools for those different branches (github pages, wiki branches, docu branches, archive/storage/vendor branches, come to mind).

In fact, shippable shouldn't ERROR at all (perhaps someone might want to turn that on, so it should be a setting) for a missing shippable.yml.

In this case we're using bitbucket - and I've never enabled any kind of PR state updating, either.

**Comment by manishas** [comment]
@keen99 we've gone back and forth on this design and there is no right or wrong here. If we do not create a build for missing yml files, customers are often misled into thinking a build wasn't triggered due to an issue with the platform. We are also working on a feature where builds triggered with missing yml files will auto-detect language and run some default commands.

That said, there are a few things that can address your issue:

- You can turn off PR builds through the UI. Go to your project settings and click on `Disable` for Pull requests:

![image](https://cloud.githubusercontent.com/assets/2983749/25560093/ef3bdec8-2cfe-11e7-8abf-7bc257c7c81e.png)

- You can add a shippable.yml to all branches but turn off builds for everything except your test branches with the [branches keyword](http://docs.shippable.com/ci/advancedOptions/branches/):

```
branches:
  only:
    - test-branch
```

**Comment by ambarish2012** [comment]
@keen99 please reopen if you need any further assistance.

**Comment by keen99** [comment]
I dont seem to have permissions to reopen - 

this continues to be a massive blocker to  our prototype shippable setup and migration since even with these options set shippable is still trigering builds and marking PRs as bad.

![image](https://cloud.githubusercontent.com/assets/1108844/25681090/11b4c0ee-3021-11e7-9e18-c8e7deef693a.png)


With merge checks enabled as part of our bitbucket config and process, this -blocks-  my dev team, even if jenkins marks the build as good after.  We're having to merge manually.


And no, spreading a "don't run" shippible.yml throughout all of our codebases and branches just to avoid your "feature" is not acceptable.

no other hosted CI solution that I've used behaves this way.   Sure, logging the attempt in the build hsitory is useful (though it should have it's own status icon and not "failed").  but failing a PR is NOT.

**Comment by manishas** [comment]
@keen99 thanks for the update. So you're saying that even with Pull Requests being disabled, builds are still being triggered for pull requests? That sounds like a bug :(

Can you point me to the project?

**Comment by keen99** [comment]
https://app.shippable.com/bitbucket/devexi/devexi/status/dashboard

**Comment by keen99** [comment]
More importantly than being triggered, PRs are having the build status flag set to failed.  

I flipped the flag as suggested a few days ago - (hopefully you guys have some log of change history since we dont...) and reenabled the project.   today I got complaints about PRs with current failed builds from shippable.  (I originally expected they were PRs impacted by the issue a few days ago, but these were not - these were new.)

(thought I attached this screenshot earlier, but my browser was being crashy..)

![image](https://cloud.githubusercontent.com/assets/1108844/25683847/2c3da542-302c-11e7-93f5-2a23ff1d1c6c.png)

**Comment by manishas** [comment]
Hmm we need to look into this. We did not detect run 14 as a PR (the status circle indicated commit 
![image](https://cloud.githubusercontent.com/assets/2983749/25684066/313accf4-3014-11e7-9a81-69ef0a6a2ad9.png)). We see it as a commit to branch `MD-4170`.

Which shouldn't post to the PR UI. Let me get someone to try and repro this..

**Comment by ambarish2012** [comment]
@keen99 can we get into a quick call to look at your issue? 

1) Our system thinks that run 14 was a commit to MD4170 branch by Zoltan. Does this not correlate with your observation? If so, we can take a look.

2) To turn off builds for commits on a branch, that branch will need to have a shippable.yml file with just this content:

branches:
  only:
    - test-branch

So to turn off builds in MD4170 branch for example, you will need to add a shippable.yml file with the above. You will have to add this file to every branch that does not want to build.

3) I only see a build triggered for a PR request in your dashboard last Saturday and none since. Is there is a build that was triggered for a PR request, please let me know which one. Build 14 does not appear to be a PR from our perspective.

**Comment by keen99** [comment]
1) yes - commits to PRs are also commits to branches....   not sure there's
a way to have a PR that isn't related to a branch. :)

2) I'm not going to try to merge a file across all of our branches.  I
don't care so much if a -build- fails (as long as it fails fast).

3) if build 14 wasn't a "PR" from your perspective, why did it update the
PR build status in bitbucket?  that's a specific API call to bitbucket, so
not something that would happen as a side effect of something else....

I'm heading out for vacation at the moment - I'll be back on friday
(eastern time) and can resume this then - in the meantime the shippable
project is paused. (I hope.)

I think 3) is the real question and problem.

**Comment by ambarish2012** [comment]
Thanks @keen99 we will investigate, thanks for your response.

**Comment by ambarish2012** [comment]
@keen99 we have created a bug to track this issue and we will let you know as soon as it in production.

**Comment by manishas** [comment]
@ambarish2012 can you post an update on this? I tried to follow the internal trail but we seem to have lost track of this issue.

**Comment by manishas** [comment]
@rageshkrishna can you post the resolution to this? I followed the internal trail and looks like we don't plan to fix this.

**Comment by rageshkrishna** [comment]
Sorry about the late reply. I reviewed the internal ticket and I think this is actually a side effect of us using the commit status APIs. There is no special API for reporting "PR status". Shippable always posts the status of a commit to the SCM, regardless of whether it was a PR build or an actual merge commit resulting from a PR merge. The way BitBucket visualizes this status in its UI is a little different from what GitHub does, which is what results in this confusion.

The only way to avoid this today is to have a shippable.yml that specifies include/exclude so the builds are skipped entirely. If a build runs, we will post the commit status and this isn't configurable today. I don't think we will be making any changes to this behaviour.

EDIT: What I said only applies to runCI jobs. For [runSh jobs](http://docs.shippable.com/platform/workflow/job/runsh/) consuming a gitRepo resource, this behaviour is indeed configurable by using the `showBuildStatus` property.
