### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by bhaumikshippable** [Shippable/support#3568]
Hello Team, 

I have bitbucket account and i am admin of the same.

But when i tried to connect the Shippable it redirect me to page ( 404 Page Not Found ) 

I see this error since last two days .. before that i was able to see the repository and other pipeline stuff.

Please help on this.

**Comment by manishas** [comment]
@bhaumikshippable  I sent you an email a few minutes ago.  Let me know if syncing work for you.

**Comment by rageshkrishna** [comment]
We resolved this over email.

The issue was that the subscription in question did not actually have any repositories on the SCM. As a result, some of our permissions checks deny access to the page resulting in a 404. Currently, we expect at least one repository to be present in a subscription for it to be manageable from the UI.
