### ISSUE TITLE
Github Pull Requests triggers two builds

### ISSUE THREAD

**Issue by asans** [Shippable/support#3569]
This is not an issue per se, but it relates to the workings of Pull Requests from Github.

Say that I create a branch.  I then commit the code to the repo.  This triggers a build as expected.

Next, I create a Pull Request for this new branch to merge into master.

Now, if I make another commit to the new branch (to fix some issues), this one ends up triggering two builds -- one for the branch and one for the pull request.  

I'm wondering how one would go about just triggering one build in this case instead of triggering two builds.  It's basically triggering both.

One way I've done so far is to just ignore doing builds if IS_PULL_REQUEST is true.  However, this ends up with a separate consequence where if someone submitted a Pull Request from a forked repo, then the build will be ignored.

Any ideas?

**Comment by deepikasl** [comment]
@asans This is by design.CI build will be triggered on both `commit` and on `pull_request` if they are enabled.
You can skip your **CI build** for a particular commit by specifying **`[skip ci]`** in that commit message.
**Example**: you can give commit message something like: **`update shippable.yml [skip ci]`** This will skip your CI build.

So whenever you dont want to trigger a build for any commit then add `[skip ci]` in commit message.

Please let me know if you have any concern. Thanks.
