### ISSUE TITLE
Validation error when try to enable project 

### ISSUE THREAD

**Issue by elicohendatos** [Shippable/support#3583]
When I try to enable my git repository in the Shippable UI I get the following error:
(Id: 4011) postResource failed for sourceName: datoshealth/datoshealth-git returned error resources.create failed with error: Validation error
verbose: projects|enableById|callerId:59198d9cf0db130700717195|projectId:5914552e9b24580700e37904|_createCIRepoResource

I have added the BitBucket as an integration in Subscription Settings -> Integrations

What am I missing here ?

**Comment by ChaitanyaVootla** [comment]
hey, @elicohendatos  we are looking into this, we'll get back to you with our findings

**Comment by kanthchandra** [comment]
Hi @elicohendatos I looked into your project and I see that there are a couple inconsistencies.

1. Had you enabled the project before and tried to build the project on shippable? - There are some builds that ran on Shippable for the particular project that you mentioned (i mean for bitbucket project with the same name).

2. Is that project a git project? Currently we don't support hg projects on Shippable - I see some builds for hg branch for that project so just wanted to confirm that branch hg is for a git project.

3. Finally did you delete the project on bitbucket and re added it back?

I think your project is in a messed up state right now, if you can answer some of our questions, we will be able to know what exactly went wrong and what we can do at our end to fix this problem for you.

**Comment by kanthchandra** [comment]
Hi @elicohendatos I think this is what happened in your case

1. You had a project on bitbucket and you had enabled it on shippable and ran a few builds, but after some time, the project was probably deleted from bitbucket (but the project still remained on shippable). Then a project with the same name was created on bitbucket and you tried to enable the new project that you created. Since the original project was not cleaned up correctly, some of the validation started to fail. 

In order to fix this issue I'm logging an internal bug, so that we handle such cases gracefully and to improve the user experience around this.

In the meantime do you want us to delete the remnants of the old project manually at our end ? Please let us know.

Thanks.

**Comment by elicohendatos** [comment]
Hi

1) We maintain our code in BitBucket and use Mercurial, however I created a duplicate GIT repository on BitBucket as I saw that Shippable doesn't support Mercurial and we wish to use your service for our CI tasks.
2) The GIT repository was never deleted - the only thing I did was to delete the Shippable access key from BitBucket as your service each time I pressed on project enable button, creates a new access key...
3) I delete my Shippable account which I created and create a new one, but it looks he "remember" my details from before.
4) Of course you can clean up my project to fix the issues I am facing.
5) It was not simple to me to understand how to configure Shippable service to build and deploy our code, although we use very standard development process:
 - Java Code
- Maven Build
- Docker to create image
- Kubernetes YML to deploy it on Google Container Engine
Since you don't have enough documentations and specially examples which covers our needs.
6) Can we make a Skype call in which you help me configure Shippable for our needs ?

Thx
Eli

**Comment by ambarish2012** [comment]
@elicohendatos please look at these kubernetes samples -

1) https://github.com/devops-recipes/deploy-kubernetes-basic
2) https://github.com/shippableSamples/node-build-push-docker-hub-deploy-kubernetes
3) https://github.com/shippableSamples/node-dockerhub-runcli-kubernetes-kubectl
4) https://github.com/shippableSamples/node-dockerhub-runsh-kubernetes-kubectl

**Comment by ambarish2012** [comment]
@elicohendatos for a java build sample, please look at - https://github.com/devops-recipes/ci-java-push-ecr.

**Comment by ambarish2012** [comment]
@elicohendatos @ttrahan will setup time with you for a call tomorrow in PST time zone. Please can you let us know your email.

For GKE, please look at this sample - https://github.com/devops-recipes/deploy-gke-basic

**Comment by kanthchandra** [comment]
Hi @elicohendatos , I have deleted the old project, so you should be able to enable the project now.

I wanted to clarify a couple things that you mentioned in your comment above

> The GIT repository was never deleted - the only thing I did was to delete the Shippable access key from BitBucket as your service each time I pressed on project enable button, creates a new access key...

When you enable a project on Shippable, we go and create webhooks and deployment keys. The reason we set up webhooks is because we want to get a payload from bitbucket whenever you push code to your repository so that we can run your builds. In order to run builds, we will need to clone the repository, to clone the respository we need the access key set up on the project.

Also the enabling of project is a one time thing and you need not do it multiple times unless you delete the project from Shippable.

Regarding the Skype call @ambarish2012 and @ttrahan will be able to help you out :)

If you have any specific questions you can open separate issues for that and we will be happy to help you.

**Comment by elicohendatos** [comment]
Hi

Thank you for reset my project - I still need urgently support from you to help me configure for the first time my build as described before.
I understand your time zone is PST (UTC-8). My time zone is UTC+2.
Can we schedule a Skype call tomorrow at 08:00 PST timezone / 18:00 my timezone ?
My Skype username is: elico1971

Eli

**Comment by ttrahan** [comment]
Closing this as Eli and I have been engaged on Skype.
