### ISSUE TITLE
"404" when getting node

### ISSUE THREAD

**Issue by kylape** [Shippable/support#3586]
### Description of your issue:

- Link to the build failure: https://app.shippable.com/github/RedHatInsights/falafel/runs/1053/1/console

All builds fail, but when we drill in to the steps, I see this:

- Initializing job
    - Getting Node
        - 404

**Comment by ambarish2012** [comment]
@kylape we are investigating.

**Comment by ambarish2012** [comment]
@kylape there was a temporary glitch which has been fixed, I am seeing builds on your subscription running successfully now.

**Comment by ambarish2012** [comment]
@kylape we are investigating, I just saw this issue resurface.

**Comment by trriplejay** [comment]
Looks like an issue with the token that was running the build. This should be resolved now. please let us know if you continue to see this error.

**Comment by avinci** [comment]
The reason this happened is that these two repos were transferred from 1 subscription to another. This is an edge case that rarely occurs and due to this our permission check was picking the perm from the other sub which no longer is valid. We are fixing this in the next rev so as to force a permission check at a subId level.

**Comment by manishas** [comment]
@kylape I am closing this issue since it should be resolved. Please let us know if you need to re-open for any reason.

**Comment by kylape** [comment]
Thanks everyone for the quick turnaround!
