### ISSUE TITLE
CI fail when trying to trigger pipeline job after CI

### ISSUE THREAD

**Issue by aurelien-reeves** [Shippable/support#3597]
To trigger a job in the pipeline I followed that documentation page: http://docs.shippable.com/ci/trigger-pipeline-jobs/

I've added something like that in the CI:
```
build:
  ci:
   - ...
    - echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/my_image.env
```

And in my pipeline:
```
jobs:
  - name: my_app_runCI
    type: runCI
    steps:
      - OUT: my_image
```

But the CI fail with the following error:
```
Processing OUT Dependency: my_image 
  Dependency Info   
Version Number: 1
Version Name: testing
  Validating my_image handler   
No special dependencyHandler for dependency type: OUT image

# ...

Processing version for my_image 
  Reading dependency metadata from file   
the path is: /build/OUT/my_image/
Successfully read dependency metadata file
  Reading resource env file   
found a key: versionName
Successfully parsed .env file.
  comparing current version to original   
versionName has changed
  Posting new version   
genExec|pipelines|__postVersion, Failed to post version for resourceId: undefined 404

```

Did I miss something?

- Link to the build failure: https://app.shippable.com/github/hiptest/hiptest/runs/2487/1/console

**Comment by ambarish2012** [comment]
@aurelien-reeves - you were seeing this error since your build was running with the token of an account id (vincent-psarga) that hadn't sync'ed for a while. This user did not have permissions on the project in which the my_image resource was defined.

After we sync'ed the permissions for this user, the user got permissions for the resource and your build should succeed.

I also suggest you look at your cache command that is failing because of errors in rvm.

tar -czf /home/shippable/cache/buildCache.tar.gz /usr/local/rvm/environments /usr/local/rvm/gems/ /usr/local/rvm/gems/@global /usr/local/rvm/rubies/ /usr/local/rvm/wrappers/ /usr/local/rvm/wrappers/@global /root/src/github.com/hiptest/hiptest/node_modules /root/src/github.com/hiptest/hiptest/frontend/node_modules /root/src/github.com/hiptest/hiptest/frontend/bower_components 1m 6s  
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
tar: /usr/local/rvm/gems/@global: Cannot stat: No such file or directory
tar: /usr/local/rvm/wrappers/@global: Cannot stat: No such file or directory
tar: /root/src/github.com/hiptest/hiptest/node_modules: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

**Comment by ambarish2012** [comment]
Also note that the user whose token is used to run a build is the one you can find configured in the `Account Used to Process Webhooks` setting in the project settings.

**Comment by aurelien-reeves** [comment]
Thank you very much!
It works fine now \o/

And thanks for the info about the account used to process webhooks :)
