### ISSUE TITLE
feature request: link to filtered view for single pane of glass

### ISSUE THREAD

**Issue by db** [Shippable/support#3621]
When we select flags for the single pane of glass view, we would like to link this view in our browser and use favourite/bookmark to this view in a web browser.

**Comment by ankul-shippable** [comment]
@db we are redoing our UI/UX. This will be available in the new UI in couple of weeks.

**Comment by asanchezgiraldo** [comment]
@ankul-shippable any update on this? our SPOG is growing very quickly due to the different products we work on

**Comment by ambarish2012** [comment]
@asanchezgiraldo we are rolling out the new UI very soon. I will let you know ASAP.

**Comment by manishas** [comment]
@asanchezgiraldo @db we launched custom views a few weeks ago which should help with your scenario. You can bookmark the custom view.

Here is a description of how custom views work (we're still in the process of documenting them):

- On your Home dashboard, click on the + icon to the far right:
![image](https://user-images.githubusercontent.com/2983749/28302272-2b518e14-6b41-11e7-8641-65ea500c51be.png)

- This will show you a page where you can select CI projects, pipeline filters, and pipeline jobs that you want in your custom view. You can also set the custom view as your default dashboard.

- Save your view. You can then access your view in the left page under the Views heading:
![image](https://user-images.githubusercontent.com/2983749/28302307-62f9269c-6b41-11e7-96c4-28458b82efbb.png)

- Since each view has a unique URL, you can bookmark your view.

Please let me know if this works for you :)

**Comment by asanchezgiraldo** [comment]
great thank you 👍

**Comment by db** [comment]
I don't use the new UI anymore.

**Comment by manishas** [comment]
@db but that UI is going to be the default very soon. We have fixed a lot of usability issues with it over the last month so it will be good to try it now :)

**Comment by manishas** [comment]
@db also, can you let us know your main issues with the new UI?
