### ISSUE TITLE
firefox 26 & firefox 27

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3626]
I configure shippable.yml to use firefox add.
Both 26 and 27 does not get installed

firefox --version  
(process:317): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Mozilla Firefox 26.0

What version of firefox can be installed, version < 27.

**Comment by ambarish2012** [comment]
@aswath-veersoft we are investigating.

**Comment by ambarish2012** [comment]
@aswath-veersoft regarding the ```firefox --version``` error, this is a benign warning that can be ignored. If you want more clarity on it, I suggest you ask a question on the FF forum (https://support.mozilla.org/en-US/questions/firefox).

Your build is failing because of a 404 on this URL ```wget http://selenium-release.storage.googleapis.com/2.43.1/selenium-server-standalone-2.43.1.jar```.

I suggest you contact Selenium support to resolve that since they host that JAR file (http://www.seleniumhq.org/support/).
