### ISSUE TITLE
Not able to deploy to ECS if using version "latest" for docker image

### ISSUE THREAD

**Issue by toomanyedwards** [Shippable/support#3654]
I am trying to get continuous deployment to ECS working through shippable. I can deploy my docker image if I specify a hard code version in the seed for the image. For example:

 seed:
      versionName: master.31

However, if I specify latest. I get the following error from ECS during the deploy:

Status reason	CannotPullContainerError: Error: image convective-core/labs/wifi-location-sensing-server:latest not found

Which is true.  There is no version explicitly labeled "latest" in the ECR repo.  How do I get continuous deployment to work to deploy the latest image to ECS without having to hardcode a version?  My github repo is here: https://github.com/toomanyedwards/wifi-location-sensing-server

Thanks for the support. I feel like I'm close to getting full CI/CD working here. Taking down the obsolete docs would definitely help to lessen confusion.

**Comment by trriplejay** [comment]
If you want to use latest, then your CI (`shippable.yml`) needs to push with the `latest` tag instead of `$BRANCH.$BUILD_NUMBER`.  Then the image will actually exist and the deployment will work.

However, you don't have to use latest to do continuous deployment, in fact i'd recommend you stick with the branch.buildnumber format.

Once you get your CI successfully triggering your deployment, the branch.buildnumber information will be passed along the pipeline, so that you don't need to hardcode anything in the yml. 

The idea of the 'seed' section is to just give a starting point, or a way to manually override, but once everything is configured, CI should take over updating your image resource.
