### ISSUE TITLE
Running dockercloud/client-proxy doesn't work

### ISSUE THREAD

**Issue by kenloburn** [Shippable/support#3693]
#### Description

I'm contemplating purchasing paid minions, but before I can proceed I will need to make sure that Shippable actually supports what I'm trying to do.

As far as I'm aware, you don't support deploying stacks to Docker Swarm nodes natively at this point in time (and rightfully so - Docker Swarm is changing very rapidly), so I'm using the `post_ci` build step to connect to my swarm through a docker cloud proxy.

These are my steps:

```yaml
# ...
post_ci:
    - $(docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client --user $DOCKER_USER --pass $DOCKER_PASSWORD --debug rknol/swarm1)
    - docker ps || true # Running docker ps through the proxy
    - unset DOCKER_HOST
    - docker ps # Running 'docker ps' locally
    - docker logs client_proxy_rknol_swarm1
    - docker rm -f client_proxy_rknol_swarm1
#...
```

Note how I'm running `docker ps || true` with an exit code toggle - this is where it goes wrong.

The first command is supposed to make the docker client connect to the proxy container rather than the local docker daemon, and this works fine locally and on my own coreos linux machine.

But on your platform when I run a subsequent docker command I get this:

```
> docker ps || true
Cannot connect to the Docker daemon at tcp://127.0.0.1:32769. Is the docker daemon running?
```

The container seems to be running fine, it bound to the ip + port just fine according to the debug messages, but for some reason this is happening and I can't figure out why.

#### References

- Link to the build failure: https://app.shippable.com/bitbucket/habuio/referencecheck/runs/64/summary/console

**Comment by kanthchandra** [comment]
Hey @kenloburn I really haven't tried to connect any remote docker swarm instances but this https://docs.docker.com/docker-cloud/cloud-swarm/connect-to-swarm/#connect-to-a-swarm-with-a-docker-cloud-generated-run-command seems to suggest that you need to export DOCKER_HOST env to complete the connection I dont see that variable set in build environment. Could that be the problem?

```


To complete the connection process, run the export DOCKER_HOST command as provided in the output of the previous command. This connects your local shell to the client proxy.

Be sure to include the given client connection port in the URL. For our example, the command is: export DOCKER_HOST=tcp://127.0.0.1:32770.

(If you are connecting to your first swarm, the command:port is likely to be export DOCKER_HOST=tcp://127.0.0.1:32768.)

```

**Comment by kenloburn** [comment]
Hi @kanthchandra 

The first command:

```
$(docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client --user $DOCKER_USER --pass $DOCKER_PASSWORD --debug rknol/swarm1)
```
actually does this. The output of this command is something like:

```
export DOCKER_HOST=tcp://127.0.0.1:32772
```

and with the `$(...)` syntax I evaluate the output directly to set the `DOCKER_HOST` env var.

**Comment by kanthchandra** [comment]
hey @kenloburn can you test one more scenario? if you have exported an DOCKER_HOST env, can you just do `echo $DOCKER_HOST` immediately after the docker run command to see if it's set?

My guess is that since you are using `(..)` a new subshell is being spawned and as a result your exported variable is not available in the main shell where you build is going on. So putting that echo statement might help us know if it's indeed the problem.

I just did a quick test to confirm this, so can you please see if this is indeed the case? else we'll debug this further.
![selection_617](https://user-images.githubusercontent.com/1583444/27769850-d78c5576-5f50-11e7-8818-99d11561f792.png)

**Comment by kenloburn** [comment]
Hi @kanthchandra,

In my latest build (https://app.shippable.com/bitbucket/habuio/referencecheck/runs/70), the post_ci node looks like this:

```yml
post_ci:
    - echo $DOCKER_HOST
    - eval $(sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client --user $DOCKER_USER --pass $DOCKER_PASSWORD --debug rknol/swarm1)
    - echo $DOCKER_HOST
```

With the resulting output:

```

```

for the first, and for the second:

```
tcp://127.0.0.1:32769
```

Meaning it actually did set the envvar. Which also shows in the initial script, as I wouldn't get an error from `docker ps` if I didn't set the envvar (as it would talk to the local docker daemon)

**Comment by kenloburn** [comment]
While my script shows `eval $(...)`, the same result happens without it (https://app.shippable.com/bitbucket/habuio/referencecheck/runs/71/summary/console) - the envvar gets set

**Comment by ambarish2012** [comment]
@kenloburn we are investigating.

**Comment by ambarish2012** [comment]
@kenloburn please replace `$(docker run --rm -v ...` with these two lines -

    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client --user $DOCKER_USER --pass $DOCKER_PASSWORD --debug rknol/swarm1
    - export DOCKER_HOST="tcp://"$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' client_proxy_rknol_swarm1)":2375"

**Comment by kenloburn** [comment]
@ambarish2012 this works :) thanks a lot for investigating

**Comment by ambarish2012** [comment]
@kenloburn I hope this unblocks you from purchasing minions. If you need any additional help, please let us know.

**Comment by kenloburn** [comment]
Yup! I still need to tinker with the end-result (as there's still some bugs in Moby, e.g. `Error response from daemon: rpc error: code = 12 desc = networks must be migrated to TaskSpec before being changed`) but as far as Shippable is concerned this will work fine for what I'm trying to accomplish :)

**Comment by jmagnusson** [comment]
Thank you @ambarish2012 for the inspect suggestion, it worked great for me as well. If you don't mind me asking, do you know the reason why this works and `127.0.0.1` does not? Is it because the test coordinator is sharing `/var/run/docker.sock` with the test runner? (I'm using Gitlab CI and not Shippable, but problem seems to exist here as well)

**Comment by a-murphy** [comment]
I'm not sure about GitLab, but with Shippable it's because the mounted `docker.sock` allows the second container to run alongside the build container.  The script is running in the build container (with the default `bridge` network mode), where `127.0.0.1` refers to the build container, not the host.  The `docker inspect` will get the IP address of the second container, which can then be used to communicate with that container from the build container.
