### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory

### ISSUE THREAD

**Issue by nathanpalmer** [Shippable/support#3694]
### Description of your issue:
I'm currently testing this service out for our project. Seems we may be running into a memory limitation? What are the current limits and how can they be increased?
 
https://app.shippable.com/github/crowdox/api/runs/3/summary/console

We're currently running this on CircleCI which I believe has a 4GB limit.

**Comment by manishas** [comment]
Hi @nathanpalmer,  our US team is out today for July 4th but we should be able to look into this tonight. 

All our standard minions are 2core 3.75 GB (c4.large on ec2). We also offer c4.xlarge and c4.2xlarge minions for 
a higher monthly price. Also you can use BYON to attach minions of any size for $25 per minion. This also lets you easily leverage docker caching if needed. 

More on BYON: http://docs.shippable.com/getting-started/byon-overview/
More on different minion sizes: http://docs.shippable.com/provision/why-infrastructure-provisioning/

That said, I don't know if your build issue is due to out of memory so we'll look into this as soon as possible.

**Comment by ambarish2012** [comment]
@nathanpalmer I am closing this issue since you added a custom node and solved the memory allocation issue.

**Comment by nathanpalmer** [comment]
Thanks! I figured BYON would solve it so I tried it out.
