### ISSUE TITLE
Error trying to edit integrations

### ISSUE THREAD

**Issue by caliagaa** [Shippable/support#3697]
Hello

I'm getting this error when trying to edit/delete a suscription:

Edit:
(Id: 4001) subscriptionIntegration not found for :id 4578
verbose: subscriptionIntegrations|getById|callerId:582b43112179161000dd929f|_getProjectAccounts

Delete:
(Id: 4001) getSubscriptionIntegrationById for id: 4578 returned error: subscriptionIntegration not found for :id 4578
verbose: accountIntegrations|getDependencies|callerId:582b43112179161000dd929f|subscriptionIntegrationId:4578|_getSubscriptionIntegration

This is after re-creating a project (deploy)

CC: @ambarish2012

**Comment by a-murphy** [comment]
It looks like your subscription integration has specified a list of projects that are allowed to use it, and you don't have access to any of those projects.    Since you don't have access to the selected projects, you don't have permission for the subscription integration.

Could you tell us what you are trying to do?  It's not clear from the actions above why you are trying to edit the integration.  Since the errors above are the result of insufficient permissions, how to resolve them depends on your goal.

**Comment by caliagaa** [comment]
Hi. What i want to do is re-enable the CI/CD for our projects. I have access actually, i have checked that

**Comment by a-murphy** [comment]
When projects are deleted from the source provider and recreated, the recreated project is considered to be a different project than the original.  GitHub and Bitbucket will consider it to be a different repository, with the same name, and so will Shippable.  As a result, you had permission on the new project, but not the one that was added to the subscription integration.

I've identified the project deleted and updated the list of projects on the subscription integration to refer to the new project.  This should allow you access to the integration.

**Comment by caliagaa** [comment]
Thank you, but there's still one missing integration throwing the same error...can you update that subscription please?

**Comment by caliagaa** [comment]
Iive created (copied) the two missing integrations. I want to re add the resource containing deployment info, but when i want to select the branch, the list is empty

**Comment by a-murphy** [comment]
Since you're selecting a branch, I guessing that you're adding a syncRepo/rSync job.  If the branches list is empty, it usually means that either syncRepos have already been added for all of the branches, the repository doesn't have any branches, or the project hasn't been synchronized with the source provider (when it will be automatically synchronized).

Would you mind checking again?  It's likely that the project was being synchronized at the time you tried to add it.  And, if there still aren't any branches, could you let us know which project you are having trouble adding.

**Comment by caliagaa** [comment]
Thanks for your help @a-murphy ..Team got fixed my account and now it works.
