### ISSUE TITLE
Dependency deletion, cant edit, system overall running poorly. Lots of 404s.

### ISSUE THREAD

**Issue by JohnDuplechain** [Shippable/support#3713]
Please delete following dependencies before deleting img-devops-django-testapp 

Dependencies
1 dependency
subscription Integrations
gulfwinds - integration-test-devops

Shows up under my project integrations.
integration-test-devops | notification | img-devops-django-testapp | JohnDuplechain | 02/15/2017 | 02/15/2017 | EditDelete
-- | -- | -- | -- | -- | -- | --

Click edit, 404 not found
Click delete, (Id: 4001) getSubscriptionIntegrationById for id: 5208 returned error: subscriptionIntegration not found for :id 5208
verbose: accountIntegrations|getDependencies|callerId:584841d4c42d210f009d64be|subscriptionIntegrationId:5208|_getSubscriptionIntegration

**Comment by a-murphy** [comment]
The subscription integration that you were trying to delete had been configured so that only one project had permission to use it.  And you don't have permission on that project, so you couldn't edit or delete it.  It's likely that the project with permission had been deleted on GitHub.  I've deleted the subscription integration to allow you to delete your account integration, if you want to.
