### ISSUE TITLE
JFrog Bintray

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#3726]
Shippable can be integrated with JFrog Artifactory. The same integration can be used to push binaries to JFrog Bintray, even in the absence of a JFrog Artifactory account? In this case, what should be the "HTTP Endpoint"? The URL of the Bintray repository?

Thanks!!

**Comment by trriplejay** [comment]
Hmm, I'm not sure that would work.  We're using the integration to run the config command for artifactory as described here: https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-Configuration

However it looks like bintray uses a key, not a password: https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Bintray

so, internally we would not set this 'key'.  You could try putting your key in place of the password in the integration, then running the config command yourself in your script.  something like:
```
jfrog bt config --user $Username --key $Password
```
(the environment variables would be different)

I'm not sure about the URL, since the bintray config example does not have any reference to a URL.  I guess you could be anything you want in there if a url is not necessary. it just won't be used.
