### ISSUE TITLE
Shipabble With PHP 5.5

### ISSUE THREAD

**Issue by Nexyssify** [Shippable/support#3739]
Hey, 

There is a solution for use Shippable with PHP 5.5 because I can't select the deprecated Machine Image "Stable" in the web Interface. 

Have you any Idea gays ? 

Thank's :-)

**Comment by a-murphy** [comment]
If you specify a version of PHP in your shippable.yml that is not pre-installed but can be installed by `phpenv`, it will be installed when the build runs.  For example, the following would install and use 5.5.38:
```YML
language: php

php:
  - 5.5.38
```

However, this does mean that your builds will take longer to run because PHP will be installed each time.  To avoid the increase in build time, you can instead create [your own build image](http://docs.shippable.com/ci/custom-docker-image/).  If you decide to use your own Docker image, an Ubuntu-based image works best.  The easiest image to build would be to use one of the official [Shippable images](http://docs.shippable.com/reference/machine-image-v573/#shippable-official-docker-images) as the base image and install the version of PHP you plan to use in your Dockerfile.  You can then push that image to Docker Hub and specify it in the `pre_ci_boot` section of your `shippable.yml`.
