### ISSUE TITLE
syncRepo not updating on commits

### ISSUE THREAD

**Issue by mumblez** [Shippable/support#3755]
Hi,

When I update the syncRepo in a few projects for some reason shippable is not updating to the latest changes (for jobs and resources), I can see it's still on the old commits, problem started happening on Friday.

E.g. in each project I have a branch called 'shippable-cd' which I added to shippable as a syncRepo, the initial setup works fine, but after a few commits, pushes it no longer updates, I have to keep deleting it (and the resources and jobs) and re-adding it.

Any idea why this happens?

Thanks
Yusuf

**Comment by ChaitanyaVootla** [comment]
@mumblez we are looking into this and will get back to you with our findings.

**Comment by mumblez** [comment]
thx, @ChaitanyaVootla if it helps, you can take a look at this project - https://app.shippable.com/github/karhoo/jobs/karhoo-website-static_shippable-cd_rSync/dashboard

I have around 10 new commits but it's stuck at commit id: 1bf87b8aa159ce7753c29b6b4b71d1ba882fb9e6
The config for the syncRepo show's it using 'Latest' but versionName tag always shows the same old commit, I've click build a few times but it's not getting the latest commits / changes.

**Comment by ChaitanyaVootla** [comment]
@mumblez seems that one of the pipeline sync jobs has been in processing state since last Friday, please check now if the problem is resolved

**Comment by mumblez** [comment]
it's better but there's quite a long duration before it actually syncs, currently 6 mins and 15 mins earlier,

**Comment by mumblez** [comment]
wait, getting confused with another project, the original project, the sync is not pulling down the latest commits, push a change to trigger sync - https://app.shippable.com/github/karhoo/jobs/karhoo-website-static_shippable-cd_rSync/builds/5988872108b58007000f3bdb/console but it's been hanging close to 10 minutes now...

**Comment by mumblez** [comment]
after 15 mins the sync completed but it's not updating, still on the same commit, not sure what's going on

**Comment by manishas** [comment]
We're looking into this. Will provide an update soon.

**Comment by mumblez** [comment]
if it helps, it was working for a few iterations today on a new repo, but now it's no longer updating, either on commits or manually in the ui

**Comment by rageshkrishna** [comment]
Hi @mumblez. I'm trying to figure out how to repro this at my end. If I've understood your scenario correctly, you have:

1. A repo on GitHub with a branch `shippable-cd`
1. You add it as a syncRepo on Shippable for the branch `shippable-cd`
1. You start pushing changes to shippable.resources.yml and shippable.jobs.yml
1. At some point, Shippable no longer runs the rSync job when you push changes and your pipeline definition is effectively stuck at a certain commit

Is this an accurate description of the repro steps?

Some follow up questions:

1. Does this always happen after a certain number of commits? Since you just added a new repo, maybe you can click on the `syncRepo` resource to see the version history. How many versions do you see there? 

1. Are you pushing a single commit, or multiple commits at a time? Are all the changes on the `shippable-cd` branch only for the YML files or do they also contain other commits? Are any of the commits forced?

We have some logic that processes the webhook to decide whether an update needs to be triggered at all. It does this by trying to determine whether one of the Shippable YML files has changed in the current push. I'm trying to determine if there's a certain scenario in which these checks might be giving us a false negative.

Thanks for your patience with us on this issue!

**Comment by mumblez** [comment]
@rageshkrishna yes, accurate description
1. Not always, but when it does I have to delete the syncRepo and then after a few versions it gets stuck again.
2. Never forced commits, small changes / commits to try to trigger shippable to update the resources and jobs. Mostly single commits at a time, e.g. extra period in a README.md so shippable see's it as new / different.

Hope this helps
Thx

**Comment by mumblez** [comment]
might be related but I have jobs with a gitRepo as `IN` that sometimes don't get triggered too, e.g. I set the gitRepo resource to `buildOnCommit: true` and on a specific branch and initially it works fine but after a few commits it doesn't trigger no more.

**Comment by mumblez** [comment]
I'm gonna remove the syncRepo and add again, need to get this project deployed...

**Comment by mumblez** [comment]
it seems to be alright now, new commits are triggering updates again.
