### ISSUE TITLE
Massive job/run queue builds up while most nodes sit idle

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#3771]
Several times a day  a massive job/run queue will build up while most of our nodes are sitting idle. Eventually the queue will run through several nodes, however, at these times it seems most of the nodes are not utilized despited reporting good status. I have not witnessed ALL of our nodes in use concurrently for sometime despite large job queues.

In the screenshots attached we have a single job from a huge queue executing while most nodes sit idle.

<img width="2285" alt="screen shot 2017-08-10 at 10 53 23 am" src="https://user-images.githubusercontent.com/4642501/29176698-97b69ba4-7dba-11e7-8c22-13e484ec818a.png">
<img width="2261" alt="screen shot 2017-08-10 at 10 53 56 am" src="https://user-images.githubusercontent.com/4642501/29176702-9a7642e0-7dba-11e7-866d-d6e13aa0c7d0.png">

**Comment by manishas** [comment]
@grouxsome if you're seeing this the last day or two, then it's due to service issues we'd had for the last couple of days. We're working on fixing the problems and things should go back to normal really soon.

Please see the recent service updates at status.shippable.com .

Are you seeing the queuing right now? Did this happen last week?

**Comment by manishas** [comment]
@grouxsome to add a little more context - the service problems for the last 1-2 days was around the slow queuing of builds, so that would explain why jobs weren't being triggered. If you were seeing this last week as well, then we will need to take a deeper look.
