### ISSUE TITLE
BYON CPU usage always 0

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3772]
I've noticed that the utilization view of our BYON nodes always displays a CPU usage of 0. I cannot imagine this to be true so I wonder if there's something wrong with the metric collection here.

**Comment by a-murphy** [comment]
It's not unusual for the CPU usage to be very, very low most of the time.  It's possible that it will miss some short CPU usage because it records one-minute averages every two minutes, but it should be fairly accurate.  Have you checked the CPU usage of a node right after it runs a build?  Ubuntu 16.04 and Ubuntu 14.04 nodes are both reporting the correct values for me.

**Comment by mbrodala** [comment]
You're right, I've compared with the stats from our node provider and they also show a almost zero CPU usage.
