### ISSUE TITLE
Trying to build new image

### ISSUE THREAD

**Issue by glozhkovoy** [Shippable/support#3775]
I'm trying to setup shippable + AWS ec2 

I have these ymls
**Shippale.yml**

> language: node_js
> node_js:
>   - 7.4.0
> 
> branches:
>   only:
>     - master
> 
> env:
>   global:
>     - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
>     - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
>     - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
>     - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
> 
> build:
>   ci:
>     - shippable_retry npm install
>     - docker build -t myRep.
>     - docker tag MyTag:MyRep:latest
>   post_ci:
>     - docker push MyRep:latest
> 
> 
> 
> integrations:
>   hub:
>     - integrationName: ECR_INTEGRATION
>       region: MY_Region
>       type: ecr
> 

**shippable.resources.yml**

> resources:
>   - name: shipdemo-img
>     type: image
>     integration: ECR_INTEGRATION
>     pointer:
>       sourceName: "MyDockerImage"
>       isPull: false
>     seed:
>       versionName: "latest" 
> 
>   - name: shipdemo-img-options
>     type: dockerOptions
>     version:
>       portMappings:
>         - 3000:3000
> 
>   - name: ecs-test-cluster
>     type: cluster
>     integration: AWS_INTEGRATION
>     pointer:
>       sourceName : "MyClaster" 
>       region: "MyRegion" 

**shippable.jobs.yml**

> jobs:
>   - name: shipdemo-manifest
>     type: manifest
>     steps:
>      - IN: shipdemo-img
>      - TASK: managed
> 
>   - name: shipdemo-test-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest
>       - IN: shipdemo-img-options
>       - IN: ecs-test-cluster
>       - TASK: managed
>         deployMethod: replace

For example I already deployed an image#1 and it works
The problem is when I'm trying to deploy image#2 into docker that running image#1 nothing happens.
Image appears in the list of images but container still runs image#1. 
Every time that I make a build I want to replace an image with the newest one. Any suggestion?

**Comment by trriplejay** [comment]
Hi @glozhkovoy ,
You've almost got it all set up.  You're missing a couple items.  You need to link the image created in CI directly to your image resource.  You'll these lines in your post_ci, after your push:
```
echo "versionName=latest" >> shipdemo-img.env
echo "commitSha=$COMMIT" >> shipdemo-img.env
```
The way shippable knows to update your image is by detecting a change in the image's version.  If you're using the 'latest' tag, we can't necessarily tell if the image was actually updated or not, so that's why I've suggested the `commitSha=$COMMIT` line.  This will change with every triggering of CI, and so the image will always be updated and Shippable will always trigger the downstream work.

In order for this to work, you'll have to add one more job to your jobs yml:
```
- name: <project_name>_runCI
  type: runCI
  steps:
    - OUT: shipdemo-img
```

Your project enabled for CI has a `runCI` type pipeline entry created for it automatically, but in order to write out to an image, you'll have to declare this job in your YML so that you can enhance it, by adding the image as an OUT step.  You can see the exact name of this runCI job in your subscription dashboard.  You'll have to make sure the name in your yml matches the name in the dashboard.

Finally, for your deploy job to automatically deploy the image, you'll need to add a `force: true` to the IN step on the manifest.  This is again because with the 'latest' tag, we're not sure if it's different from the previous "latest" tag, and deploy jobs prefer to avoid deploying the same thing multiple times.  `force: true` will deploy it regardless of how the manifest compares to its previous version.
```yml
- name: shipdemo-test-deploy
  type: deploy
  steps:
  - IN: shipdemo-manifest
    force: true
  - IN: shipdemo-img-options
  - IN: ecs-test-cluster
    TASK: managed
    deployMethod: replace
```

Once you've made these adjustments, CI will update your image, which will trigger your manifest, which will trigger your deploy job, and you should see your new image getting deployed successfully!

Let me know if you have any other questions.

**Comment by glozhkovoy** [comment]
@trriplejay Thank for you answer
I added all of the things that you mentioned but nothing happened

My files looks like

**shippable.yml**

> language: node_js
> node_js:
>   - 7.4.0
> 
> branches:
>   only:
>     - master
> 
> env:
>   global:
>     - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
>     - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
>     - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
>     - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
> 
> build:
> 
>   ci:
>     - shippable_retry npm install
>     - docker build -t testshippable .
>     - docker tag testshippable:latest **PATH**/testshiprep:latest
>   post_ci:
>     - docker push **PATH**/testshiprep:latest
>     - echo "versionName=latest" >> shipdemo-img.env
>     - echo "commitSha=$COMMIT" >> shipdemo-img.env
> 
> 
> integrations:
>   hub:
>     - integrationName: ECR_INTEGRATION
>       region: us-west-1
>       type: ecr

**shippable.resources.yml**

> resources:
>   - name: shipdemo-img
>     type: image
>     integration: ECR_INTEGRATION
>     pointer:
>       sourceName: "**PATH**/testshiprep" 
>       isPull: false
>     seed:
>       versionName: "latest"  
> 
>   - name: shipdemo-img-options
>     type: dockerOptions
>     version:
>       portMappings:
>         - 3000:3000
> 
>   - name: ecs-test-cluster
>     type: cluster
>     integration: AWS_INTEGRATION
>     pointer:
>       sourceName : "testshipcluster" 
>       region: "us-west-1" 

**shippable.jobs.yml**

> jobs:
>   - name: shipdemo-manifest
>     type: manifest
>     steps:
>      - IN: shipdemo-img
>      - TASK: managed
>        
>   - name: Test_Shippable_runCI
>     type: runCI
>     steps:
>       - OUT: shipdemo-img
>        
>   - name: shipdemo-test-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest
>         force: true
>       - IN: shipdemo-img-options
>       - IN: ecs-test-cluster
>       - TASK: managed
>         deployMethod: replace
        
Problem still the same. Image was uploaded into amazon repository but not on AWS instance.
I tried also using bash scripts and stop the docker container so it can reload it with newest image but I failed.

**Comment by trriplejay** [comment]
can you try running your CI one more time? it looks like it's set up properly, but i think your CI ran before your rSync could update the resource relationships.

**Comment by glozhkovoy** [comment]
@trriplejay 
I made some changes and pushing them.
On the shippable's dashboard running only **runCI**. Why I need to do in order to run rSync before runCI?

**Comment by trriplejay** [comment]
hey, ok this time i think it's because the manual run had the same commit sha... lets make this change:
instead of `commitSha=$COMMIT`, use this instead:
```
echo "buildNumber=$BUILD_NUMBER" >> shipdemo-img.env
```
This way your image will be considered "changed" even on a manual CI build, since the BUILD_NUMBER changes every time.

To answer your question: rSync only runs when you change your pipeline files (shippable.[jobs|resources|triggers].yml), while CI triggers on any change.  What i'd typically recommend if you're making a pipeline change is to push the commit with `[skip ci]` in the commit message. Shippable will ignore your runCI job if you do this.  Then once rSync completes and updates your pipeline, you can manually run the CI job.

**Comment by trriplejay** [comment]
in the case of making that above change I suggested, you don't need to use [skip ci], you can just make the change and let it run. Hopefully that gets the pipeline going.

**Comment by glozhkovoy** [comment]
It doesn't. Only runCI runs and AWS instance doesn't get my latest image.

**Comment by trriplejay** [comment]
ok... one latest change, my apologies.
```
echo "versionName=latest" >> $JOB_STATE/shipdemo-img.env
echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img.env
```

**Comment by glozhkovoy** [comment]
@trriplejay 
You are the one that answered me and I appreciate your help. Thank you a lot! I will try this one.

**Comment by glozhkovoy** [comment]
@trriplejay 
Still no changes in AWS instance

**Comment by glozhkovoy** [comment]
![image](https://user-images.githubusercontent.com/20016615/29285940-f446ccdc-8138-11e7-8346-1560ecf1002c.png)

That's latest image inside my AWS instance

**Comment by trriplejay** [comment]
it looks like your deploy job is in progress right now, but it might be having trouble pulling your image, since it seems to be taking awhile.

**Comment by trriplejay** [comment]
the deploy job will give up after 10 minutes and print the latest messages from ECS, which should indicate what went wrong.  Alternatively you can check the service on your ECS cluster to try and figure out why the image isn't being pulled or started.

**Comment by glozhkovoy** [comment]
Cluster contains 2 services
![image](https://user-images.githubusercontent.com/20016615/29286447-c47bda68-813a-11e7-9687-2c8a885f4d7e.png)

First one have these events

![image](https://user-images.githubusercontent.com/20016615/29286541-12e425a2-813b-11e7-864f-621d61c47957.png)

That's the second
![image](https://user-images.githubusercontent.com/20016615/29286598-4cbbc726-813b-11e7-9189-749b551ff7ae.png)

It seems like I need to force docker run

**Comment by trriplejay** [comment]
it looks to me like shipservice is running successfully, but is using the same port that the auto-deployed service is trying to use. Did you create this service manually? If so, i'd recommend scaling it down to 0 (or maybe deleting it if it's running the same thing as the shippable deployment), then running the deploy job again from the shippable UI.

**Comment by glozhkovoy** [comment]
Yep, I did it manually. When I scale down the number of tasks it finally starts working. You helped me a lot, thank you!
My latest question is -- if I want to delete unused images I need to do it with scripts or shippable has something for this ?

**Comment by trriplejay** [comment]
we don't do any automatic removal of unused images. You'll have to do that manually or write a script.  There is some ECR documentation on how to accomplish that:

cleaning up from ecr:
https://aws.amazon.com/blogs/compute/automated-cleanup-of-unused-images-in-amazon-ecr/
You could run this script in a shippable runSh job on a timer (nightly, weekly, etc) or add it to your pipeline somewhere else (after deployment, maybe?)

looks like amazon already does some automatic cleanup from the instances themselves:
https://github.com/aws/amazon-ecs-agent/issues/118

**Comment by glozhkovoy** [comment]
Thank you for time that you spent with me and your advises / setup instructions!

**Comment by trriplejay** [comment]
You're welcome. Let us know if you have any other questions!

**Comment by guruprasad85** [comment]
i have configured the same. but manifest not triggered after CI build.

build:
  on_success:
    - echo CI Running
    - export IMAGE_NAME=123.amazonaws.com/services-api
    - export TAG_NAME=test-services
    - sudo docker build -t $IMAGE_NAME:latest .
    - sudo docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG_NAME
    - sudo docker push $IMAGE_NAME:$TAG_NAME
    - sudo echo "versionName=$TAG_NAME" >> $JOB_STATE/test-services-api-img.env


jobs:
  - name: services-api_runCI
    type: runCI
    steps:
      - OUT: test-services-api-img


Is there any problem. please help me to resolve.

**Comment by a-murphy** [comment]
guruprasad85, your image resource is most likely not updated because the `$TAG_NAME` isn't changing.  The image resource will only be updated if something changes.  Most often, `$BUILD_NUMBER` is used in the tag to generate a unique tag for each run.  You can also set another field that changes to trigger the jobs following the image resource, but will likely need to force-deploy in your deploy job to make sure the image is updated when the tag is unchanged in the manifest.  If this doesn't solve your problem, could you please open a new issue with either a link to the job that is not triggering your manifest job or the project or job ID from the bottom right corner of that page?
