### ISSUE TITLE
disable a non-buildable project

### ISSUE THREAD

**Issue by yingqiaomxi** [Shippable/support#3815]
### Description of your issue:
NOTE: . By accident, I enabled a non-buildable project. I could not disable it. The message that: No projects found for projectId(s): 57e594b7fa747a0f008ab6b8  appears
The project is mxitechnologies/lrp-deploy
- Link to the build failure: https://app.shippable.com/subs/bitbucket/mxitechnologies/enable

- Scripts called from the yml (optional)

**Comment by ambarish2012** [comment]
Project that the Ying wants to specifically disable is `lrp-deploy`.

**Comment by trriplejay** [comment]
We've gone ahead and disabled this, seeing as it only had 2 builds, both of which showed that there was no shippable.yml.  The error is because while a project collaborator is allowed to enable, only project admins can disable. In the future you can also resolve this by asking someone with admin permissions on the project to disable it.
