### ISSUE TITLE
Elasticsearch version mismatch causes build failure

### ISSUE THREAD

**Issue by ratpik** [Shippable/support#3821]
### Description of your issue:

We use ElasticSearch 2.x in development and production. But Shippable seems to be only supporting 5.x version of Elasticsearch now.

All our builds are now failing with message - 

> Error creating index

 while running tests that connect to Elasticsearch. Is there a way to specify a version for Elasticsearch? We do not want to change our code to update to Elasticsearch 5.x.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure - https://app.shippable.com/bitbucket/postmanlabs/universal-search/runs/505/1/console

- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
We don't currently allow a version of Elasticsearch to be specified in `shippable.yml`.  However, you can install Elasticsearch yourself instead of listing it in the `services` section of your `shippable.yml`.  This can be done either by adding commands to your `shippable.yml` to install Elasticsearch or by building [your own image](http://docs.shippable.com/ci/custom-docker-image/) with the version of Elasticsearch you want to use.  Either way, you'll also have to start Elasticsearch in your build; it won't start automatically.

If you decide to build your own image, I would suggest using the Shippable image on which your build currently runs as the base image, installing the version of Elasticsearch you want, and pushing it to Docker Hub or another image registry.  Then specify your new image in the `pre_ci_boot` section of your `shippable.yml` and start the services you need with commands in the `ci` section.

**Comment by ratpik** [comment]
👍
