### ISSUE TITLE
post_ci is executed outside of provided container

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#3825]
Our shippable ci is configured to be executed in a provided container:
build:
  pre_ci_boot:
    image_name: <image>

and ci steps are running inside the container.
Logically we are expecting that post_ci will be executed inside container too.

> shippable docs: Commands in the post_ci section are executed inside the build container.
http://docs.shippable.com/ci/why-continuous-integration/

But we see that post_ci go executed outside off container.

**Comment by depohmel** [comment]
Also, we have seen the same inconsistency with on_failure

**Comment by a-murphy** [comment]
Could you include a job where you see this and how you are determining that your commands are running outside the build container?  The `post_ci` and `on_failure` sections are a part of the same Bash script as the `ci` section and run in the build container.

**Comment by depohmel** [comment]
https://app.shippable.com/github/kastenhq/k10/runs/6966/1/console
this one is for on_failure  our image does contain go.  
You can that ci is using go cmd

**Comment by depohmel** [comment]
and this one for post_ci 
https://app.shippable.com/github/kastenhq/k10/runs/6974/1/console 
the same thing go is missing which equals code got executed outside on of image.

**Comment by trriplejay** [comment]
I notice that your script is setting PATH in CI, but does not seem to be setting PATH in the other sections. Since that variable is set inside the script that runs as a sub-process, it will only be local to that script (and any of its own sub-processes) but it will not be available to the subsequent sections of CI. I'd recommend setting path in each of your scripts. You could also use `export PATH=...` as its own line directly in CI if you wanted to just set it once and have it be available for all sections.

**Comment by depohmel** [comment]
@trriplejay , thanks for finding this. 
We actually have this PATH update in our image, but it's not getting an effect in current execution. 
I've have made a couple of changes to our scripts. Testing them now.

**Comment by depohmel** [comment]
It works now. Thanks for the help. 
The bug can be closed.

**Comment by trriplejay** [comment]
awesome, glad that worked!
