### ISSUE TITLE
"no basic auth credentials" Error When Pushing to Repository

### ISSUE THREAD

**Issue by ceecer1** [Shippable/support#3841]
Manually pushing the image to ecs repository works fine, but while pusing via shippable build post ci, the error in the title occurs.

May be shippable build container also needs to run on the same region, not sure about this.

**Comment by manishas** [comment]
Hi @ceecer1 I suspect it's an indentation issue with the yml. Can you either post the yml here or send it to me at manisha@shippable.com?

The reason I suspect this is because if you go to your build page, choose the yml tab, and expand the integrations section, it doesn't show your hub integration. This means our parser could not read the integration for some reason.

**Comment by ceecer1** [comment]
Hi @manishas, not sure, why I do not see yml tab in the build page.

**Comment by ceecer1** [comment]
Thanks, fixing indentation issue worked well.
