### ISSUE TITLE
PEM integration in CI step not setting the _KEYPATH env var

### ISSUE THREAD

**Issue by pstreef** [Shippable/support#3848]
I'm trying to use PEM integration in my CI step

However I'm getting the following error, indicating that the env variable is not set (note i have also tried all capitals for the env var):

```
cp $ca_cert_KEYPATH /certs/ca.pem
cp: missing destination file operand after '/certs/ca.pem'
Try 'cp --help' for more information.
```

I've defined the PEM integrations as resources like this:

```
resources:
  - name:           ca_cert
    type:           integration
    integration:    ca_pem
  - name:           client_cert
    type:           integration
    integration:    cert_pem
  - name:           client_key
    type:           integration
    integration:    key_pem
```
I'm trying to move these files into a known location in the CI step (I need them for an integration test step).

I'm having trouble using the \<name\>_KEYPATH variable that the [docs](http://docs.shippable.com/platform/workflow/resource/integration/) say should be set when using this resource as an INput

My jobs file looks like this:
```
jobs:
 - name: my_runCI
    type: runCI
    steps:
      - IN: ca_cert
      - IN: client_cert
      - IN: client_key
```

And the relevent part of my base yml looks like this:

```
build:
  ci:
    - mkdir -p /certs/
    - cp $ca_cert_KEYPATH /certs/ca.pem
    - cp $client_cert_KEYPATH /certs/cert.pem
    - cp $client_key_KEYPATH /certs/key.pem
```

**Comment by a-murphy** [comment]
Could you try using the environment variables `$CA_CERT_KEYPATH`, `$CLIENT_CERT_KEYPATH` and `$CLIENT_KEY_KEYPATH`?  The documentation isn't very clear about how the resource names are changed to turn them into valid environment variables.  We remove any characters that are not letters, numbers, or underscores, and then capitalize the name.  So `ca_cert` becomes `CA_CERT`.

**Comment by pstreef** [comment]
As stated in the OP I have tried all capitals and it did not work either. I've added echo's before the cp step and they output nothing for both lowercase and uppercase options.

**Comment by a-murphy** [comment]
Could you include a link to the failing build, or the project ID from the bottom of that page?  The `$CA_CERT_KEYPATH` should be defined for an input resource with a `pem-key` integration and we don't see anything wrong snippets above other than the capitalization.

**Comment by pstreef** [comment]
Sure, it is a private repo/build. ID: 59b675beb54e3d0700f4fe9a

**Comment by a-murphy** [comment]
The `resources.yml` and `jobs.yml` files update Shippable Assembly Lines through `syncRepo`s.  A particular branch in a repository is added as a `syncRepo` following [these directions](http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/) in order to create (and later update) the resources defined in that `shippable.resources.yml`.  Your subscription doesn't have any `syncRepo`s, so the integration resources were never created and the `runCI` job doesn't know to use them.

You have two choices to add the PEM keys to your build:
1.  You can either add your repository with the `shippable.resources.yml` and `shippable.jobs.yml` as a `syncRepo`.

2.  Or you can add the integrations directly to your [`shippable.yml` file](http://docs.shippable.com/ci/yml-structure/#keys) in the `integrations: keys` section.  If you decide to add the integration to your `shippable.yml` file, you will not have any environment variables for the path to the keys; they will be in `/tmp/ssh/` and the file name will be the alphanumeric characters in the integration name (underscores removed).
The format for an `ssh-key` integration in `shippable.yml` is:
```YML
integrations:
  key:
    - integrationName: my_custom_key
      type: pem-key
```

**Comment by pstreef** [comment]
I've got it working now. It was indeed the sync repo that was my first step and then some other yaml based issues. Thanks for the help!

ps. Sorry for the late response. I've been on holiday the last few days.
