### ISSUE TITLE
build just stops: how to debug?

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3867]
folks,

working on porting an existing build over to shippable.

this build just dies - it doesn't trigger `on_failure` nor `on_success` - and the trap wrapper that's running the `npm build` that handles failure detection never fires.

I can run this same build in the same custom build container locally successfully.   Since `on_failure` doesnt trigger, I can't upload the broken container state to ECR...

What's the best path to debug this moving forward?

example failure:
(url removed, no longer relevant)

**Comment by a-murphy** [comment]
We've seen a similar problem before when processing logs containing a large npm tree.  In that case, redirecting output from the `npm install` command to `/dev/null` was the only solution found to reliably work because it was the only way to not print the tree.  Only standard out needs to be redirected.  Standard error can still be printed because it doesn't have the tree.  Or, alternatively, it looks like npm versions 5.0.0 and later don't print a tree.

**Comment by keen99** [comment]
thanks, testing around that now.

is this something specific to  `npm install` (and/or `npm list`) outputs (doing something bad with tty or something?), or any command that might output large volumes (but less than the shippable log limits)?

**Comment by a-murphy** [comment]
It's not always `npm install`, although most of the few cases we've seen have been, so we believe it to be related to the speed at which the logs are printed and may be related to buffering.  Unfortunately we also usually can't get the error to appear when we expect it to and can typically output a lot more logs than an npm tree.

**Comment by manishas** [comment]
@keen99 is this working for you now?

**Comment by keen99** [comment]
thanks yes - I'm just doing a `| tail -n1000` from the process that kicks `npm install` for the moment and that unbreaks things.
