### ISSUE TITLE
2 Links in docs search don't work and docker question

### ISSUE THREAD

**Issue by dankonino** [Shippable/support#3870]
### Description of your issue:
Hi I experienced that two links in screenshot in docs don't work
<img width="345" alt="screen shot 2017-10-03 at 11 41 21 pm" src="https://user-images.githubusercontent.com/8626427/31159092-86a6ddf6-a894-11e7-8e42-cea4cba56843.png">

I also would like to ask you about my thing with starting up docker inside of your shippable docker.
I do `gcloud docker -- pull ` in `before_install` part and also have `services: -docker` specified (which I don't think is right). but when I try to restart the service in `install` part of`shippable.yml` like this `sudo service docker.io restart` or without `io` I get error  `Attempting to restart the Docker service... docker: unrecognized service`

So I would like to know what's my best option to fix this. 
Since I already started installing docker in yml from the [official source](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#recommended-extra-packages-for-trusty-1404) 
running this ` sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual`
I got `E: Unable to locate package linux-image-extra-3.19.0-51-generic` which is not that much of your issue(or is it related to being able to find [official pacakges ?](https://packages.ubuntu.com/trusty-updates/kernel/) so I proceed with rather these two commands for hopefully proper installation 
`- sudo apt install linux-image-generic-lts-vivid linux-image-extra-virtual-lts-vivid`
`  - sudo apt-get install linux-image-extra-virtual`
but then on this install script : `sudo apt-get install docker-ce`
I saw this.
`dpkg: error processing archive /var/cache/apt/archives/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb (--unpack):`
`unable to make backup link of './usr/bin/docker' before installing new version: Invalid cross-device link`
Which makes me wonder if I am doing this whole thing right. Hopefully you see something I don't see, in this special case since we need to run docker inside your docker.

**Comment by a-murphy** [comment]
We mount Docker on the host to the build container to make Docker available in the build.  This means that you should be able to start or stop containers on the host from when running your build and those containers will run alongside the build.  I would not suggest restarting Docker though; it would affect the build container. 

Is there a reason you need to run Docker inside the build container, or could you use the currently available Docker running on the host?  I'm not sure if it's possible to unmount Docker from the running build container and we don't have an option to not mount Docker right now.  The error you got while installing is because that is the location where Docker is mounted.

Where did you find the docs links that don't work?  I just tried searching "docker" at docs.shippable.com and didn't get those search results.  Here are some pages that might be relevant, depending on what you're trying to do with Docker:
  - [Pushing a Docker image to GCR](http://docs.shippable.com/ci/push-gcr/)
  - [Using Docker Compose in CI](http://docs.shippable.com/ci/docker-compose/)
  - [Using a Custom Docker Image](http://docs.shippable.com/ci/custom-docker-image/)

**Comment by dankonino** [comment]
Thank you. If I am able to start the docker container inside I should be good. I let this open till it's resolved. 
And I can't find the link where I searched for docker, but these were broken http://docs.shippable.com/deploy/howto-configure-deploy-replicas/#scenarios 
http://docs.shippable.com/deploy/howto-configure-deploy-envs/#scenarios

**Comment by ambarish2012** [comment]
@dankonino the broken links have been fixed. If you search for `docker push` or `docker compose` you will find those links.

**Comment by dankonino** [comment]
Okay thank you guys. This is solved since docker looks running for me since I saw right output plus this `the input device is not a TTY`  after I started up what was needed. Thank you for the help and right info 
Thanks and keep up the good work 💯 👍
