### ISSUE TITLE
AWS integration issue - updating integration credentials

### ISSUE THREAD

**Issue by goodway-wmccarthy** [Shippable/support#3885]
We had AWS integration setup a few months ago and it continues to run today. We need to change the integration at this time to be owned by our main user. When we attempt to add the new integration of the same type (family: deploy, Account Integration: aws), the aws option under Account Integration is no longer available.

Did you update the integration configuration and remove the AWS Account Integration? If so, how can I add a new AWS integration?

**Comment by a-murphy** [comment]
The AWS integration has been deprecated.  You can create a new [AWS Keys integration](http://docs.shippable.com/platform/integration/aws-keys/) and use it instead of the AWS integration.  AWS Keys will be listed as a "generic" integration on the new account integration page.

If you are using the environment variables for the AWS integration in a runSh or runCI job, you will need to update your scripts because the variable names for the access key and secret will change (`<NAME>_INTEGRATION_AWS_ACCESS_KEY_ID` and `<NAME>_INTEGRATION_AWS_SECRET_ACCESS_KEY` to `<NAME>_INTEGRATION_ACCESSKEY` and `<NAME>_INTEGRATION_SECRETKEY`), but other than that you should be able to use the new AWS Keys integrations in the place of AWS integrations without further changes.

**Comment by manishas** [comment]
@goodway-wmccarthy I am closing this issue, but please let us know if you need help.
