### ISSUE TITLE
Unable to see repos under Github organisation that I am owner

### ISSUE THREAD

**Issue by thigm85** [Shippable/support#3887]
Hi,

In my Shippable subscription dashboard, I can see all repos (public and private) under my Github user name (thigm85). However, I am unable to see the repos under a Github organisation (AIA Science) that I am owner. I am therefore unable to enable Shippable integration for those repositories.

I am not sure the reason for that as I think those private organisation repos should be visible for my Shippable account.

**Comment by Riturajcse** [comment]
Hi @thigm85, are you able to see your organization name  `AIA Science` in  Shippable sidebar under GitHub section? 

![image](https://user-images.githubusercontent.com/14016521/31443803-1082fb76-aeb8-11e7-9c9e-a49e9a1a5dab.png)


If yes then you need to sync your account by clicking sync button in Account Profile page.
Otherwise, if the organization name itself is not showing you might need to grant organization access for `AIA Science` by visiting `Github->Settings->Applications->Authorized OAuth Apps` (https://github.com/settings/applications) and clicking on `prod-shippable`. After granting access please sync your account in Shippable again.

**Comment by thigm85** [comment]
Thanks. I had to grant access to my organisation. Problem solved.
