### ISSUE TITLE
Format of REPOSITORY_URL env var changed (Bitbucket)

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3894]
Most likely related to the change in Bitbucket which caused #3878 the format of the environment variable `REPOSITORY_URL` has changed.

- Before: `ssh://git@bitbucket.org/<owner>/<repository>.git`
- After: `<user>@bitbucket.org:<owner>/<repository>.git`

Can you restore the previous format, thus overwrite the one coming from Bitbucket?

**Comment by mbrodala** [comment]
@rageshkrishna Can you have a look at this?

**Comment by trriplejay** [comment]
marking this as a feature request and opening an internal ticket to see what we can do.

**Comment by mbrodala** [comment]
For the time being we use the following as workaround:

```sh
  # Convert to old repository URL format
  if [[ "${REPOSITORY_URL}" =~ .+@bitbucket\.org:(.+) ]]; then
    REPOSITORY_URL="ssh://git@bitbucket.org/${BASH_REMATCH[1]}"
  fi
```

**Comment by rageshkrishna** [comment]
@mbrodala Sorry for the late update on this. We've discussed this internally and decided that we will not be fixing this as we'd like to faithfully reproduce what the source control service is telling us. I'm glad you have a workaround.

I'm going to close this issue as we don't plan on making any changes. Feel free to reopen if you feel otherwise.
