### ISSUE TITLE
Custom Node for a single repo in a subscription

### ISSUE THREAD

**Issue by seniorquico** [Shippable/support#3903]
We have a particular project that requires a very heavy build tool-- multi GB download/install. The rest of our projects work great on Shippable's dynamic nodes with the pre-made images. We were hoping to "upgrade" and execute the heavy build on a BYON while leaving the rest of the projects on Shippable's dynamic nodes. However, it appears the nodes on which pipelines are executed are configured at the subscription level. How can we configure just a single project to execute on BYON?

Thanks!

- Kyle

**Comment by ttrahan** [comment]
@seniorquico: This is a feature we have in our backlog. We'll update this issue when it's available. 

Until then, to accomplish what you've described, you would need to do one of the following:
  * Upgrade your dynamic nodes to use one of our larger machine sizes (standard is 2 core/3.75GB RAM - we also offer 4 core/7.5GB and 8 core/15GB). Note that all builds would run on these larger nodes if you select them for your subscription. See more [in our docs](http://docs.shippable.com/platform/tutorial/runtime/dynamic-nodes/).
  * Use a second GitHub organization/account in order to process that project on BYON, while the others are on the standard dynamic nodes

**Comment by seniorquico** [comment]
Thanks, @ttrahan! I'll keep my eye on this issue.

**Comment by manishas** [comment]
This is now in progress and coming up soon :)

**Comment by ambarish2012** [comment]
@seniorquico  we have implemented this feature. After you upgrade to the latest release, you can create a Node pool(s), attach a BYON node to a node pool and assign jobs to that Node pool. Node pools are documented [here](http://docs.shippable.com/platform/management/subscription/node-pools/).
