### ISSUE TITLE
Gradle cache

### ISSUE THREAD

**Issue by danielsuter** [Shippable/support#3913]
Where is the gradle cache on shipable? I would like to only enable caching for gradle artifacts.

**Comment by manishas** [comment]
We'll need to add docs for grade caching, but the general docs on caching are here http://docs.shippable.com/ci/caching/

So if you know what folders you want to cache you can specify them and it should work as expected.

**Comment by danielsuter** [comment]
Thanks for your answer. I found the caching page but I don't know where the gradle cache is located on shippable. I don't know how to inspect the "workspace".

**Comment by a-murphy** [comment]
Assuming you're looking for the [Gradle build cache](https://guides.gradle.org/using-build-cache/), caches should be found in the default location, `~/.gradle/caches`, and you can cache the whole directory by adding `~/.gradle/caches` to your `cache_dir_list` in your shippable.yml.  However, caching can be slower than not using a cache in some cases because of the time required to download the cache.  It's usually best to only add the files or folders that you need to `cache_dir_list`.

**Comment by danielsuter** [comment]
Thanks that's what I was looking for. Didn't know I could use user home of if shippable had a different path configured.
The builds run much faster (3x). Otherwise all dependencies will have to be downloaded each time. So it makes sense to cache them.
