### ISSUE TITLE
rSync error: project is not enabled

### ISSUE THREAD

**Issue by navymaker** [Shippable/support#3927]
Hi,
I've tried to enable pipeline for one of our projects, but rSync build are failed with the following error:

rSync encountered 1 errors while processing openbridge/ob_api_events_init: 
  - Cannot add runCI job, please enable the project before adding job: ob_api_events_init_runCI

But project is actually enabled.

Here is the link to build:
https://app.shippable.com/github/openbridge/jobs/ob_api_events_init_pipeline_rSync/builds/59f71351e07b77070018997b/console

**Comment by ambarish2012** [comment]
@navymaker rSync is failing since the runCI job for the `ob_api_events_init` project is actually `ob_api_events_client`. From our logs, it appears that you renamed your project  and hence the discrepancy between the job name in our system and the project name.

```
Successfully updated resource: ob_api_runCI
Successfully updated resource: ob_api_events_client_ciRepo
Successfully updated resource: ob_chatbot_ciRepo
Successfully updated resource: ob_api_events_client_runCI```

To fix this error, use `ob_api_events_client` in your shippable.jobs.yml file.

**Comment by navymaker** [comment]
Re-enabling this project helps, thanks.
