### ISSUE TITLE
Unable to detele stale resource

### ISSUE THREAD

**Issue by caliagaa** [Shippable/support#3942]
Hi there,

I'm having issues trying to delete a resource

https://app.shippable.com/subs/bitbucket/mxitechnologies/resources/moc-env-staging-ecs/versions

Can you please clean up this ?

Thanks

**Comment by trriplejay** [comment]
It looks like that resource was created by the sync repo "moc-deploy_master".  You can remove the resource by commenting it out (or deleting it) from that repository's shippable.resources.yml

If we manually force a delete, the resource will be added back again the next time sync runs, since it is still part of the yml.

Once you commit a change with the resource removed, the sync job should run and the resource should then show up as a "deleted resource", at which point you can permanently delete it from the UI.

**Comment by caliagaa** [comment]
Oh got it...i will do it as specified..Thanks!!

**Comment by a-murphy** [comment]
It looks like you've been able to delete the resource, so I'm closing this as resolved.
