### ISSUE TITLE
Build failed when exit code is 0

### ISSUE THREAD

**Issue by 1deviljohn1** [Shippable/support#3954]
https://app.shippable.com/bitbucket/visagehall/visagehall/runs/2692/1/console

**Comment by a-murphy** [comment]
Would you be able to use `return 0` instead of `exit 0` in your script?  An `exit 0` in the `ci` section can cause the build section to end without the expected ending line, which makes the build processor think that something went wrong and fail the build.

**Comment by 1deviljohn1** [comment]
What your mean return 0?

**Comment by luckyraul** [comment]
@a-murphy  https://app.shippable.com/bitbucket/visagehall/visagehall/runs/2698/1/console


It started build success, but still -  build failed

**Comment by a-murphy** [comment]
A similar problem is seen when including `exit 0` in the build script, and in some cases `return 0` can be used instead.  I can't see your `gulp lint` script.

If you don't have `exit 0` in your script, and you're sure the exit code is 0, you might be running into a problem we've seen rarely where the build runner is unable to process large groups of logs printed very quickly.  Those errors don't happen very consistently and the only solution we've found for them is to log less.  So, you could try logging less to see if it goes away.

**Comment by luckyraul** [comment]
1) we tested locally - exit code is 0
2) what about shippable running build_success?

**Comment by a-murphy** [comment]
The build script runner is definitely missing the ending line of the script output, which means that either the script suddenly exited before it got to `on_success` or the output logs went missing.  The "Invalid or no script tags received"  message (which appears in the downloaded logs) is almost always because the script exited and the build was unable to continue, but is also seen occasionally when the build script runner is unable to process large groups of logs.  Basically, the build didn't run long enough to get to the `on_success` section.
