### ISSUE TITLE
Skipped: You do not have minions to run this job

### ISSUE THREAD

**Issue by danielmenezesbr** [Shippable/support#3955]
I am getting this error `You do not have minions to run this job. Please contact Shippable if you think this is a mistake.`

Project Id: 58cd4cf5e832fb0800d98f60

update:
  My job doesn't use bitcoin miners.
  Others references: #3428 #3537

**Comment by manishas** [comment]
@danielmenezesbr Sorry for the delay in responding to this! We recently started receiving many 'malicious usage' reports from AWS about our nodes being used for port scanning. We narrowed down the problem nodes to your subscription so it looks like one of your projects does port scans.

If you can disable the project that does scans, we can re-activate your subscription. Another alternative is to use [Custom hosts](http://docs.shippable.com/platform/runtime/nodes/#custom-nodes) so that you're using your own nodes for your jobs.

**Comment by danielmenezesbr** [comment]
@manishas, thanks for your response.

I disabled the job that does port scan.

This job matters to us. It points only to a specific host (our server), runs only once a day, and spends about a minute. Maybe we should look for another service to do that.

It might be interesting to include in the Shippable documentation what a job can not do. Although there was only one port scan job, all jobs were disabled. This is a bit frustrating.

**Comment by manishas** [comment]
@danielmenezesbr thanks for the clarification. I agree that your job was only scanning your own server, but it started triggering repeated AWS notifications at our end which we cannot turn off since at some point, a user might be port scanning maliciously and we'd need to know that. 

I will make sure docs are updated for this... and also enable your subscription right away.

**Comment by manishas** [comment]
@danielmenezesbr your builds should trigger as expected now.
