### ISSUE TITLE
"parallelized_test: true" runs success/failure block twice

### ISSUE THREAD

**Issue by lukehutton** [Shippable/support#3988]
I have two set of unit tests to run in parallel, both fail, however, two success blocks are running in each build group. 

I would expect the on_failure section to be called only once. However, it is executing on_success twice.

- Build: https://app.shippable.com/bitbucket/xeraflop/duber-pos/runs/58/summary/console
- Shippable.yml:

```
language: node_js

node_js:
  - 8.6.0

# This tag will ensure that your after_success or after_failure steps will be executed only once for the build group.
# http://blog.shippable.com/shippable-v2-what-works-differently-from-v1
parallelized_test: true
env:
  matrix:
    - TEST_SUITES=web_unit_tests
    - TEST_SUITES=server_unit_tests

build:
  ci:
    - npm install -g yarn
    - yarn && cd web && yarn && cd ..
    - mkdir -p shippable/codecoverage/$TEST_SUITES
    - mkdir -p shippable/testresults/$TEST_SUITES
    - if [ $TEST_SUITES = 'web_unit_tests' ]; then
          cd web;
          yarn run coverage --coverageDirectory=../shippable/codecoverage/web_unit_tests --coverageReporters=cobertura --testResultsProcessor ./node_modules/jest-junit;
          mv junit.xml ../shippable/testresults/web_unit_tests/;
          cd ..;
      fi;
    - if [ $TEST_SUITES = 'server_unit_tests' ]; then
          yarn run test-server-coverage;
          mv coverage/*.xml shippable/codecoverage/server_unit_tests/;
      fi;

  on_success:
    - echo "Build success, this should only run once..."
    - if [ $PULL_REQUEST = 'true' ]; then
          echo "skipping tagging and push artifacts for pull requests...";
      fi;
    - if [ $PULL_REQUEST = 'false' ]; then
          echo "tagging build for release...";
          git tag -a build-v$BUILD_NUMBER -m "build-v$BUILD_NUMBER";
          git push --tags;
      fi;

  on_failure:
    - echo "Build failed, this should only run once..."
```

**Comment by a-murphy** [comment]
The `on_success` step is running because the `ci` step did not return an error.  An unstable status means that the tests failed and all of the commands returned exit code 0.  We won't determine that it's unstable until we parse the test results.

There isn't currently a way to run `on_success` or `on_failure` only once in a CI matrix.  However, you can add a `runSh` job in an Assembly Line to run your commands after your runCI job, which would only run once for the matrix and take unstable statuses into account.

To add a `runSh` job,  you'll need to [add a syncRepo](http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/) (it can be the same Bitbucket repository as your CI job or a different one) with a [runSh](http://docs.shippable.com/platform/workflow/job/runsh/) job defined in the `shippable.yml`.  The runSh job should have your runCI job listed as an `IN` resource so that the runSh job will be triggered for each successful CI run.  You will also want to add a [gitRepo](http://docs.shippable.com/platform/workflow/resource/gitrepo/) resource to your `shippable.yml` and as an `IN` resource (with `switch: off`) on the `runSh` job to clone your git repository for the runSh job.

The build number and SHA can be made available in the runSh job by saving them to the runCI state.  You can use [`shipctl put_resource_state`](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#put_resource_state) to save values that will be available in the runSh job.  The `shipctl` commands will work in the `push` section of your CI `shippable.yml`, or you can update to a newer build image (by [updating your subscription](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-subscription-machine-image) or specifying an image in the `pre_ci_boot` section) and use them in the CI section.  For example, `shipctl put_resource_state duber-pos_runCI BUILD_NUMBER $BUILD_NUMBER` will copy the build number, and you can get it in the runSh job with [`shipctl get_resource_version_key duber-pos_runCI BUILD_NUMBER
`](http://docs.shippable.com/platform/tutorial/workflow/access-resource-data/#get-value-for-a-key).  Then you'll be able to check out the same commit as in CI and tag it.

**Comment by lukehutton** [comment]
Thanks for feedback. Ok, thanks for explanation on unstable, I will get it to return error codes so it will fail.

Just for clarification, I thought this feature was supported already (running only one success block)?
"This is also useful if you parallelize your test suite to run across minions and get results faster. While we’re on this point, we have also added a yml tag parallelized_test: true if you’re splitting your test suite to run across minions. This tag will ensure that your after_success or after_failure steps will be executed only once for the build group." from http://blog.shippable.com/shippable-v2-what-works-differently-from-v1 and also mentioned in https://github.com/Shippable/support/issues/279

Sure, I can build out a separate process for adding a single on_success hook for the entire build, do you guys have any sample shippable files for that?

**Comment by a-murphy** [comment]
Both the blog post and that support issue are over three years old.  The CI build runner has changed substantially since then.

I couldn't find any sample projects for this case, but this one has a runSh job with a gitRepo input and may be helpful: https://github.com/devops-recipes/provision-aws-ansible/blob/master/shippable.yml

Including your runCI job as an `IN` will trigger the runSh job when the CI run is successful, and adding `switch: off` to the other inputs keeps them from triggering the runSh job when they are updated.

**Comment by lukehutton** [comment]
Aww ok, was looking for output maybe to spit out deprecated then for line parallelized_test: true, all good.

Ok will try and hack together single hook, even not, back to single builds. Thanks for help.

**Comment by lukehutton** [comment]
Ok proof of concept, got it working, thanks, can close issue.

```
resources:
  - name: duber_pos_repo_dev
    type: gitRepo
    integration: provision-duber-pos
    pointer:
      sourceName: xeraflop/duber-pos
      branches:
        only:
          - dev
    flags:
      - duber-pos_rSync

jobs:
  - name: provision_duber_pos_dev
    type: runSh
    steps:
      - IN: duber-pos_runCI
      - TASK:
        - script: |
            export BUILD_NUMBER=$(shipctl get_resource_version_key duber-pos_runCI BUILD_NUMBER)
            echo "tagging build $BUILD_NUMBER for release...";
            #todo build image and deploy for environment dev, etc.
            cd $DUBER_POS_REPO_DEV_STATE
            git checkout $DUBER_POS_REPO_DEV_COMMIT;
            git tag -a build-dev-v$BUILD_NUMBER -m "build-dev-v$BUILD_NUMBER";
            git push --tags;
      - IN: duber_pos_repo_dev
        switch: off
    flags:
      - duber-pos_rSync
```

**Comment by a-murphy** [comment]
Great!  Let us know if you run into any other problems.
