### ISSUE TITLE
Please delete integration

### ISSUE THREAD

**Issue by JaZo** [Shippable/support#4006]
I can't delete this integration: https://app.shippable.com/subs/bitbucket/swisnl/integrations/3311. Can you please delete it for me? Thanks!

> delete subscriptionIntegrationPermissionById for id: 1290 returned error: No projects found for projectId(s): 5845bb579d09cc0f0055dbda

**Comment by a-murphy** [comment]
That subscription integration was configured so that only one project has permission to use it.  Permission on the project is required to delete the integration as a result.  Based on the error message, it sounds like you don't have write access to that project.  However, since there other accounts that have write access and the project is enabled, I can't conclude that the integration is not in use.  Could you ask someone in your team with write access to that project to delete the integration?

**Comment by JaZo** [comment]
Thanks for the answer! A team member with write access got the same error. After toggling permissions to 'selected projects' and back to 'all projects', he managed to delete the integration.
