### ISSUE TITLE
ActiveRecord::NoDatabaseError: FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by jeremiahlukus** [Shippable/support#4018]
Build Failure: https://app.shippable.com/github/stordco/order-inventory/runs/47/1/console
```
  before_script:
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database order_test' -U postgres
 script:
   - bundle exec rails db:migrate RAILS_ENV=test
   - bundle exec rspec

```

After my Database it created in the before script when i try to run `bundle exec rails db:migrate RAILS_ENV=test` The build fails with 
```
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "root" does not exist
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `rescue in connect'
```

I have tried these variations 
```
  3   - bin/rake db:migrate RAILS_ENV=test
  2   - bin/rake
  1   - xvfb-run bundle exec rspec spec/features/shipper
37    #- bundle exec rails db:migrate RAILS_ENV=test
  1   #- bundle exec rspec
  2   #- xvfb-run bundle exec rspec spec/features/shipper
```

I am close to reaching 50 builds for just setting this up.

**Comment by a-murphy** [comment]
It sounds like you're trying to connect to the Postgres database as a user that doesn't exist.  You can either specify a user when connecting to the database (the `postgres` user should work, as it was used in the previous command) or add a new user.

If you decide to specify a user instead of defaulting to the current operating system user, this may help: https://stackoverflow.com/questions/27225524/fatal-role-root-does-not-exist.

And if you choose to create a new role "root," there's an example of how to create another database user in [our Postgres documentation](http://docs.shippable.com/ci/postgresql/#continuous-integration-with-postgres).  For a role named "root," the command should be `psql -c 'create role root with superuser;' -U postgres`.

**Comment by jeremiahlukus** [comment]
```
  psql -c 'create database myapp_test' -U postgres  
CREATE DATABASE

  psql -c 'create role root with superuser;' -U postgres 0s  
CREATE ROLE

  bin/rake db:migrate RAILS_ENV=test 4s  
rake aborted!
PG::ConnectionBad: FATAL:  role "root" is not permitted to log in
```

Still not letting me after adding `psql -c 'create role root with superuser;' -U postgres`

**Comment by jeremiahlukus** [comment]
"the postgres user should work, as it was used in the previous command" 
Can you explain this? I'm still unsure why I'm not able to connect.

 I do not want to specify a new user or anything I just want it to connect.

**Comment by a-murphy** [comment]
In your `psql` commands, the `-U postgres` is telling psql to connect as with user `postgres`.  So the `postgres` user definitely exists and is able to connect.

Could you try `psql -c 'create user root with superuser;' -U postgres` instead of `psql -c 'create role root with superuser;' -U postgres`?  Depending on how you're specifying the database configuration for your `db:migrate` command, it may still complain about passwords, but it should get past the "not permitted to log in" error.

**Comment by jeremiahlukus** [comment]
Ah great this worked! Now my tests are running. Thank you

**Comment by bishwas-bh** [comment]
It's because you might haven't configured your PostGreSql well, [this source](https://webmatrices.com/d/1258-activerecordnodatabaseerror-or-connectionnotestablished-fatal-role-does-not) worked well for me.

**Comment by jeremiahlukus** [comment]
Issue has been closed for 5 years lol
