### ISSUE TITLE
Unable to delete account, remove integrations

### ISSUE THREAD

**Issue by monocongo** [Shippable/support#4029]
I am unable to work out how to disassociate my project's repository from Shippable. I can't delete my account due to database errors, and now every click on the Shippable site gives me an "invalid API token" message. I can't see anything in my github settings for the repository that mentions shippable, but everytime I push code I see a red X from Shippable in the github status (although with Travis CI and others the build is fine) so something is still connecting the repo to Shippable, I just can't figure out what/where.

Can someone please walk me through the steps to walk away clean, with no more Shippable association with my repository?

Thanks in advance for your help!
 
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by monocongo** [comment]
I can't seem to login to the site at all now due to the aforementioned invalid ApiToken issue. Does this mean I need to clear a cache in the browser or something like that in order to login again?

**Comment by a-murphy** [comment]
The error while attempting to log in is because the account deletion deleted an account token stored in a cookie.  You can clear this cookie by going to https://app.shippable.com/logout, and a new token will be generated if you log in again.

Projects are usually removed from Shippable by going to the project settings page and clicking the delete button at the bottom.  (Project settings documentation available [here](http://docs.shippable.com/platform/management/project/settings/).  To get to the project settings page, click on the gears in the top right corner of the project dashboard.) This will remove the build history on Shippable and the webhook triggering the new builds on GitHub.  If you can't see the delete button, you'll need to ask someone with admin permissions on the repository to delete it.

**Comment by monocongo** [comment]
Thanks so much for your help.

When I come back around to trying Shippable again for my project can you
advise a simple configuration? I'm unaware of a .*rc file for Shippable or
a similar method of configuration. Can you reference a link to the relevant
documentation?

​Thanks again!​
​
--James​

**Comment by a-murphy** [comment]
Build configuration is in a [shippable.yml](http://docs.shippable.com/ci/yml-structure/) file at the root of the repository.  We have basic examples for each supported language [here](http://docs.shippable.com/ci/supported-languages/).  Let us know if you run into any problems configuring shippable.yml files or if you're looking for an example of something more specific.
