### ISSUE TITLE
Support language settings for runSh

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4036]
feature request - specify node version as in runCI job

**Comment by manishas** [comment]
If you use the [official Shippable node image](https://hub.docker.com/r/drydock/u16nodall/) as [a custom image with runSh](http://docs.shippable.com/platform/tutorial/workflow/use-custom-image/), language specific settings are taken care of (such as exporting NVM_DIR). 

At this time, we do not plan to offer a separate `language` setting in runSh since that comes with it's own complexity and runCI already has that. I'm closing this issue as deferred, if we hear many +1 comments, happy to bring back in scope.
