### ISSUE TITLE
How can I see the TestNG output result after my test completed on shippable?

### ISSUE THREAD

**Issue by tarpanMpatel** [Shippable/support#4041]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

Account link:
https://app.shippable.com/github/Falkonry/ui-test-automation/runs/117

I am using the TestNG and Selenium web driver in java, My build run successfully, but I want to see the exact TestNG report after build run. How can I see it? Please help me. 

Thanks in advance.

**Comment by a-murphy** [comment]
It looks like your test report was correctly parsed.  The total tests passing and failed appear at the top of the page and on the tests tab.  There is usually more information on the tests tab for failing tests, but we don't display the original test report.

The most common method of accessing artifacts after the build is complete is to upload the files to your own S3 bucket, documentation available [here](http://docs.shippable.com/ci/push-to-s3/).

**Comment by tarpanKiwiqa** [comment]
Yes, Total test cases passed and Failed showing me correctly.
But as TestNg generating the complete HTML test-output report, I need this report.

I want to see the complete steps and also wants to see that where my scripts was failed.

**Comment by trriplejay** [comment]
Unfortunately we don't support displaying these files in the Shippable UI today.  I'd say your best option is to use s3 to store these files as the previous comment suggested.  I'll mark this as a feature request for the ability to display these files in the Shippable UI.

**Comment by tarpanKiwiqa** [comment]
Hi, 
Right now my junitreprots stopped to parse. I am not getting the reports. From last 10-12  builds, Test report stopped to parse.

**Comment by a-murphy** [comment]
The report isn't being parsed when your build fails because it isn't being copied to `shippable/testresults`.

There are two ways that you can solve this:

You can update your test configuration to specify the `shippable/testresults` directory instead of `test-output` and remove the `cp` command from your `shippable.yml`.  [This Stack Overflow answer](https://stackoverflow.com/questions/22996542/how-to-config-testng-test-output-folder-to-be-inside-maven-target-folder/27100056#27100056) should help if you decide to do that.

Or you can add the same `cp` command in your shippable.yml to the [on_failure](http://docs.shippable.com/ci/build-and-test/#on_failure) section in `build`.  Then the `cp` command in `ci` will copy the test reports when it's a success and the command in `on_failure` will copy them when it fails.

**Comment by manishas** [comment]
Closing in favor of https://github.com/Shippable/support/issues/1582 which is tracking Test results improvements. 

Another issue that is related is this one: https://github.com/Shippable/support/issues/2444 If we provide a way to archive some files, you can download it.
