### ISSUE TITLE
Builds failed, but never finishes

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#4055]
### Description of your issue:
Perhaps due to the bitbucket integration and bitbucket being more or less down, but we *should* be able to at least cancel the builds. Queued builds are piling up...

- Link to the build failure
https://app.shippable.com/bitbucket/uberresearch/radar/runs/3962/1/console
https://app.shippable.com/bitbucket/uberresearch/radar/runs/3961/1/console

- Scripts called from the yml (optional)
Not really needed - we have done a ton of builds with this.

**Comment by a-murphy** [comment]
A cancel button should be shown on queued and processing runs for accounts that have at least write access to the repository.  It's possible that we may have been unable to determine that some accounts had write access last time they were synchronized because of the Bitbucket errors.  If this is the case, clicking the "sync" button on the account profile page should update the account with the correct permissions and make the cancel button visible again.

**Comment by sdlarsen** [comment]
No buttons shown, but things are slowly returning to 'normal'. Thanks.
