### ISSUE TITLE
/data/aufs on custom nodes grows without bounds

### ISSUE THREAD

**Issue by keen99** [Shippable/support#4071]
we have a problem that's caused all three of our custom shippable nodes to drop out without any kind of notice.  we only discovered there was a problem when shippable started `SKIPPED`ing all of our builds.

`/data/aufs` seems to be growing without constraint nor cleanup

```
root@shippable02:/# du -hsc data/*
174G	data/aufs
8.2M	data/containers
432M	data/image
56K	data/network
20K	data/plugins
4.0K	data/swarm
4.0K	data/tmp
4.0K	data/trust
28K	data/volumes
174G	total
```

```
...
4.0K	diff/f74279359f801736cf012772fc783fa91a41a21cbb73fad36f28d6967f5a6a87
824M	diff/fa58aeb27e3680db5da7d3c4f93f8e204942069b766b6555c2727bfea1507481
979M	diff/fa8f7e0a9b098d47d4adba314006c75f58f8695f2da6367054dc7742600aca10
867M	diff/fa9012cab78f894d6079b8e94bc1ea7b604278e70186e5aa3b7efc879a8ff5da
814M	diff/fb54ac9fc37102404502ee125ca51b2565bc12fe96e68632895f49003c39d840
22M	diff/fb6d948e31dd56b9bd6600a165b5463da24bb1af6cd4574804e432c1373d696a
1.3G	diff/fc7dae7042a2a7ae241dfa0e6cfcec28f75703eccedb60206423ce2868215ed4
40K	diff/fcd35e9c56b727b38b52d866ce1d62c8cb4230cd6d2fbaf3c84064cd3d835577
20K	diff/fcd35e9c56b727b38b52d866ce1d62c8cb4230cd6d2fbaf3c84064cd3d835577-init
1.4G	diff/fe4083ddb1ec3643473fda8f6b2d214f1f0db2ccef1d83bb90b61c5a9c0a95a9
1.4G	diff/ff8ec04e6374af37c976cfc8672994f7601af21cb670cdf9d1807bbe2260a140
175G	total
root@shippable01:/data/aufs#
```

Looking at older tickets - https://github.com/Shippable/support/issues/1096 and https://github.com/Shippable/support/issues/1517 - it seems to be there's no user-friendly way to purge this, leaving the only option to recreate these machines.

what's the CORRECT process for a customer to deal with this?  why doesn't shippable clean up after itself here?

other useful information:

Skipped jobs report:

```
You do not have any active custom nodes to run this job. Please add a valid custom node to run jobs. You can find more information at http://docs.shippable.com/platform/tutorial/runtime/custom-nodes 
```

the nodes in the we web interface report this, if you drill deep enough:

```
Node stopped due to insufficient space.
  The node has been stopped as disk usage exceeds 90%. Please free up disk space and reset the node to allow builds to continue on this node.
```

I'm not sure 90% is always a sane place to stop - with 1T of storage, that's 100G of disk wasted.  It might be saner to make that a disk space threshold or a sliding scale......

Since I need to get builds going, I'm going to have to re-provision two of these hosts.  I'll leave the 3rd in case it's useful.

**Comment by a-murphy** [comment]
Looking at some of your previous builds, your nodes had quite a few old Docker containers.  These containers were not started by Shippable, so they were most likely started in one of your build scripts (unless you were starting them manually).  Since they weren't started by Shippable, we won't remove them.  There were also far more Docker images than typical; we won't remove those either because it increases build time to pull the image next time you need it.

To reduce the likelihood of this happening again, I would suggest identifying the jobs that are starting images and not removing them or pulling images that are often updated.  We'll usually suggest removing any containers that you start in your build at the end of a run (including `on_failure`) and/or at the beginning of the next run.  You can remove images at the same time as long as there aren't any containers using those images.  Since you're using Docker 1.13, there are [`docker image prune -f`](https://docs.docker.com/v1.13/engine/reference/commandline/image_prune/) and [`docker container prune -f`](https://docs.docker.com/v1.13/engine/reference/commandline/container_prune/) commands that you might want to try if you know you won't be using untagged images or  containers.

Once a node runs out of space, it's usually easiest to just replace it.  The other option is to remove images and containers to reduce the space used and reinitialize.

I'll open an internal issue to investigate changing the 90% disk usage limit.

**Comment by keen99** [comment]
```
your nodes had quite a few old Docker containers. These containers were not started by Shippable, 
```

to make sure I understand this...  `docker run ....` in a runsh or runci job would cause this?  or something else?   `docker build` ?

what's the correct cleanup process for that?  the container "completes" by the end of the job.

is there a command i can run inside a runci/runsh to see containers/images that would cause this (or is it already in the log somewhere), so I can see before/after as I make changes?

```
We'll usually suggest removing any containers that you start in your build at the end of a run (including on_failure) and/or at the beginning of the next run
```

is there a best practices document somewhere that covers this?   I've never seen anything on it.


Also - how do you handle this case when customers do this on the nodes you manage?  I'd assume you have some sort of prune/purge process running regularly - why not allow that to be run on customer nodes?


It's kind of disappointing that this isn't handled automatically (like I expect to be on shippable managed nodes) - I don't have control over what the developers do with their builds, so trying to babysit all the changes they make, to make sure they clean up after themselves, will be an additional chore....

**Comment by keen99** [comment]
also - can the prune commands be executed manually on the build nodes (for one-time type cleanups) or do they have to be run inside a runsh/runci job?

**Comment by a-murphy** [comment]
Most containers will have been started with either a `docker run` or `compose` command.  It's less likely that they are from `docker build` command, but possible because Docker uses containers to build the image layers.  Usually, if you start a container in your build, you will then either stop the container at some point or it exits and (if you aren't planning to use the same container again) then can use `docker rm` to remove it.  If you name the containers when you start them, you can use the same name to remove them.

You can run `docker ps -a` to list all of the containers on the node.  And `docker images` will list the images.  The output of `docker ps -a` is already in the "job node info" section of your build logs.  There should be at least one container listed there (to listen for and run builds), but not usually much more than that.

The Shippable managed nodes are periodically removed if there aren't aren't any builds for them to run and are replaced on the very rare occasions when they run out of space.  We don't remove containers other than the build containers automatically.

Running Docker commands, including `prune`, on the nodes will have exactly the same effect as if you run it in a runSh or runCI script, so it's up to you where you would prefer to run it.

We'll look into if there is any automatic cleanup we could do, but we also have to be careful not to remove any containers or images that others want to keep on their build nodes.  In the meantime, if you can't find an immediate source of the containers and images filling up space, you may want to set up a cron job on your build nodes to remove what you think is reasonable for your subscription.  Alternatively, you could set up a runSh job triggered by a time resource, but there's no way to make sure it runs on all of the build nodes with about the frequency right now.

**Comment by keen99** [comment]
thanks, appreciate the info - will dig further into this on monday!

**Comment by keen99** [comment]
having some trouble with in-job cleanups around images we build in `pre-ci`

for example:

```
env:
  global:
    - ECR_PREFIX="....amazonaws.com"
    - IMAGE_NAME="$ECR_PREFIX/name"
....
  pre_ci:
     - export IMAGE_TAG=pre_ci.$BRANCH.$BUILD_NUMBER
     - docker build -t $IMAGE_NAME:$IMAGE_TAG build
```

this image needs to be around for later steps - `pre_ci_boot` and `ci` for example.  but once those are complete, it's never needed again.

but the env variable scope in `pre_ci` isn't global - so there's no way to set (for example) a variable containing an image name that can be used in `on_...` 
to use for `docker image rm `.   

with the above example, 
```
on_success:
  - docker image rm $IMAGE_NAME:$IMAGE_TAG
```
would fail because `$IMAGE_TAG` is unset


At best I'd have to reproduce the logic used to assemble the image name (and that may not always be available - the simplistic example above is possible though), and that gets pretty complicated.

An alternative might be if there's a filesystem path that's in scope between those steps - I could append and read a file?  Not sure if there is a space in scope though....

**Comment by trriplejay** [comment]
what about something like this:

`docker image rm $(docker images -q $IMAGE_NAME)`

since image name is global, it should be present in those sections.  This will remove all tags of that image.  Only drawback is if you actually wanted to keep certain tags but get rid of others.

**Comment by keen99** [comment]
yep, that drawback is the kicker - though I guess since builds never run
concurrently on the same node, we might be able to get away with it (need
to evaluate further).  my current plan might still delete too much, will
have to see.

I'll give that a shot.

**Comment by keen99** [comment]
heh nope 

```Error response from daemon: conflict: unable to delete 53883e979ac6 (cannot be forced) - image is being used by running container 039ff2cf9554```

**Comment by trriplejay** [comment]
ah, my mistake... on_success is occurring inside the container, and you built the container specifically to run the CI inside i'm guessing.. so it hasn't exited yet... 

you could use the `push` section for this, which runs outside the build container, much like `pre_ci`. It still wouldn't have access to variables defined in pre_ci, but at least the container will have exited and the rm should work.

**Comment by trriplejay** [comment]
If you prefer the more tag-specific solution using the filesystem as you suggested, that is a possibility.

in pre_ci, write some file like:
```yml
pre_ci:
  - export IMAGE_TAG=pre_ci.$BRANCH.$BUILD_NUMBER
  - docker build -t $IMAGE_NAME:$IMAGE_TAG build
  - echo "IMAGE_TAG=$IMAGE_TAG" > tag.env
```

then in push section:
```yml
push:
  - source $SHIPPABLE_BUILD_DIR/tag.env
  - docker image rm $IMAGE_NAME:$IMAGE_TAG
```

basically `pre_ci` occurs inside `$SHIPPABLE_BUILD_DIR` by default, but `push` does not, so if you write a file in `pre_ci`, you'll have to the utilize the predefined `$SHIPPABLE_BUILD_DIR` variable in `push` in order to read it.  (originally `push` was simply for pushing your docker image, so it didn't matter which directory it was in)

**Comment by keen99** [comment]
thanks, `push:` looks like it gets me where I need to be!

I dont see that section documented - (presumably because it's purpose has
changed?) could be worth adding it to the anatomy doc?
http://docs.shippable.com/platform/tutorial/workflow/shippable-yml/

**Comment by ambarish2012** [comment]
Docs have been updated, closing.

**Comment by keen99** [comment]
back on this - looks like `push:` doesnt run on failure, so it's imperfect - but as long as my success runs happen enough, and are open minded about what they delete, it might be ok.
