### ISSUE TITLE
EC2 application load balancer

### ISSUE THREAD

**Issue by bdrachinsky** [Shippable/support#4092]
Hi there,
My issue close to #3876 . 
I'm using upgrade deployment with Application Load Balancer
My **dockerOptions** is 80:80. At the first deployment everything's good but when I started second -- it ended with 

> (service ship-test-deploy-ship-manifest) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance a9f8488b-222b-4096-809a-ee4a991920e6) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide. (Fri Jan 26 2018 22:01:36 GMT+0000 (UTC))

If I changed **portMaping** in **dockerOptions**
to 0:80 everything works but it start new container each deployment and don't kill previous

**Comment by trriplejay** [comment]
are you certain the old container isn't being removed? ECS sometimes can take awhile to remove the old version. It could be related to the load balancer health check or something like that.  If the health check isn't passing on the new container then it might be killed/restarted.  Or, if the new container is having some error that is causing it to restart  for some reason, ECS might never decide that it's safe to remove the old version. I would check the event logs to see if there are any more details.  Perhaps there is some error related to running two copies of the container side by side on the same host?

Regarding the first error, I'm guessing that you only have 1 EC2 instance connected to you cluster.  When you say "80:80", it attempts to utilize port 80 on the host.  When you deploy with upgrade mode, it means the new container will run at the same time as the old container.  However, port 80 is taken by the old container, and therefore cannot be used by the new container, and so you see that error.

I think using `0:80` is the right approach though since that is how application load balancers are meant to be used.

**Comment by bdrachinsky** [comment]
Yes, I have 1 EC2 instance. I want to have deployment without downtime if I doing `0:80` if creates each time new container with new port. Is there a way to create temp container that will run my image then we can kill my first container, deloy to the first and take down the second?

**Comment by trriplejay** [comment]
if you want the host port to always be 80, then there is no way to do that with a single instance.  A second container cannot be started with the same port.  However, if you list `0:80`, then that should be the exact behavior that you get.  

Your application load balancer knows what the new randomly assigned port for your container is, so each new deployment should automatically register with the LB, and once the new container is running steady, the old container will be stopped.  That's how ECS natively handles updates.

If you want to use `80:80`, then you can use `method: replace` in your deploy job, however there would be some small downtime associated with that, since the old container is deleted before the new one is deployed.

**Comment by bdrachinsky** [comment]
> once the new container is running steady, the old container will be stopped.
How much time it took? Can I say something like "remove old container right after new was deployed"?

>  if you list 0:80, then that should be the exact behavior that you get.
The instance will be accessable on **url.com:80** or **url.com:32543** ?

**Comment by trriplejay** [comment]
It should be available at 80, if your ALB is configured correctly.  The power of the ALB is that the traffic should be routed like 80:random:80 (external:host:container), and you can scale your service up to as many instances as your machine can handle, and the ALB will distribute the requests across them all.

Stopping the old container in this case cannot be modified from Shippable. This is a behavior that ECS implements, so even if you directly updated your task definition on ECS and deployed it, this is the behavior that you'd see.  I know that typically services that are not load balanced will remove the old container faster than ones that have load balancers. I think this is because of the health check.  ECS will wait for the health check to pass and consider the new container healthy before it brings down the old container.  So, for example, if your health check is defined as 3 intervals with 20 second between, it might take at least 40 seconds. Perhaps you can adjust any health check you have to minimize this time.

**Comment by bdrachinsky** [comment]
> It should be available at 80, if your ALB is configured correctly. The power of the ALB is that the traffic should be routed like 80:random:80 (external:host:container), and you can scale your service up to as many instances as your machine can handle, and the ALB will distribute the requests across them all.

My task definition is

`"portMappings": [
        {
          "hostPort": 0,
          "protocol": "tcp",
          "containerPort": 80
        }
      ],`

HealthCheck for ALB
![image](https://user-images.githubusercontent.com/13419649/35466945-85af9064-0311-11e8-818b-bbf80bcc0e85.png)

I can't get access to my instance n 80port using `0:80`  setting

That's my container

![image](https://user-images.githubusercontent.com/13419649/35467012-498c91e4-0312-11e8-8cff-fdb7103949e1.png)

**Comment by trriplejay** [comment]
can you check your ALB and your target groups? The target group should show some evidence that it is connected to the container on that port (32772).  If its running for 7 minutes, it sounds like aws thinks it's fine. are you sure your load balancer is publicly exposing port 80? maybe check the security group? what about a docker logs on your container, does everything look normal?

**Comment by bdrachinsky** [comment]
Docker port mapping

![image](https://user-images.githubusercontent.com/13419649/35473061-07b806e2-0383-11e8-8a37-968eadf66df9.png)

Target Group

![image](https://user-images.githubusercontent.com/13419649/35473067-17459fde-0383-11e8-95be-ceeff90048c6.png)

ALB listener

![image](https://user-images.githubusercontent.com/13419649/35473077-2d0a158e-0383-11e8-835b-205111de74cd.png)

Inbound and outbound rules

![image](https://user-images.githubusercontent.com/13419649/35473085-52dfffd0-0383-11e8-9c5d-60c31862da1c.png)

Cluster LB

![image](https://user-images.githubusercontent.com/13419649/35473098-97b5a632-0383-11e8-9ec7-8a6eaa8c4c93.png)

So it almost work. When I deployed the app it started new container on port **32773** and killed **32772** but I still can't go to  **80** port 

Also checked logs -- everything's good

**Comment by bdrachinsky** [comment]
I have followed [this](http://www.awsomeblog.com/aws-application-load-balancer-amazon-ecs-using-dynamic-port-mapping/) guide but still have the same problem. I start thinking the problem with my ALB rules

Checked rules -- everything seems fine for me

![image](https://user-images.githubusercontent.com/13419649/35477400-4ade4bf6-03ca-11e8-9d4d-b491e1a6a1f5.png)

Container seems fine too....

![image](https://user-images.githubusercontent.com/13419649/35477408-75d26b26-03ca-11e8-9a87-a7b24b58a35c.png)

I'm stuck with this. Spent the whole day for deep understanding how it works but still can't figured out how to fix this
