### ISSUE TITLE
dependencyMode misunderstanding?

### ISSUE THREAD

**Issue by aurelien-reeves** [Shippable/support#4102]
Hi,

I tried to tune dependencyMode to optimize our pipeline. However It does not seems to work as I expected:

I first tried to set it to "strict" for the job to be executed only when previous jobs are finished and green. Waiting jobs was created, but never triggered, even when nothing more was running and everything was green. I had to trigger it manually.

So I set it to chrono. But the job seems to be queued and triggered every time a IN job has finished, not one for all the IN jobs.

The job is that one: https://app.shippable.com/github/hiptest/jobs/feature-tests-job/dashboard

The goal is to trigger it one and only one time after the two previous one are green. Is it possible? Am I doing something wrong?

**Comment by trriplejay** [comment]
you were correct in choosing `strict` mode.  I think the issue here is that you have an image that is used in your last job, as well as being an output of your CI.  To resolve the waiting job, we look not only at your incoming two jobs, but also one step above any IN resources.  In this case, we would find your runCI job one step above your image resource.  

I notice that around the time you opened the issue, your runCI job was in a failed state.  If your two parallel test jobs completed while runCI was running, then the final job would consider runCI an input, and would wait for runCI to finish. If runCI then failed, or was already in a failed state, the waiting job would not be resolved.

In this case, i'd recommend removing the image IN from your final job, and instead passing the image information through the state of the parallel runSh jobs.

You can do something like:
```
IMG_NAME=$(shipctl get_resource_version_key <image resource name> sourceName)
IMG_TAG=$(shipctl get_resource_version_name <image resource name>)
shipctl put_resource_state $JOB_NAME  MY_IMAGE "$IMG_NAME:$IMG_TAG"
```
in your parallel runSh jobs.

Then in your final job, instead of accessing the image data from the image resource, you can access it from one of the jobs
```
FINAL_IMAGE=$(shipctl get_resource_version_key <jobName> MY_IMAGE)
```
Then in your script you can just `docker pull $FINAL_IMAGE`

This also ensures that the image tag that your final job is operating on is the same as the one that was validated by the parallel jobs, whereas your current setup leaves a possibility that your final job would run on a tag that runCI just created, but the two parallel runSh jobs did not yet test.

Hope this helps. Let me know if you have any questions!

**Comment by aurelien-reeves** [comment]
Thank you very much, I will give it a try like you described.

I just wanted to let you know that actually the job remains in a waiting even when the whole chain was green, even the runCI one. But yeah, I guess I misused the image resource.

**Comment by aurelien-reeves** [comment]
Hi,

I have set up may jobs as you explained, but it still remains a waiting job, it is not triggered.
Do the IN resources set up with "switch: 'off'" may be the cause of that behavior?

**Comment by trriplejay** [comment]
hmm, it looks like it's set up correctly. Do you mind if I trigger your workflow so i can watch how it processes?

**Comment by aurelien-reeves** [comment]
Yes, you can trigger it :)

Le 5 février 2018 20:00:46 GMT+01:00, John Stockbauer <notifications@github.com> a écrit :
>hmm, it looks like it's set up correctly. Do you mind if I trigger your
>workflow so i can watch how it processes?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Shippable/support/issues/4102#issuecomment-363186380

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by aurelien-reeves** [comment]
So do you have all the info you need to analyze what is happening?

**Comment by trriplejay** [comment]
definitely something strange going on here. we're investigating, but yes, I think I have all the info I need, thanks!

**Comment by aurelien-reeves** [comment]
Ok, thank you for your feedback

**Comment by aurelien-reeves** [comment]
Hi,

I had to set back the dependencyMode of my job to chrono for it to be executed. Until now I had to trigger it manually.

Do you need I set it to strict again for test purpose?

**Comment by trriplejay** [comment]
Hello

Yes, if you don't mind returning it to strict mode, that would be great. so far we've been unable to reproduce this on any other subscription. Is it also OK for us to trigger your job a few more times?

**Comment by aurelien-reeves** [comment]
I have set it to strict again.

Yes, you can trigger the jobs as many time as you want.

**Comment by trriplejay** [comment]
ok, we figured it out. one of your old builds had an incorrect status, causing strict mode to think another job was running, thus preventing the final job from starting. we corrected it, and now the pipeline is working as expected. let us know if you're seeing any other unexpected behavior.

**Comment by aurelien-reeves** [comment]
Great! Thank you!
I will perform some tests and check and get back to you very soon.
