### ISSUE TITLE
runCI as IN not working

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4106]
This was working, and now it isn't.

From the docs:

> Now if you want your runCI job to interact with other entities of the Assembly line, you can fully customize it by adding it as a job in shippable.yml. This creates a wrapper around your existing job. **You can also use this pre-defined job as an IN to any other job in your pipeline without having to explicitly define it in shippable.yml**.

This week, if a job is not explicitly defined in yaml, you get the following error during build which kills the job.

```
Validating job dependencies 0s  
myProject_runCI dependency has been deleted from the yml or has no versions
```

**Comment by BryanCrotaz** [comment]
ember-media-player build 207 failed, with previous builds succeeding. I then added the missing jobs explicitly today. It still fails.

**Comment by trriplejay** [comment]
ah, I see. I think this is a side effect of having clicked "hook pipeline", but then not running those jobs after hooking them into pipelines.  It looks like those 6 input jobs haven't run since before you hooked them.  The result is that they have no "versions" in the pipeline context, and therefore they cause this kind of failure when used as an input.

I'd recommend removing those 6 runCI definitions from your yml, and instead running each of the runCI jobs at least once to produce a version, then the subsequent "ember-media-player" job should be able to run without getting that error.

**Comment by trriplejay** [comment]
@BryanCrotaz any luck with this? I'd be happy to get on a quick call to help you get this configured.

**Comment by BryanCrotaz** [comment]
For now I've removed them and it's running again

**Comment by BryanCrotaz** [comment]
> I see several runCI jobs that don't have a 'steps' section, making them inconsistent, causing the subsequent job to fail.

This should make the assembly line parse job fail then?

**Comment by trriplejay** [comment]
I can see that it failed properly here: https://app.shippable.com/bitbucket/silvercurve/jobs/sc-pp-assembly-line_master_rSync/builds/5a787f81d953dd0700dc3f50/console

though the subsequent job succeeded a couple hours later.  Do you recall if that subsequent job ran due to changes you made in the yml-defined runCI jobs?

**Comment by manishas** [comment]
Closing this since there seems to be no further action needed.

@BryanCrotaz let me know if you have any more questions around this.
