### ISSUE TITLE
Cannot disable/re-enable project to set up nightly build

### ISSUE THREAD

**Issue by wwerner** [Shippable/support#4109]
I am experiencing the same problem as described in #3927.
I tried to re-enable the repo as suggested, However, this times out.
Note that is is shown as disabled on the UI after a while until the page is reloaded, see screenshots.

![image](https://user-images.githubusercontent.com/189410/35854743-71a6f210-0b31-11e8-95e6-f57eb300b0a7.png)

![image](https://user-images.githubusercontent.com/189410/35854979-2db8e440-0b32-11e8-8738-8202182a6c92.png)

The build in question is https://app.shippable.com/github/BlueRainSoftware/jobs/nightly-test_rSync/builds/5a798164e6ed5b0600750836/console.
Any  pointers?

**Comment by a-murphy** [comment]
When adding a runCI job to your shippable.yml, the name should match an existing enabled project with `_runCI` added to the end.  Could you update the runCI job in your YML file to `projectName_runCI`?

**Comment by stangls** [comment]
Since I am in the same devops team, maybe this info can help you resolve the issue:
1. This issue is not about the name of the job, but about the problem, that disabling and re-enabling a *project* does not work - at all -  independently of the naming of any jobs.
2. The background is about creating a second CI-Job. Two CI-Jobs can not be named the same. So your solution can not be applied.

**Comment by a-murphy** [comment]
Requests to disable a project do occasionally time out, usually when there are a lot of builds to be deleted.  This does not mean that the project disable has failed; it continues after the request has timed out.  We try to reduce the time required to disable a project where we can, but some projects still take longer than others.

It looks like that project has since been disabled and re-enabled, so I'm assuming that you no longer need it deleted.  Let us know if you still need it to be deleted, and we can delete it.

However, disabling and re-enabling the project worked in the other issue because the project had been re-named and the resource names attached to it no longer matched the project.  That did not appear to be the case with your project and would not have helped with the error in the linked rSync logs.  Projects that have been renamed more recently (in the last several months) also won't have that problem because we will automatically update the ciRepo and runCI resource names.

Two runCI jobs cannot currently be created for the same project.  And the ciJobs listed in your shippable.yml must have names that match an already enabled project.  So, one enabled project can be listed in one `shippable.yml`.  If you need more jobs than enabled projects, you may want to look at using [runSh](http://docs.shippable.com/platform/workflow/job/runsh/) jobs.

**Comment by stangls** [comment]
runSh is too limited, we tried that already.

The limitations of Shippable produced a lot of overhead work for us. Especially annoying is the UI and the required scripting in the job description files.

**Comment by wwerner** [comment]
After spending quite some time trying to figure out common tasks (multiple build jobs/nightlies, caching)  - which we feel should be easy to accomplish - we decided to switch to another CI/CD platform. We've been on shippable ~3 months.
Another reason is that we really found the UI to be quite buggy & unintuitive.
We do have extensive DevOps background, so don't dismiss this too quickly.

Sorry for that, feel free to reach out for additional information.
