### ISSUE TITLE
runCI failing to setup key-value pair dependency

### ISSUE THREAD

**Issue by seniorquico** [Shippable/support#4114]
Our runCI jobs are failing on PR builds before executing our build scripts. They appear to fail while mapping in a key-value pair integration, and the Shippable console log indicates "success" on every step 😕. We recently migrated to the "node pools" licensing model and upgraded the machine image to v6.1.4. Otherwise, we haven't made any recent changes to our pipelines.

Here is an example of the failure:

https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/309/1/console
https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/309/2/console

Thanks in advance for your time and assistance!

Kyle

**Comment by trriplejay** [comment]
Hi @seniorquico. we're investigating. it looks like the parser is having trouble with one of your integration values.  I believe it's handled slightly differently in the new build agent, so that may be why this issue appeared after you upgraded to node pools.

We'll investigate and try to get a workaround/fix available asap.

**Comment by ambarish2012** [comment]
Closing this issue as the demo is complete and we are patching it in PROD today.

**Comment by trriplejay** [comment]
@seniorquico 

Based on our investigation, it seems like any occurrence of an `=` character in your integration values will cause this to happen for runCI jobs on the new node pools feature.

As a workaround, since this is a runCI job, you could use our [encrypted variables](http://docs.shippable.com/platform/tutorial/security/encrypt-vars/#encrypting-information) support to add them directly to your shippable.yml, making sure to use `"` around any value that contains an `=`.  This should unblock you until we are able to release the full fix.

Let me know if you have any questions.

**Comment by seniorquico** [comment]
@trriplejay @ambarish2012 I appreciate the assistance and updates.

I removed the value that contained an equal sign (=) from the key-value pair integration and moved it into a secure environment variable as recommended. Unfortunately, the build *still* fails at the same step, merging in the integration.

https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/313/1/console
https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/313/2/console

Thanks,

Kyle

**Comment by a-murphy** [comment]
Based on the location of the error, the value with an `=` is likely related to the input before the one that failed (variables couldn't be added for the input with the red "x" because one of the variables already added wasn't parsed correctly).  It looks like it's a cliConfig resource.  Have you checked the integration attached to the first input, or could you try moving those values to a secure environment variable?

**Comment by seniorquico** [comment]
@a-murphy Thanks for the tip! The red "x" indicating a problem with the *previous* step was not intuitive in this instance. I'll have to keep that in mind for future troubleshooting.

The temporary workaround is now working.

**Comment by ambarish2012** [comment]
@seniorquico we have fixed this bug. Please let us know if this issue can be closed.

**Comment by seniorquico** [comment]
I can confirm that this is now working in our pipeline with the original key-value pair & cliConfig resources.

Thanks for the assistance!
