### ISSUE TITLE
Error using github key in runCLI job

### ISSUE THREAD

**Issue by mliszewski** [Shippable/support#4118]
Starting this morning I am receiving an error when trying to use a GitHub key to push to a repo from a runCLI job. This was working yesterday. It seems like it is unable to find the ssh key added by the GH integration. 

Here is a link to the failed build:
https://app.shippable.com/github/CompanionLabs/jobs/bidtest-orchestrator-deploy/builds/5a8462e2ef1ac00700be030d/console
And a link to a version that worked last Thursday:
https://app.shippable.com/github/CompanionLabs/jobs/bidtest-orchestrator-deploy/builds/5a7c73521672160600ed1b10/console

It seems like the issue may be that now the CLI steps are running in a new container whereas they weren't before.

**Comment by mliszewski** [comment]
Also here is a link to a job yesterday morning using this same pattern that worked: https://app.shippable.com/github/CompanionLabs/jobs/account-onboarder-deploy/builds/5a82ea4c8dfc650600c34c36/console

**Comment by ric03uec** [comment]
@mliszewski yes, you're correct. The problem here is that the CLI steps now execute in a separate container that does not have access to the correct keys to enable a push to github. We've moved your subscription to use the previous workflow which should fix the issue for now.
We're tracking this issue internally and it will be fixed in the next release by end of this week.
Sorry for the inconvenience.

**Comment by ambarish2012** [comment]
@mliszewski we have implemented this fix, please let me know if the problem is resolved.

**Comment by mliszewski** [comment]
It does appear to be fixed. Thank you.
