### ISSUE TITLE
Hub login failed - no successful auth challenge

### ISSUE THREAD

**Issue by goskydive** [Shippable/support#4120]
### Description of issue
The error message I'm seeing is this:
```hub_login 1s
  echo 'Hub login failed' 0s  
Hub login failed
  echo 'Docker login failed for username goskydive and email dev@goskydive.com' 0s  
Docker login failed for username goskydive and email dev@goskydive.com
  echo 'Error response from daemon: no successful auth challenge for https://goskydive.azurecr.io/v2/ - errors: [authorization server did not include a token in the response]' 0s  
Error response from daemon: no successful auth challenge for https://goskydive.azurecr.io/v2/ - errors: [authorization server did not include a token in the response]
```

The password is correct.  (If I use an incorrect password then I see a 401 instead.)

### Background
My setup has worked fine for over 6 months, so I think something has changed behind the scenes.

### Research
I found #3725 as the closest match for my issue.  The suggestion was to not use special characters in the password.  Unfortunately, in my case, the passwords are generated by Azure.  They always contain special characters.

### Example failing build
https://app.shippable.com/github/goskydive/svc-dropzones/runs/37/1/console

### Example YML file
language: node_js

node_js: 8.9.4

build:
  ci:
    # full test (using dev dependencies)
    - npm install
    - npm run shippable
    - npm run docs

    # production install
    - rm -rf node_modules
    - npm install --production

    # create new docker build and send to registry
    - echo $(npm run version --silent)
    - docker build -t goskydive.azurecr.io/svc-dropzones:$(npm run version --silent) .
    - docker push goskydive.azurecr.io/svc-dropzones:$(npm run version --silent)

integrations:
  hub:
    - integrationName: AzureCR
      type: "Private Docker Registry"

env:
  global:
    blah blah blah

**Comment by ric03uec** [comment]
@goskydive we're looking into it. we'll get back to you as soon as we're able to narrow down the cause.

**Comment by trriplejay** [comment]
@goskydive is it possible that your azure registry version was recently updated? it is possible that the version of docker that is currently being used is too old to properly communicate with the registry.  

You can change this by going to your subscription dashboard, click the gears in the top right, select "node pools", click "edit" next to the node pool.  You'll see a screen like this:

![image](https://user-images.githubusercontent.com/6869398/36273708-405899a6-123a-11e8-9db2-943e7580ca63.png)

You can change the "runtime version" dropdown to a newer version. I'd recommend 6.1.4 since it's the latest.  This will have much newer version of docker, which will hopefully resolve your problem.

For more information on what those runtime versions mean, check out our docs here: http://docs.shippable.com/platform/runtime/machine-image/ami-overview/

If you still see this error after upgrading, let us know and we'll continue to investigate.

**Comment by goskydive** [comment]
Brilliant.  That has fixed it!

Thanks for the support.
