### ISSUE TITLE
locally built image not available shortly after building

### ISSUE THREAD

**Issue by cjerdonek** [Shippable/support#4121]
Hi, I have a question regarding BYON nodes and Docker image cleanup.

With BYON nodes, does Shippable install anything on the node that would cause Docker images to be "cleaned up" in the middle of a test run (e.g. during the `build_ci` step)?

We had a run recently where in one `build_ci` command an image was built locally, but in the following `build_ci` command very shortly afterwards, the image was no longer available locally. An error like the following occurred:

    Pulling (********: (********:latest)...
    b'repository (********: not found: does not exist or no pull access'

Is this type of error something that might be due to a Shippable script, etc? If you'd like more details, I can send via email. Thank you.

**Comment by a-murphy** [comment]
No, we don't remove Docker images built in your scripts.  And definitely aren't removing any images in the middle of `build_ci`.  

Since you are using your own node, did you set up a cron job to remove stray images (likely to avoid running out of space)?  If it happened to run between building that image and your next command, that might explain it.

**Comment by cjerdonek** [comment]
Okay, thank you for the info.
