### ISSUE TITLE
Are there shared Account Integrations? Or Subscription Level Integration Primitives?

### ISSUE THREAD

**Issue by prov-thinrichs** [Shippable/support#4128]
My organization is using Key-Value Pair integrations for pipeline secret management. (We like that it's backed by Vault)

The scheme looks roughly like this:

KVP Account Integration -> Subscription Integration -> Build Agent Environment Variables -> Kubernetes Secret <- Container Environment Variable <- Deployed Instance

But the problem with this setup is the secrets / key-value pairs are tied to the individual developer's shippable account / github account.  

We'd really like it if any developer on the application team could see / use / change these secrets.  Is there a way to something like:
*  Account Integrations shared across accounts (chosen as another level of granularity after setting the subscription and project scopes, a shared visibility opt-in for other accounts in our organization)
* Subscription Integrations as a primitive, not tied to an account integration (you would just setup all the integration information at the subscription level)

Things we've thought about that would work that we don't really like:
* One shared Shippable account specific to each application.  We don't like this because it's a shared account, less secure / auditable than we would like.
* All account integrations setup under our main build process account.  We don't like this because then either everyone has those credentials or one person / group is responsible for everyone's secrets.

Is there an existing way to do something like this that we haven't thought about and I'm just missing it?

**Comment by a-murphy** [comment]
Subscription integrations currently link one account integration to a subscription.  You can't add additional keys to a subscription integration or share account integrations in any way other than using them in subscription integrations.

Subscription integrations can be updated by another account when that user selects an integration to replace the existing account integration in the subscription.  If your key-value pair integrations each have relatively few keys, replacing the account integration with one belonging to the current user when it needs to be updated may be an option.

Allowing other accounts in your subscription to see the values in your integration is difficult because integrations exist to keep credentials secure.  We won't stop you from using `echo` to print them in job logs, but otherwise they won't be displayed to other users.  If you need other accounts to be able to see the values, you may also want to consider using [params](http://docs.shippable.com/platform/workflow/resource/params/) resources with [encrypted values](http://docs.shippable.com/platform/tutorial/security/encrypt-vars/) because they can then be decrypted by subscription owners.

**Comment by Kirtap** [comment]
This is also causing grief as we need a shared account to old all our account integrations so any authorized dev can go modify them when a need arises. I would prefer those integrations to be defined at the subscription level without a need for "account" integrations.

**Comment by manishas** [comment]
This is being worked on as we speak.... it will be launched as early as next week.

**Comment by rageshkrishna** [comment]
You can now create integrations at an org-level instead of linking a user's account integrations: http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/#creating-an-integration

We launched this in v6.7.4. Sorry about the delayed update here.
