### ISSUE TITLE
GitLab: The project you were looking for could not be found.

### ISSUE THREAD

**Issue by efeller** [Shippable/support#4131]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure

https://app.shippable.com/github/zenreach/jobs/mactocontactmappings-stag-deploy/builds/5a87d719c2d3a20700d1e58d/console

- Scripts called from the yml (optional)

genExec|_common|saveState|_postFiles, :postFilesByResourceId failed for resourceId: 19943 with error Failed to execute project clone script for resource with id 19943 and name mactocontactmappings-stag-deploy with err Identity added: /tmp/57ad1ecd8b15830f00408229-228b2366-3af2-43bf-bbbb-3268e97693ee.pem (/tmp/57ad1ecd8b15830f00408229-228b2366-3af2-43bf-bbbb-3268e97693ee.pem)
,Cloning into '/tmp/57ad1ecd8b15830f00408229-228b2366-3af2-43bf-bbbb-3268e97693ee'...
,GitLab: The project you were looking for could not be found.
,fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**This is a huge blocker for us. How do we fix that?**

**Comment by ankul-shippable** [comment]
@efeller we are looking into it, will get back to you in sometime.

**Comment by rageshkrishna** [comment]
@efeller We took a look at this job and noticed that it has been failing for well over 6 months (probably more; I haven't bothered to look further). As the error message indicated, the root cause was a missing project in our GitLab server, which we internally to maintain the state of the jobs. There was likely an issue with initializing this project when the job was originally created in your pipeline.

The problem has been corrected. You can try re-running your job now.

**Comment by efeller** [comment]
@ankul-shippable @rageshkrishna Works. Thanks a lot.
