### ISSUE TITLE
POST /clusterNodes - non of available options for nodeInitScript are working

### ISSUE THREAD

**Issue by psoders** [Shippable/support#4142]
Hi
i got an problem with setting up BYON nodes, for every script name from https://github.com/Shippable/node/tree/master/scripts i get validation error

Example request
```
 curl --request POST \
  --url https://api.shippable.com/clusterNodes \
  --header "authorization: apiToken <token>" \
  --header "cache-control: no-cache" \
  --header "content-type: application/json" \
  --data '{"subscriptionId": "59f08e78a64bbc0700a8aa4d","friendlyName": "test", "clusterId": 110758,"location": "<ip>","nodeInitScript": "x86_64__Ubuntu__16.04__Docker__17.06.sh","initializeSwap": false,"nodeTypeCode": 7000,"isShippableInitialized": false}'
```
```
{
    "logType": "verbose",
    "methodName": "clusterNodes|post|callerId:59dff12a82a9930700c9b25f|_generateInitSteps",
    "id": 4003,
    "message": "failed to parseScriptName for: x86_64__Ubuntu__16.04__Docker__17.06.shwith error: Error: Invalid script name, cannot parse for Arch and OS"
}
```
few weeks ago have used `ubu_16.04_docker_1.13.sh` but it does not work right now
i have tried most of scripts names available in repo but them and all return same message, also node is actually created, just without `Docker Version`

**Comment by shrivara** [comment]
Since the subscription has been upgraded to node pools, a couple of changes to the API payload are required:
- `nodeInitScript` now refers to the scripts in [`node/initScripts`](https://github.com/Shippable/node/tree/master/initScripts) instead of [`node/scripts`](https://github.com/Shippable/node/tree/master/scripts). In your example this will be
`x86_64/Ubuntu_16.04/Docker_17.06.sh`
- `clusterId` is a required field. You can find this by navigating to the subscription's node pools page and clicking on the edit button on one of the node pools. The number after `nodePools` in the address bar will be `clusterId`. You can also find this by making a `GET /clusters` call.

Let us know if this works for you. You might also want to check the [release notes](https://github.com/Shippable/admiral/blob/master/releaseNotes/v6.2.2.md#features) related to this.

**Comment by manishas** [comment]
@shrivara are these changes documented?

**Comment by shrivara** [comment]
The opt-in button links to the [release notes](https://github.com/Shippable/admiral/blob/master/releaseNotes/v6.2.2.md#features) which document these changes.

**Comment by psoders** [comment]
thanks for quick response @shrivara 
somehow i have missed this in release notes, would be nice if documentation could be updated to http://docs.shippable.com/platform/api/api-overview/#!/ClusterNodes/post_clusterNodes

`x86_64/Ubuntu_16.04/Docker_17.06.sh` work perfectly
