### ISSUE TITLE
v6.2.4: docker fails with  `invalid reference format`

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4175]
Hello,

I upgraded my shippable worker nodes from "stable" to v6.2.4. Since that I have been encountering `invalid reference format` error when pushing a docker image. See the [failed build](https://app.shippable.com/github/damejidlo/jobs/cargo-build/builds/5a9fab08ee460416001b758b/console). My colleague [encountered the same](https://app.shippable.com/github/damejidlo/damejidlo/runs/19842/1/console) error when pulling a CI image (different image) in a different git repository. We both had v6.2.4 (`Linux 58389d302350 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`). I changed node version and although the nodes still claim to have Agent Version v6.2.4 in shippable GUI, another CI job works correctly (probably "stable" version from 2016 `Linux c3fda9f82aa7 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`).

**Comment by a-murphy** [comment]
The "stable" version has Docker 1.9.1, and v6.2.4 uses Docker 17.06.  The CI image pull failure is explained by the change in Docker version; some versions would assume `latest` if the tag was missing, including 1.9.1, and other versions of Docker do not.  Adding `image_tag` to the `pre_ci_boot` section [as described in the documentation](http://docs.shippable.com/ci/custom-docker-image/#pulling-your-custom-image-and-using-it-for-ci) will fix that.

For the error on `docker push`, could you try adding an `echo` of the command you are going to run first?  That might help identify any unexpected characters or strange formatting.  Since your `docker push` commands are so similar, I wonder if it could be trying to push an empty image name for the last line.

**Comment by RadekDvorak** [comment]
Wow, I would never find this out myself. Thanks a lot. I will adjust the settings in our projects and see if it is OK (and then upgrade nodes). As for the push issue, it will take some time to verify as I temporarilly changed the pipeline to build images in post_ci in the meantime.

**Comment by RadekDvorak** [comment]
As I rewrote the particular code in the meantime I have no further information on the error on `docker push`. Thanks
