### ISSUE TITLE
Missing zip command on V6.2.4

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4200]
Might just be the language being set to java but on version 6.2.4 I'm getting command not found when using the zip command.

**Comment by andye2004** [comment]
P.S. Unzip is there

**Comment by trriplejay** [comment]
Hello,

We install unzip since we ourselves use it in creating our build images to install certain packages.  I don't think any of our images have zip today (was it working before you switched to 6.2.4?).  We can certainly get this added in an upcoming release. We'll update the issue here once it's available.  In the meantime, i'd recommend you install it as part of your script.

**Comment by andye2004** [comment]
@trriplejay, thanks for the response. We haven't used it previously but I had read some discussions here on the issues repo about others who have been using it. Maybe it was on other language images. I had already been installing it but it would be nice if it were natively available.

**Comment by andye2004** [comment]
Just for anyone else who might be reading this; we're using the Java JAR command instead of downloading the zip command. It adds a manifest tho' so if this is a problem for you then downloading zip is the only option.

**Comment by a-murphy** [comment]
The new [v6.4.4](http://docs.shippable.com/platform/runtime/machine-image/ami-v644/) images have `zip` installed.  Directions to change the machine image (and default image versions) for node pools in your subscription are [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).  If you have your current image specified in the `pre_ci_boot` section of your `shippable.yml` file, you'll also need to update that.  Let us know if you have any trouble using `zip` in the v6.4.4 build images.
