### ISSUE TITLE
Problem with dockerfile FROM ... AS ... command

### ISSUE THREAD

**Issue by MysterionRise** [Shippable/support#4201]
Basically, during CI build, Docker didn't allow me to pull image and somehow recognize AS part as a tag name

- Link to the build failure
https://app.shippable.com/github/MysterionRise/fantazy-mma/runs/100/1/console

The Dockerfile:

```
FROM openjdk:8u151-jdk-alpine AS BUILD_IMAGE
USER root
ENV APP_HOME=/root/dev/project
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
COPY . $APP_HOME
RUN ./gradlew clean build
```

Error message:

```
Step 1 : FROM openjdk:8u151-jdk-alpine AS BUILD_IMAGE
Pulling repository docker.io/library/openjdk
Tag 8u151-jdk-alpine AS BUILD_IMAGE not found in repository docker.io/library/openjdk
```

**Comment by ric03uec** [comment]
@MysterionRise this seems to be happening because your builds are running on an old version of docker that does not support the `AS` keyword. you can update the version by navigating to the node pools page and changing the `Runtime Version`.
- click on the gears icon on the top right panel of subscriptions page and select `Node Pools`
- click on `Edit` for the node pool which is set to `default` in the list
- change the `Runtime Version` to the latest (currently `v6.2.4`)
- run the build again

hope this fixes your problem.

**Comment by MysterionRise** [comment]
Yes, it's working, thx!
