### ISSUE TITLE
Sync'ing GitHub org permission changes

### ISSUE THREAD

**Issue by seniorquico** [Shippable/support#4210]
An employee recently separated from our team. We have removed the individual from our GitHub repos and teams. How do we ensure these changes are sync'd to Shippable and validate that the individual no longer has access to our pipelines and logs?

Thanks!

Kyle

**Comment by trriplejay** [comment]
Shippable automatically syncs permissions every 4 hours, or at next login (or attempted api use) if the user has not logged in in > 4 hours.

If you can provide me the username, I can manually force a sync to ensure the permissions are updated immediately, otherwise at the next login, the permissions will be automatically updated to reflect any changes.

If it has already been > 4 hours since they were removed, then the permissions may already be up to date.  We don't have a way for you to view another user's permissions, but I can verify this for you from our side if you can provide me a username.

**Comment by seniorquico** [comment]
yashsvir

Thanks,

Kyle

**Comment by trriplejay** [comment]
I've forced an account sync, and he does not have permission to your subscription.

**Comment by seniorquico** [comment]
Thank you!
