### ISSUE TITLE
Terraform Version Upgrade

### ISSUE THREAD

**Issue by RichardSlater** [Shippable/support#4214]
# Problem Statement

When creating a pipeline for infrastructure deployment to Azure using [Terraform][tf] using the [AzureRM][tf-azurerm] provider the build fails with the following error:

```
Your version of Terraform is out of date! The latest version
is 0.11.4. You can update by downloading from www.terraform.io
Get: file:///var/lib/shippable/build/IN/github_chatbot_170_infrastructure/gitRepo/dev
Get: file:///var/lib/shippable/build/IN/github_chatbot_170_infrastructure/gitRepo/dev/uksouth
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * azurerm_application_insights.dev: Provider doesn't support resource: azurerm_application_insights
  * azurerm_storage_account.dev: "account_type": required field is not set
  * azurerm_storage_account.dev: : invalid or unknown key: account_tier
  * azurerm_storage_account.dev: : invalid or unknown key: account_replication_type
```

After adding a few diagnostics statements, namely `terraform --version` I discovered that the version of Terraform v0.8.7 released over a year ago on February 15, 2017, and more importantly one that doesn't support a compatible AzureRM provider.

# Self-help

I have tried [changing the machine image][manage-machine-image], however, the documentation is quite out of date so I am not 100% sure if I am changing the right thing.  Regardless of the Node runtime I choose I still only ever get Terraform v0.8.7.

# Questions

1. Are there any plans to upgrade the Node Runtimes to include later versions of Terraform.
2. Are there practical ways of upgrading Terraform using `shippable.yml`, other than BYON.
3. Is there a reason why the documentation seems to be so far out of date.
4. Is it possible to declaratively specify pre-requisites through `shippable.yml` so that builds can fail fast if Terraform 0.11+ is not available?

# Final Thoughts

I like the Shippable platform, as a guy with a DevOps mindset and as a consultant I think the flexibility built into the Shippable is a huge advantage over Circle, Travis, AppVeyor, et. al.  However, the learning curve is not helped by out of date documentation and software packages.

My goals for this personal project was to build a PoC of the shippable platform to share with my colleagues and potentially as material for a blog post.  Hopefully, the time I have invested in learning the product hasn't been wasted.

Many thanks in advance.

  [tf]: https://www.terraform.io/
  [tf-azurerm]: https://www.terraform.io/docs/providers/azurerm/
  [manage-machine-image]: http://docs.shippable.com/ci/build-image/#manage-machine-image

**Comment by trriplejay** [comment]
Hi @RichardSlater, 

Thanks for bringing this to our attention. We're working on correcting the docs.

The newest version of terraform we have available at this time would be `0.10.0`, and here is how you can make sure you runCLI job uses the correct build image to access that version. If that version is not sufficient for your requirements, then skip to below, where i show how to install any custom version you want as part of your script:

- set your node runtime to v5.8.2 (yes those instructions you linked are out of date, [here](http://docs.shippable.com/platform/management/subscription/node-pools/) are some more recent instructions)
- update your runCLI script to have a section like this (also i'd recommend using runSh instead of runCLI):
```yml
type: runSh
steps:
  - TASK:
      runtime:
        options:
          imageName: drydock/u16
          imageTag: v5.8.2
      script:
        - echo "your commands here"
```

This syntax can be seen here: http://docs.shippable.com/platform/workflow/job/runsh/

To answer your questions:
1. yes, we try to periodically update our runtime packages, however terraform has clearly slipped behind.  I think we had previously run into some issues with a newer version that we tried, so we left it alone at the time and haven't come back to it, but i'll make sure this is part of our next runtime release
2. if you'd prefer to install terraform directly in your script, here are the steps you can add to your yml:
    ```yml
    - export TF_VERSION=0.11.4
    - export TF_FILE=terraform_"$TF_VERSION"_linux_amd64.zip
    - mkdir -p /tmp/terraform
    - wget -nv https://releases.hashicorp.com/terraform/$TF_VERSION/$TF_FILE
    - unzip -o $TF_FILE -d /tmp/terraform
    - sudo chmod +x /tmp/terraform/terraform
    - mv /tmp/terraform/terraform /usr/bin/terraform
    - terraform --version
    ```
3. not a good reason that I can think of. we haven't been keeping up with the changes, but we're working on getting a better system in place to make sure this kind of thing doesn't slip through.
4. there's no special declarative way. I'd just recommend doing an up-front `terraformm --version`, compare it to your desired version, then `exit 1` if the desired version is not present.

Let us know if you have any further questions.  We'd be happy to work with you to get your scenario up and running.

**Comment by manishas** [comment]
@RichardSlater I apologize for the documentation issues... we'll get that corrected asap.

Since you're doing this project as a PoC, we are happy to jump on a quick call tomorrow or later this week and provide whatever help you might need to successfully configure your scenario. Let me know if this is of interest and I can set something up.

**Comment by RichardSlater** [comment]
@manishas I'm just going to work through the comprehensive answer @trriplejay provided; on the surface of it seems to cover off all of my questions and provide me with a clear path forward.  If I don't get any further than I shall reach out later today (I'm in the UK so it's 0740 now).

As a secondary question, if I was to write an analogue to the [Provisioning Microsoft Azure with Ansible][shippable-azure-ansible] would you be willing to include it in your documentation to help further people landing on the platform?

  [shippable-azure-ansible]: http://docs.shippable.com/provision/microsoft-azure-with-ansible/

**Comment by manishas** [comment]
Yes we’d be happy to add it to our docs. In fact, I’d also love to turn it into a guest blog post if possible.

**Comment by RichardSlater** [comment]
@manishas great, I will get plugging away at this and produce something that you guys can use, really is a great platform.

**Comment by manishas** [comment]
The latest images 6.4.4 have an upgraded terraform version 0.11.7. Closing this issue.
