### ISSUE TITLE
adduser: The group `shippable' does not exist.

### ISSUE THREAD

**Issue by mustela** [Shippable/support#4216]
We have renamed a repository, so the old one was no longer valid and we enabled the "new" one, but 
we keep having: 

``` 
 export DISPLAY=:0.0 0s  

  sudo service xvfb start & echo "Xvfb started" 0s  
Xvfb started

  sudo adduser www-data shippable 0s  
xvfb: unrecognized service
adduser: The group `shippable' does not exist.

```

**Comment by a-murphy** [comment]
It sounds like the old repository was using the `shippable/minv2` build image and the newly-enabled one is using a newer default build image.  The newer build images have newer versions of dependencies installed and work better for most projects.  However, they don't have a `shippable` user or a `shippable` group.  You could try adding your `www-data` user to another group or creating a `shippable` group with `addgroup`.  Please include either a link to the project or the project ID from the bottom right corner of the page so that we can see what you are attempting to accomplish in your project and are better able to help.

**Comment by mustela** [comment]
Thanks @a-murphy this is the project id 545006b044927f89db3e1018

**Comment by a-murphy** [comment]
I don't see where you are using the `www-data` user.  It could be hidden in one of your commands so it's not visible in the `shippable.yml`, but if you're not using it, you can probably just remove that line from your `shippable.yml`.

**Comment by mustela** [comment]
I fixed that, but now Im having 
``` 
Server started on port 3000.
[20:52:46] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[20:52:46] I/launcher - Running 1 instances of WebDriver
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
error: XDG_RUNTIME_DIR not set in the environment.
Error: cannot open display: :0.0

	at 
``` 
do you have any recomendation on that?

**Comment by a-murphy** [comment]
The `xvfb-run` command, as in [this sample](https://github.com/shippableSamples/sample_node_selenium/blob/chrome/shippable.yml), usually works better than `service xvfb start` in that build image.  You may want to try that.  I am not, however, a Selenium expert. It could also be related to permissions.  Is this where you are using the `www-data` user?
