### ISSUE TITLE
Cannot upgrade plan

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#4220]
Hello,

I'm using BYON to use shippable, and trying to increase the number of minions from 3 to 5. However, it says that my billing account is being migrated and cannot upgrade my plan.

I tried the following link(instead of V2) to upgrade the plan but it didn't work and the credit card is not charged.
https://app.shippable.com/subs/github/Knowre-Dev/billing

The github account linked with the BYON nodes is `Knowre-Dev`, and the email address linked with the billing information is `infra@knowre.com`.

Will there be any way to quickly upgrade it?

**Comment by rageshkrishna** [comment]
@Kivol Sorry about the delay. I have migrated your billing now. You should be able to make changes to your billing now at https://app.shippable.com/subs/github/Knowre-Dev/billingV2

Please do NOT use the old billing page. We have a new billing system for node pools, and so that page is no longer meant to be used for your subscription. Because you had attempted to upgrade with the old page, you might now notice a charge of approximately $16 on your card, but I can assure you that I have voided this charge immediately at our end. Please let me know if you do not see this reversed on your card within the next couple of days.

You can reach me at ragesh@shippable.com if you have any specific questions around this.

**Comment by Kivol** [comment]
Thanks for the support. It seems to be working very well!
