### ISSUE TITLE
Job stuck on "uploading test reports" without doing anything

### ISSUE THREAD

**Issue by xificurk** [Shippable/support#4227]
### Description of your issue:

Our build jobs are waiting for ~10min in between "uploading test reports" and "upload_cache" steps for no apparent reason.

Link to example build job: https://app.shippable.com/github/damejidlo/damejidlo/runs/20722/1/console
The job duration is 42min, but if you sum up the durations of the individual steps you'll get you'll get ~35min. The missing 7 minutes were spent in between "uploading test reports" and "upload_cache" steps.

Here is a screenshot of the console taken during the processing of the job
![uploading-test-reports](https://user-images.githubusercontent.com/117465/37910111-0567d0ea-310d-11e8-8edc-1f64a211cae9.png)
To job reached "uploading test reports" step, reported it has nothing to do, then simply waited for 7 minutes, and after that continued with "upload_cache" step.

This behavior was observed on multiple jobs in our projects with various time delays.

**Comment by trriplejay** [comment]
I notice that your "cache" step at the end fails due to "cannot allocate memory". could you add a `free -m` command to your `post_ci` step? could something from your tests be hogging the memory?

It seems like in subsequent jobs that you've had where the delay does not occur, the "cannot allocate memory" also doesn't occur, so it seems like the problems are related.

**Comment by xificurk** [comment]
Good catch, thank you. I completely missed that the root cause might be related to memory.
We are aware of high memory consumption of our CI pipeline and we are taking steps to lower the memory requirements. I will close the issue now and reopen it only if it keeps happening after we resolve the memory problem.
Thank you.
