### ISSUE TITLE
Unable to add syncRepo

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4230]
I am trying to add an Assembly Line to one of our repositories. I am pretty sure I have done something wrong, and I am getting the error message below. Unfortunately, I don't now how to interpret this error message to figure out what is actually wrong.

> Please make sure subscription integration used to add syncRepo has admin access on project:5ab9f5974a24a20700a07574

**Comment by a-murphy** [comment]
When adding a syncRepo, you select a subscription integration to be used to create webhooks on the repository.  This subscription integration should be connected to an account integration belonging to an account with admin access to the repository in order to be able to create webhooks.  You should be able to see whose account integration each subscription integration is using by clicking the gears in the top right corner of the subscription dashboard (above the SPOG) and then "integrations."

If you believe that the integration should have admin access and it's a new project, it may be that the owner of the account integration just needs to click "sync" on the account profile page to update project permissions.  Otherwise, you can create a new subscription integration or edit the existing integration to use your own account.

**Comment by oyving** [comment]
Thanks! That provided the necessary information for me to understand what was going on. Maybe update the error message to be a little bit more helpful?
