### ISSUE TITLE
Intermittent failure to parse test results - "No valid test parser"

### ISSUE THREAD

**Issue by katelynmcgovern** [Shippable/support#4237]
The following build should be marked "Unstable" due to a test failure that can be seen in the log of build-ci:
https://app.shippable.com/github/PassageTech/Helper-Suite/runs/4039/1/console

However, the build passed.  If you check the "parse test reports" section, a few error messages appear: "No valid test parser" and  "Unable to parse XML content"

This issue is occurring intermittently - it's not encountered on all builds.  A rebuild of the branch linked with no changes behaved as expected.

Please let me know if any further details are needed from our end.  Thanks for your help!

**Comment by a-murphy** [comment]
It looks like we couldn't parse the test reports for that job because one of the XML files was incomplete.  Is the build creating the test reports in `shippable/testresults` or copying them there?  I couldn't tell from the logs.  Either way, it may be that the build continued while the reports were being written or copied and the complete file wasn't available by the time the reports were parsed.

**Comment by katelynmcgovern** [comment]
Interesting.  We do create the file in shippable/testresults.  Is there anything we could do to mitigate this issue?  It's not ideal for builds to pass in this situation - if possible I'd like to fail the build if we fail to read the XML file.

**Comment by manishas** [comment]
Closing in favor of https://github.com/Shippable/support/issues/1582 which is tracking all improvements to test results.
