### ISSUE TITLE
Pipe to sudo bash gives unbound variable error: Variable defined in env: matrix:

### ISSUE THREAD

**Issue by taqtiqa-mark** [Shippable/support#4244]
Hi,
Thanks for all the work put into Shippable and for making it available to open-source projects - it is much appreciated.

I'm in the process of attempting a port from Travis-CI....

### Description of issue:
Post CI step fails with bash unbound variable when env variable defined in `env: ... matrix: ...`

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure: 
https://app.shippable.com/github/taqtiqa-admin/rkt-stacks/runs/31/1/console
- Scripts called from the yml (optional)

Please advise

**Comment by trriplejay** [comment]
From my testing, this appears to be the result of the use of `sudo`.  can you remove `sudo` from your command `cat <script> | sudo bash`? by default the build runs as a root user and shouldn't require sudo anyway.

**Comment by taqtiqa-mark** [comment]
Hmm, that is the issue.  Is there a way to ensure the env variables survive to the post-ci step.  

The same issue occurs in a sub-script that is expecting an env variable be set.

At the moment this would require maintaining two scripts one for Shippable and one for Travis :(

**Comment by ambarish2012** [comment]
post_ci should have the same ENVs available as CI. Are you seeing a different behaviour?

**Comment by taqtiqa-mark** [comment]
Yes.  Whenever something is executed as follows:

````bash
cat myscript.sh | sudo bash
````

**Comment by taqtiqa-mark** [comment]
Also affects secure environment variables as was reported in issue #4247

**Comment by trriplejay** [comment]
I've found that adding a `-E` to the sudo will preserve the environment. I think that this change is unlikely to cause issues with Travis since the environment was already being preserved.

so the command would become: 
`cat script.sh | sudo -E bash`

Also, since your first script is running with `sudo`, doesn't that mean your inner script doesn't need to be called with `sudo` since its already being executed by the super user?

otherwise this just seems to be a fundamental difference in how travis runs vs shippable.  I'm not finding many other options.

**Comment by taqtiqa-mark** [comment]
Thanks, much appreciated.  The inner script is a wip to something more generic.  Hopefully.

This issue could be closed with a documentation note, unless you want to have it 'just-work'.  I'll leave to you.

**Comment by taqtiqa-mark** [comment]
See #4259 for advise that `-E` won't work.  Cross referencing these the closing #4259

**Comment by rageshkrishna** [comment]
I want to clarify that `-E` only fails for $PATH, because sudo wants to protect users from accidentally running unexpected binaries.

[This StackOverflow discussion](https://stackoverflow.com/questions/257616/sudo-changes-path-why) suggests that `sudo "PATH=$PATH" your_command` will preserve PATH. So perhaps `cat script.sh | sudo -E "PATH=$PATH" your_command` will get everything working for you. However, I haven't tried this out myself yet.

**Comment by taqtiqa-mark** [comment]
Yes I've got things working but by removing sudo and rewriting the scripts and the Travis instructions.  More work that I was planning/hoping for.

Think this issue could be closed by adding notes to the documentation?

Leave to your discretion.
