### ISSUE TITLE
ssh integration for private project dependencies

### ISSUE THREAD

**Issue by elmpp** [Shippable/support#4250]
### Description of your issue:
 - https://app.shippable.com/github/elmpp/api/runs/12/1/console

I am unable to pull from a private repository (triggered during a `composer install`). I am trying to debug the ssh agent config at this time and am finding it difficult to see anything in the logs. There is the following but it doesn't mention the integration name `partridge_sshkey`
```
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone git@github.com:elmpp/api.git /root/src/github.com/elmpp/api' 19s  
Identity added: /tmp/ssh/01_deploy (rsa w/o comment)
```

What am i doing wrong here?

**Comment by a-murphy** [comment]
That line is for cloning the `api` project.  Your SSH key integration should also have been added to `ssh-add` and will be available.  Could you check that the public key for the key in the integration has access to the other project you are trying to clone on GitHub?

Composer may also be trying to use the wrong key because the project key has access to GitHub, but not that project.  You can also try adding the [subscription SSH key](http://docs.shippable.com/ci/ssh-keys/) to the project cloned by Composer.  The subscription key will usually be the first key tried for SSH authentication because its name is alphabetically first.

**Comment by elmpp** [comment]
Thanks. It does appear to be due to Composer not using the correct key first. Surprising that the ssh-agent wouldn't attempt all its keys as part of a normal Composer clone
