### ISSUE TITLE
What is the best way to push to a git repo?

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4255]
I would like to push a commit made in a runSh job to the git repository.
I did not find documentation regarding this case of "commit deployment".

What would you recommend? Is there a way to use the Shippable autorization?

Thanks

**Comment by trriplejay** [comment]
This is possible, but one downside is that when you push the commit, it will trigger the gitRepo that is an IN to the runSh job, and you'll get an infinite loop of builds.

CI can mitigate this by adding [skip ci] in the commit message, but gitRepo currently does not have this feature.  You can create your own tag by adding something to the commit msg then checking for it in your runSh script logic, that's probably the best solution.

To answer your main question, if your project is private, then shippable creates a deploy key in order to be able to clone it from source.  I think the only think you'll have to do is modify that key on your SCM provider to give that key write permission.  After this you should be able to commit/push.

let me know if you have any questions!

**Comment by BotellaA** [comment]
Thanks for the concern but infinite loop will not be an issue in my case.

I have a private project and I was thinking about adding the write permission but I did not find how to do it with a bitbucket account. I think the idea is to change the OAuth but I did not see anything related to their modification.

The best way might be to create another OAuth for the write permission but I will have to add the token value as a secret variable in the `shippable.yml`.

**Comment by BotellaA** [comment]
Is there a way to have a sevure variable accessible from all the jobs?

**Comment by trriplejay** [comment]
I would recommend using the [params](http://docs.shippable.com/platform/workflow/resource/params/) resource, which accepts secure encrypted variables, and will automatically add the decrypted key/value pair to your build ENV. the same params resource can be included as an IN to both your runSh and runCI jobs.

**Comment by BotellaA** [comment]
It fits perfectly my goal. Thanks!
