### ISSUE TITLE
How to display detailed coverage report?

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4257]
Is there a way to display the coverage report parsed by Shippable?
It will be great to have access to line hits and not only the per file coverage percentage to directly see the intested lines.

**Comment by a-murphy** [comment]
We currently display additional information for Jacoco coverage reports.  Documentation for using Jacoco with Shippable is available [here](http://docs.shippable.com/ci/jacoco-reports/).

Since that probably isn't what you're looking for, could you include which coverage report format you are using?

**Comment by BotellaA** [comment]
I am using gcov to compute my coverage and then convert this report into a cobertura report so that Shippable can parse it.

**Comment by BotellaA** [comment]
Do you plan to do it? Since you already did it for Jacoco, maybe it is not that hard. It will be a really great new feature!

**Comment by mikemhenry** [comment]
Just to add to this, we use pytest + pytest-cov for our coverage report and it supports an annotated source output. We would be very interested in shippable support that format.

**Comment by manishas** [comment]
Closing in favor of https://github.com/Shippable/support/issues/1582 which is tracking test results and code coverage enhancements.
