### ISSUE TITLE
CRITICAL: projectId 57ad1f388b15830f004082d2 returned error: POST /runs? returned 504

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#4268]
```{"logType":"error","methodName":"projects|triggerNewBuildRequest|projectId:57ad1f388b15830f004082d2|_queueRun","id":1005,"message":"postRun for :projectId 57ad1f388b15830f004082d2 returned error: POST /runs? returned 504"}```

The above error is occurring when trying to manually kick a build for one of our projects. Webhooks for the project also look to be dead. This is critical and is blocking a release.

**Comment by manishas** [comment]
@grouxsome I want to request your team to use the private bug ticketing system next time since your organization qualifies for it. 

This forum is for free users and for orgs with less than 5 build nodes. I’ve tried to reach out to various folks on your team in the past to get you moved over but without any success. 

While I’m glad we could respond quickly this time and the last couple of times you’ve run into issues on weekends and Friday nights, there is no SLA for this forum unless the service is down. Let me know if you’re interested in onboarding to the private ticketing system.

**Comment by a-murphy** [comment]
One of the notification subscription integrations in your subscription had been updated a few days ago to no longer reference an account integration.  This usually occurs when an account integration is deleted, and is expected to result in runs that use that integration displaying clear error messages with the name of the integration.  Although the subscription integration did not appear to be used by the most recent runs in your project, it must have still been listed in the `shippable.yml` files in other branches.  We will certainly fix the error that prevented the proper error message being displayed in the UI.

If you go the the integrations page in your subscription (under the gears in the top right on the dashboard), there are warning symbols next to the integrations that don't have an account integration.  You can edit those to select one of your account integrations for it to use.  Or, if you really don't need the integration, remove integration from your shippable.yml and optionally delete the subscription integration as well.
