### ISSUE TITLE
ecr_login "ECR get-login failed" error when using custom Docker image

### ISSUE THREAD

**Issue by cjerdonek** [Shippable/support#4288]
Hi, I'm using a custom Docker image. Recently, when I tried switching the `FROM` line of our custom image from one of your images (a `drydock/u16` image) to a standard Ubuntu image, I started getting the following error in the `ecr_login` stage after the `boot_container` stage:

> echo -e 'ECR get-login failed\n\n'/root/d5d0f918-....sh: line 329: aws: command not found

In your documentation, you only say that `apt-get` is required in the custom image, and it was:
http://docs.shippable.com/ci/custom-docker-image/#minimum-requirements
So I'm not sure why an error is occuring. Do you know? If additional info is needed, I can send that by email. Thank you.

**Comment by cjerdonek** [comment]
Never mind. Thanks!

**Comment by a-murphy** [comment]
Since you have an ECR integration in your shippable.yml, we will automatically authenticate with ECR.  This requires `aws` to be installed.  If you only need ECR in the `pre_ci_boot` section, you can add add `agent_only: true` to the integration in your shippable.yml file [as documented here](http://docs.shippable.com/ci/push-amazon-ecr/#using-a-custom-image-for-ci) to skip the ECR login in the build container.  Otherwise, you'll need to install the AWS CLI in your image.

**Comment by cjerdonek** [comment]
Okay, thanks. That worked. I would consider adding a clarification to this section of your docs, though http://docs.shippable.com/ci/custom-docker-image/#minimum-requirements
because it currently says:
> If your custom Docker image has apt-get pre-installed, we will install any additional packages required at runtime.

This makes it seem like Shippable will install the `aws` CLI automatically if it sees it's needed.

Also, in a later section these docs do say the `aws` CLI is needed if you are pulling a private image, but for people that are pushing but not pulling, there isn't a clear indication that it's needed.

**Comment by manishas** [comment]
Thanks. We'll fix the docs to be more clear.
