### ISSUE TITLE
Weird unbound variable error

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#4290]
### Description of your issue:
Some of our builds give an unbound variable error in your scripts. I can't really find why this is.

https://app.shippable.com/bitbucket/swisnl/jobs/gaasReportBuildSize/builds/5ae05fbeb5dd7d0700c74349/console

**Comment by trriplejay** [comment]
do any of the scripts you're sourcing contain `sudo` commands? if so, using sudo will actually change the available environment, At which point a variable that you might have defined previously will no longer be available, and typically results in this error.  

If you don't want to remove sudo from your script, i'd recommend at least adding the `-E` option so that the environment is inherited.  

Some extra discussion on this issue can be found here: https://github.com/Shippable/support/issues/4244

**Comment by bbrala** [comment]
I've gone through the scripts, and although they to a lot, they do not use sudo, i did find one sudo, but that is in an draft script that is not used.

**Comment by bbrala** [comment]
I'm wondering how to debug this. Would something like dumping `$1` trough the lifetime of the script help?

**Comment by trriplejay** [comment]
it looks like the use of the $1 is in one of Shippable's internal scripts.  I see that one of your scripts is calling `set -euo pipefail`.  The -u is telling the script to fail if it runs into any unbound variable.

We'll take a look at how to better handle this internally, but you might want to try removing that option as a workaround for now.

**Comment by bbrala** [comment]
Thanks, i've removed the variable and will look into the problems again. Should i need more assistance i'll let you know.
