### ISSUE TITLE
pytest for python3 in runSh

### ISSUE THREAD

**Issue by khskrede** [Shippable/support#4323]
I need to run tests with pytest for python3 and install packages with pip for python3.

How should I achieve this in a runSh job?

> whereis python
> python: /usr/bin/python /usr/bin/python2.7-config /usr/bin/python2.7 /usr/bin/python3.4 /usr/bin/python3.4m /etc/python /etc/python2.7 /etc/python3.4 /usr/lib/python3.4 /usr/lib/python2.7 /usr/bin/X11/python /usr/bin/X11/python2.7-config /usr/bin/X11/python2.7 /usr/bin/X11/python3.4 /usr/bin/X11/python3.4m /usr/local/lib/python2.7 /usr/local/lib/python3.4 /usr/include/python2.7 /usr/share/python /opt/az/bin/python3.6-config /opt/az/bin/python3.6 /opt/az/bin/python3.6m /opt/az/bin/python3.6m-config /usr/share/man/man1/python.1.gz

> whereis pip3
> pip3: /opt/az/bin/pip3.6 /opt/az/bin/pip3

> pip3 install pytest
> /var/lib/shippable/build/scripts/yml_task_1.sh: line 96: pip3: command not found

>  apt-get install python3-pip
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
>
> The following packages have unmet dependencies:
> python3-pip : Depends: python3-setuptools but it is not going to be installed
>               Depends: python3-requests but it is not going to be installed
>               Recommends: python3-dev (>= 3.2) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

**Comment by a-murphy** [comment]
Using a Python image instead of the default will likely work better.  You can specify one of the [Python build images](http://docs.shippable.com/platform/runtime/machine-image/language-versions/#python) in the `runtime` section under `TASK` as `imageName` in `options` (documentation [here](http://docs.shippable.com/platform/workflow/job/runsh/)):
```YML
  - TASK:
       name: <task name>
       runtime: 
         options:
           imageName: drydock/u16pytall
           imageTag: <tag of the image to boot>
       script:
         - <script command>
         - <script command>
```

With a Python image, you can then use `virtualenv` in the `script` with the [`-p`](https://virtualenv.pypa.io/en/stable/reference/#cmdoption-p) option to specify the version of Python to use.  For example:
```YML
  - virtualenv -p usr/bin/python3.6 $HOME/venv/3.6
  - source $HOME/venv/3.6/bin/activate
  - python --version
```
