### ISSUE TITLE
build_environment: Ubuntu 16.04 and ruby 2.3

### ISSUE THREAD

**Issue by nathanaherne** [Shippable/support#4331]
During the build process, I am installing some packages via apt-get in the build container. I am running the following commands:
```
build:
  ci:
    - apt-get dist-upgrade
    - apt-get install ruby-full
    - gem install compass
    - gem install ceaser-easing
    - gem install susy
    - gem install breakpoint
    - npm install -g bower
    - npm install -g gulp-cli
    - npm install
```

I need to use Ruby 2.3 to get my container to build properly but 1.9.3 is installed instead. When I search the Ubuntu package repository for 16.04 it shows Ruby-full as being version 2.3. For some reason 1.9.3 is being installed.
It is probable that I am making a mistake somewhere but Ive tried everything I can to see if I can think of (apt-get dist-upgrade **was** apt-get update) get Ruby 2.3 to install.
Could someone point me in the right direction to get Ruby 2.3 installed without having to use RVM please?

**Comment by a-murphy** [comment]
Usually, language versions in CI are specified in the `shippable.yml` file.  The example structure for specifying a Ruby version is [here](http://docs.shippable.com/ci/ruby-continuous-integration/#language).  Shippable will then automatically set up the requested version.  However, that will use RVM to switch versions.

If you really don't want to use RVM, you may want to consider [using a custom image](http://docs.shippable.com/ci/custom-docker-image/) because all of the Shippable Ruby images will have RVM installed.

**Comment by nathanaherne** [comment]
Thank you @a-murphy, I appreciate the clarification and help to understand this issue.

The build environment we are using is:

```
# Build Environment
build_environment: Ubuntu 16.04
language: node_js
node_js:
  - 4.8.4
```
```
- apt-get install ruby-full
```
Could you explain why the above command does not install Ruby 2.3 but instead installs Ruby 1.9.3?

**Comment by a-murphy** [comment]
The NodeJS images also have RVM installed with one version of Ruby.  If RVM is configured, that will be used instead of the version of Ruby you are installing with `apt-get`.  It doesn't necessarily mean that `apt-get` is installing 1.9.3 because there is a version of Ruby already installed.

Since you're finding 1.9.3 to be installed, it sounds like you are using one of the older images.  Either [updating the runtime version](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) to update the default image in your subscription or specifying a newer image in your `pre_ci_boot` section may help if you just need a newer version of Ruby.  The latest (6.4.4) NodeJS image has Ruby 2.5.0 installed.  

If you would prefer to continue to use the current image and install Ruby 2.3, you can add the RVM commands to install and use 2.3 to the `ci` section of your `shippable.yml`, but the commands vary a bit for the oldest default images.  For the newer images it would be:
```YML
  - . /usr/local/rvm/scripts/rvm
  - rvm install 2.3 --verify-downloads 1
  - rvm use 2.3
```

And to install Ruby without RVM, the best solution would still be to use your own custom image.  Although you can try uninstalling RVM (`rm -rf /usr/local/rvm/`).

**Comment by nathanaherne** [comment]
Thank you very much @a-murphy. Updating the default runtime environment to the latest version solved the issue.
