### ISSUE TITLE
Error with new GitHub integration. 

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4341]
I've recently added 2 github integrations. 1st one old way with 
```  
type: gitRepo
pointer:`
`` and 2nd with new config 
```
type: gitRepo
versionTemplate:
    sourceName:
```
when I'm running ```shippable_retry ssh-agent bash -c "ssh-add ${REPO_KEYPATH};git push --tags" ```
the old one works just fine and the new one is failing with:
```
fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by a-murphy** [comment]
There shouldn't be any difference between specifying a gitRepo resource with `pointer` and with `versionTemplate`.  

The deploy keys added to GitHub to clone private gitRepos don't usually have write access.  Which resource are you using for your `REPO_KEYPATH` variable?  And, are these public or private repositories?  Public repositories are cloned with HTTPS instead of SSH.

**Comment by depohmel** [comment]
it's a Public repo added with a token with has write access.

**Comment by a-murphy** [comment]
Have you tried adding a new remote (with `git remote add`) to the cloned repository with the credentials you plan to use and then specifying that remote in your `git push`?  Since the tokens are specified in same format as basic authentication, `ssh-add` is unlikely to help.  Another option would be to add an SSH key and an SSH remote.

**Comment by depohmel** [comment]
Yes ended up using git set-url, but it feels hacky
