### ISSUE TITLE
Node agent upgrade is not working

### ISSUE THREAD

**Issue by nmarjanovic** [Shippable/support#4348]
Hi,

I try to upgrade nodes to agent v6.4.2 but clicking on "re initialize" do nothing. In console i can see only "No Consoles Found " then:

Establishing connection and copying files to remote host...
ssh: connect to host x.x.x.x port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]

Your platform can't connect to our vm's any more, and we din't make any changes on our side.

**Comment by trriplejay** [comment]
can you verify that your IP address has not changed from what is listed on shippable? and that there have been no changes to any security configuration? can you ssh into the machine from your own computer?

**Comment by nmarjanovic** [comment]
Hi,

I checked that before. Same IP's on both sides. Firewall rules changed last time few months ago. SSH is working too. Did you changed your IP's, that is the question?!

Edit: Can you provide your IP's by mail, I will add them to whitelist.

**Comment by nmarjanovic** [comment]
@trriplejay can you provide IP list? Having port 22 open for anybody is not acceptable in secure cloud infrastructure.

**Comment by trriplejay** [comment]
unfortunately we're not able to provide a whitelist of IPs, as they change quite often with our current configuration, however this has been requested before and we're investigating the best way to accomplish this.

If keeping port 22 restricted is important, I would suggest using the "manual initialization" feature for custom nodes.  If you do this, then shippable does not need ssh access to the machine.  Instead, you download the script and run it yourself.  Once the shippable agent starts, it just needs to make an outgoing connection so that it can receive build messages.

**Comment by manishas** [comment]
Closing this since manual initialization should work for this scenario.
