### ISSUE TITLE
Builds failing when creating postgresql database

### ISSUE THREAD

**Issue by pmarti** [Shippable/support#435]
It fails with a `Failed executing CMD: psql -c drop database \drop_test\; -U postgres -w` this started on Saturday more or less. My bitbucket username is `pmarti`.

Thanks

**Comment by the-kid89** [comment]
I know this is already closed but I found what was causing the issue "megazord" was having.

In the yaml file provided there was a very small typo that caused it to not run correctly. Its rather easy to overlook as well. I have posted both the line with the issue and the line with the issue fixed below. The issue is with the ";" being placed outside of the database DROP rule.

Line with the bug:
  - psql -c 'DROP DATABASE IF EXISTS test_database'; -U postgres

Line with bug fixed:
  - psql -c 'DROP DATABASE IF EXISTS test_database;' -U postgres
