### ISSUE TITLE
Failed to pull docker image ， I do not know how to solve it.

### ISSUE THREAD

**Issue by justbiaoliu** [Shippable/support#4363]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/github/justbiaoliu/ansible/runs/7/1/scripts

- Scripts called from the yml (optional)

2018-05-28 01:08:09 [32mRun command: docker pull 

ansible/ansible:default@sha256:b651e5964e192c12ef574646a9c724e72fd94615d37d47ffad986408b2097a07

[0m
2018-05-28 01:08:09 repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-

z0-9](?:-*[a-z0-9])*)*"
2018-05-28 01:08:09 [35mWARNING: **# **Failed to pull docker image**** 

"ansible/ansible:default@sha256:b651e5964e192c12ef574646a9c724e72fd94615d37d47ffad986408b2097a07

". Waiting a few seconds before trying again.

**Comment by rageshkrishna** [comment]
Hi @justbiaoliu. This is happening because your subscription's node pool is currently configured to run the (unfortunately named) "Stable" runtime version, which runs a very old version of Docker that does not understand how to pull by SHA.

You can see this setting on [your node pools page](https://app.shippable.com/subs/github/justbiaoliu/nodePools). Please "Edit" your node pool and pick a more recent version (v6.4.4 is the latest one).

If you want to know more about node pools and how they work, you can take a look at [the docs](http://docs.shippable.com/platform/management/subscription/node-pools).

**Comment by justbiaoliu** [comment]
@rageshkrishna . Thank you very much, it works now. I will take a look at the docs.
