### ISSUE TITLE
[All jobs failing] due to putJobById: err: 404

### ISSUE THREAD

**Issue by UncleTawnos** [Shippable/support#4365]
### Description of your issue:
Currently our jobs fails with following message on cleanup step

2s
  Saving Job Files 0s  
Validating dependencies to save current job files
Successfully validated dependencies to save current job files
Creating file list for current job
Successfully created file list for current job
Reading file permissions for current job
Successfully read file permissions for current job
Constructing message for current job
Successfully constructed message for current job
Posting message for current job
reqProc|_common|saveState|_postFiles, :postFilesByResourceId failed for resourceId: 68571 with error No projects found for projectId(s): 5acba31ce19d23070054bf14
  Updating job status 0s  
reqProc|runCI|_updateJobStatus, failed to :putJobById for jobId: 5b0d6d6d58d6290800aec0e7 with err: 404

- Link to the build failure
https://app.shippable.com/bitbucket/humanoitgroup/crm/runs/29/1/console
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
It looks like the account used to process that webhook was found to no longer have write access to the project once it was synchronized.  Because the account previously selected lost access, another account has been automatically selected for future webhook builds on the project.  If you would like to select a different account that should be used for webhook builds, you can do so in the project settings.  The option is labeled "account used" in the first panel on the project settings page.  Accounts that have not been synchronized recently may appear to have the wrong permissions until they are synchronized.

**Comment by UncleTawnos** [comment]
that is strange, as account used for sync is still available and have full rights. Either way, re-sync of SCM solved the issue for now
