### ISSUE TITLE
Minimal IAM policy for Elastic Beanstalk deployments

### ISSUE THREAD

**Issue by completer** [Shippable/support#4367]
Hello, the AWS policy `AWSElasticBeanstalkFullAccess` suggested [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles-user.html) by Amazon is wide open.  EC2: "*" for example.

It appears that a compromise of Shippable under this policy could result in control of essentially all of an account's AWS resources. AWS are providing no real help on how to lock this down. This is not strictly the job of Shippable but unfortunately it could rule Shippable out for us. 

Do you have any advice or alternative recommendations?

**Comment by a-murphy** [comment]
AWS Elastic Beanstalk requires access to several other AWS services in order to function.  Assuming that you're intending to run `eb deploy`, this [StackOverflow answer](https://stackoverflow.com/a/33979816) may be helpful.  There is also an example policy at the bottom of [this page](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.iam.managed-policies.html) in the AWS documentation to restrict access to one Elastic Beanstalk Application.

**Comment by completer** [comment]
Thanks.
