### ISSUE TITLE
how to add deploy step to build

### ISSUE THREAD

**Issue by grandvizier** [Shippable/support#4368]
I've added a node cluster to the integrations, and added a `job` section of type `deploy` to the shippable.yml file, but it's still not running the script to deploy when a build succeeds. The documentation on this topic is all over the place and not very clear.

**Comment by trriplejay** [comment]
Based on your scenario, I think I would recommend adding your machine's ssh key as an [ssh-key integration](http://docs.shippable.com/platform/integration/sshKey/), and then add the deployment script in the `on_success` section of the CI yml.

You can include this key integration directly in the integrations section of the yml like this:
```yml
integrations:
  key:
    - integrationName: my_custom_key
      type: sshKey
```

This will automatically ssh-add your key, so that you can just do a `ssh user@ip` to access the machine.  Then you can either use rsync/scp to copy a script and execute, or just directly execute via `ssh -t uesr@ip <command>`

If you do it this way, you can remove the "jobs" section.

Using the `deploy` type job would require a few additional steps: 
- adding your repo as a `syncRepo`
- creating a manifest
- creating a cluster resource with the node cluster integration
- creating a deploy job with the cluster resource

so given your scenario, that might be a bit overly complex.

Let me know if you have additional questions!
