### ISSUE TITLE
Support for AWS Network Load Balancer

### ISSUE THREAD

**Issue by nvmker** [Shippable/support#4372]
In September 2017 Amazon introduced new AWS Network Load Balancer, but Shippable supports only Application Load Balancer and Classic ELB according the docs.
Can you please add support for NLB?

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html

**Comment by trriplejay** [comment]
it looks like the implementation of NLB with regard to ECS services is the same as ALB. I'd recommend using `method: application` in your yml, and give the correct targetGroupArn associated with your NLB in the `sourceName` section, and it will work.

I'll open a feature request in case there's any more native support we can offer, or to at least allow a "network" keyword instead of "application".

**Comment by nvmker** [comment]
It works with that workaround, thank you!
