### ISSUE TITLE
Cleanup disk for custom nodes

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4393]
Any easy way to clean up /var/lib/docker/aufs directory? Disk almost full, no builds getting started.

**Comment by trriplejay** [comment]
can you try issuing `docker image prune` on the machines? that should also report how much space it clears up.

For the machines that are in a failed state due to space, they'll have to be reset via the UI.

If that doesn't clear the space, let me know and I can try to find some other options.

**Comment by phagunbaya** [comment]
@trriplejay 
```
root@falkonry-ci-02:~# docker image prune
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0 B
```

**Comment by trriplejay** [comment]
You can also just try removing all docker images, and then reset the node. the images that you need will be downloaded on the fly. the first build-per-node might be slower since it'll have to pull again, but it would ensure that any extra images are removed.

another option might be to just create brand new nodes, start from scratch.

also maybe check for stopped containers with `docker ps -a`. If there are a lot of them, they could be taking up precious space. they can be removed with `docker rm <id>` or `docker rm -f $(docker ps -a)` to get rid of all containers. then you can reset the node.

**Comment by phagunbaya** [comment]
Isn't that an automatic way to do it? Why cannot the shippable agent can take care of it?

**Comment by trriplejay** [comment]
we do clean up our own agent and containers, but we don't typically do general cleanup of the node, since we don't want to remove customer data that they may have wanted on the machine. 

For example, each build runs in a docker container, and we don't remove the related images during cleanup or reset, but we do remove the build containers that shippable creates from those images.

Also, if your build script starts up multiple containers for testing purposes, we won't remove any of those, only the job container.

**Comment by mbrodala** [comment]
Also see #3833

**Comment by manishas** [comment]
Closing this since the question is answered.
