### ISSUE TITLE
Rsync repoNormalizer failing

### ISSUE THREAD

**Issue by provScottGiminiani** [Shippable/support#4399]
### Description of your issue:
Rsync failing with the following message:

```
rSync encountered 3 errors while processing providenceinnovation/api.identity: 
  - Failed to update resource: 77834, with error: repoNormalizer failed for: providenceinnovation/apiidentity
  - Failed to update resource: 77835, with error: repoNormalizer failed for: providenceinnovation/apiidentity
  - Failed to update resource: 77833, with error: repoNormalizer failed for: providenceinnovation/apiidentity
```

- Link to the build failure: https://app.shippable.com/github/providenceinnovation/jobs/apiidentity_FUEGO-680_rSync/builds/5b21bc8e27ca7d07002f5e5d/console

**Comment by trriplejay** [comment]
I think you might be missing the `.` in your repo sourceName for these resources.  Can you add that and let me know if that resolves the problem?

**Comment by prov-thinrichs** [comment]
Easy to miss that at the end of a long day, Thanks @trriplejay .  What is the best way for us to debug these types of issues in the future so we don't have to bug you guys?

**Comment by trriplejay** [comment]
No problem. The errors can sometimes be too generic to be helpful. In this case we don't know if the error was because the project doesn't exist, or if the supplied token just doesn't have access. I think it's also possible to see this message if the repo runs out of webhook space.

I'll see if we can enhance this to print a more specific error that will help be more helpful in diagnosing the issue.

**Comment by manishas** [comment]
This has been fixed. The error will have more information moving forward.
