### ISSUE TITLE
on_cancel is apparently ignored for runCI jobs

### ISSUE THREAD

**Issue by immerrr** [Shippable/support#4402]
Hi!

It appears that `on_cancel` step is ignored for runCI jobs.
Also, `shippable.yml` anatomy page doesn't mention `on_cancel`, only having `on_success` and `on_failure`: http://docs.shippable.com/platform/tutorial/workflow/shippable-yml/

A build that had a shippable.yml with on_cancel but didn't have it run is:
- project id: 5ac638e654f7fe0700529a16
- run id: 254/1

While we're at it, I'm quite uncomfortable having to send a link to a private repository, which quite obviously reveals the name of the repository. Could you guys add a way to share a link to a build with an anonymous link that is checked if the user has access to the repository before the redirect?

**Comment by immerrr** [comment]
Also, I wonder if there's a place for a "finally"-like section in the config, for some steps that should run regardless of the outcome. I find myself only using "on_failure" and "on_cancel" for cleanup operations like this:
```
on_success:
  - <do smth on success, e.g. deploy the result>
  - <do cleanup>
on_failure:
  - <do cleanup>
on_cancel:
  - <do cleanup>
```
As you see all three sections have the same "cleanup" operation which has to be altered three times on every change. Ideally it would look smth like
```
on_success:
  - <do smth on success, e.g. deploy the result>
cleanup/finally/on_exit/whatever:
  - <do cleanup>
```

Let me know if you'd like me to create another issue about it.

**Comment by trriplejay** [comment]
The `on_cancel` section can only be used for notifications today. It can't run custom scripts.  For the CI part of `shippable.yml`, instead of having an `on_cancel` section, you can set up a notification integration with `on_cancel: always|never|change` as defined here: http://docs.shippable.com/ci/send-notifications/ but custom scripting is not possible.

regarding linking, you can actually use https://app.shippable.com/projects/5ac638e654f7fe0700529a16 and it will redirect to the url using the fullname (for users who have access).

There is an `always` section that is supported. You can add scripts to this. however it does not apply when the job is cancelled. but it can be used for items that you would otherwise put in both on_success and on_failure.  If cleaning up on cancel is a concern, you may want to consider adding some cleanup to the beginning of the script instead for now as a workaround.

I'll open a feature request to allow scripts in the on_cancel section (or maybe just execute the `always` section even when cancelled).

**Comment by manishas** [comment]
Closing in favor of https://github.com/Shippable/support/issues/3017, so please track that issue for resolution.
