### ISSUE TITLE
Could not fetch specs from https://rubygems.org/

### ISSUE THREAD

**Issue by mustela** [Shippable/support#4410]
Since yesterday we are getting 
``` 
  bundle install --gemfile=$SHIPPABLE_GEMFILE $SHIPPABLE_BUNDLER_ARGS
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
``` 

Project id: `Project Id: 54109f0c21c97efdb898bb0b`

**Comment by trriplejay** [comment]
I see that you're using custom nodes. could anything have changed with the nodes' network configuration that would make rubygems.org inaccessible?

**Comment by mustela** [comment]
No, nothing has changed there :/, and I dont know what else to try really.

**Comment by lucasmpb** [comment]
Looks like rubygems use fastly as proxy, and their certs doesn't support TLS1.0 anymore.
The actual error was:
```
HTTP GET https://index.rubygems.org/api/v1/dependencies
Fetching source index from https://rubygems.org/
Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://rubygems.org/specs.4.8.gz)
```

We solve this issue with:
```
before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get -y install ca-certificates curl libcurl3 libcurl3-gnutls openssl libssl-dev libssl-doc libssl1.0.0
```

@trriplejay Is there any chance to bake this into https://hub.docker.com/r/shippable/minv2/  image?

**Comment by trriplejay** [comment]
Typically we don't modify existing build images so that dependencies don't change underneath the people using them.  Instead we build new ones every few months which will have the latest versions available at the time.  

In this case I'd recommend you update your node pool to use a [more recent AMI](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/).  Actually I can see in your subscription that you have recently switched to v6.1.4.  However, for this project, in order to get the build to use the newer default build image, I'd recommend you update your `shippable.yml` to the latest format shown here: http://docs.shippable.com/ci/yml-structure/#anatomy-of-shippableyml  

more ruby-specific info can be found here: http://docs.shippable.com/ci/ruby-continuous-integration/ (for setting ruby version, bundler args, etc)

Let me know if you have any questions.
