### ISSUE TITLE
Can not trigger build for deploying the service

### ISSUE THREAD

**Issue by xiaoxipang** [Shippable/support#4417]
### Description of your issue:
In our pipeline, I try to trigger a build for deployment job. However, after I click the build button, it doesn't start the build. No matter I refresh the page or logout, the job is red and have no way to retrigger a build. The previous stage job like runCI or manifest also not be able to trigger the deploy job.

- Link to the build failure
  https://app.shippable.com/subs/bitbucket/mxitechnologies/dashboard#
  The broken job called "fp-validator-deploy-staging-ecs", it under the flag "Fleet Planner"

Waiting for response online because it's blocked our planned release today.

**Comment by trriplejay** [comment]
it looks like that job has some inputs defined in the yml that have been deleted. This is preventing the job from running, since it is unable to get those dependencies.  If those resources are no longer needed for that job, can you remove them from that job's yml and try again?

**Comment by Zingoer** [comment]
@trriplejay In my SPOG, I can't find the soft-deleted resources.

**Comment by xiaoxipang** [comment]
@trriplejay I clicked the soft-deleted resources/jobs, but it doesn't give me any response in SPOG View. I can't delete them. Many of the resource doesn't provide delete action in SPOG List View as well.

**Comment by trriplejay** [comment]
actually what you need to do is update the yml of the job so that those resources are no longer listed as IN steps.  basically the job depends on resources that have been deleted, and so it will not run.

normally this would result in the job being visibly disabled in the spog, so i'm going to open a ticket to investigate why yours appears normal.  But updating the job's yml to remove the resources is the way to get the job running again.

**Comment by xiaoxipang** [comment]
@trriplejay Aha, I see. My bad I forgot to remove them from the INs... Thank you so much! It would be nice if during the shippable yml resync it give a warning or error for the unremoved dependencies.
