### ISSUE TITLE
Not building the tag

### ISSUE THREAD

**Issue by arturmatos** [Shippable/support#4422]
Hi,

I have my builds set up to trigger whenever we create tags, but that doesn't seem to be working. We've tagged our project yesterday and I cannot find any build related to the tagging in our history.

Can you please advise? Do we need to set up anything on shippable.yml?

**Comment by deepikasl** [comment]
Hi @arturmatos, you need to enable `Tags` in `Webhook config` section of that project settings. Turning that `on` will trigger builds whenever you create tags for that project.

In project dashboard, click on `settings` 
![screenshot from 2018-06-26 16 45 27](https://user-images.githubusercontent.com/18304961/41908057-5d2b9fd2-7960-11e8-8604-2ba1d489217e.png)

You will find `Tags` option under `Webhook Config` enable it.
![screenshot from 2018-06-26 16 46 30](https://user-images.githubusercontent.com/18304961/41908104-81b6bff8-7960-11e8-8b98-db9acbb09cc0.png)

**Comment by arturmatos** [comment]
Hi @deepikasl . As I mentioned in my text above, I have tags enabled but it isn't building.

We create tags via a github release. Does that mean we need to have releases enabled as well?

**Comment by a-murphy** [comment]
Does your `shippable.yml` file have a `branches: only` section?  If so, could you make sure that there is a pattern that matches the tags you are creating?  It's possible that the tags aren't triggering anything because the tags don't match any of the branches in `branches: only` or match a branch in `branches: except`.  The format for `branches` in `shippable.yml` and an explanation of how to use wildcards is documented [here](http://docs.shippable.com/ci/specify-branches/)

**Comment by arturmatos** [comment]
@a-murphy OK that works, but I think it's rather confusing to treat tags and branches names the same. I'll close it but are you planning to change it going forward?

**Comment by a-murphy** [comment]
Unfortunately, we're not planning to change that at this time because it would affect the tags that run for projects with existing `shippable.yml` files.  We will make it clearer in the documentation that `branches` will filter tags as well when tags are enabled.
