### ISSUE TITLE
Trying to get AWS keys into CI job

### ISSUE THREAD

**Issue by michael-paddle** [Shippable/support#4430]
### Description of your issue:
According to the last instructions I'm tryiing to get AWS credentials from an AWS keys integration to be usable in my ci/runCI job.  To be honest I've tried many different variations and copying different things from all sorts of examples repos but I can't get anything to work . 

How do I get an integration to deliver keys into the ci section?  The keys always seem to be empty.

Is a script provided in a runCI job (see [a few commits ago](https://github.com/PaddleHQ/aws-cloudflare-secgroup/blob/3e6b1005d960f5e6da6f9a6253f986bf500ff719/shippable.yaml))  equivalent to a ci job in the build section?  It doesn't seem to run automatically.

- Link to the build failure

https://app.shippable.com/github/PaddleHQ/aws-cloudflare-secgroup/runs/43/1/console

- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
[runCI jobs](http://docs.shippable.com/platform/workflow/job/runci/) do not support `TASK` or `script` sections.  They will run the [CI YML sections](http://docs.shippable.com/ci/yml-structure/) defined in the `shippable.yml` file for the branch currently running.  Typically, most commands will be in the `build` section of a CI YML, usually in the `ci` section of `build`.

The failed job doesn't show the resource integration input; normally it would be listed in the "setup" section of the logs.  This could be because the name of the runCI job in `shippable.yml` didn't match the name of the job running (`projectName_runCI`, with most special characters removed) or if the `shippable.yml` hadn't been added as a [syncRepo](http://docs.shippable.com/platform/workflow/resource/syncrepo/).

**Comment by manishas** [comment]
@michael-paddle do you still need help with this? Let me know if you want to schedule a call for help with configuration or a Q&A.

**Comment by michael-paddle** [comment]
@manishas no help needed any more.  Your hints were enough for me to get things working.  Thanks.
