### ISSUE TITLE
The path /usr/bin/python3.7 (from --python=/usr/bin/python3.7) does not exist

### ISSUE THREAD

**Issue by arturmatos** [Shippable/support#4476]
### Description of your issue:

I'm trying to upgrade my build to use python 3.7. I've changed shippable.yaml to use python 3.7 like this:

```
# Version number
python:
  - 3.7
```
But the build is currently failing on the setup_ve step with:

```
The path /usr/bin/python3.7 (from --python=/usr/bin/python3.7) does not exist
```

Can you please advise?

Link to the build:
- https://app.shippable.com/github/findpace/pricingmodels/runs/45/summary/console

**Comment by a-murphy** [comment]
This usually occurs when the version of Python you selected is not available on the build image.  A list of the images with each version of Python is available [here](http://docs.shippable.com/platform/runtime/machine-image/language-versions/#python).  For 3.7, you'll need to use a v6.5.4 image.  If you have specified the image tag in the `pre_ci_boot` section of your `shippable.yml`, you can update it there.  Otherwise, you can change the default images for your subscription by [changing the runtime verision in the node pool](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).

**Comment by arturmatos** [comment]
OK, that works. Thanks.
