### ISSUE TITLE
What happens to integration ownership when an account is removed from Bitbucket?

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#4513]
What happens to integration ownership when that account is removed from Bitbucket, but there are other Administrators on the project?

**Comment by a-murphy** [comment]
If an account integration is linked to a subscription integration, another account can [update the subscription integration](http://docs.shippable.com/platform/tutorial/integration/howto-crud-integration/#updating-a-subscription-integrations-underlying-account-integration) to instead reference an account integration belonging to that account.

We also now allow integrations to belong directly to the subscription instead of an account that grants the subscription permission to use the integration, in which case the administrators would edit the integration instead of connecting a new one.  You can read about both options [here](http://docs.shippable.com/platform/tutorial/integration/howto-crud-integration/#adding-integration-to-a-subscription).

**Comment by pwarnock** [comment]
Thanks for the link. I was reviewing that documentation, but wasn't 100% clear. Does the switch need to occur before the account is removed from Bitbucket, or does the account integration become immutable with all of the CI/CD remaining functional?

**Comment by a-murphy** [comment]
The account integration will likely continue to work until the account is next synchronized, depending on the integration type.  Another administrator will be able to update the subscription integration to use a different account integration whether or not the current one is still valid.

**Comment by pwarnock** [comment]
Is there documentation that shows how I go about obtaining the token from Bitbucket Cloud? My Bitbucket has multiple projects, so I'm looking to created scoped integration.

Is it an oAuth token? Is it a refresh_token? What scopes does it need granted? Can I use a token from the Bitbucket project or does it need to be from my user?

**Comment by a-murphy** [comment]
Is this a token for an `scm` subscription or account integration?  And what are you planning to use the integration for?  Assuming you are planning to use the token in an integration, the requirements for the token will depend on the integration type and how you intend to use it.

**Comment by pwarnock** [comment]
I need to change the account integration on https://app.shippable.com/subs/bitbucket/bncompass/integrations/11241/edit 

In the short-term, I can toggle to my 'bitbucket - Peter Warnock' integration, right? But then all of my projects are accessible through that integration.

**Comment by a-murphy** [comment]
Yes, you can set the subscription integration to use your own account integration and resources using the subscription integration would then have access to your projects.

The usual solution to set up Bitbucket integrations with limited access is to create a new account on Bitbucket, log into Shippable, and use that account for the integration.  It's relatively easy to update the permissions on Bitbucket that way because they'll be displayed in the repository settings.

The Bitbucket integrations created by Shippable use OAuth, and you can't create another OAuth token for the same consumer yourself or edit the permissions by project.

**Comment by pwarnock** [comment]
Thanks! That sounds a lot easier.
