### ISSUE TITLE
git config in CI question

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4530]
We are trying to run a git commit in our CI build . via a groovy script called through maven and getting an error because the global config doesn't appear to be set. If we add a command to the shippable.yml file just prior to running the maven command it works.

Is this an issue or is it by design?

**Comment by Bharath92** [comment]
could you please give us the subscription name?

**Comment by andye2004** [comment]
yambay-tech

When I say if we add a command I mean a 'git config --global.....' command.

**Comment by Bharath92** [comment]
Could you please share the build link where you are experiencing this issue?

**Comment by andye2004** [comment]
https://app.shippable.com/github/yambay-tech/mobility-server/runs/1678/1/console

**Comment by Bharath92** [comment]
Is the build trying to create a new git folder and trying to add a commit there?

**Comment by andye2004** [comment]
Yes, we have generated folder with generated sources and we are doing a git init, followed by git add followed by git commit.

**Comment by Bharath92** [comment]
Ok. Currently, in a CI build's `git_sync` step we `git config` the `user.name` and `user.email` to the CI repo, if it is not configured. But, since we do not do it using `--global`, the config is set only for the folder which the CI build runs against.

Setting `user.name` and `user.email` is essential for a git repo because it is baked into the commits as mentioned [here](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup). So, using the `git config --global` command helped in succeeding the subsequent builds.

Shippable also allows git configs to be set globally from the yml using the `gitConfig` tag specified [here](http://docs.shippable.com/ci/yml-structure/). But, note that the configs set using this tag will also be set against the CI repo. If the requirement is to create a folder, `git init` the folder and add a commit to it, use `git config ` without the `--global` flag so that the config is set only for that specific folder.

**Comment by andye2004** [comment]
Thanks @Bharath92 ! Appreciated. Will give this a go now.

**Comment by andye2004** [comment]
Thanks again @Bharath92, that has worked a treat. I love it when I learn something new and --local switch is todays lesson!
