### ISSUE TITLE
Builds failing for no apparent reason

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#4539]
Builds for our project `55d549ca6ed0590b008bba40` have started failing for no apparent reason since last Thursday. According to the logs for builds `3202` - `3204` that have failed, one of the tests (and only one) has been failing. However, this test passes on all other environments. Further, no changes have been made to the part of the code that the test works against since Wednesday, when the last build passed.

**Comment by rageshkrishna** [comment]
@manish-in-java I'm unable to locate a project with that id. Can you please email a link to the project to ragesh@shippable.com if you would rather not share it here? Thanks!

**Comment by manish-in-java** [comment]
@rageshkrishna, sent an email to you. Please check and advise.

**Comment by manishas** [comment]
@rageshkrishna can you post an update for this issue?

**Comment by rageshkrishna** [comment]
Manish and I discussed this over email. Their project doesn't perform well on our newer, bigger nodes because these machines lack enough entropy and Manish's builds use an RNG to randomize the tests. 

I moved them back to the older nodes until we figure out how to improve the situation on the new nodes.

Build perf is currently back to normal on their projects.

**Comment by rageshkrishna** [comment]
We have resolved the problem with entropy on all node types now. Builds that use RNG heavily will not see any performance degradation on the new nodes. 

I'm closing this issue.
