### ISSUE TITLE
No projects visible

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#4540]
There are no projects visibile again. Any idea why?

https://app.shippable.com/subs/bitbucket/swisnl/dashboard (bbrala)

**Comment by trriplejay** [comment]
can you try clicking the "sync" button on your account profile page? How often would you say this happens to you? typically we'd only see it if there was some kind of outage from the source control provider.

**Comment by bbrala** [comment]
That is the first thing i tried. I've openened the app again, and it does say its syncing...

**Comment by trriplejay** [comment]
hmm, based on our logs it actually looks like you're being rate limited by bitbucket at the moment. I see you've had issues in the past with this as well.  We've taken some steps to make fewer calls when syncing bitbucket accounts, but it looks like this is still an issue for you.

Do you know if your account is listed as the builder for any of your projects? It might be beneficial to create a bitbucket account specifically for the purpose of being the builder account.

**Comment by bbrala** [comment]
I think i might have ratelimited myself through a plugin on bitbucket itself.  :(

From what i understand shippable uses any account within the organisation automaticly to spread the load? Thats what was told a while back. We have quite a few projects enabled, looking at which i might be mensioned as the one triggering is kinda hard?

**Comment by trriplejay** [comment]
Typically the builder account selection looks like this:
- default to the person who enabled the project
- if that person doesn't have sufficient permission, find someone who does, and they become the builder.
- any time the job is triggered, validate the builder, and select a new one if necessary

The builder doesn't change as long as the currently selected one has appropriate access, so for example, if you were listed as the builder for any project, and those projects get triggered right now while you don't have access, they will find someone else within the org to be the builder.  Since some calls will be made utilizing the builder's token, this does slightly increase the risk of rate limiting, though we really only make I'd say 1-3 calls per build.

If you suspect one of your plugins then I'd definitely look into that before worrying about the selected builders on your projects, since I would think that you'd have to run a huge number of builds per hour to come close to the limit.

We do have an item in our backlog to implement a better way to handle situations like this in the sync process. for example: not allowing a rate-limit issue to prevent you from seeing your shippable data in the UI.

**Comment by bbrala** [comment]
Good to hear you have some ideas on getting the flow a bit better.

For now I've disabled the plugin in bitbucket, and hopefully this will help. Should i run into problems again i'll open a new ticket.
