### ISSUE TITLE
git clone Error in the pull function

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#4542]
Hi, I'm getting a strange error in the automatic build of this project https://app.shippable.com/github/jacopo-chevallard/BEAGLE/runs/228/1/console

```
git clone https://github.com/jacopo-chevallard/cmake-dependencies.git $CMAKE_DEPENDENCIES
Cloning into '/root/cmake-dependencies'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

although I didn't change the yml scripts since last build, and I checked that the clone command works without errors on my local machine. Any clue?

Thanks !

**Comment by trriplejay** [comment]
has anything changed in the custom base image that you're building with? Do you know which version of git is installed on that image? Is the repo particularly large or contain large files?

Some suggestions that I've found online for that error include:
- If your base image is old, try updating openssl `sudo apt install openssl` before cloning
- if that doesn't work, try increasing the git post buffer value: `git config --global http.postBuffer 1048576000` (1000MiB)
- if that doesn't work, try doing a shallow clone by adding `--depth 1` to your clone command.
- there are other suggestions that if none of the above steps work, switching to ssh instead of https clone might help.  I can provide instructions for that if necessary.

I'm not sure why this would suddenly have an error when it was previously working, but there has been no fundamental underlying platform change that I can see that would cause this, especially since you are using a custom image and have not changed any runtime settings on Shippable for quite awhile.  Can you try some of these suggestions and let me know if any of them work?

**Comment by jacopo-chevallard** [comment]
Thanks for the super quick reply, I'll follow your suggestions and report back here

**Comment by jacopo-chevallard** [comment]
Updating the base image solved the problem, thanks a lot John!
