### ISSUE TITLE
Unable to initialize new node

### ISSUE THREAD

**Issue by aedades** [Shippable/support#4560]
### Description of your issue:
We see the following error when initializing the node either manually or automatically (`/bin/bash /root/node/initScripts/x86_64/Ubuntu_14.04/boot.sh`):
```
# 23:41:51 #######################################
# Starting install_docker_prereqs
##################################################
Installing docker prerequisites
|___ Running apt-get update
Hit:1 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                         
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                 
Fetched 163 kB in 0s (471 kB/s)
Reading package lists... Done
|___ Completed apt-get update
|___ Running apt-get -yy install apt-transport-https git python-pip software-properties-common ca-certificates curl wget tar linux-image-extra-virtual linux-image-extra-4.15.0-1020-aws
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-image-extra-4.15.0-1020-aws
E: Couldn't find any package by glob 'linux-image-extra-4.15.0-1020-aws'
E: Couldn't find any package by regex 'linux-image-extra-4.15.0-1020-aws'
```

Our build node image is: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20180823 (ami-0f70471ae2a09c9df).

**Comment by a-murphy** [comment]
An Ubuntu 18.04 node cannot be part of an Ubuntu 14.04 Shippable node pool.  Since the only [node pool](http://docs.shippable.com/platform/tutorial/runtime/manage-node-pools/) currently in your subscription is an Ubuntu 14.04 node pool, you can only add Ubuntu 14,04 nodes.  Could you try with an Ubuntu 14.04 AMI?

If you would prefer to use Ubuntu 16.04 nodes, you can edit your [subscription plan](http://docs.shippable.com/platform/management/subscription/billing/) to add an Ubuntu 16.04 node pool.  Unfortunately, Ubuntu 18.04 nodes are not supported at this time.

**Comment by aedades** [comment]
Thank you for the quick fix @a-murphy !
