### ISSUE TITLE
Replicas resource not working

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4570]
We run a [deployment](https://app.shippable.com/github/damejidlo/jobs/dj-prod-app-deploy/builds/5ba8dfc0f6a3220600aadb2d/console) task. Although we applied the replicas resource (Resource Id: 80683) with `count: 20` to the appropriate manifest, shippable deploys only few pods (possibly a single pod only).

```
...
- IN: dj-prod-php-fpm_replicas
  applyTo:
    - dj-prod-php-fpm_manifest
...
```

```
deployment "php-fpm-806240" created
Waiting for rollout to finish: 0 of 1 updated replicas are available...
Waiting for rollout to finish: 0 of 1 updated replicas are available...
Waiting for rollout to finish: 0 of 1 updated replicas are available...
Waiting for rollout to finish: 0 of 1 updated replicas are available...
Waiting for rollout to finish: 0 of 1 updated replicas are available...
deployment "php-fpm-806240" successfully rolled out
```

Do we miss something important? Is this a bug?
This is kind of show stopper for us at the moment :disappointed:

**Comment by RadekDvorak** [comment]
FYI replica works well when used in manifests. Application in deployments seems broken.

**Comment by trriplejay** [comment]
glad you found a workaround. i'm investigating this.

**Comment by trriplejay** [comment]
@RadekDvorak I haven't been able to reproduce this replicas issue.  When I add replicas to a deploy job it seems to work as expected. It's probably not the type of thing that you'd want to reproduce, but if you run into this again, please let me know so that I can examine the job and yml before you change it for a workaround.

I tried a few scenarios, but perhaps there's some extra factor that was in your job that I'm missing.  I'm going to close for now, but please re-open (or open a new issue) if you see it again.
