### ISSUE TITLE
How to enable experimental mode in docker?

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#4578]
Hello,

I have a job running a docker build command. I would like to run it experimental mode, so how do I get this done in shippable?

Yours,

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
Since enabling experimental mode requires restarting the daemon, it can't really be done on dynamic nodes without getting the build stuck.

I think this would be possible if you used a [custom node](http://docs.shippable.com/platform/tutorial/runtime/manage-byon-nodes/) and enabled experimental after the shippable initialization script completes, though I haven't tried this.

**Comment by mikkopori** [comment]
Okay, thank you for the answer!
