### ISSUE TITLE
Cassandra won't start on shippable > 6.7.4

### ISSUE THREAD

**Issue by clippermadness** [Shippable/support#4580]
Cassandra is failing to start in my builds when I switch to 6.8.4 or 6.9.4 from 6.7.4.

The build gets to the cassandra_start step, then just hangs there:
cassandra_start
  shippable_service cassandra start
================= Starting Cassandra ===================

Waiting for Cassandra to start...
Waiting for Cassandra to start...
Waiting for Cassandra to start...
Waiting for Cassandra to start...
Waiting for Cassandra to start...
Waiting for Cassandra to start...

Failing build:
https://app.shippable.com/bitbucket/thetalake/ingester/runs/145/1/console

Switching back to 6.7.4 resolves the issue, but I'd like to keep upgrading and stay with the latest.

**Comment by ric03uec** [comment]
@clippermadness we're investigating this. will post an update shortly.

**Comment by rageshkrishna** [comment]
@clippermadness It's breaking because 6.8.4 has Java 10 and Cassandra 3.x doesn't work with anything newer than Java 8. I believe support for Java 11 is scheduled for the Cassandra 4.x release, but I'm not sure when that is.

Our handling of the error is less than optimal, so we are going to address that in the next release and show a better message in this scenario.

However, this still means that for the near future you need to stick with a runtime version that has Java 8, which at this point happens to be 6.7.4.

**Comment by rageshkrishna** [comment]
The error message has been improved with the v6.12.4 drydock images.

At this time, Cassandra still does not support Java 8+, so you will need to stick with an image that has a compatible version of Java.

I'm closing this issue now.
