### ISSUE TITLE
Passing/failing cypress tests are not displayed in Tests tab

### ISSUE THREAD

**Issue by raelgc** [Shippable/support#4583]
I'm using mocha (as described in cypress) to produce junit XML results, but they're never displayed in the Tests tab, even passing or failing.

- Link to the build failure: https://app.shippable.com/github/arizonabay/output/runs/9167/1/console

- Scripts called from the yml (optional):

```bash
npm run cypress -- --reporter junit --reporter-options "mochaFile=$CI_REPORTS/cypress.xml,toConsole=true"
```

`cypress.xml` is generated, but appears to be not used.

**Comment by a-murphy** [comment]
Looking at the test reports saved for the linked job, there is a `cypress.xml` reporting four successful tests and no failures.  The total successful test count shown next to "tests" in the Shippable UI appears to be the correct sum of the reports in the `shippable/testresults` directory.

Since the failing tests appear to be missing from the report file, you may want to try writing test suites to separate files as described in this [Stack Overflow question](https://stackoverflow.com/questions/51180963/cypress-tests-with-mocha-multi-reports-not-able-to-get-aggregated-results-for-a).

**Comment by raelgc** [comment]
Indeed, it worked! Thanks @a-murphy!
