### ISSUE TITLE
`after` step does not contain credentials configured in `IN` steps

### ISSUE THREAD

**Issue by provPaulBrousseau** [Shippable/support#4592]
### Description of your issue:

The `cleaning cli integrations` step comes right after the last `TASK`, before `on_success` and `after` are fired, so if the script in those needs to access any credentials pulled in via an `IN` step, they are lost.  In particular, I'm thinking about k8s configuration.  This is causing a problem running a `helm` command to delete and purge a release that is meant to be short-lived.

In an ideal world, that cleanup step should happen _after_ `after`.

**Comment by trriplejay** [comment]
Thanks for pointing this out. cliConfig scripts are designed to be set up at the beginning of a task, and cleaned up at the end of the task.  "after" steps (on_success, on_failure, always) are designed to be added on to the last task that runs.  Because of this, they end up added to the last task, but after the cliConfig cleanup step has completed, thus the integrations have already been removed.

we'll investigate moving the cleanup step.

In the meantime, the recommended workaround is to manually re-configure whichever integration is required for the "after" steps.  "after" steps do still have access to the resources, integrations, and ENVs, so the information is there, just no longer configured.  The exact way to reconfigure depends on the integration type.

**Comment by provPaulBrousseau** [comment]
Was the behavior changed?

**Comment by trriplejay** [comment]
@provPaulBrousseau Hi Paul, This behavior has not yet been changed. we've opened an internal feature request, but we don't have a timeline for its implementation yet. I'll re-open this issue to keep it open until the feature is released.

**Comment by provPaulBrousseau** [comment]
:+1: Thank you, much appreciated.
