### ISSUE TITLE
Docker container size is much larger compared to locally build image

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#4594]
Builds made on shippable are much larger than local ones. Already touched on in #1150 and #1202, but it is unclear to me if a fix is available as of today?

**Comment by a-murphy** [comment]
What kind of builds?  Is this referring to a build image (specified in the `pre_ci_boot` step) that is then committed or a Docker image that is built and immediately pushed?  In which step is the Docker image built or committed?

It would be helpful if you could include either a link to a job where this occurs or the project ID from the bottom right corner of that page.  Some methods of creating a Docker image will create a larger image on Shippable because they will inadvertently contain build scripts and other methods should not.  It may also be that different dependencies are installed depending on the current state of your cloned repository.  A larger image implies that it has more files, but without knowing more about what those files may be, we can't tell if it is something that can be fixed.

**Comment by sdlarsen** [comment]
Hi. The project id is: 5a1841d51e6eda0700078680

It's a simple python build. Then a docker build adding the files from there (and lots more it seems). There's ~600MB difference in the container size.
I'd like to avoid getting any files not in my repo or artifacts from building it. Obviously I'm failing at that right now.
The build in question is from the load-entity-cores branch (build 91)

**Comment by a-murphy** [comment]
Since your Dockerfile contains a line to add the current directory (the build directory/cloned repo) to the new image, I suspect that's where the extra files are added.  There are two definite possibilities for extra files you may not have locally.  

First, some of the commands you're running before the `docker build` command are adding files and directories to the build directory (`cp`, `mkdir`, and `install`).  If you don't need these in your image, you may want to move those commands after your `docker build`.

Second, your project uses a cache.  It could be that you have cached dependencies that you no longer use and don't have installed locally.  You may want to try clearing the cache ("reset cache" in the second-to-last panel on the project settings page) to see how much that reduces the image size.  The cache could have saved anything you previously installed in the repo in a build.

If you know exactly which files you want in the image, another choice would be to be more selective in the files you add to the image.  This could even make your locally built images smaller.  Instead of `ADD . .`, you can just add the subdirectories that you need.  Or, better, reduce the size of the [build context](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#understand-build-context) to a subdirectory or add a [.dockerignore file](https://docs.docker.com/engine/reference/builder/#dockerignore-file).

**Comment by sdlarsen** [comment]
Clearing the cache was it. Shaved off ~600mb. Whoops. Thank you for pointing that out.
