### ISSUE TITLE
Build failing after project being disabled

### ISSUE THREAD

**Issue by adinuca** [Shippable/support#4601]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

Hello, 

Yesterday we realised that project was disabled and we couldn't enable it, your support did it for us( #4597 ). Now, the build fails, although it was working fine a month ago, without us doing any changes to shippable configuration.

We get the following errors:
<img width="1060" alt="screen shot 2018-10-12 at 04 28 35" src="https://user-images.githubusercontent.com/3942821/46842633-56a33780-cdd7-11e8-8676-cbfff6d3960c.png">

- Link to the build failure
[Build URL - old version of code that used to work](https://app.shippable.com/github/NRGI/open-jade-data/runs/33/summary/console)
[Build URL - new version of code](https://app.shippable.com/github/NRGI/open-jade-data/runs/32/1/console)
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
Your project was never actually disabled; it just appeared to be because there was a duplicate copy (and only one copy was shown at a time).  For this error, some of the resources associated with the project were soft-deleted (not fully deleted) at some point and so could no longer be updated by the job.  I've restored those resources.  Could you try again?

**Comment by adinuca** [comment]
Thank you, that helped!
