### ISSUE TITLE
LoadBalancer in deploy job does not work

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4616]
Hello,

I am tinkering with loadBalancer settings in kubernetes deploy job as I get some connection errors at the time deployment ends. Yet I am unable to make it work. [All I get in the job](https://app.shippable.com/github/damejidlo/jobs/dj-playground-php-fpm-deploy/builds/5bcb6852a362a50700c8a4ac/console) is
```
Validating dj-playground-php-fpm-lb handler
No special dependencyHandler for dependency type: IN loadBalancer
```
I tried to help it by removing the lb, installing lb with provision job or removing selector definition - with no success at all.

Could you please give me an advice?

**Comment by trriplejay** [comment]
actually kubernetes based loadBalancers do not need to be included in the deploy job.  In order to connect your deploment to an existing kube service, you just have to add the appropriate labels.  There are a couple ways you can do this:

1. Shippable automatically adds labels to the pods that you can then put in your kube service (which you can create via provision or any other method). This is described on this page: http://docs.shippable.com/deploy/lb-kubernetes/#1-add-a-loadbalancer-resource

so your deploy job will automatically get the labels `shippable.manifestName` and `shippable.jobName`.  The combination of these two labels should be guaranteed unique across your subscription.  When creating your kube service, you just need to add the same labels.  The value of shippable.manifestName will be the name of the manifest job that produced the manifest you're trying to connect to, and the value of shippable.jobName is the name of the deploy job.

2. You could just add your own custom labels.  the [dockerOptions](http://docs.shippable.com/platform/workflow/resource/dockeroptions/) resource allows you to add customized labels to your deployments, and the [loadBalancer resource](http://docs.shippable.com/platform/workflow/resource/loadbalancer/) allows you to specify the "selector" field of the kubernetes service when using it as an input to a `provision` job.

Hopefully one of these methods will work for you, let me know if you have any other questions.

**Comment by RadekDvorak** [comment]
Hi trriplejay,

Thank you for your aswer. I had basic working kubernetes svc in place. While reading [the documentation](http://docs.shippable.com/platform/workflow/job/deploy/) I got the impression that correct settings could turn the Blue/Green deployment into a "Red/Black" deployment (a similar strategy with the svc selector patched to point to the later deployment before the the former one is deleted). Specifically this sentence caught my eye:
> It is used to attach a load balancer to a particular service and automatically update routing information upon subsequent deployments.

This is what I wanted to test. I guess I misunderstood that, did I not?

**Comment by trriplejay** [comment]
Unfortunately that piece of functionality only applies to ECS deployments.  I think our docs don't make that very clear. The load balancer section on the deploy job page should really say "ECS only" somewhere... The load balancer resource is used in two separate ways right now: one is in creating kube services via provision job, and the other is being attached to ECS services in deployment jobs.  There is no functionality for a kube load balancer in a deploy job, and there is no functionality for an EC2 load balancer in a provision job. I'll update the docs to make this separation more clear.
