### ISSUE TITLE
All builds on repo are failing during git_sync

### ISSUE THREAD

**Issue by io41** [Shippable/support#4646]
One of our repo's starting failing every build, no matter what branch is being built. Example of failed build url:

https://app.shippable.com/github/fieldaware/fieldaware/runs/4657/summary/console

The error occurs during git_sync:

```
git checkout -f release/1.34.0 --
fatal: invalid reference: release/1.34.0
```

Same error for every other branch.

**Comment by trriplejay** [comment]
@io41 we're currently investigating. it seems cache related, can you try resetting your cache from the project settings page?

**Comment by io41** [comment]
We reset the deployment keys... that seems to have resolved the issue

**Comment by io41** [comment]
Thanks for looking into it!

**Comment by io41** [comment]
@trriplejay so it seems we've hit this again... 

https://app.shippable.com/github/fieldaware/fieldaware/runs/4674/1/console

Same errors:
```
git checkout -f feature/ut-type-db-scripts --
fatal: invalid reference: feature/ut-type-db-scripts
```

We'll hold off resetting the deployment keys this time, so that you can investigate why it can't pull new requests, and get to the root cause of this problem.

**Comment by io41** [comment]
I'll try resetting the cache as you suggested

**Comment by io41** [comment]
Resetting the cache appears to work... 

Yesterday we hit "Reset All Keys" from the project settings page. Does this also reset the cache? If yes, then this could be a reoccurring problem, given it's shown up again today...

**Comment by trriplejay** [comment]
"reset all keys" does not reset the cache. not sure why resetting the keys would've helped at all if it was only temporary... we're continuing to investigate. 

Does resetting the cache seem to work for multiple runs?

I'd say the main change we noticed in your build was that the cache_dirs_list was changed to use `$SHIPPABLE_BUILD_DIR` whereas it used to have a couple different directories, but not the main build directory.

**Comment by trriplejay** [comment]
@io41 we've confirmed that this issue is the result of the combination of the use of `depth` with caching enabled. 

git clone with a `depth` parameter will only clone a single branch.  This single branch gets cached when you use `SHIPPABLE_BUILD_DIR` in your cached_dirs_list.  Then, when you later run a build on a different branch, the cache is restored, and because the repo already exists,  Shippable performs a git fetch instead of a git clone.  This git fetch only fetches for existing branches, which is only the single branch that was cached, and so later when we try to check out that other branch, it fails because the branch was not fetched.

You can do one of the following things to work around this:
- modify your cache_dirs_list so that it does not include the repo
- turn off caching
- remove the depth option.

Let me know if you have any questions.

**Comment by io41** [comment]
That's some really good detective work, thank you @trriplejay
