### ISSUE TITLE
Build fails with _createNewAccounts postOfflineAccount failed for 

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4668]
Automatic trigger of one job fails with the following message

```runs|post|callerId:548f3fff637861dc007737f2|projectId:5b749097f50d4207001d7d09|_createNewAccounts postOfflineAccount failed for account:bitbucket/mazoea-binaryruns|post|callerId:548f3fff637861dc007737f2|projectId:5b749097f50d4207001d7d09|_createNewAccounts postOfflineAccount failed for account:bitbucket/mazoea-binaryruns|post|callerId:548f3fff637861dc007737f2|projectId:5b749097f50d4207001d7d09|_createNewAccounts postOfflineAccount failed for account:bitbucket/mazoea-binary```

If run manually, it succeeds.

**Comment by vidiecan** [comment]
related to this, I also get 
```
TokenError: The specified code is not valid.
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:320:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:367:16)
    at /home/shippable/www/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /home/shippable/www/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/shippable/www/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
``` 
when trying to login using the problematic account

**Comment by a-murphy** [comment]
For the second error, I would suggest going to https://app.shippable.com/logout to make sure that you are completely logged out of Shippable before logging in and checking that you are not in an incognito or private browsing window.

For the original error, has the name of the account listed in the error message changed?  It's possible that a changed name could be causing a conflict if that account hasn't logged in to Shippable since the name was changed.  It would look like a new account while it's actually not.

**Comment by vidiecan** [comment]
@a-murphy ad original error - no account name change by me but I see this in shippable.com (check the Triggered by column)

![image](https://user-images.githubusercontent.com/332350/49344706-527af400-f67b-11e8-900c-9736ee5b7b1f.png)

**Comment by vidiecan** [comment]
and in bitbucket I see:
```
Full name:Mazoea Binary
Username:mazoea-binary
```

**Comment by a-murphy** [comment]
Thank you for letting me know that it was an existing account that had been used before.  Now that I've found it, it turned out to have a very strangely formatted Bitbucket integration that was making the account difficult to find.  I've fixed the formatting so that you shouldn't see this particular error.  However, that account can't be used as the builder account actually used for running a job until the integration is valid.  Logging in to Shippable again should fix the integration so that it has valid Bitbucket access again, should you need it.  Let us know if you have any more trouble with this account.

**Comment by vidiecan** [comment]
fixed, thank you
