### ISSUE TITLE
runSH job continues to run even after I cancel the job

### ISSUE THREAD

**Issue by Mendalorien** [Shippable/support#4673]
### runSH job continues to run even after I cancel the job:

I have a runSH job which is running some E2E tests using Nightwatch and Browserstack.  However, when I cancel the job mid-way it is continuing to run the tests.  I can see them running in Browserstack, even thought the job has a status of "canceled" in shippable.

How can I ensure that canceling a job in shippable actually terminates the running task?  This is holding up my Browserstack queue until it completes.

Thanks

- Link to the build failure

https://app.shippable.com/github/supplypike/jobs/analytics-e2e-tests_analytics-ui_stage_analytics_smokeTests/builds/5c0a916c1474dc0700edec93/console

**Comment by a-murphy** [comment]
When a runSh job is canceled and has already started running, the script should stop running within a minute.  On average, it would take about ten seconds for the cancel message to be picked up by the node and the script to stop executing.  If your script includes a command that starts your Browserstack tests outside of the current container and then doesn't require further input, it's possible that they may continue to run after the task container or script was killed.  Unfortunately, that would be because Shippable doesn't know that they are running, or where they are running, at that point.

**Comment by Mendalorien** [comment]
I am doing a 'docker run ...' command to execute the tests.  When I run it locally I can simply do a 'docker stop ...' or 'docker kill ...', and it will successfully terminate the tests.  However, when I add that to the 'on_cancel' event in the runSH job it doesn't terminate like it will locally.

**Comment by a-murphy** [comment]
The `on_cancel` section of a runSh job only supports notifications, as documented [here](http://docs.shippable.com/platform/workflow/job/runsh/#yml-definition).  Scripts in an `on_cancel` section will not run.  There is not currently any way to run a script when a job is canceled.

**Comment by Mendalorien** [comment]
I attempted to add the `docker kill ...` command to the `always` section of the runSH job, but after canceling the job the shippable log doesn't show that it is being executed and the job is still running my tests.

**Comment by trriplejay** [comment]
"always" will execute regardless of success or failure, but unfortunately will not execute for a cancelled job.  I think the best option might be to execute the `docker kill` at the beginning of your script so that incoming jobs aren't held up by anything leftover on the machine.

**Comment by rageshkrishna** [comment]
@Mendalorien Do you still need help with this?

**Comment by Mendalorien** [comment]
This is still an on-going issue.  The fact that we have no reliable way to cancel the job is rather annoying.  We have simply told our engineers not to cancel them, but... That's not a solution.
