### ISSUE TITLE
Changed the owner of the git repo made my integrations disappear

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#4678]
Hello,

lost everything it seems. How can we get it back?

Also later on we need to transfer ownership to new people, how do I do that?

Yours,

Mikko

**Comment by trriplejay** [comment]
It looks like you've moved your sync repo to a different subscription. We don't really support moving assembly line items between subscriptions at the moment, but we'll see what we can do to get you transitioned in this case. 

Integrations are associated with a subscription, so if you move your project to a different subscription, you'll have to manually recreate your integrations in that particular subscription. However, you should still be able to see the old integrations in the original subscription that your project was moved from.

Which subscription are you trying to move the repo to?

**Comment by mikkopori** [comment]
Thank you.

We just changed the owner/path of the git-repository from:
https://github.com/mikkopori/enterlot
to:
https://github.com/ktoiskal/enterlot

So, we need to create a new account/organisation to move these to?

**Comment by trriplejay** [comment]
If you're planning to change ownership again in the future, have you considered using a github organization instead? then you can change ownership without actually moving the project.

At the moment, the project is not visible on Shippable because it is unable to transfer from one account to the other.  We can do this transition internally, but ideally the first thing to do would be to take any integrations that you are using in `mikkoport`, and re-recreate them in `ktoiskal`.  Then, when we are transitioning, we can update the resources to reference the new integrations.

**Comment by mikkopori** [comment]
Okay, so I will create the organisation.

Currently there is no account in Shippable for ktoiskal, and if I create a organisation (Enterlot) we could transfer the integrations there directly?

**Comment by trriplejay** [comment]
The integrations can't be directly transferred, they'll have to be recreated in the new account or org.  If the `ktoiskal` user logs into shippable, an account will be created, though the project will still not be visible due to the transfer conflict.  At that time, that user could create the subscription integrations, and then we could complete the transfer of the assembly line objects.

If you decide to use an org, you can recreate the integrations yourself in the new org, and then we can transfer the objects. Does that make sense?

**Comment by mikkopori** [comment]
I think the second option is easier for us, let's choose that one.

**Comment by trriplejay** [comment]
ok then. it's possible that you'll need to create a dummy project on the new org just so that you can find it on shippable until we can get the real project transferred.  Let me know once you are able to access the new org and create the integrations.

After creating the new org on github, you should manually sync your shippable account on the profile page.

**Comment by mikkopori** [comment]
Hmm, where do I create the new org? Cannot seem to find it..

**Comment by a-murphy** [comment]
Organizations can be created on GitHub (documentation [here](https://help.github.com/articles/creating-a-new-organization-from-scratch/)) and will then appear on Shippable when your Shippable account is synchronized (click the "sync" button on the profile page).  You may need to add another project to the organization temporarily in order to see it; empty organizations/subscriptions aren't shown on Shippable.

Since this is a new organization, you may also have to allow Shippable access if you have [OAuth App access restrictions](https://help.github.com/articles/about-oauth-app-access-restrictions/) enabled.  Directions for that are [here](https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/) and [here](https://help.github.com/articles/approving-oauth-apps-for-your-organization/).

**Comment by mikkopori** [comment]
Okay, I was looking in Shippable, not Github. Tnx!

**Comment by mikkopori** [comment]
Hmm, would this be easier if the repository would be moved back to /mikkopori/ and then moved under the new organisation?

**Comment by a-murphy** [comment]
No, it wouldn't really make much difference, at least on Shippable.  If it makes it easier for you on GitHub for some reason, you certainly can, but transferring to a new subscription on Shippable will be the same for us either way.  User subscriptions and organization subscriptions are handled almost identically on Shippable, with the biggest difference being that the source providers (i.e. GitHub) offer more permission options in organizations.

**Comment by mikkopori** [comment]
The new people taking over the project have now decided to move away from Shippable, so thank you for your help and these years!
