### ISSUE TITLE
rSync Job Fails 

### ISSUE THREAD

**Issue by slevert** [Shippable/support#4683]
Our teams are experiencing a build failures:

rSync encountered 1 errors while processing mxitechnologies/lpa-deploy: 
  - Automated versions are not enabled because webhook was not setup for resourceId: 72498 andresourceName: lpa-deploy-master

Here is one specific job that has failed.

- https://app.shippable.com/bitbucket/mxitechnologies/jobs/lpa-deploy_master_rSync/builds/5c1a52a0023fb10700e53aad/

**Comment by trriplejay** [comment]
Hi @slevert, we're looking into this. I have a couple questions about your setup.

We still see two sync jobs, "lpa-deploy_master_rSync" and "lpa-deploy-master_rSync".  It looks like they point to the same repo, but the old one is still the parent of many resources.  Are you trying to move everything to the new repo? was this repo deleted/recreated on the source control?

I also notice that the old sync job has a ton of .yml files, and 500+ resources associated with it while the new one only has two files and about 10 resources.  Were you trying to delete all of the old 500+ resources and replace them with the 10? 

We can help clean up the old repo, but it looks like that would result in a lot of resources being removed. Is that intentional?

**Comment by slevert** [comment]
Hello,

Yes, we are moving to the new repository.  We did indeed deprecate and rename and old bitbucket repository (../lpa_deploy->../lpa_deploy_old) and created a new repository in source control with the same name (../lpa_deploy).  This appears to be the root of our problems.  We have simplified the existing architecture and this is why you are seeing fewer .yml files and resources.

We are trying to delete the 500+ resources and replace with the 10.

Clean up the old repository would be great.  We have backed up our repos and our .yml's so we are not concerned about losing the 500+ resources.  This is intentional.

Thanks,

Stephane

**Comment by xiaoxipang** [comment]
Hello @trriplejay 
I'm a colleague of @slevert who works in another team. I just curious about one thing, those 500+ result is not relating to a prefix with le or lrp or fp. All 500+ resources only relate to lpa. Because inside the rSync of our deploy process, I found it tries to rSync a lot of things that are not related to our lrp team, like lp, le, mx and so on. So my concern is that we may set up some dependencies incorrect to make all projects link with each other. Or do this potentially relate to the single subscription we have?
https://app.shippable.com/bitbucket/mxitechnologies/jobs/lrp-deploy_master_rSync/builds/5c196d82ad1053060059cacc/console

**Comment by a-murphy** [comment]
@Zingoer The logs for the rSync jobs show all of the runCI jobs and ciRepo resources in the subscription, including ones that don't belong to that syncRepo and may belong to other syncRepos.  Only ciRepo resources or runCI jobs that are actually listed in a YML file in the `lrp-deploy-master` (old) syncRepo would have been included in that count, and even then removing the syncRepo does not disable or delete CI projects.

The runCI and ciRepos appearing in all of the rSync logs is expected, and does not indicate any potential problems (or any links between the projects).

**Comment by trriplejay** [comment]
@slevert everything should be cleaned up now, can you run that failing rSync job again?

**Comment by slevert** [comment]
I just ran it.  I'm no longer seeing the reported issue anymore.  I do see a new one but I think it's related to what we've coded in our .yml files.

**Comment by slevert** [comment]
@trriplejay @Zingoer @a-murphy 

Thank you for all the help.  We now having everything passing.

Stephane

**Comment by trriplejay** [comment]
great! glad everything's working.

**Comment by xiaoxipang** [comment]
@a-murphy @trriplejay @slevert 
Got it! Thank you! Our team's deployment also works now.
