### ISSUE TITLE
Using external github repositories correctly

### ISSUE THREAD

**Issue by nathanaherne** [Shippable/support#4684]
### Description of your issue:
I am experiencing a build failure because I am not sure how to use external git repositories correctly. I would like to understand how to use git repos correctly in my shippable.yml file.

I have bitbucket repository for a Hugo Theme that we have built (repo1). I would like to use this theme as base theme for multiple sites. I am using Shippable to build a docker container.

I have created another repository (repo2) which contains all the modifications required to make the Hugo theme (repo1) suit this particular site. My plan was to pull in the Hugo theme bitbucket repo (repo1) with shippable, copy in the data from the current repo (repo2) and then run "Hugo build" to build the static site.

I have done things like this before with shippable but cannot remember how I got it to work. I cannot remember how I got the built code into the container. I am not even sure if I should be using Shippable this way. I have tried to use the shippable.yml file to pull in repo1 and that has not worked. I have tried to use the Dockerfile to pull in repo1 and I am getting a bunch of ssh errors from the Alpine container.

I would appreciate any information you could provide me on how to solve this issue.

**Comment by a-murphy** [comment]
There are a few possibilities. One option would be to use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).  In this case, your base theme would be a submodule in the other git repositories.  Documentation on submodules in Shippable is [here](http://docs.shippable.com/ci/git-submodules/#using-git-submodules).

If you would rather not use submodules, you can either clone the base theme repository in the build script for your other repositories in order to get the code or store it in the Docker image.  Cloning the repository with `git clone` would be very similar to a submodule, just not officially a submodule and less automatic.

The third option, storing the base theme in a Docker image, would require building a Docker image containing the base theme, usually in the Shippable CI project for that repository, and pushing it to a Docker registry.  You can then use that image as the base image in your Dockerfile for the other projects so that the base theme code will already be in the container.  You'll just have to make sure you don't overwrite it when copying more files during `docker build`.  If you want to keep track of the versions of the images, this is usually done with an [image resource](http://docs.shippable.com/platform/workflow/resource/image/) created in a [syncRepo](http://docs.shippable.com/platform/workflow/resource/syncrepo/) that is [updated](http://docs.shippable.com/platform/tutorial/workflow/writing-keyvalues-to-output-resource/) when a new image is pushed and added as an `IN` resource to the other jobs to determine which tag to use, but that is completely optional.

**Comment by nathanaherne** [comment]
@a-murphy thank you for your very helpful comment. I am trying the submodules option right now.

**Comment by rageshkrishna** [comment]
@nathanaherne Were you able to make this work? Please let us know if you need more help with this.

**Comment by rageshkrishna** [comment]
Hi @nathanaherne. I'm going to close this issue now. Feel free to re-open it if you still need help. Thanks!
