### ISSUE TITLE
Error to download Spring Boot parent pom

### ISSUE THREAD

**Issue by lgblaumeiser** [Shippable/support#4700]
### Description of your issue:
I was using an external docker image, namely maven:3.6-jdk-11-slim. With this, the build worked fine. I just switched back to your standard image drydock/u16javall:v6.10.4 resp. v6.12.4 and get the failure below, the build cannot contact maven central for retrieving the parent pom of spring boot. Any idea why? Any solution?

- Link to the build failure
https://app.shippable.com/github/lgblaumeiser/ProjectTimeManager/runs/259/1/console

Shippable.yml: 

> language: java
> jdk:
>   - openjdk11
>
> build:
>   ci:
> - mvn clean install
> 
> 

Scripts called from the yml (optional)
None

**Comment by trriplejay** [comment]
Hi @lgblaumeiser, 

In the past when we've seen this "trust anchors" issue, the customer was able to resolve it by using the suggestion here: https://stackoverflow.com/questions/47921563/javax-net-ssl-sslexception-the-trustanchors-parameter-must-be-non-empty

which is to add a line like this to your script, before your maven commands:
- `sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure`

Could you give that a try and let us know how it goes?

**Comment by lgblaumeiser** [comment]
Hi @trriplejay ,

No it is not working: see https://app.shippable.com/github/lgblaumeiser/ProjectTimeManager/runs/262/1/console.
It seems that you do not understand my problem. I do not have a certificate or trust store problem. My build in your build container from drydock cannot access maven central whereas it has no issue when I use a different container type like maven:3.6-jdk-11-slim. The problem with this started when I began to use java versions above 8.

The problem is that the build takes much longer with containers that are not directly supported by you, so using the drydock container would speed things up.

**Comment by trriplejay** [comment]
I see that your project is public.  Would you mind if I fork it and try to reproduce this? I think I have a solution but would like to verify before asking you to make further changes to your yml.

**Comment by lgblaumeiser** [comment]
It is MIT licensed so feel free to use it.

The breaking build is in the 102 branch.

Thanks,
Lars

Von meinem iPhone gesendet

**Comment by trriplejay** [comment]
It might sound unrelated, but the issue is actually caused by the ca-certificates-java package that is installed in our java images.  Due to differences in keystore types, the newer java version cannot read the certificates, and thus is not allowed to make any secure connections, causing your download to fail.

To work around this issue until we can fix our images, you can add these lines to your script:
```
    - dpkg --purge --force-depends ca-certificates-java
    - apt-get install ca-certificates-java
```
(you can remove the line that I previously asked you to add)

There was a bug discovered in Debian/Ubuntu that was recently fixed, but our images do not yet include the fix.  Here's a link to one of the original bug reports: https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631

It seems that purging and reinstalling ca-certificates-java fixes this issue in my testing, and is probably faster than downloading a custom image, so I'd recommend using this as a workaround until we can release an updated java image.

Let me know if you have any additional questions.

**Comment by lgblaumeiser** [comment]
Your explanation now gives a story. And actually it worked, thank you very much
