### ISSUE TITLE
Freetype not installed in PHP builds

### ISSUE THREAD

**Issue by shmax** [Shippable/support#4708]
### Description of your issue:

I'm running a static checker ([phpstan](https://github.com/phpstan/phpstan)) on my PHP code in my CI flow. It's complaining about not being able to find two functions:

```
------ ---------------------------------- 
  Line   SigBuilder.php                    
 ------ ---------------------------------- 
  48     Function imagettfbbox not found.  
  111    Function imagettftext not found.  
 ------ ---------------------------------- 
```

These are both from the FreeType library.

When freetype is properly installed, you see it in your `php -i` output like this:

```sh
gd

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.4.11
```

But when I run `php -i` in the context of my `shippable.yml` like this:

```
before_install:
  - php -i
```

I get the following output:
```
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.2.54
WBMP Support => enabled
XBM Support => enabled
```

You can see that FreeType is not installed.

I've tried manually installing freetype a few different ways:

```
before_install:
  - apt-get install -y freetype*
  - apt-get install -y libfreetype6
```

But it has no effect. Please advise!

https://app.shippable.com/github/shmax/shmax.com/runs/1101/1/console

**Comment by trriplejay** [comment]
Thanks for reporting. We should be able to get this extension into our next drydock image release. We'll update here once the feature is available.

The reason your apt-get install doesn't work, is that the extension must also be specified at php compile time, so in order to get it to work today, you'd have to build a custom image on which php has been compiled with that extension.  If you'd like instructions on how to do that, we can provide them. Otherwise, our next image update is scheduled for the end of the month.

**Comment by shmax** [comment]
Thanks much for the response. I figured it was something you would have to sort out, which is why I posted. This isn't holding my work back so I'm happy to wait until the next image update, but at the same time I would also be curious to see the custom build instructions. Thanks again!

**Comment by trriplejay** [comment]
Our build images are open source, so you can actually see exactly how the php image is built here: https://github.com/dry-dock/u16phpall

I think the best approach would be to clone this, then make a couple changes, docker build, push to docker hub, then specify it in the "pre_ci_boot" section of your shippable.yml

For the changes, I haven't tested this but based on what i've read, you'd add the `apt-get install freetype*` line in this section: https://github.com/dry-dock/u16phpall/blob/master/install.sh#L22

and you'd add a `--with-freetype-dir=/usr` to this line: https://github.com/dry-dock/u16phpall/blob/master/version/7_1.sh#L6  (since you're using 7.1)

then in the root directory of the repo: `docker build -t shmax/u16phpall:freetype .` should build the image.  This build will take awhile since it's compiling from source.  Once it's done you can push it to docker hub. Once it's pushed and publicly available, you can use it in CI by modifying your yml as shown here: http://docs.shippable.com/ci/custom-docker-image/#pulling-a-public-image  This will cause your builds to use the custom image, which should now contain the extra plugin.

**Comment by shmax** [comment]
Beautiful, I'll look into that. Thanks much!

**Comment by shmax** [comment]
Ah, I guess we'd better leave this open until you make the change.

**Comment by shmax** [comment]
Hey there, I see that you've [installed FreeType](https://github.com/dry-dock/u16phpall/commit/354f5940889e8e141a9b13ebce4fceb85613e600) in your u16phpall image. I went to update my node pool, but the "Runtime Version" widget only goes as high as `6.12.4`:

![image](https://user-images.githubusercontent.com/773172/52322794-4b2fd980-298f-11e9-8c02-d9ac4b877757.png)

How does one gain access to the next major release? Thanks much.

**Comment by Bharath92** [comment]
We will be releasing `v7.1.4` later this week. After that, you should be able to select `v7.1.4` runtime where freetype is installed on the u16phpall image.

**Comment by shmax** [comment]
Glad to hear it. I'll watch for it. Thanks again.

**Comment by shmax** [comment]
I see the release is complete, and my builds have gone green. Thanks much, guys! 👍
