### ISSUE TITLE
CI regularly hanging, apparently during install of deprecated dependencies

### ISSUE THREAD

**Issue by benkermode** [Shippable/support#4728]
### Description of your issue:
Our builds are regularly hanging indefinitely, and need to be re-started. I often have to restart a build three or four times, and sometimes have to give up. Some repos regularly hang, other don't. It's as if shippable cannot install deprecated dependencies, as the hang seems to occur during deprecated warnings. See attached images.
I thought it was an old version of `graceful-fs` causing the issue. I updated gulp, and it seemed to fix the issue. Now I'm seeing the issue again.

See attached images and hung builds:
https://app.shippable.com/bitbucket/repomode/anti-essays-frontend/runs/330/1/console
https://app.shippable.com/bitbucket/repomode/bartleby-frontend/runs/866/1/console

![hung-build-1](https://user-images.githubusercontent.com/6098080/52220742-72ce5700-2854-11e9-8221-afbd46457bc6.png)
![hung-build-2](https://user-images.githubusercontent.com/6098080/52220744-72ce5700-2854-11e9-989e-d17cca6c1bb3.png)

**Comment by a-murphy** [comment]
It looks like the build containers in those jobs may have unexpectedly exited.  Since you are using older build images, and problems do appear with those images as the dependencies installed become outdated, you may want to see if updating to a newer build image helps. You can do this for your subscription by changing the machine image in your subscription node pool to a newer machine image; the default images used matches the version of the machine image selected.  A list of available machine images is available [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/) and directions to update the machine image [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).

Another thing to check would be the available CPU and memory reported by the nodes.  If you go to the node page right after you find a job that appears to be stuck (click on "node pools" in the settings dropdown on the subscription dashboard, then the node pool name, and then the node) there are graphs with recent data reported by the node.  Two of the graphs report memory and CPU, both of which show a definite increase when running your other jobs.  There is also a graph with the number of containers on the node, which can be used to determine when the job was actually running.  If the stuck jobs show even more memory or CPU usage, you may want to look into increasing the memory and/or CPU available on your build nodes by either [using custom nodes](http://docs.shippable.com/platform/tutorial/runtime/manage-byon-nodes/) or [increasing the size of dynamic nodes](http://docs.shippable.com/platform/management/subscription/billing/#upgrade-or-downgrade-your-plan) in your subscription.

**Comment by benkermode** [comment]
Thanks, we can try those things. Would the above issues explain why the builds seem to hang while trying to install npm dependencies? Even if they are old? Not sure I understand why. We'll certainly give it a try though. Any thoughts appreciated.

**Comment by a-murphy** [comment]
Strange errors occur often enough with the oldest build images that we always consider it to be a definite possibility with any otherwise unexplained errors on those older images.  Those errors are usually related to a version of something on the image that is no longer supported, so it may be incompatible with something else on the image or installations may fail.  However, we don't often see exactly the same error in multiple projects because they all use different dependencies.  And if updating the build image doesn't help, the logs are also consistent with some out-of-memory errors (some languages/commands tend to get stuck and some crash when they run out of memory).

**Comment by manishas** [comment]
Closing since there is no action items on our side. Let us know if you still need help with this..
