### ISSUE TITLE
Integration rename

### ISSUE THREAD

**Issue by vidavidorra** [Shippable/support#4729]
I tried to rename one of my integrations but was unable to use the new name after I renamed it. I've read the conversation in #3585 and came to the conclusion that changing the 'name' does not actually rename the integration. That cannot be done AFAIK, so I've just deleted it and created a new one.

As a user, I don't expect this behaviour so I'd suggest adding a description to the name field in Integrations explaining that it is not the actual name of the integration. Perhaps also show the actual name of the integration that can be used in yml, since that won't be visible anymore once you've 'renamed' an integration AFAIK. Or just simply don't allow the name to be changed.

**Comment by a-murphy** [comment]
There are currently two different types of [subscription integrations](http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/): org integrations that are created in the subscription and account integrations that are linked to the subscription.  It sounds like you renamed an account integration in your account that was linked to a subscription integration.

Org integrations and account integrations at the account level can be renamed, but a subscription integration that links an account integration to a subscription cannot be renamed at this time.   However, because the credentials are stored in the account instead of the subscription, you can add a new subscription integration linked to the same account integration with a new name as long as it is an account integration belonging to your account.  If you go to the [subscription integrations dashboard](http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/#subscription-integrations-dashboard), you can manage integrations at a subscription level.  This allows you to [delete the subscription integration with the old name](http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/#deleting-account-integrations) and [add a new subscription integration linked to the same account integration with the new name](http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/#creating-an-account-integration).

The names of all of the integrations available for use in a subscription (whether added by you or another user) are listed on the [subscription integration dashboard](http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/#subscription-integrations-dashboard).

**Comment by vidavidorra** [comment]
Thanks, didn't know about the multiple integrations. The subscription integration shows all I asked for above, thanks!
