### ISSUE TITLE
[question] How to customize the docker image name dynamically? 

### ISSUE THREAD

**Issue by uilianries** [Shippable/support#4755]
### Description of your issue:
Hi!

I'm read the documentation, but I didn't find any tips to customize the docker image name by env vars

reference: http://docs.shippable.com/ci/custom-docker-image/

I would like to configure a specific custom image by CI job:

```ỳaml
env:
  matrix:
    - DOCKER_IMAGE: "foobar/qux"
    - DOCKER_IMAGE: "foobar/baz"
    - DOCKER_IMAGE: "foobar/couse"
build:
  pre_ci_boot:
    image_name: ${DOCKER_IMAGE}
    image_tag: latest
    pull: true    
  ci:
    - ./run.sh
```

As you can see, I would like to use a matrix for that.

Is there any way to customize the docker image name?

Regards!

**Comment by a-murphy** [comment]
The example you included will work.  The first job in the matrix will use `foobar/qux` and the second `foobar/baz`.  Could you clarify where you are having trouble?  Please include either a link to the project or the "Project Id" from the bottom of the page if possible so that we can see how your project is configured.

**Comment by uilianries** [comment]
Thanks for your quick answer!

Okay, I gonna reproduce the error and link the log ASAP!

**Comment by uilianries** [comment]
Sorry, It's working like you said!

https://app.shippable.com/github/uilianries/conan-folly/runs/14

I made some confusion between `matrix config` vs `env`

Regards!
