### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by magwasada** [Shippable/support#4764]
### Description of your issue:
The magwasada account is blocked by shippable.
Yes, I have another account, this one is specifically made in order to create videos helping new developers of a specific project (edemo/PDEngine) to go through the setup steps, in Hungarian language. I cannot demo it with my main account, as the integration is already set up there.
(Here is the first video of the series: https://www.youtube.com/watch?v=4KWTocBuPXY )

A special issue here is that I might need to delete and recreate the account several times to start with a clean sheet state.

I will delete everything once the videos are made, promise.

**Comment by a-murphy** [comment]
I've unflagged your account so that you should be able to log in.  If you delete your account, it's possible that the new account will also be flagged.  You can either avoid this by deleting the integrations and disabling any projects enabled for your video instead of deleting your account to reset, or you can ask us to unflag your new account again when it happens.  In any case, the accounts are flagged by an algorithm that identifies potentially malicious accounts and accidentally flags some legitimate accounts as well.  It is entirely up to you if you want to delete your second account when you are done with your project or continue to use it.

**Comment by magwasada** [comment]
Thank you.
