### ISSUE TITLE
Way to see how much resources a job is consuming?

### ISSUE THREAD

**Issue by jmreicha** [Shippable/support#4765]
### Description of your issue:

I am debugging some build failures and was wondering if there is a way to see how much memory/cpu a job is taking?  The job seemingly just dies and I don't have much else to go on.

I have been able to verify everything is working locally but the local environment has significantly more resources and would like to know if that can be ruled out or not.

- https://app.shippable.com/github/jmreicha/jobs/build_arm64/builds/5c785c5eb2f57f060000a9f1/console
- https://github.com/jmreicha/freeipa-container/blob/master/shippable.yml

**Comment by jmreicha** [comment]
The other thing I was curious about is if it is possible to remove the no log 10 minute timeout [described here](https://blog.shippable.com/changing-the-default-timeout-for-a-continuous-integration-project) to rule that out as a culprit?

**Comment by a-murphy** [comment]
The memory and CPU in use on a node can be seen on the node page.  Directions to view a node pool are [here](http://docs.shippable.com/platform/management/subscription/node-pools/#viewing-subscription-node-pools) and if you click on a node within that node pool, there are graphs with recent data about the node.

And there is no timeout after there are no logs for ten minutes at this time.  When that did exist, the status would have been updated to `TIMEOUT`, the same as for the 60 and 120 minute default timeouts.

**Comment by jmreicha** [comment]
Hrm, I am building against the arm node pool and don't see any way to view the graphs, I'm guessing because it is a shared node pool?

**Comment by a-murphy** [comment]
Sorry, I hadn't noticed that you were using a shared node pool.  Unfortunately, there isn't currently a way for you to see statistics for the nodes in a shared pool because the nodes are also used by other subscriptions.  The resources available when the job starts are shown in the "setup" section of the console logs.  The node in the shared pool will only be used for your job while the job is running, so all of the resources shown in the "setup" section should be available.  You could try adding commands to the `on_failure` section to log additional information when your job has failed, but I'm not sure how useful that information would be to you.

**Comment by jmreicha** [comment]
No worries.  I would love to see resource usage for shared pools in the future.
