### ISSUE TITLE
S3 Artifacts Trigger

### ISSUE THREAD

**Issue by dsarfati** [Shippable/support#4766]
### Description of your issue:
We have a create-react-app that is currently being built with shippable, then deploying the artifacts to an S3 bucket, with each build being placed into a new "folder". We would like to trigger subsequent CD to actually deploy that new build, I have been unable to find any examples of using S3 as a resource. Are we better of using a direct trigger rather than a resource based trigger?

Thanks for the help in advanced!

**Comment by a-murphy** [comment]
In this case, it sounds like it would make the most sense for you to update a resource after updating S3 and using that resource as an input to the next job to trigger the following job.  Some more information about updating resources is [here](http://docs.shippable.com/platform/tutorial/workflow/writing-keyvalues-to-output-resource/).  Basically, just choose a [resource](http://docs.shippable.com/platform/workflow/resource/overview/) type that makes sense for the information you need to store (probably a name or location of some kind), add it as an `OUT` to the first job and an `IN` to the second and update the resource in the first job using [shipctl](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#put_resource_state) to trigger the second.

**Comment by dsarfati** [comment]
Thanks for the fast response! When you same name or location you are referring to the state we would pass though not a resource type correct? I was looking at either the file or a params resource type.

**Comment by a-murphy** [comment]
You can pass information in the job state as well if you include the first job as an `IN` to the second.  However, that can confuse triggering somewhat if you are also using resources.  They'll both trigger unless one has `switch: off` on the `IN` step.

If you don't really need the state from the previous job, a resource between the jobs containing the pieces of information you do need gives an easy-to-read history of what triggered the second job.  Params resources work well in almost all applications because the environment variables created for the values in a params resource are usually easy to use.

If you are planning to use information from the previous job state directly, you don't actually need the resource to trigger.  You can just list the first job as an `IN` to the second.  It can be a little simpler, but you lose some control over when it triggers and the history can be a little harder to read without the `versionName`s of a resource version list.

**Comment by dsarfati** [comment]
Right now it’s a runci that is pushing the artifacts to S3 so it sounds easy enough to have a params resource that I can just set the S3 url in. Then my deploy job can simply copy the S3 artifact to the production location.
