### ISSUE TITLE
Queued jobs not moving to running

### ISSUE THREAD

**Issue by tylertravismya** [Shippable/support#4768]
Hi,

Started my eval last night.  Very straightforward and things were working just fine and suddenly none of my builds transition from queued status.

I went so far as to start from scratch.

I removed the project from BitBucket, refreshed the SCM to see it was removed from the Shippable dashboard.  I then created the project within BitBucket, refreshed the SCM, enabled the project for CI, and created a subscription integration.

Dashboard link - https://app.shippable.com/subs/bitbucket/tylertravismya/dashboard

Any help to moved forward with the eval would be appreciated.

**Comment by a-murphy** [comment]
Builds usually remain queued when there is no node available to run them in your subscription.  In your case, an rSync job appeared to have gotten stuck processing, and since it was using the only available node (your subscription allows one job to run at a time on the free plan), nothing else could run.  I've cancelled the stuck rSync job and your other jobs have now completed.

**Comment by manishas** [comment]
Closing since there is no additional action item on our side.
