### ISSUE TITLE
Deployment jobs are failing

### ISSUE THREAD

**Issue by Mendalorien** [Shippable/support#4782]
### Deployment jobs are failing:

We have several deployment jobs which fail on a regular basis.  The initial failure comes after the deployment to Kubernetes completes, and it deletes the previous deployment.  It then tries to save the manifest information, and that part has the following error:

> Failed to persist data for manifest analytics-ui_analytics_manifest due to Error: ENOENT: no such file or directory, unlink '/build/state/analytics-ui_analytics_manifest/kube-deployment-spec.json',Error: ENOENT: no such file or directory, unlink '/build/state/analytics-ui_analytics_manifest/kube-namespace-spec.json'

The job in Shippable fails, but the actual deployment to Kubernetes was successful, and deleted the previous one.  However, because the manifest info couldn't be saved, re-running the failed deployment in Shippable results in it looking for the previous deployment that was deleted in the failed deploy, and orphaning the deployment that it actually did.  The result is two deployments in Kubernetes of this service.  If this one fails as well then the process repeats, and we have many orphaned deployments of the same service in Kubernetes.

Once the deployment actually runs successfully we can go into Kubernetes, and manually delete all of the orphaned deployments.  Most of our services are resilient to the number of pods running, so the orphaned deployments are mostly an annoying resource allocation issue.  However, they are untracked deployments, which means we have to manually look for them, and remove them.

Now, re-running the deploy job after a failure like this basically hoses the blue/green logic.  It is looking for a previous deployment that was deleted, and throws an error.  It then repeats this multiple times until the job either fails again, or by some magic it actually finishes successfully.

We have multiple service deployments that suffer from this, but here's an example from just one:

The initial failure:
https://app.shippable.com/github/supplypike/jobs/analytics-ui_prod_analytics_deploy/builds/5c90f60d2d85e6000700d3f7/console

A successful re-run of the deploy job immediately after, which orphans the deployment done in the failed job:
https://app.shippable.com/github/supplypike/jobs/analytics-ui_prod_analytics_deploy/builds/5c90faaa5142dd0007e8df1d/console

**Comment by trriplejay** [comment]
Hi @Mendalorien,

It seems like your deploy job is trying to deploy multiple copies of the same manifest. I think this is the reason for the strange behavior you are seeing.  I notice that you have a deploy job IN as well as a manifest IN.

When you use a deploy job as an IN to another deploy job, it will actually pass its manifest along the chain of jobs, so it seems like you should not need to also list `analytics-ui_analytics_manifest` as an IN, since that is the same manifest that is already being passed in from `analytics-ui_demo_analytics_deploy`.

You can still keep your `applyTo` sections that reference the manifest, because the manifest name is also passed in from the deploy job.

The other option is to remove the deploy job instead since the job is only triggered by a time resource, but if you like seeing the connection between deploy jobs in the UI, then I'd recommend removing the manifest resource and letting the previous deploy job pass the manifest along.

Let us know if you have any questions!

**Comment by manishas** [comment]
Closing since the question has been answered.
