### ISSUE TITLE
Increased nodes but seeing jobs as waiting

### ISSUE THREAD

**Issue by DeanHutchison** [Shippable/support#4785]
### Description of your issue:

We added a new node yesterday but we are still seeing jobs as waiting when only one job is processing. I have seen two jobs processing at the same time but mostly there is one job waiting when one job is processing.

Is someone able to take a look at our account and make sure that everything is ok ?

Subscription Id: 5bc848eba362a50700c71d63 

Cheers,
Dean

**Comment by a-murphy** [comment]
It looks like you have both nodes in the same node pool, so it most likely has to do with how the waiting jobs are configured.  The dependency modes are described [here](http://docs.shippable.com/platform/workflow/job/overview/#job-trigger-modes).  It's likely that the waiting jobs were waiting for another job to complete because they have been configured not to run while there is an input still processing.  It's also possible that you had triggered the same assembly line job multiple times.  Jobs other than runCI or runSh with [triggerMode](http://docs.shippable.com/platform/workflow/job/runsh/#yml-definition) set will wait until previous builds for the same job are complete before running.

**Comment by DeanHutchison** [comment]
Thanks @a-murphy.

We were looking to reduce the processing time of each job. Do you think it would be better to increase the size of the node (XL) rather than go with two nodes of the same size (L)?

Cheers,
Dean

**Comment by a-murphy** [comment]
Is there a particular type of job that you are trying to speed up?  Increasing the node size typically only helps if a runSh or runCI job is currently using all of the resources available on the nodes.  You can see what is currently used by recent jobs on the page for a node by going to the node pool page and clicking on the nodes.

**Comment by manishas** [comment]
Closing... please let us know if you need help with anything else.
