### ISSUE TITLE
docker network issues 

### ISSUE THREAD

**Issue by fieldawarepiotr** [Shippable/support#4805]
### Description of your issue:
Number of our jobs fails due to the some docker leftovers from other projects.
- docker networks
- running containers with exposed ports that are causing port clashes.

I am missing something from documentation? My understanding is that each job should run in isolation.

- Link to the build failure
https://app.shippable.com/github/fieldaware/fieldaware/runs/6273/3/console

**Comment by a-murphy** [comment]
It looks like you're using Docker Compose to start some containers in your builds.  Nodes are reused for other jobs in the same subscription and containers started during a build run on the node, not within the build container.  Shippable will remove the build container when a job is complete, but does not know if other containers have been started or if you intend to reuse those containers in future builds.  We usually suggest that if you are starting containers in your builds, that your script also remove any containers at the beginning and/or end of your build to prevent these sort of conflicts.

**Comment by fieldawarepiotr** [comment]
@a-murphy thank you for the quick response.
Can I just `docker ps -q | xargs docker rm -f` at the begging of each job then?

**Comment by a-murphy** [comment]
Unfortunately, that would remove the container that processes the build.  Naming the containers that you start in order to make them easier to remove is usually best.  You could also add a filter ([Docker documentation](https://docs.docker.com/engine/reference/commandline/ps/#filtering) to your `docker ps` or try [docker compose down](https://docs.docker.com/compose/reference/down/) if either of those work better for you.

**Comment by fieldawarepiotr** [comment]
Thank you for clarification.
