### ISSUE TITLE
Deploy to baremetal

### ISSUE THREAD

**Issue by Asgoret** [Shippable/support#4808]
Hi to everyone! Can somebody route me to documentation where described how to deploy on baremetal?
What i mean. I have this workflow:
1) SSH to VM
2) Pull build container
3) Stop run container
4) Run new container

**Comment by trriplejay** [comment]
I don't think we have specific documentation for that flow, however it should be fairly straight forward to achieve within a Shippable CI job.

You can take a look at this page, which describes how ssh keys work on Shippable: http://docs.shippable.com/ci/ssh-keys/#ssh-keys

I'd recommend finding your subscription's public ssh key on the subscription settings page, and manually ssh into your vm to add the public key to the `authorized_keys` file in ~/.ssh.

Shippable will automatically add your subscription's private key to the machine that the build is running on, so inside your build, you can directly ssh into your vm.

so, you could arrange your shippable job to do something like:
- run tests
- build new docker image
- push to hub
- ssh into VM
   - pull image that was just built
   - stop running container
   - run new container based on new image

The IP of the image could be included as either a [key-value pair integration](http://docs.shippable.com/platform/integration/key-value/) or a [secure environment variable](http://docs.shippable.com/ci/env-vars/#secure-variables). If the machine IP changes frequently i'd recommend the key/value pair since the integration can be easily changed without having to make adjustments to the .yml.

let me know if you have any other questions!

**Comment by Asgoret** [comment]
@trriplejay thanks for answer! I can work at this case only on next week. Close at this moment this issue or you can wait?

**Comment by trriplejay** [comment]
I'll close for now, but feel free to comment or open a new issue if you run into something.
