### ISSUE TITLE
Cloning git repo inside a build

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4809]
For a node.js build, I added following in the package.json under dependencies and have enabled the project on shippable:
```
"<masked>": "git+ssh://git@github.com/<masked>/<masked>.git"
```

When building it complains that it cannot clone the repo.
https://app.shippable.com/github/Falkonry/saker/runs/1794/1/console

Can you please suggest what is the right way to do it?

**Comment by trriplejay** [comment]
i think you'll need to take your public subscription key, found on the subscription settings page, and add it to that github repository as a deploy key (go to repository settings -> deploy keys).  This should give the shippable build authorization to clone the repo.

Enabling the project isn't enough, because each project is given a unique project key on shippable, so when running project A, it cannot by default clone project B, even if both are enabled in the same shippable subscription.  However if you manually add the subscription key to the repo, then the key is shared across projects (within the same subscription) and will be able to clone.

**Comment by phagunbaya** [comment]
thanks. that worked.
