### ISSUE TITLE
Builds Intermittently Timeout

### ISSUE THREAD

**Issue by bpummill1** [Shippable/support#4813]
### Description of your issue:

We are experiencing intermittent timeouts with the build of our UI service. Sometimes it is succeeding, sometimes it timeouts, and then on the first time we rebuild after the timeout, it succeeds. I saw issue #3819 but we are not using gulp. 

Build example: https://app.shippable.com/github/supplypike/cs-service-web-ui/runs/2202/summary/console

Changing nothing and just rerunning the build seems to resolve the issue.

**Comment by a-murphy** [comment]
The account currently selected to run webhook builds for that project only has read access to the repository, and it can't update the runSh job state when it is complete.  Manual runs will use the account that triggered them, so that is why those are working.  Could you try selecting a different account on the project settings page?  Documentation for the project settings page is [here](http://docs.shippable.com/platform/management/project/settings/), and the "Account Used" setting near the top of the project settings page is the one that determines which account is used to run webhook builds.

**Comment by bpummill1** [comment]
Thanks, we are going to give that a try. Appreciate the quick response.
