### ISSUE TITLE
No global git configs found

### ISSUE THREAD

**Issue by damianszczepanik** [Shippable/support#4815]
### Description of your issue:
I'm not able to build java project as `No global git configs found` is printed.

- Link to the build failure
https://app.shippable.com/github/jenkinsci/office-365-connector-plugin/runs/97/1/console
- Scripts called from the yml (optional)
https://github.com/jenkinsci/office-365-connector-plugin/pull/115

Same happens on master branch

**Comment by a-murphy** [comment]
Not finding any global git configs, although logged, is very unlikely to cause any errors and did not cause your build to fail.  It looks as though one of your Maven plugins is checking the Maven version and the version in that build image does not match what it requires.  Since you are still using the same build image, the failure most likely started when one of your Maven plugins was updated.  As your project is using an older image, I would suggest updating the node pool (directions [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image)) to use a newer default image.  Newer images will have newer versions of dependencies installed and may resolve your issue.

**Comment by damianszczepanik** [comment]
It does. I did not have such problem with other CI and hopefully other projects can also run with the same image.
