### ISSUE TITLE
Release webhook for Github doesn't work

### ISSUE THREAD

**Issue by Asgoret** [Shippable/support#4819]
I make settings for repository and then make release in github and nothing happend
![image](https://user-images.githubusercontent.com/30697011/56890354-e2ce3100-6a81-11e9-9727-9159903a3acb.png)

**Comment by a-murphy** [comment]
Did your release contain `[skip ci]` or `[ci skip]`?  If so, nothing will be triggered.  Could you also confirm that the GitHub webhook has "releases" checked?  It can be viewed on GitHub in the repository settings under webhooks.

**Comment by Asgoret** [comment]
@a-murphy Hi.
No, i haven't `skip ci` in my shippable.yml. I make release through github gui.

**Comment by Asgoret** [comment]
@a-murphy 
I see pushes from GitHUb to Shippable and nothing happens

**Comment by a-murphy** [comment]
Could you try clicking the "reset all keys" button in the second-to-last panel on the project settings page to replace the webhook on GitHub?  Your project has commit and tag webhooks disabled, so webhooks for commits and tags would have been ignored, but the webhooks for releases created should have processed if they were received.

**Comment by Asgoret** [comment]
@a-murphy ok...do so and then create new release in github, in shippable nothing happens

**Comment by Asgoret** [comment]
UPD: I see this in jobs, but it doesn't trigger job to start 
![image](https://user-images.githubusercontent.com/30697011/57092425-16c08500-6d14-11e9-88cc-aedcfc51ddf6.png)


UPD#2: If i open more, i can see this:
```
....
    "isRelease": true,
    "releaseName": "v1.1.1",
    "releaseBody": "Test webhook with new keys",
....
```

UPD#3: Maybe there isn't some part in yml file? Or shippable saw new release and must start job be himself?

UPD#4: Or can be problem because it's private repo? But i can run CI manually

**Comment by a-murphy** [comment]
Do you have a `branches` section in your `shippable.yml`?  If so, if the tag in the release either matches something in [except](http://docs.shippable.com/ci/specify-branches/#excluding-specific-branches) or doesn't match anything in a [only](http://docs.shippable.com/ci/specify-branches/#including-specific-branches) section, the release will not trigger anything.  Since you only have release builds enabled, you shouldn't need a `branches` section unless you want to limit the releases built to certain tag patterns.

**Comment by Asgoret** [comment]
@a-murphy yeah... i delete branch section and it works...but why it doesn't work before? release is worked only for master branch...

**Comment by a-murphy** [comment]
A release doesn't have a reference to a branch.  It may look like it does in the GitHub UI when you create the release, but it will actually create a tag for the latest commit in that branch and the release references the tag.  The commit that is tagged may even be in multiple branches.

**Comment by Asgoret** [comment]
@a-murphy Thanks for help! I close issue!)

**Comment by Asgoret** [comment]
@a-murphy i understood correctly, that i can't get badge from tag? only from branch?

**Comment by a-murphy** [comment]
Although the branches aren't listed on the badge tab, you can edit the badge URL for another branch to create a URL for a tag.  For example, changing the ending from `badge?branch=master` to `badge?branch=v1.1.0` will create a URL for a badge for `v1.1.0` tags and releases.  There isn't much demand for a badge for a tag because a tag will usually only reference one commit (and not change).

**Comment by Asgoret** [comment]
@a-murphy ok.... and is there any workarounds to have release and badges?

**Comment by a-murphy** [comment]
A badge URL with a tag name in the branch query parameter will show the latest status for a build related to that tag.  That would be either release or tag builds.  We don't currently have any options that would exclude tag builds while still including release builds , but since you have tag builds disabled that shouldn't be a problem.  Basically, the badge URL will return a badge with the status of the latest build on the history tab, that isn't a pull request, with the `branch` parameter in the URL matching the "context" column on the history page.

**Comment by Asgoret** [comment]
@a-murphy but i saw only builds for master branch...should i clean history? or something?

**Comment by a-murphy** [comment]
If you go to your [project page](http://docs.shippable.com/platform/visibility/project/dashboard/) and then click the "history" tab between the header at the top and the table with the latest project for each branch, you should see all the builds that have run, including your release builds.

**Comment by Asgoret** [comment]
@a-murphy yeah. I saw builds there, but how see last build in project home? And how do badge from that? I look inside settings but branch is hard-code everywhere

**Comment by a-murphy** [comment]
Release builds will not appear on the project dashboard; it's not currently an option.

And the tags are not shown on the badge tab because there is very little demand for them and listing all tags in many repositories would make it difficult to find the branches.  However, you can copy the badge information for `master` and replace `master` with your tag to get a badge for a tag.  If you have a particular tag in mind and don't mind it being posted publicly, I can also paste the badge for that tag here.

**Comment by Asgoret** [comment]
@a-murphy is any project when this will be fixed? I mean normal work with release and tags....

**Comment by a-murphy** [comment]
We're not planning any changes to how releases and tags are shown at this time.  Could you open a new issue describing what you would like so that we can tag it as a feature request?
