### ISSUE TITLE
Jobs got deleted

### ISSUE THREAD

**Issue by buckett** [Shippable/support#4852]
### Description of your issue:

I just went back to my shippable dashboard and one of my Github organisations was missing from my dashboard, I went to my account and re-synced the SCM setup and the organisation re-appeared and the job re-appeared, but it's lost all of it's history.

https://app.shippable.com/subs/github/oxctl/dashboard
https://app.shippable.com/github/oxctl/canvas-calendar-import/dashboard

I am sure I didn't delete the job, is this expected behaviour?

**Comment by buckett** [comment]
And the history has just re-appeared.....

**Comment by a-murphy** [comment]
The organization disappearing was mostly likely because Shippable was unable to determine that your account had access to any of the repositories in that organization.  The history would not be deleted because permissions often change and we have no way of knowing if that access was only temporarily lost or if there will be another account that also has access to those repositories.  Synchronizing the account usually corrects any permissions that may have been lost as the result of an error the last time the account was synchronized.

From the description, I would guess that the history reappeared after the page was refreshed.  It sounds like something may have happened while the updated permissions were being processed for display that resulted in the enabled projects appearing but not the build history.  Refreshing the page would have fetched everything again.
