### ISSUE TITLE
ECR Docker login fails with 'Cannot autolaunch D-Bus without X11 $DISPLAY'

### ISSUE THREAD

**Issue by dagomar** [Shippable/support#4862]
I've followed the integration guide here: http://docs.shippable.com/ci/push-amazon-ecr/

I am getting the following error when doing a build:
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

https://app.shippable.com/bitbucket/swisnl/era/runs/15/1/console

Googling the issue seems to indicate that there is an issue with docker-compose in Ubuntu 18.04 (provided by Shipable I believe). The resolution may be found here: 
https://github.com/docker/compose/issues/6023

**Comment by a-murphy** [comment]
It looks like you are using your own custom image in the linked build, and the error occurs in a container from that image.  Since you are using an Ubuntu 14.04 host that shouldn't have `docker-compose` installed on the host, it's a little hard to see how it could be related to an error occurring with the versions of packages installed on the host.  Do you have `docker-compose` installed in your image?  And is it an Ubuntu 18.04 image?

**Comment by dagomar** [comment]
Thanks for the reply, I'm looking into it right now and I believe you might be right. I'll close this for now as it seems to be on our end!
