### ISSUE TITLE
rails builds with Postgres 9.5  breaking

### ISSUE THREAD

**Issue by rabicherian** [Shippable/support#4881]
### Description of your issue:
A stable build pipeline has broken with this error:
sudo apt-get -y install libpq-dev
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  postgresql-doc-9.5
The following NEW packages will be installed:
  libpq-dev
0 upgraded, 1 newly installed, 0 to remove and 395 not upgraded.
Need to get 172 kB of archives.
After this operation, 759 kB of additional disk space will be used.
Err http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main libpq-dev amd64 9.5.1-1.pgdg14.04+1
  404  Not Found [IP: 87.238.57.227 80]
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-9.5/libpq-dev_9.5.1-1.pgdg14.04+1_amd64.deb  404  Not Found [IP: 87.238.57.227 80]

- Link to the build failure
https://app.shippable.com/bitbucket/nsox/bigchill/runs/1399/1/console

- Scripts called from the yml (optional)
language: ruby
rvm:
  - 2.2.3
services:
  - postgres
build:
  ci:
    - sudo apt-get -y update
    - sudo apt-get -y install libpq-dev
   ...

**Comment by rabicherian** [comment]
Note in previous successful builds here are the relevant logs:

sudo apt-get -y install libpq-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libpq5
Suggested packages:
  postgresql-doc-11
The following NEW packages will be installed:
  libpq-dev
The following packages will be upgraded:
  libpq5
1 upgraded, 1 newly installed, 0 to remove and 401 not upgraded.
Need to get 325 kB of archives.
After this operation, 850 kB of additional disk space will be used.
Get:1 http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main libpq5 amd64 11.3-1.pgdg14.04+1 [165 kB]
Get:2 http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg/main libpq-dev amd64 11.3-1.pgdg14.04+1 [161 kB]

**Comment by rabicherian** [comment]
Looks like the issue is the default Shippabe node defaults to   Ubuntu 14.04  (Trusty) on-demand node
and the postgres default repo (http://apt.postgresql.org/pub/repos/apt/trusty-pgdg/main) for Ubuntu 14.04  (Trusty) is now broken.

The  Default Node Pool settings do not allow me to  choose anything other than Ubuntu 14.04, so I guess this will affect all PG builds on  shippable free plans?

**Comment by a-murphy** [comment]
This appears to be because the node pool in your subscription is configured to use the oldest default images, and those images don't have a more recent key to verify the signature on that repository.  The default build images on Ubuntu 14.04 with a newer machine image selected are Ubuntu 16.04 images and should work, and [directions to change that in your node pool are here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).  I've checked that `libpq-dev` can be installed in a `v7.2.4` image.

**Comment by rabicherian** [comment]
Thanks for the response. 
Using the v7.2.4 image I was abe  to get past the libpq-dev install stage, but running into build failures during cache stage. Not sure how to resolve this:
https://app.shippable.com/bitbucket/nsox/bigchill/runs/1436/1/console

cache
  tar -czf /home/shippable/cache/buildCache.tar.gz /usr/local/rvm/gems/ruby-2.2.3

**Comment by rageshkrishna** [comment]
This might be happening because the v7.2.4 images do not have ruby 2.2.3 installed as a system package. It's actually being installed by `rvm` at run time, so I suspect the `/usr/local/rvm/gems/ruby-2.2.3` directory doesn't exist, causing `tar` to fail.

Can you try caching ` ~/.rvm/gems/$(rvm strings 2.2.3)` instead?

**Comment by rabicherian** [comment]
Thanks for the quick response:

I changed shippable.yml to :
 cache: true
  cache_dir_list:
    - ~/.rvm/gems/$(rvm strings 2.2.3)
    - $SHIPPABLE_BUILD_DIR

But similar build failure:
https://app.shippable.com/bitbucket/nsox/bigchill/runs/1442/1/console

cache
  tar -czf /home/shippable/cache/buildCache.tar.gz ~/.rvm/gems/ruby-2.2.3

Suggestions to resolve, please?

**Comment by a-murphy** [comment]
Both `/home/shippable/cache` and `/usr/local/rvm/gems/ruby-2.2.3` should be defined at that point.  Are you removing either of those in your script?  I would also suggest resetting the cache from the project setting page if you haven't reset the cache since you switched images, just to rule it out.  If resetting the cache doesn't help, are you able to cache just `$SHIPPABLE_BUILD_DIR` (meaning the problem must be with `/usr/local/rvm/gems/ruby-2.2.3`), or just `/usr/local/rvm/gems/ruby-2.2.3`?

**Comment by rabicherian** [comment]
Thanks for the explanation.

The build succeeds with just caching  $SHIPPABLE_BUILD_DIR

The build also succeeds when I hardcode  ruby 2.2.3 location in shippable.yml
  cache: true
  cache_dir_list:
    - /usr/local/rvm/gems/**ruby-2.2.3**/gems
    - /usr/local/rvm/gems/**ruby-2.2.3**/specifications
    - $SHIPPABLE_BUILD_DIR

The build fails when shippable.yml has ruby version defined with  $(rvm strings 2.2.3)
  cache: true
  cache_dir_list:
    - /usr/local/rvm/gems/$(rvm strings 2.2.3)/gems
    - /usr/local/rvm/gems/$(rvm strings 2.2.3)/specifications
    - $SHIPPABLE_BUILD_DIR 

Not sure if this helps but the output of    **echo $(rvm strings 2.2.3)**  is
ruby-2.2.3 __SH__CMD__END__|{"type":"cmd","sequenceNumber":"1562647598","id":"2b50b911-6f35-4c44-a567-3c9f189a6b3a","exitcode":"1"}|echo $(rvm strings 2.2.3) __SH__GROUP__END__|{"type":"grp","sequenceNumber":"1562647598","id":"1aa15736-fa69-4e01-8ecb-2229150c81f7","is_shown":"false","exitcode":"1"}|build_ci __SH__GROUP__START__|{"type":"grp","sequenceNumber":"1562647598","id":"7137c141-3e89-46c0-9594-2db62846a236","is_shown":"true"}|build_on_failure __SH__GROUP__END__|      
....
....

So certainly a workaround is to not use **$(rvm strings 2.2.3)**  but to hardcode the location.
Suggestions?

**Comment by a-murphy** [comment]
It's certainly unusual that you see some of the log formatting in the command output.  It implies that the line output didn't end when it should have.

For now, since you are only using one version of Ruby and the paths won't change unless you switch to a different image, I would suggest continuing to hardcode `ruby-2.2.3`.

**Comment by rabicherian** [comment]
Thanks. Works. Closing the issue.
