### ISSUE TITLE
Builds failing after OS upgrade

### ISSUE THREAD

**Issue by benjamin-ltr** [Shippable/support#4888]
### Description of your issue:

After changing the OS from Ubuntu_14.04 to Ubuntu_16.04 on our node pool, the build keeps failing on the postgres start and I have no logs on this build step.

![Screenshot from 2019-07-17 10-49-48](https://user-images.githubusercontent.com/37066221/61361464-d38ca180-a880-11e9-8324-c41a0c71aac9.png)

I tried different runtime versions but the problem is the same every time.

**Comment by rageshkrishna** [comment]
Do you have an `.nvmrc` or `.rvmrc` file in your git repo?

**Comment by benjamin-ltr** [comment]
Yes we have a .nvmrc in the git repo (v8.16.0).

**Comment by rageshkrishna** [comment]
I think that's what's causing the problem.

With runtime version 6.1.4 and above, the build containers source nvm and rvm when the build begins. The default behaviour of these tools is to automatically switch the language version based on the presence of `.nvmrc` or `.rvmrc`.

The ruby image you are using does not have any node versions initialized through npm. Node v10.14.2 is available, but it is not managed by npm. As a result, after your git repository is cloned and the next command runs to start postgres, npm throws an error because it cannot switch to the node version your `.npmrc` file is requesting (8.16.0) and causes the build to terminate. The error, unfortunately, is silent because of the way the build script handles bash traps.

At this time, there are only two ways to work around this issue:

1. Remove the `.npmrc` file, or
2. Use a custom image that has both the node and ruby versions that you need

**Comment by rageshkrishna** [comment]
It looks like you got it working. I'm going to go ahead and close this issue, but feel free to reopen it if you still have trouble.

**Comment by benjamin-ltr** [comment]
Yep, it worked.
Thanks
