### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by db** [Shippable/support#4893]
### Description of your issue:

I have raised issue in zen desk portal also. New user sees Account Blocked message. What information do you need to check this? Prefer not to expose the user information in public issues register.

**Comment by a-murphy** [comment]
In order to unblock an account, we need some information to identify the account.  This is usually the username on the source provider, but some people prefer to provide an e-mail address.  Our usual suggestion for issues that require information that should not be public is to either open the issue on Zendesk for those with access or send an email.  Although we may be able to identify the correct blocked account with less information in some cases, we can't be certain that will always be possible.
