### ISSUE TITLE
Migrate existing Account Integration entries to Subscription Integration

### ISSUE THREAD

**Issue by Bekt** [Shippable/support#4921]
Account: https://app.shippable.com/subs/github/supplypike/integrations

Hello, we need to migrate all Account Integration entries belonging to @Boolos to be a Subscription Integration on our org. We couldn't figure out how to do this through the UI. Can you help?

The individual Account Integrations were created before Subscription Integration was released.

**Comment by a-murphy** [comment]
There isn't a way for you to convert subscription integrations linking account integrations to standalone subscription integrations, but we will do that for the integrations you have specified in your subscription.  I'll let you know when we're done.

**Comment by a-murphy** [comment]
I've updated most of those subscription integrations to no longer reference the account integrations.  The remaining Docker integration is an older type of Docker integration that would not usually be a possible integration type for an org subscription integration, so I'll investigate if it would work as a subscription integration before updating it.  And I have not updated the SCM integration because we don't usually recommend creating an SCM integration as an org subscription integration.

**Comment by Bekt** [comment]
@a-murphy thanks so much!

I updated the SCM integration to point to mine (i'm an org owner). Can you also update the following to subscription integrations please?
```all_clusters, cgen_secrets_key, testing_cluster```

**Comment by a-murphy** [comment]
I've updated those integrations.  Please let us know if I've missed anything.

**Comment by Bekt** [comment]
much thanks :)
