### ISSUE TITLE
Build is not being pushed. New Owner and credentials used.

### ISSUE THREAD

**Issue by sun71** [Shippable/support#4929]
### Description of your issue:
When we commit changes to Github, Build was always pushed to EC2 server. Since 27, it is stopped working. We do not receive any error. Person, who set it up left the company. I am not able to see Shippable log from my credentials. Please help. 

language:   node_js
name: shocaseapi_ciRepo
type: ciRepo
pointer:
  souceName: ShocaseEntertainment/shocase-api

node_js:
  - 8.1.4

**Comment by a-murphy** [comment]
It looks like your account was flagged as a potentially malicious account, so I've unblocked it.  If you have access to the repository on GitHub, you should be able to see it on Shippable.

Since you mentioned that the person who set it up has left, I assume that account no longer has access.  It looks like their access may have been synchronized at the same time that the job last ran, causing some job updates to fail.  I would suggest trying again, and let us know if it is still failing or you are still unable to see it.

**Comment by sun71** [comment]
Thanks a lot for your quick response. When we commit changes, we do not see any errors or messages. We do not see changes are reflected anywhere. I can not see logs to analyze the issue. I only see followings:




    On Monday, September 2, 2019, 11:23:50 AM PDT, a-murphy <notifications@github.com> wrote:  
 
 
It looks like your account was flagged as a potentially malicious account, so I've unblocked it. If you have access to the repository on GitHub, you should be able to see it on Shippable.

Since you mentioned that the person who set it up has left, I assume that account no longer has access. It looks like their access may have been synchronized at the same time that the job last ran, causing some job updates to fail. I would suggest trying again, and let us know if it is still failing or you are still unable to see it.

**Comment by a-murphy** [comment]
If there should be jobs that aren't there, then GitHub probably deleted the webhook when an account on GitHub lost access to the repository.  This can be fixed by going to the project setting page (documentation [here](http://docs.shippable.com/platform/management/project/settings/)) and clicking the "reset all keys" button in the second-to-last panel.  That button will create a new webhook on GitHub to trigger the project on Shippable.
