### ISSUE TITLE
Unauthorized errors because shippable_retry npm install does not recognize --only=prod flag

### ISSUE THREAD

**Issue by gabrielpascua** [Shippable/support#4939]
### Description of your issue:
Shippable builds are failing because it installs non-production dependencies.  These are private git repositories from which it does not have authorization.

- Error
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@bitbucket.org/private-repo-url/goes-here.git
npm ERR! 
npm ERR! Unauthorized
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/bitbucket/bncompass/solutions_service/runs/490/1/console

- Scripts called from the yml (optional)
```
build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flakey, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - shippable_retry npm install --only=prod
    #- npm test
```

**Comment by gabrielpascua** [comment]
Just worth noting that these build step from our deployment has been working properly before yesterday's outage.

**Comment by gabrielpascua** [comment]
Tried resetting keys for the project as [described in known issues](https://github.com/Shippable/support/wiki/Known-issues#september-4-2019), but the build is still failing.

**Comment by trriplejay** [comment]
Hi @gabrielpascua 

It looks like your npm install is trying to install another repository that it doesn't have access to.  I think in this case, you'll need to add your subscription key to the repo that npm is trying to fetch.  

You can find the public key at the bottom of the subscription settings page.  Add that key as a deploy key on the repository, and npm should be able to properly download it during the build.

Let me know if you have any questions.

**Comment by gabrielpascua** [comment]
@trriplejay , we have the flag --only=prod on our `npm install` that should not download that package.  Like I mentioned in my first comment, this was working for us before yesterday's outage. We haven't had any configurations changes in our deploy for ~1 month.

here's a snip of our package.json
```
{
    ....
    "devDependencies": {
      "privaterepo": "git+ssh://git@bitbucket.org/privaterepo/repo-name.git"
  }
}
```

**Comment by trriplejay** [comment]
I see your latest build succeeded, did you end up adding the key, or was there some other issue with the npm --only flag?

**Comment by gabrielpascua** [comment]
Our Ops copied over the shippable key into the bitbucket repo.  Can you help me understand why we had to do this step?  I'm having a hard time wrapping my head around this because like i said, we have not changed our config for quite some time.

**Comment by trriplejay** [comment]
as a result of yesterdays outage, bitbucket users had to re-authorize with Shippable, and old deploy keys that were created on bitbucket were removed.  This means that any cloning of a project would fail.

Normally, resetting the project would re-establish the keys and allow the clone, but in this case, the project was an npm dependency, not a project on Shippable.  For a build in project A to pull private project B, project B needs to have a deploy key that will be present in the build for project A.  In this case, that is the subscription key.

So, I think it was working before because at some point someone in your org had added the subscription key in bitbucket, and yesterday's outage removed it.  As far as why npm install with --only=prod needs access when its a devDependency? i'm not sure. maybe that's just the behavior of npm install or maybe a bug? I agree that it seems odd, since that's the whole purpose of devDependencies.

**Comment by gabrielpascua** [comment]
thanks that helped.
