### ISSUE TITLE
Not able to see checks running on Pull request

### ISSUE THREAD

**Issue by akshay-ship-it** [Shippable/support#4951]
When I click on checks running on my PR.

Shippable.com throws error 404 page not found.

**Comment by a-murphy** [comment]
Would this be a public pull request for which you can include a link?  Do you see your account name in the bottom left corner on the 404 page to indicate that you are logged in?  Are you able to navigate directly to www.shippable.com and find the run for your pull request?

There isn't enough information here to determine what the problem may be.  It could be that the run was deleted and no longer exists, or that you haven't logged in and need to log in in order to see a private project.

**Comment by akshay-ship-it** [comment]
Yes i do see my account name, so i am logged in.

https://app.shippable.com/github/kastenhq/k10/runs/29208/summary/console 
this is the link i am trying to go to and i get 404 page not found error.

**Comment by akshay-ship-it** [comment]
I saw this error even when checks were in "Processing" state.

**Comment by a-murphy** [comment]
It doesn't look like you have access to that project.  Could you try clicking "profile" in the left sidebar and then the "sync" button to re-sync your permissions?

**Comment by a-murphy** [comment]
Your account appears to have been synchronized.  Let us know if you still have trouble seeing runs for that project.
