### ISSUE TITLE
Errors trying to delete integrations associated with subscription

### ISSUE THREAD

**Issue by 345paul** [Shippable/support#4961]
I'm trying to delete all integrations associated with a particular subscription and getting a number of database errors, such as:

```
subscriptionIntegrations.destroy failed for id: 1848 returned error: update or delete on table "subscriptionIntegrations" violates foreign key constraint "resources_subscriptionIntegrationId_fkey" on table "resources"
```

```
delete subscriptionIntegrationPermissionById for id: 1399 returned error: No projects found for projectId(s): 579a302fdb05080c00c308e6
```

```
No access for subscriptionIntegration :id 4983
```

I'm currently an owner of the GitHub organisation and it has been recently renamed, which may have caused this issue.  Also, the owner of the integrations is no longer associated with the GitHub organisation, which may also be a factor.

**Comment by a-murphy** [comment]
The first error is because the integration you are trying to delete is in use by an Assembly Lines resource.  It can't be deleted until the resource is deleted or updated to use a different integration.  Since it looks like you have an rSync job but aren't otherwise using Assembly Lines, I would suggest [deleting the rSync job and syncRepo](http://docs.shippable.com/platform/tutorial/workflow/delete-assembly-line/#instructions).  You don't need them for your CI projects.  If you're planning to add Assembly Lines resources later, you can add the syncRepo back with another integration 

The other errors are a result of the integration only allowing access for certain projects that you no longer have permission to see.  Most likely, the projects were deleted at some point in the past.  I can delete those integrations for you since you will not have permission to use or delete them with their current lists of allowed projects.

**Comment by 345paul** [comment]
Hi, thanks for deleting the other integrations.  I've removed all projects so have empty jobs and SPOG and resources view, however, I still cannot delete those integrations, so I'm not sure what now what else I can delete.

**Comment by a-murphy** [comment]
Then the syncRepo and rSync job are for a project that was most likely deleted on GitHub, which means that Shippable can't be sure if it still exists or not and only knows that you don't have permission.  Since it sounds like you won't mind, I'll delete that as well.

**Comment by 345paul** [comment]
Yes please, thanks.

**Comment by a-murphy** [comment]
All of the integrations in that subscription have now been deleted.  Let us know if you see anything else strange.

**Comment by 345paul** [comment]
Thanks for your help, I'll close the issue.
