### ISSUE TITLE
Could not read from remote ssh://git repository.

### ISSUE THREAD

**Issue by gabrielpascua** [Shippable/support#4964]
### Description of your issue:
We have a private repo in bitbucket we reference via a ssh://git url.  We do have the deploy key in bitbucket set to use the shippable key.  What did we misconfigure?

Follow up to this.. what is Shippable's recommended setup for private repos?

- Link to the build failure
https://app.shippable.com/bitbucket/bncompass/oauth-token/runs/127/1/console

- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
The build appears to be failing in a `docker build`.  Since the SSH key isn't in the context of the Docker build, this is expected.  If you need the key in your Docker build, the subscription SSH key should be in `/tmp/ssh/00_sub` and you can copy it into the build.  However, the image will then contain the SSH key.  If you are able to instead `npm install` outside that particular build and copy the `node_modules` directory into your new container, it would avoid making the SSH keys available to your image.
