### ISSUE TITLE
Run only chosen test and stop (exit) after first successful test

### ISSUE THREAD

**Issue by Gadzillion** [Shippable/support#4966]
I use Codeception (PHP) + Shippable and i have 30 tests.
My questions is:

1) Can i run only chosen test ?
I have .json only for one test and i don't want to run other tests. It will be great if i can specify test name outside of shippable.yml. Something like that (text from shippable.yml):

```
ci:
     - if [[ -e ./env.json ]]; then codecept run acceptance -vvv -d --env chromeheadless $testname
```

Where $testname will be set in code in TestCest.php file.

2) Can i stop (exit) after first successful test ?
I don't want to run through all tests. 
Example: my first 14 tests was failed, but 15th was successful. And i want to exit after this 15th test will be done.

**Comment by a-murphy** [comment]
For the first question, if you go to the project page on Shippable there is a manual build button in the top right (it looks like a "play" button).  Clicking that will take you to a page that allows you to specify additional variables for the triggered run.  Alternatively, variables that are already available are listed [here](http://docs.shippable.com/ci/env-vars/).

The second question is really about the test runner you are using, not Shippable.  If you are able to configure your tests so that they stop after the first successful test locally, you should be able to do the same thing on Shippable.

**Comment by Gadzillion** [comment]
@a-murphy thx

**Comment by Gadzillion** [comment]
@a-murphy Sorry for distracting you, but can I run a test with multiple json files ?

**Comment by a-murphy** [comment]
That's another question that Codeception would be better able to answer.  Reading their documentation, [this page](https://codeception.com/docs/08-Customization) appears to suggest that you can have a configuration file that combines multiple test suites each with their own configurations.

**Comment by Gadzillion** [comment]
@a-murphy thx you a lot)
