### ISSUE TITLE
Private docker hub login issue

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#4984]
It was working on this build
https://app.shippable.com/bitbucket/mygento/images/runs/243/1/console

Now it fails with on login
https://app.shippable.com/bitbucket/mygento/images/runs/246/1/console

Registry Login account contains $. On the failed build log it does not have correct Login

**Comment by a-murphy** [comment]
Since both appear to be using the same integration, and the integration hasn't been updated, the credentials are most likely no longer valid.  The missing part of your Docker Registry username is only a problem with the log statement and should not be related to the failure.

Could you update the subscription integration with a password that is known to currently work to connect to your Docker Registry?  The password has most likely changed since it was last working.

**Comment by luckyraul** [comment]
```Docker login failed for username robot and email ....```
is not equal
<img width="342" alt="Screenshot 2019-11-11 23 01 56" src="https://user-images.githubusercontent.com/7735520/68617025-580dca80-04d7-11ea-907f-360abfecedd6.png">

I guess this can be related to the login problem

**Comment by a-murphy** [comment]
The message in the logs has the wrong username, but the username in the `docker login` command should still be correct.  The way the script is assembled, the `$` caused the logs to show the wrong name, but it shouldn't be a problem in the `docker login` command.

The script, and how it's assembled, hasn't changed at all since your successful build, so it is most likely a problem with the password.  Could you confirm that your Docker Registry password is valid?

**Comment by luckyraul** [comment]
These was password expiration, Thank you
