### ISSUE TITLE
Cannot manage Assembly Line even though accounts have necessary credentials

### ISSUE THREAD

**Issue by shekerev-progress** [Shippable/support#5008]
Greetings

I am a member of Telerik / Progress. I try to add a sync repo to my project in order to manage our assembly line

I am given the following error:
```
Please make sure subscription integration used to add syncRepo has admin access on project:5cefb3b61f6d130007401fa4
```

My user (shekerev-progress) has admin access to said project. The owner of our subscription also has admin access to said project. Both accounts are enabled for private repos. We have clicked the button for sync SCMs for both accounts. We have also clicked the same button but from the screen for enabling projects. We still get the error above.

Please advise.

**Comment by a-murphy** [comment]
Since it looks like your project is on GitHub, could you check if it already has twenty webhooks?  GitHub only allows twenty webhooks in a repository.

Other than that, if you can see both the repository content and the webhooks page, you usually would have the required permission to add a repository as a syncRepo or enable a project for CI.

**Comment by shekerev-progress** [comment]
Greetings, @a-murphy 

I confirm both accounts (the one owning the subscription integration and the one trying to add the repo as syncRepo)  see both pages and have the necessary creds. The repo has only 2 webhooks. We still see the error

From my time troubleshooting the issue, I am fairly certain we encounter some undercover edge case bug. Could someone on Shippable side have a quick look?

**Comment by a-murphy** [comment]
Sorry, I hadn't checked the integration settings.  Subscription level SCM integrations don't always work as expected, so we recommend linking an account integration (select "use an account integration" when adding the subscription integration) for all GitHub and Bitbucket integrations.

If you can link an account integration instead of creating a standalone subscription integration, please do so.  If there's a reason you can't, then was the token copied from an account integration or created on GitHub as a "personal access token"?  Just because an account has permission to do something doesn't mean that all tokens also have permission.

**Comment by shekerev-progress** [comment]
Following your advice, it worked like a charm. Closing ticket
