### ISSUE TITLE
Console lag in UI of Shippable

### ISSUE THREAD

**Issue by shekerev-progress** [Shippable/support#5018]
I work for Telerik / Progress. We have a CI enabled repo called `kendo-react-private`. One of its CI steps produces a long log, 204Kb of text to be exact. When we open the long log in the console in the Shippable Web UI, the console lags. Consequently reading the log and debugging is very difficult. Screenshot attached

![ConsoleLag](https://user-images.githubusercontent.com/40392886/72350195-a06b8380-36e6-11ea-9f6e-993804b47351.png)

Is there a way to break that log into multiple sections that would be easier to process? Or is there an alternative solution to this issue.

**Comment by shekerev-progress** [comment]
Greetings, Shippable team

We understand that a company operates with limited resources and not every support ticket warrants a custom solution. But as paid customers we expect at least a response when we encounter performance issues

**Comment by a-murphy** [comment]
Sorry for the delay.  Now that we’ve been able to look into this issue, it looks like clicking the download logs option in the build information above the console and viewing the logs in the downloaded text file may be a reasonable option for you.  The downloaded logs are simply all of the logs, without the ability to collapse sections, but since most of your logs are from the same section you might not lose too much readability.  It's one collapsible section per command in the YML, and breaking one command into multiple sections is not feasible right now.

**Comment by shekerev-progress** [comment]
Thanks for the reply

Closing
