### ISSUE TITLE
on_success gets executed despite test failures

### ISSUE THREAD

**Issue by pvangeel** [Shippable/support#5025]
After some recent changes we are experiencing an 'on_success' script getting executed, despite test failures in the build. (https://app.shippable.com/bitbucket/Addocted/ghost/runs/3038/1/console)

on_succes is defined as follows in shippable.yml:

  on_success:
    - ./deploy_app.sh

I can see the results of the script (actual deployment of the application and a message sent to our Slack), however the execution is also missing from the logs!

**Comment by a-murphy** [comment]
It certainly looks like run 3038 shouldn't have run anything in the `on_success` section.  Are you sure the deployment and Slack message weren't from run 3039?  Run 3039 was the same commit, but successful.

**Comment by pvangeel** [comment]
Unfortunately I'm quite sure: the build number is included in the slack message (provided by $BUILD_NUMBER)

**Comment by a-murphy** [comment]
That you for confirming that the message was from that run.  We've found that the run was triggered twice, so the message must have been sent the second time it ran.  Since the run was already complete by then, the later logs were not saved.  We've corrected the issue that caused the same run to run twice, so we do not expect this to reoccur.

**Comment by pvangeel** [comment]
Ok thanks, that's great to hear! (We also recently did some big changes so it was hard to eliminate if the issue was caused internally or not)
