### ISSUE TITLE
No access for subscriptionIntegration error while deleting Integration

### ISSUE THREAD

**Issue by andrii-shkuropii-altium** [Shippable/support#5056]
Hi, we want to delete integration
https://app.shippable.com/subs/github/pcbng/integrations/12490

But during this action we receiving the message
"No access for subscriptionIntegration :id 12490"

What can we do to remove this integration?

**Comment by a-murphy** [comment]
That integration had been configured so that only one project was allowed to use the integration, and only accounts with access to that project could update the integration.  Since the project had not been recently updated, it's likely that it had been deleted on GitHub and I've removed the subscription integration.  Let us know if you have trouble updating any other integrations.

**Comment by andrii-shkuropii-altium** [comment]
Thank you!
