### ISSUE TITLE
some users have job visibility that others do not - same github permissions

### ISSUE THREAD

**Issue by lw-kaijparo** [Shippable/support#5091]
some users have job visibility that others do not - same github permissions

users with issues show a 404 - and when listing the jobs - some users have different lists showing up

https://app.shippable.com/github/lacework/hawkeye/runs/920/summary

**Comment by a-murphy** [comment]
Since it's a private GitHub repository, it will only be visible to users that have enabled private repositories.  To enable private repositories, click on "profile" in the left sidebar and then, on the account profile page, enable private in the identities panel.  If the project still can't be accessed, try the "sync" button on the account profile page to resynchronize repository permissions.

**Comment by lw-kaijparo** [comment]
thanks 💯
