### ISSUE TITLE
SpotHopperApp Build error in setup_ruby 

### ISSUE THREAD

**Issue by ljubishan** [Shippable/support#5110]
The build is failing with the error:
`curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`
`There was an error while trying to resolve rubygems version for 'latest'.` 
`Halting the installation.`

- Link to the build failure https://app.shippable.com/github/SpotHopperLLC/SpotHopper-Backend/runs/8576/1/console
- Yml file [shippable.zip](https://github.com/Shippable/support/files/4805056/shippable.zip)

This issue is causing our updates to the production app to be published without automated testing.

**Comment by a-murphy** [comment]
I would suggest updating to a newer build image, since the image you are using now hasn't been updated for over four years.  To do so without changing your YML to the new format, you can add `build_image: drydock/u16ruball:v5.10.4` to your `shippable.yml`.  The [v5.10.4](http://docs.shippable.com/platform/runtime/machine-image/language-versions/#ruby) image has Ruby 2.3.5 pre-installed.  I would also suggest [changing the machine image version](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) in your subscription's node pool to v5.10.4 (to match the image version) so that the image will not have to be pulled every time your job runs.

**Comment by ljubishan** [comment]
I have updated the default node pool from v7.2.4 to v5.10.4 and added the `build_image: drydock/u16ruball:v5.10.4` to the `shippable.yml` and now I have a different issue at the build_ci step.

- link to the build failure: https://app.shippable.com/github/SpotHopperLLC/SpotHopper-Backend/runs/8582/1/console
- shippable file [shippable.zip](https://github.com/Shippable/support/files/4807752/shippable.zip)

**Comment by a-murphy** [comment]
If you need to run `apt-get update`, could you try the latest version (v7.2.4) of the image?  I looks like some keys in 5.10.4 are no longer valid.  Unfortunately, 5.10.4 was the last image with Ruby 2.3.5 pre-installed, so the build will have to install Ruby on a newer image.

**Comment by ljubishan** [comment]
@a-murphy 
After trying multiple combinations I figured out the solution with using `build_image: drydock/u14ruball:v5.10.4` in shippable.yml. The difference from the code you provided is `u14` instead of `u16` 

Thanks!
