### ISSUE TITLE
Scala + JDK

### ISSUE THREAD

**Issue by vfarcic** [Shippable/support#620]
I've trying to compile an application that is a mix of Scala and Java code. It fails saying UnsupportedClassVersionError. My assumption is that it tries to compile the code with JDK6 instead of JDK7.

You can see the log from https://app.shippable.com/builds/5429a9c6dae349860167d362

Is there a way to specify JDK used to compile an Scala project?

**Comment by manishas** [comment]
@vfarcic actually, we took a look at this issue and here's what our engineer had to say -
---
You will need to invoke nvm because you're doing global installs of grunt, bower, etc., and that either needs everything including the build to run with sudo, or using nvm so everything stays local to the user account. 
The working YML file is here: https://github.com/rageshkrishna/TechnologyConversationsBdd/blob/master/.travis.yml

We still see some PhantomJS tests failing, but they aren't marking the build as broken so we're not sure what's going on there. The original issue with JDK/JRE does seem to be addressed with the yml change.
---
Please let me know what you think.

**Comment by manishas** [comment]
Closing this issue due to lack of response. @vfarcic let me know if we can help with anything.
