### ISSUE TITLE
Unicode output not supported

### ISSUE THREAD

**Issue by dreispt** [Shippable/support#747]
A test script printing out Unicode is breaking the Shippable build.
TravisCi and local machine tests run good.
As an example, see build https://app.shippable.com/builds/545baa3f95a51f7800f01b11
The "offending" script is: https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_run_tests

**Comment by rageshkrishna** [comment]
@dreispt Sorry for the long delay in getting around to this. I forked OCA/project-service and ran it today. It looks like build 1 fails because of a pep8 error (E402 module level import not at top of file), and this error is not currently being ignored in  `maintainer-quality-tools/travis/cfg/travis_run_flake8__init__.cfg`. 

Are you running your build locally against the latest version of pep8? It looks like this behaviour was introduced recently (in v1.6.0, which was released on 2015-02-06).

**Comment by rageshkrishna** [comment]
I no longer see any unicode related errors on the 8.0 branch.

**Comment by dreispt** [comment]
@rageshkrishna In fact, the test script [was changed](https://github.com/OCA/maintainer-quality-tools/commit/67eb46a17b202b732cebde6775a6a0aeb3c5b813) as a workaround for this issue. Some people [reported](https://github.com/OCA/maintainer-quality-tools/issues/103) finding the unicode problem when trying to use Docker.

Sorry, i don't have a currently example of the issue.

**Comment by manishas** [comment]
@dreispt thanks for the update! I am closing this issue but we will keep an eye out for this happening again.
