### ISSUE TITLE
Support .NET languages

### ISSUE THREAD

**Issue by fagnercarvalho** [Shippable/support#759]
I was looking for a free hosted CI for my Web API developed in C# and I read that some folks said that Shippable supports C# but when I access the language specific help section I cant find .NET in there.
What happen exactly?

**Comment by TheEadie** [comment]
+1 Any ideas where this fits in with your current road map? I'm using Travis CI at the moment but would like to move across to shippable for private projects.

**Comment by manishas** [comment]
Closing as dup of #105 since all additional language requests are consolidated there.

In general, customers are using officially unsupported languages by supplying their own docker image or dockerfile and installing all their tools in the image. Then they lie on the language tag in the yml by saying ```language: python``` and they can successfully run builds.

We'll explore making this easier and document it soon.
