### ISSUE TITLE
Opt out of notifications

### ISSUE THREAD

**Issue by evilmarty** [Shippable/support#872]
Can you please make it possible to opt out of notifications. My organisation was added to Shippable and now whenever anything happens within that organisation I receive a notification even though I didn't have an account. I created one in the hopes to be able to stem these notifications but there is no settings available anywhere, even in the emails (which should have an unsubscribe link). This gets very annoying as I don't want to be notified of things I am not involved within the organisation I am in.

**Comment by bittner** [comment]
@evilmarty The fundamental difference of the emails here and the emails you get from an e-commerce service is that here in CI (hopefully) everything is "infrastructure as code". Understanding this is crucial.

In other words, as @manishas already pointed out, you get email notifications because someone (of your team) has activated repositories with:

1. either no Shippable configuration (and you get notified -- by default, you're the owner -- e.g. if something goes wrong)
1. or a Shippable configuration that includes you as a recipient.

For more details see the "Notifications" sections in http://docs.shippable.com/en/latest/config.html#configuration

Conclusion: You should send the "unsubscribe" request to the colleague of yours that made this happen! Fix the configuration.

**Comment by manishas** [comment]
@evilmarty I realize what you're saying - you're not talking about build notifications, but about the notification that someone added a repo to shippable.

We do this because in most cases, folks who are a part of the github org want to know the build status of the repositories they have permissions to. When a repository is enabled, we send a one time notification informing everyone in the org that this repo was enabled and they can check build status on shippable.

Sorry these emails are annoying you! We haven't heard complaints about this before, so if more folks express their concerns, we will take another look at our model.

**Comment by mbrevoort** [comment]
Oh my, please make it possible to turn off email notifications. I'm getting notified by everything in slack and my email is a mess. For example:

![screen shot 2015-04-29 at 9 24 12 pm](https://cloud.githubusercontent.com/assets/30455/7405875/29b06a26-eeb6-11e4-98a9-f60d8ef5ab24.png)

My only recourse is a gmail filter :(
