### ISSUE TITLE
Notifications should support sending to committer and predefined list of e-mails

### ISSUE THREAD

**Issue by HenrikOssipoff** [Shippable/support#901]
Extending upon #900, I would like to add a feature request to be able to add a new way of doing notifications.

In our use case, we don't want to spam the entire development team whenever our build breaks. We have HipChat for this. However, we would like to do the following, which is not currently possible in Shippable:

- Send an e-mail to the last committer so they definitely know they broke something
- Send an e-mail to a predefined list of e-mails -- we have a shared e-mail folder which we use to keep track of such things

**Comment by lkiesow** [comment]
This would be really great.

**Comment by manishas** [comment]
Dup of #901

**Comment by HenrikOssipoff** [comment]
@manishas closed because being a duplicate of itself...?

**Comment by manishas** [comment]
sigh... the follies of trying to get through old support issues and consolidate :(

@HenrikOssipoff meant to leave this open and close https://github.com/Shippable/support/issues/1213 instead. Thanks for pointing out the error!

Reopening.

**Comment by manishas** [comment]
this is now fixed and documented at http://docs.shippable.com/ci_configure/#email-notifications

Please note that you have to convert your projects to the new yml format detailed at http://docs.shippable.com/ci_configure in order to use this enhancement.

relevant docs - 
recipients specifies the email addresses you want to send build status notifications to. This overrides the default setting of 'last committer' and 'project owner(s)'.
To specify 'last committer' and 'project owner(s)' as part of this list, you can use --lastcommitter and --owners.
