### ISSUE TITLE
Build hang after "Build completed".

### ISSUE THREAD

**Issue by Zapata** [Shippable/support#928]
Build continuously hang after the script section (after displaying "Build completed").
It should be at the "scan for test result" step, but nothing displayed.
The only option it's to cancel the build.

Please have a look to: https://app.shippable.com/builds/54a41a0e0bb1a11000d4ef47

**Comment by manishas** [comment]
Closing this issue. Please feel free to re-open if you run into this again.

Thanks!

**Comment by josebama** [comment]
I'm trying shippable and I have never been able to make a successful build yet, but now I think I have run into this problem, because after completing every step okay and even completing all the tests, it gets stuck after Build completed.

Here is the console output:
![screen shot 2015-02-05 at 14 47 33](https://cloud.githubusercontent.com/assets/2027580/6062232/fcfe9d88-ad45-11e4-81e1-6d5212207b55.png)

But it still says processing, and there are no tests results nor coverage anywhere. This is my build https://app.shippable.com/builds/54d37dad08ac4d0e00c8897e

**Comment by rageshkrishna** [comment]
@josebama Yes, one of our queues got a little backed up again. We've reset the processor so everything will be back to normal in another minute or two. Please let me know if there's anything I can do to help your builds run successfully on Shippable.

**Comment by josebama** [comment]
it worked, thank you :+1:
