### ISSUE TITLE
Build timeouts while trying to install packages

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#943]
I am trying to install some dependencies, they are properly resolved by apt but then build fails.

````
Repo	radiokit-webapp
Repo URL	https://bitbucket.org/svada/radiokit-webapp.git
Language	ruby
Triggered By	Marcin Lewandowski (mspanc)
Commit Message	Attempt to force shippable to use ubuntu 14.04
Branch	gst
Changes	b9f114d24a462123a94a009d4b39f0921c08dc69
````

**Comment by manishas** [comment]
Tagging @rageshkrishna to take a look at this.

**Comment by rageshkrishna** [comment]
@mspanc Can you please try adding `-y` to your apt-get install step? I believe apt is waiting for confirmation to install/update packages.

So instead of 
````
apt-get install {your packages}
````

do this: 

````
apt-get install -y {your packages}
````

**Comment by mspanc** [comment]
It works fine right now.

**Comment by DanLipsitt** [comment]
This behavior seems to differ depending on the value of `build_image` in the config file. `shippableimages/ubuntu1404_python` needs `install -y` while the standard image (no `build_image` specified) only needs `install`. I'm guessing that's because the environment is missing `DEBIAN_FRONTEND=noninteractive` for some images.
