### ISSUE TITLE
Bug: can't run build container

### ISSUE THREAD

**Issue by pnpritchard** [Shippable/support#947]
I am using dedicated hosts, and have successfully used the build container to deploy and run my software. However, now when I try running the container, it is failing with the following error. I noticed that this started happening when shippable added the branch name to the image tag.

Please, I need urgent help because I don't know how to workaround this issue.

```
$ sudo docker run [redacted] falkonry/insight:master.203.1 [redacted]
7155663c66e88f448dadedb01494020881f671feb477d65f2e0aa8983e6cfaed
2015/01/08 18:15:02 Error response from daemon: Cannot start container 7155663c66e88f448dadedb01494020881f671feb477d65f2e0aa8983e6cfaed: exec: "/home/shippable/wrk/boot.sh": stat /home/shippable/wrk/boot.sh: no such file or directory
```

**Comment by manishas** [comment]
@pnpritchard we'll take a look at this now.

**Comment by ragsden** [comment]
@pnpritchard : We are overriding the entry point of the custom image to execute the build. When this container is committed, the entry point is being persisted and hence you are seeing this issue. 
You can override the entry point when the docker run command.
We switched to using entry point because this is a reliable way to ensure our build code gets executed on top of the custom image.

Please let me know if you have any questions. I'm available on Google hangout if you want to chat. raghu@shippable.com

**Comment by pnpritchard** [comment]
OK thanks, I changed my run commands with --entrypoint flag and its working now!

**Comment by ragsden** [comment]
Perfect! Sorry for the inconvenience.

**Comment by phagunbaya** [comment]
@ragsden : Thanks ! I was wondering when these kind of changes are made, do you also publish it anywhere ? In some newsletter or any change log ?

**Comment by vivekmshah** [comment]
@phagunbaya :+1:
