### ISSUE TITLE
Downgrade

### ISSUE THREAD

**Issue by jtmarmon** [Shippable/support#969]
I subscribed to the 'startup' plan and realized that shippable doesn't quite suit our needs. I removed my credit card but it still says my plan is 'startup'. How can I be downgraded? Also, will I be charged for my 4 hours of use of your service? :stuck_out_tongue_closed_eyes:

**Comment by manishas** [comment]
@jtmarmon our free plan is full featured and the only restriction is on the number of concurrent builds, so we let you try out our service as much as you want before you pay. We do not issue refunds due to this reason.

I'd love to find out why our service did not address your scenario. Can we do a quick google hangout? Anytime next week works for me.

**Comment by jtmarmon** [comment]
Sure. 1 PM next wednesday is good for me. My email is jtmarmon@gmail.com

**Comment by manishas** [comment]
@jtmarmon I am assuming 1pm EST. I'll send you a meeting request now. Thanks!
