### ISSUE TITLE
Build is slow

### ISSUE THREAD

**Issue by luigi7up** [Shippable/support#971]
Hi guys,

2 questions:

1) I am running integrations tests on my machine in 4:30min (:webkit) - 6min(:selenium) and on Shippable it takes 18min. Is there a way to lower this time? 

2) Also, what we see is that the install takes 8-10min so we added _cache: true_ today and ran a rebuild and a new commit few times, but it still takes the same...

Thank you.

EDIT:
Last push shows build: 2 seconds - forget the 2nd question...

**Comment by manishas** [comment]
@luigi7up we have currently implemented caching on a per host level, so it takes a few builds for it to kick in. I'm glad your builds are faster now :)

**Comment by luigi7up** [comment]
@manishas Yes, that's great news. From 35min to 16min!!! Can you tell me what can be done to speed it up a bit more considering that the suite runs in max. 6min on local machine and in Shippable it takes 15min? Is this normal behaviour?

**Comment by manishas** [comment]
@luigi7up we will take a look at why this is happening and get back to you.

**Comment by luigi7up** [comment]
as a reference:
:selenium driver (starts firefox): 7:02 min or 6:32 min
:capybara-webkit (headelss): 4:46min

**Comment by luigi7up** [comment]
hi guys, any update on 15min duration for the tests?

**Comment by jeffkole** [comment]
I have noticed that caching does not seem to work for me either.  The environment variable `SHIPPABLE_CACHE_ENABLED=True` is set correctly, but the prior build's `SHIPPABLE_REPO_DIR` never seems to exist so the build always runs from scratch.

**Comment by manishas** [comment]
I think this is a side effect of how our caching currently works...

We cache the container the first time a build with cache=true comes in, and all subsequent builds simply use this cache without adding stuff each time. If you make changes to your install section or add something to package.json, you will need to do a commit with [reset_minion] in your commit message in order to delete current cache and cache again so that the latest changes are picked up.

This is because we run all builds inside docker containers. When a build comes in with cache=true, docker adds a layer to the base image with the cached stuff and we commit this as :latest
The next time a build runs, Docker again adds a layer to the image, however, we do not commit this back since it adds to the number of layers. Docker has a limit of 127 layers, so simply adding layers will cause builds to fail at some point.

Hope this helps... let me know if you want more clarity. You should try using the [reset_minion] in your commit message and caching will kick in again and you'll see faster build times.

**Comment by manishas** [comment]
Closing. please let us know if we can help further.
