### ISSUE TITLE
Shippable don't install ruby

### ISSUE THREAD

**Issue by Nayalison** [Shippable/support#982]
Hi,

I have a java project but i need ruby and node to do automatic deploy so in my yml i set 

``` YML

before_install:
  - source ~/.nvm/nvm.sh && nvm use 0.10
  - source ~/.rvm/scripts/rvm && rvm use 2.0.0

```
 This was working but now all buils is failing and this is the log message
![shippable_falha](https://cloud.githubusercontent.com/assets/1777732/5793160/5ce3098c-9f18-11e4-8964-2bfc8044389e.png)

**Comment by rwwagner90** [comment]
+1 I get the same error saying ruby is not installed.

**Comment by rwwagner90** [comment]
@Nayalison not sure if it was a coincidence, but not doing && and putting them on separate lines worked for me.
```
- source ~/.rvm/scripts/rvm
- rvm use 1.9.3
```

**Comment by rageshkrishna** [comment]
@Nayalison Sorry about this. We upgraded `rvm` and it turns out that it now points to newer Ruby releases by default for 1.9.3, 2.0.0 and jruby. I'm going to push a fix for this so our images have the latest rubies pre-installed.

As a quick fix, you can update your YML file to optionally install the required ruby if it's not available on the minion by doing this:
````
 - source ~/.rvm/scripts/rvm && (rvm use 2.0.0 || rvm install 2.0.0)
````
This isn't optimal as you'd have to take the hit of ruby installation on each build, but it will unblock your builds until I deploy the updated rubies to the minion image.

**Comment by rwwagner90** [comment]
What is the most recent version of ruby that currently is supported? I don't need any exact version

**Comment by rageshkrishna** [comment]
We've deployed a fix for this. 2.0.0-p598 is what will be used if you specify `2.0.0` in your YML now. Can you please try your build again and let me know if it works? Thanks.

**Comment by rwwagner90** [comment]
I would just like to use the most recent ruby. What is the most recent supported?

**Comment by rageshkrishna** [comment]
2.1.1 is the latest available version that is pre-installed.

**Comment by manishas** [comment]
Closing since this is resolved.
